[package]
name = "keshvar"
version = "0.1.0"
edition = "2021"
build = "code_gen/main.rs"

[dependencies]
thiserror = "1.0"
lazy_static = "1.4"
hashbrown = "0.13.*"
serde = { version = "1.0", features = ["derive"], optional = true }
chrono = { version = "0.4.*", default-features = false, optional = true }
iso_currency = { version = "0.4.*", default-features = false, optional = true }

[build-dependencies]
serde = { version = "1.0", features = ["derive"]}
serde_yaml = "0.9"
anyhow = "1.0"

