// DO NOT TOUCH THIS FILE. (Auto-generated via `code_gen/countries.rs`)

// The United Arab Emirates

#[cfg(all(feature = "ae", feature = "constants"))]
pub mod consts {
    #[allow(unused_imports)]
    use crate::{
        Alpha2, Alpha3, Continent, CurrencyCode, Region, SubRegion, WeekDay, WorldRegion, GEC, IOC,
    };

    pub const ADDRESS_FORMAT: Option<&str> =
        Some("{{recipient}}\n{{street}}\n{{postalcode}} {{city}}\n{{country}}");
    pub const ALPHA2: Alpha2 = Alpha2::AE;
    pub const ALPHA3: Alpha3 = Alpha3::ARE;
    pub const CONTINENT: Continent = Continent::Asia;
    pub const COUNTRY_CODE: usize = 971;
    pub const CURRENCY_CODE: CurrencyCode = CurrencyCode::AED;
    pub const GEC: Option<GEC> = Some(GEC::AE);
    pub const INTERNATIONAL_PREFIX: &str = "00";
    pub const IOC: Option<IOC> = Some(IOC::UAE);
    pub const ISO_SHORT_NAME: &str = "United Arab Emirates";
    pub const ISO_LONG_NAME: &str = "The United Arab Emirates";
    pub const OFFICIAL_LANGUAGE_LIST: &[&str] = &["ar"];
    pub const SPOKEN_LANGUAGE_LIST: &[&str] = &["ar"];
    pub const NATIONAL_DESTINATION_CODE_LENGTH_LIST: &[usize] = &[2];
    pub const NATIONAL_NUMBER_LENGTH_LIST: &[usize] = &[7, 8, 9];
    pub const NATIONAL_PREFIX: &str = "0";
    pub const NATIONALITY: Option<&str> = Some("Emirian");
    pub const NUMBER: &str = "784";
    pub const POSTAL_CODE: bool = false;
    pub const POSTAL_CODE_FORMAT: Option<&str> = None;
    pub const REGION: Option<Region> = Some(Region::Asia);
    pub const START_DAY_OF_WEEK: WeekDay = WeekDay::Monday;
    pub const SUBREGION: Option<SubRegion> = Some(SubRegion::WesternAsia);
    pub const UN_LOCODE: &str = "AE";
    pub const UNOFFICIAL_NAME_LIST: &[&str] = &[
        "United Arab Emirates",
        "الإمارات العربية المتحدة",
        "Vereinigte Arabische Emirate",
        "Émirats Arabes Unis",
        "Emiratos Árabes Unidos",
        "アラブ首長国連邦",
        "Verenigde Arabische Emiraten",
    ];
    pub const WORLD_REGION: WorldRegion = WorldRegion::EMEA;
    #[cfg(feature = "translations")]
    pub const TRANSLATIONS: &[(&str, &str)] = &[
        ("ab", "United Arab Emirates"),
        ("af", "Verenigde Arabiese Emirate"),
        ("ak", "United Arab Emirates"),
        ("am", "ፘተባበሩት ጐረብ ጔሤሳትስ"),
        ("an", "Emiratos Arabes Unius"),
        ("ar", "الإمارات العربي\u{651}ة المت\u{651}حدة"),
        ("as", "ইউন\u{9be}ইটেড আৰৱ ইমিৰেটছ"),
        ("ay", "United Arab Emirates"),
        ("az", "Birləşmiş Ərəb Əmirlikləri"),
        ("ba", "United Arab Emirates"),
        ("be", "Аб'яднаныя Арабскія Эміраты"),
        ("bg", "Обединени арабски емирства"),
        ("bi", "United Arab Emirates"),
        ("bn", "সংয\u{9c1}ক\u{9cd}ত আরব আমিরশ\u{9be}হী"),
        ("bn_IN", "সংয\u{9c1}ক\u{9cd}ত আরব আমিরশ\u{9be}হী"),
        ("br", "Emirelezhioù Arab Unanet"),
        ("bs", "Ujedinjeni Arapski Emirati"),
        ("ca", "Unió dels Emirats Àrabs"),
        ("ce", "Iаьрбийн Цхьаьнакхетта Эмираташ"),
        ("ch", "United Arab Emirates"),
        ("cs", "Spojené arabské emiráty"),
        ("cv", "Iаьрбийн Цхьаьнакхетта Эмираташ"),
        ("cy", "Emiriaethau Arabaidd Unedig"),
        ("da", "Forenede Arabiske Emirater"),
        ("de", "Vereinigte Arabische Emirate"),
        ("dv", "އ\u{7ac}ކ\u{7aa}ވ\u{7ac}ރ\u{7a8} ޢ\u{7a6}ރ\u{7a6}ބ\u{7a8} އ\u{7a8}މ\u{7a7}ރ\u{7a7}ތ\u{7aa}"),
        ("dz", "ཡ\u{f74}་ནའ\u{f72}་ཊ\u{f7a}ཊ་ ཨ་རབ་ ཨ\u{f72}་མ\u{f72}་ར\u{f7a}ཊ\u{f72}ས\u{f72}།"),
        ("ee", "United Arab Emirates"),
        ("el", "Ηνωμένα Αραβικά Εμιράτα"),
        ("en", "United Arab Emirates"),
        ("eo", "Unuiĝintaj Arabaj Emirlandoj"),
        ("es", "Emiratos Árabes Unidos"),
        ("et", "Araabia Ühendemiraadid"),
        ("eu", "Arabiar Emirerri Batuak"),
        ("fa", "امارات متحده عربی"),
        ("ff", "United Arab Emirates"),
        ("fi", "Yhdistyneet arabiemiirikunnat"),
        ("fo", "Sameindu arabisku emiratini"),
        ("fr", "Émirats arabes unis"),
        ("fy", "Feriene Arabyske Emiraten"),
        ("ga", "Aontas na nÉimíríochtaí Arabacha"),
        ("gl", "Emiratos Árabes Unidos"),
        ("gn", "United Arab Emirates"),
        ("gu", "ય\u{ac1}નાઇટ\u{ac7}ડ આરબ અમીરાત"),
        ("gv", "Ny h-Emmiraidyn Arabagh Unnaneysit"),
        ("ha", "Taraiyar larabawa"),
        ("he", "איחוד האמירויות הערביות"),
        ("hi", "स\u{902}य\u{941}क\u{94d}त अरब अमीरात"),
        ("hr", "Ujedinjeni Arapski Emirati"),
        ("ht", "Emira Arab Ini"),
        ("hu", "Egyesült Arab Emírségek"),
        ("hy", "Միացյալ Արաբական Էմիրաթներ"),
        ("ia", "Emiratos Arabe Unite"),
        ("id", "Uni Emirat Arab"),
        ("io", "Unionita Araba Emirati"),
        ("is", "Sameinuðu arabísku furstadæmin"),
        ("it", "Emirati Arabi Uniti"),
        ("iu", "United Arab Emirates"),
        ("ja", "アラブ首長国連邦"),
        ("ka", "არაბეთის გაერთიანებული ემირატები"),
        ("ki", "United Arab Emirates"),
        ("kk", "Біріккен Араб Әмірліктері"),
        ("kl", "United Arab Emirates"),
        ("km", "អារ\u{17c9}ាប\u{17cb}\u{200b}រ\u{17bd}ម"),
        ("kn", "ಯುನೈಟ\u{cc6}ಡ\u{ccd} ಅರಬ\u{ccd} ಎಮ\u{cbf}ರೇಟ\u{ccd}ಸ\u{ccd}"),
        ("ko", "아랍에미리트"),
        ("ku", "Mîrtiyên Ereb ên Yekbuyî"),
        ("kv", "Ӧтувтчӧм Араб Эмиратъяс"),
        ("kw", "Pennternasedh Unys Arabek"),
        ("ky", "Бириккен Араб Эмирликтери"),
        ("lo", "United Arab Emirates"),
        ("lt", "Jungtiniai Arabų Emyratai"),
        ("lv", "Apvienotie Arābu Emirāti"),
        ("mi", "United Arab Emirates"),
        ("mk", "Обединети арапски емирати"),
        ("ml", "ഐക\u{d4d}യ അറബ\u{d4d} എമിറേറ\u{d4d}റ\u{d41}കള\u{d4d}\u{200d}"),
        ("mn", "Арабын нэгдсэн имерат"),
        ("mr", "स\u{902}य\u{941}क\u{94d}त अरब अमिराती"),
        ("ms", "Emiriah Arab Bersatu"),
        ("mt", "Emirati Għarab Maqgħuda"),
        ("my", "အာရပ\u{103a}စော\u{103a}ဘ\u{103d}ားများပြည\u{103a}ထောင\u{103a}စ\u{102f}"),
        ("na", "Emireitit Arabiya"),
        ("nb", "De forente arabiske emirater"),
        ("ne", "स\u{902}य\u{941}क\u{94d}त अरब इमिर\u{947}ट\u{94d}स"),
        ("nl", "Verenigde Arabische Emiraten"),
        ("nn", "Dei sameinte arabiske emirata"),
        ("nv", "Ásáí Dineʼé Bikéyah Yázhí Ałhidadiidzooígíí"),
        ("oc", "Emirats Arabs Units"),
        ("or", "ସଂଯ\u{b41}କ\u{b4d}ତ ଆରବ ଏମ\u{b3f}ରେଟ"),
        ("pa", "ਸ\u{a70}ਯ\u{a41}ਕਤ ਰਾਜ ਅਮੀਰਾਤ"),
        ("pi", "United Arab Emirates"),
        ("pl", "Zjednoczone Emiraty Arabskie"),
        ("ps", "عربي متحده امارات"),
        ("pt", "Emirados Árabes Unidos"),
        ("pt_BR", "Emirados Árabes Unidos"),
        ("ro", "Emiratele Arabe Unite"),
        ("ru", "Объединённые Арабские Эмираты"),
        ("rw", "Repubulika Nyarabu Zunze Ubumwe"),
        ("sc", "Emiratos Àrabos Unidos"),
        ("sd", "گڏيل عرب امارات"),
        ("si", "එක\u{dca}සත\u{dca} අර\u{dcf}බ\u{dd2} එම\u{dd3}ර\u{dca}"),
        ("sk", "Spojené arabské emiráty"),
        ("sl", "Združeni Arabski emirati"),
        ("so", "Imaaraadka Carabta ee Midoobay"),
        ("sq", "Emiratet e Bashkuara Arabe"),
        ("sr", "Уједињени Арапски Емирати"),
        ("sv", "Förenade Arabemiraten"),
        ("sw", "Falme za Kiarabu"),
        ("ta", "ஐக\u{bcd}கிய அர\u{bbe}பிய எமிரேட\u{bcd}சு"),
        ("te", "యున\u{c48}ట\u{c46}డ\u{c4d} అరబ\u{c4d} ఎమ\u{c3f}ర\u{c47}ట\u{c4d}స\u{c4d}"),
        ("tg", "Амороти Муттаҳидаи Араб"),
        ("th", "สหร\u{e31}ฐอาหร\u{e31}บเอม\u{e34}เรตส\u{e4c}"),
        ("ti", "የተባበሩት አረብ ኤምሬትስ"),
        ("tk", "Birleşen Arap Emiratlary"),
        ("tl", "Mga Pinag-isang Arabong Emirado"),
        ("tr", "Birleşik Arap Emirlikleri"),
        ("tt", "Берләшкән Гәрәп Әмирлекләре"),
        ("ug", "ئەرەب بىرلەشمە خەلىپىلىكى"),
        ("uk", "Об’єднані Арабські Емірати"),
        ("ur", "متحدہ عرب امارات"),
        ("uz", "Birlashgan Arab Amirliklari"),
        ("ve", "United Arab Emirates"),
        ("vi", "Các Tiểu Vương Quốc A-rập Thống Nhất"),
        ("wa", "Emirats Arabes Unis"),
        ("wo", "Imaarati Araab yu Bennoo"),
        ("xh", "United Arab Emirates"),
        ("yo", "Àwọn Ẹ\u{301}mírétì Árábù Aṣọ\u{300}kan"),
        ("zh_CN", "阿联酋"),
        ("zh_HK", "阿拉伯聯合酋長國"),
        ("zh_TW", "阿拉伯聯合大公國"),
        ("zu", "United Arab Emirates"),
];
    #[cfg(all(feature = "ae", feature = "geo", feature = "constants"))]
    pub mod geo {
        pub const LATITUDE: f64 = 23.424076;
        pub const LONGITUDE: f64 = 53.847818;
        pub const MAX_LATITUDE: f64 = 26.0765;
        pub const MAX_LONGITUDE: f64 = 56.4395001;
        pub const MIN_LATITUDE: f64 = 22.6315138;
        pub const MIN_LONGITUDE: f64 = 51.4723;
        pub const NORTHEAST_LATITUDE: f64 = 26.0765;
        pub const NORTHEAST_LONGITUDE: f64 = 56.4395001;
        pub const SOUTHWEST_LATITUDE: f64 = 22.6315138;
        pub const SOUTHWEST_LONGITUDE: f64 = 51.4723;
    }
}
#[cfg(all(feature = "ae", feature = "geo"))]
pub mod geo {
    use crate::{CountryGeo, CountryGeoBound, CountryGeoBounds};

    pub fn new() -> CountryGeo {
        CountryGeo {
            latitude: 23.424076,
            longitude: 53.847818,
            max_latitude: 26.0765,
            max_longitude: 56.4395001,
            min_latitude: 22.6315138,
            min_longitude: 51.4723,
            bounds: CountryGeoBounds {
                northeast: CountryGeoBound {
                    latitude: 26.0765,
                    longitude: 56.4395001,
                },
                southwest: CountryGeoBound {
                    latitude: 22.6315138,
                    longitude: 51.4723,
                },
            },
        }
    }
}

#[cfg(all(feature = "ae", feature = "subdivisions"))]
pub mod subdivisions {
    use crate::Subdivision;
    use std::collections::HashMap;
    // In this state, We do not know if subdivisions have geo or not!
    #[cfg(feature = "geo")]
    #[allow(unused_imports)]
    use crate::{Alpha2, SubdivisionGeo, SubdivisionType};

    pub fn new() -> HashMap<&'static str, Subdivision> {
        HashMap::from([
            (
                "AJ",
                Subdivision {
                    name: "AJ",
                    country_alpha2: Alpha2::AE,
                    code: "AJ",
                    #[cfg(feature = "geo")]
                    geo: Some(SubdivisionGeo {
                        latitude: Some(25.3995),
                        longitude: Some(55.4796),
                        max_latitude: Some(25.450004),
                        min_latitude: Some(25.3488018),
                        max_longitude: Some(55.6371712),
                        min_longitude: Some(55.4239777),
                    }),
                    comments: None,
                    subdivision_type: SubdivisionType::Emirate,
                    #[cfg(feature = "translations")]
                    translations: HashMap::from([
                        ("ar", "عجمان"),
                        ("be", "Эмірат Аджман"),
                        ("bg", "Аджман"),
                        ("bn", "আজম\u{9be}ন এমির\u{9be}ত"),
                        ("ca", "Ajman"),
                        ("ccp", "𑄃𑄌\u{11134}𑄟𑄚\u{11134}"),
                        ("ceb", "‘Ajmān"),
                        ("cs", "Adžmán"),
                        ("da", "Ajman"),
                        ("de", "Adschman"),
                        ("el", "Αϊμάν"),
                        ("en", "Ajman"),
                        ("es", "Ajmán"),
                        ("eu", "Ajman"),
                        ("fa", "عجمان"),
                        ("fi", "Ajmān"),
                        ("fr", "Ajman"),
                        ("gu", "અજમાન અમીરાત"),
                        ("he", "עג׳מאן"),
                        ("hi", "अजमान"),
                        ("hr", "Ajman"),
                        ("hy", "Աջմանի Էմիրություն"),
                        ("id", "Ajman"),
                        ("is", "Adsman"),
                        ("it", "Ajman"),
                        ("ja", "アジュマーン"),
                        ("ka", "აჯმანის საამირო"),
                        ("kk", "Аджман"),
                        ("kn", "ಅಜ\u{ccd}ಮಾನ\u{ccd} ಎಮ\u{cbf}ರೇಟ\u{ccd}"),
                        ("ko", "아지만 토후국"),
                        ("lt", "Adžmanas"),
                        ("lv", "Adžmāna"),
                        ("ml", "അജ\u{d4d}\u{200c}മ\u{d3e}ൻ"),
                        ("mn", "Эмирт Ажман"),
                        ("mr", "अजमान"),
                        ("ms", "Ajman"),
                        ("nb", "Emiratet Ajman"),
                        ("nl", "Ajman"),
                        ("no", "Emiratet Ajman"),
                        ("pa", "ਅਜਮਾਨ"),
                        ("pl", "Adżman"),
                        ("pt", "Ajman"),
                        ("ro", "Ajman"),
                        ("ru", "Аджман"),
                        ("si", "අජ\u{dca}මන\u{dca} එම\u{dd2}රේටය"),
                        ("sk", "Adžmán"),
                        ("sr", "Аџман"),
                        ("sr_Latn", "Adžman"),
                        ("sv", "Emiratet Ajman"),
                        ("sw", "Ajmān"),
                        ("ta", "அஜ\u{bcd}ம\u{bbe}ன\u{bcd}"),
                        ("te", "అజ\u{c4d}మన\u{c4d} ఎమ\u{c3f}ర\u{c47}ట\u{c4d}"),
                        ("th", "ร\u{e31}ฐอ\u{e31}จมาน"),
                        ("tr", "Acman"),
                        ("uk", "Аджман"),
                        ("ur", "عجمان"),
                        ("vi", "Ajman"),
                        ("yo", "Ajman"),
                        ("yo_BJ", "Ajman"),
                        ("yue", "阿治曼酋長國"),
                        ("yue_Hans", "阿治曼酋长国"),
                        ("zh", "阿吉曼"),
                    ]),
                    unofficial_name_list: ["-إمارة عجمان\u{651} - Ujman"].to_vec(),
                },
            ),
            (
                "AZ",
                Subdivision {
                    name: "AZ",
                    country_alpha2: Alpha2::AE,
                    code: "AZ",
                    #[cfg(feature = "geo")]
                    geo: Some(SubdivisionGeo {
                        latitude: Some(24.466667),
                        longitude: Some(54.36666700000001),
                        max_latitude: Some(24.6213301),
                        min_latitude: Some(24.1517661),
                        max_longitude: Some(54.8509598),
                        min_longitude: Some(54.268856),
                    }),
                    comments: None,
                    subdivision_type: SubdivisionType::Emirate,
                    #[cfg(feature = "translations")]
                    translations: HashMap::from([
                        ("af", "Aboe Dhabi"),
                        ("ar", "إمارة أبوظبي"),
                        ("az", "Əbu-Dabi"),
                        ("be", "Эмірат Абу-Дабі"),
                        ("bg", "Абу Даби"),
                        ("bn", "আব\u{9c1}ধ\u{9be}বি আমির\u{9be}ত"),
                        ("ca", "Abu Dhabi"),
                        ("ccp", "𑄃𑄝\u{1112a} 𑄙𑄝\u{11128}"),
                        ("cs", "Abú Zabí"),
                        ("da", "Emiratet Abu Dhabi"),
                        ("de", "Abu Dhabi"),
                        ("el", "Άμπου Ντάμπι"),
                        ("en", "Abu Dhabi"),
                        ("es", "Abu Dabi"),
                        ("et", "Abu Dhabi emiraat"),
                        ("eu", "Abu Dhabi"),
                        ("fa", "ابوظبی (امارت)"),
                        ("fi", "Abu Dhabi Emirate"),
                        ("fr", "Abou Dabi"),
                        ("gl", "Emirato de Abu Dabi"),
                        ("gu", "અબ\u{ac1} ધાબી અમીરાત"),
                        ("he", "אבו דאבי"),
                        ("hi", "अब\u{942} धाबी अमीरात"),
                        ("hr", "Abu Dhabi"),
                        ("hy", "Աբու Դաբիի Էմիրություն"),
                        ("id", "Abu Dhabi Emirate"),
                        ("it", "Abu Dhabi"),
                        ("ja", "アブダビ"),
                        ("jv", "Abu Dhabi"),
                        ("ka", "აბუ-დაბის საამირო"),
                        ("kk", "Абу-Даби"),
                        ("kn", "ಅಬುಧಾಬ\u{cbf} ಎಮ\u{cbf}ರೇಟ\u{ccd}"),
                        ("ko", "아부다비"),
                        ("ky", "Абу-Даби"),
                        ("lt", "Abu Dabio emyratas"),
                        ("lv", "Abū Dabī"),
                        ("mk", "Абу Даби"),
                        ("ml", "അബ\u{d41}ദ\u{d3e}ബി"),
                        ("mn", "Эмирт Абу-Даби"),
                        ("mr", "अब\u{942} धाबी अमिरात"),
                        ("ms", "Abu Dhabi Emirate"),
                        ("nb", "Emiratet Abu Dhabi"),
                        ("nl", "Abu Dhabi"),
                        ("no", "Emiratet Abu Dhabi"),
                        ("pa", "ਅਬ\u{a42} ਧਾਬੀ"),
                        ("pl", "Abu Zabi"),
                        ("pt", "Emirados Abu Dhabi"),
                        ("ro", "Abu Dhabi"),
                        ("ru", "Абу-Даби"),
                        ("si", "අබ\u{dd4}ඩ\u{dcf}බ\u{dd2} එම\u{dd2}රේට\u{dca}"),
                        ("sk", "Abú Zabí"),
                        ("sr", "Абу Даби"),
                        ("sr_Latn", "Abu Dabi"),
                        ("sv", "Emiratet Abu Dhabi"),
                        ("ta", "அபூ ழப\u{bc0}"),
                        ("te", "అబు ధ\u{c3e}బ\u{c3f} ఎమ\u{c3f}ర\u{c47}ట\u{c4d}"),
                        ("th", "ร\u{e31}ฐอาบ\u{e39}ดาบ\u{e35}"),
                        ("tr", "Abu Dabi Emirliği"),
                        ("uk", "Абу-Дабі"),
                        ("ur", "ابوظہبی"),
                        ("vi", "Abu Dhabi"),
                        ("yue", "阿布扎比酋長國"),
                        ("yue_Hans", "阿布扎比酋长国"),
                        ("zh", "阿布扎比"),
                    ]),
                    unofficial_name_list: [
                        "Abu Dhabi",
                        "Abu Dhabi",
                        "Abu Zabi",
                        "Abu Zaby",
                        "Abū Z\u{328}abī",
                        "أبو ظبي",
                    ]
                    .to_vec(),
                },
            ),
            (
                "DU",
                Subdivision {
                    name: "DU",
                    country_alpha2: Alpha2::AE,
                    code: "DU",
                    #[cfg(feature = "geo")]
                    geo: Some(SubdivisionGeo {
                        latitude: Some(25.2048493),
                        longitude: Some(55.2707828),
                        max_latitude: Some(25.356306),
                        min_latitude: Some(24.7914099),
                        max_longitude: Some(55.56369770000001),
                        min_longitude: Some(54.895991),
                    }),
                    comments: None,
                    subdivision_type: SubdivisionType::Emirate,
                    #[cfg(feature = "translations")]
                    translations: HashMap::from([
                        ("af", "Doebai"),
                        ("ar", "امارة دبي"),
                        ("az", "Dubay"),
                        ("be", "Эмірат Дубай"),
                        ("bg", "Дубай"),
                        ("bn", "দ\u{9c1}ব\u{9be}ই আমির\u{9be}ত"),
                        ("bs", "Dubai"),
                        ("ca", "Dubai"),
                        ("ccp", "𑄘\u{1112a}𑄝\u{1112d}"),
                        ("ceb", "Dubai"),
                        ("cs", "Dubaj"),
                        ("da", "Dubai"),
                        ("de", "Dubai"),
                        ("el", "Εμιράτο του Ντουμπάι"),
                        ("en", "Dubai"),
                        ("es", "Dubái"),
                        ("et", "Dubai emiraat"),
                        ("eu", "Dubai"),
                        ("fa", "دبی، امارات"),
                        ("fi", "Dubai"),
                        ("fr", "Dubaï"),
                        ("gl", "Dubai"),
                        ("he", "דובאי"),
                        ("hr", "Dubai"),
                        ("hu", "Dubaj"),
                        ("hy", "Դուբայի Էմիրություն"),
                        ("id", "Keamiran Dubai"),
                        ("it", "Dubai"),
                        ("ja", "ドバイ首長国"),
                        ("ka", "დუბაის საამირო"),
                        ("kk", "Дубай"),
                        ("ko", "두바이"),
                        ("ky", "Дубай"),
                        ("lv", "Dubaijas emirāts"),
                        ("mn", "Эмирт Дубай"),
                        ("nb", "Emiratet Dubai"),
                        ("ne", "द\u{941}बईको अमिरात"),
                        ("nl", "Dubai"),
                        ("no", "Emiratet Dubai"),
                        ("or", "ଦ\u{b41}ବ\u{b3e}ଇ"),
                        ("pl", "Dubaj"),
                        ("ro", "Emiratul Dubai"),
                        ("ru", "Дубай"),
                        ("sk", "Dubaj"),
                        ("sl", "Dubaj"),
                        ("sq", "Emirati i Dubait"),
                        ("sr", "Дубаи"),
                        ("sr_Latn", "Dubai"),
                        ("sv", "Emiratet Dubai"),
                        ("sw", "Dubai"),
                        ("th", "ร\u{e31}ฐด\u{e39}ไบ"),
                        ("tk", "Dubaý"),
                        ("tr", "Dubai Emirliği"),
                        ("uk", "Дубай"),
                        ("ur", "امارت دبئی"),
                        ("uz", "Dubay"),
                        ("vi", "Dubai"),
                        ("yue", "杜拜酋長國"),
                        ("yue_Hans", "杜拜酋长国"),
                        ("zh", "迪拜酋长国"),
                    ]),
                    unofficial_name_list: ["Dubai", "دبي"].to_vec(),
                },
            ),
            (
                "FU",
                Subdivision {
                    name: "FU",
                    country_alpha2: Alpha2::AE,
                    code: "FU",
                    #[cfg(feature = "geo")]
                    geo: Some(SubdivisionGeo {
                        latitude: Some(25.4110762),
                        longitude: Some(56.24822769999999),
                        max_latitude: Some(25.667782),
                        min_latitude: Some(24.907855),
                        max_longitude: Some(56.3760899),
                        min_longitude: Some(55.96323),
                    }),
                    comments: None,
                    subdivision_type: SubdivisionType::Emirate,
                    #[cfg(feature = "translations")]
                    translations: HashMap::from([
                        ("ar", "الفجيرة"),
                        ("az", "Əl-Füceyrə əmirliyi"),
                        ("be", "Эмірат Эль-Фуджайра"),
                        ("bg", "Фуджейра"),
                        ("bn", "ফ\u{9c1}জ\u{9be}য\u{9bc}র\u{9be}"),
                        ("ca", "Fujairah"),
                        ("ccp", "𑄜𑄎\u{1112d}𑄢𑄦\u{11134}"),
                        ("ceb", "Al Fujayrah"),
                        ("cs", "Fudžajra"),
                        ("da", "Fujairah"),
                        ("de", "Fudschaira"),
                        ("el", "Φουτζέιρα"),
                        ("en", "Fujairah"),
                        ("es", "Fuyaira"),
                        ("et", "Al-Fujayrah’ emiraat"),
                        ("eu", "Fujaira"),
                        ("fa", "فجیره"),
                        ("fi", "Fudžaira"),
                        ("fr", "Fujaïrah"),
                        ("gu", "ફ\u{ac1}જ\u{ac8}રા"),
                        ("he", "פוג׳יירה"),
                        ("hi", "फ\u{93c}\u{941}ज\u{948}रा"),
                        ("hr", "Fujairah"),
                        ("hy", "Ֆուջեյրայի Էմիրություն"),
                        ("id", "Fujairah"),
                        ("it", "Fujaira"),
                        ("ja", "フジャイラ"),
                        ("kn", "ಫುಜೈರಾ"),
                        ("ko", "푸자이라 토후국"),
                        ("lt", "Fudžeira"),
                        ("lv", "Fudžeiras emirāts"),
                        ("ml", "ഫ\u{d41}ജൈറ"),
                        ("mr", "फ\u{941}ज\u{948}रा"),
                        ("ms", "Fujairah"),
                        ("nb", "Emiratet Fujairah"),
                        ("nl", "Fujairah"),
                        ("no", "Emiratet Fujairah"),
                        ("pa", "ਫ\u{a3c}\u{a41}ਜ\u{a48}ਰਾ"),
                        ("pl", "Fudżajra"),
                        ("pt", "Al Fujayrah"),
                        ("ro", "Fujairah"),
                        ("ru", "Эль-Фуджайра"),
                        ("si", "ෆ\u{dd4}ජය\u{dd2}ර\u{dcf}"),
                        ("sk", "Fujairah"),
                        ("sq", "Fuxhaira"),
                        ("sr", "Фуџејра"),
                        ("sr_Latn", "Fudžejra"),
                        ("sv", "Emiratet Fujairah"),
                        ("sw", "Fujairah"),
                        ("ta", "புஜைர\u{bbe}"),
                        ("te", "ఫుజ\u{c3e}య\u{c3f}ర\u{c3e}"),
                        ("th", "ร\u{e31}ฐฟ\u{e39}ไจราห\u{e4c}"),
                        ("tr", "Füceyre"),
                        ("uk", "Фуджейра"),
                        ("ur", "فجیرہ"),
                        ("vi", "Fujairah"),
                        ("yo", "Fujairah"),
                        ("yo_BJ", "Fujairah"),
                        ("yue", "富查伊拉酋長國"),
                        ("yue_Hans", "富查伊拉酋长国"),
                        ("zh", "富吉拉"),
                    ]),
                    unofficial_name_list: ["Al Fujayrah", "Fujairah", "الفجيرة"].to_vec(),
                },
            ),
            (
                "RK",
                Subdivision {
                    name: "RK",
                    country_alpha2: Alpha2::AE,
                    code: "RK",
                    #[cfg(feature = "geo")]
                    geo: Some(SubdivisionGeo {
                        latitude: Some(25.8006926),
                        longitude: Some(55.9761994),
                        max_latitude: Some(25.9116106),
                        min_latitude: Some(25.540431),
                        max_longitude: Some(56.0727597),
                        min_longitude: Some(55.8637944),
                    }),
                    comments: None,
                    subdivision_type: SubdivisionType::Emirate,
                    #[cfg(feature = "translations")]
                    translations: HashMap::from([
                        ("ar", "رأس الخيمة"),
                        ("be", "Эмірат Рас-эль-Хайма"),
                        ("bg", "Рас ал-Хайм"),
                        ("bn", "র\u{9be}স আল-খ\u{9be}ইম\u{9be}হ"),
                        ("ca", "Ras al-Khaimah"),
                        ("ccp", "𑄢𑄌\u{11134} 𑄃𑄣\u{11134}-𑄈\u{1112d}𑄟𑄦\u{11134}"),
                        ("ceb", "Ras al-Khaimah"),
                        ("cs", "Rás al-Chajma"),
                        ("da", "Ras al-Khaimah"),
                        ("de", "Ra’s al-Chaima"),
                        ("el", "Ρας αλ-Καϊμά"),
                        ("en", "Ras al-Khaimah"),
                        ("es", "Ras al-Jaima"),
                        ("et", "Ra’s al-Khaymah’ emiraat"),
                        ("eu", "Ras al-Khaima"),
                        ("fa", "رأس\u{200c}الخیمه"),
                        ("fi", "Ra’s al-Khaima"),
                        ("fr", "Ras el Khaïmah"),
                        ("gu", "રાસ અલ-ખ\u{ac8}માહ"),
                        ("he", "ראס אל-ח׳ימה"),
                        ("hi", "रस अल ख\u{948}मा"),
                        ("hr", "Ras al-Khaimah"),
                        ("hu", "Rász el-Haima"),
                        ("hy", "Ռաս-ալ-Խայմայի էմիրություն"),
                        ("id", "Ras al-Khaimah"),
                        ("it", "Ras al-Khaima"),
                        ("kn", "ರಾಸ\u{ccd} ಅಲ\u{ccd} ಖೈಮಾ"),
                        ("ko", "라스알카이마 토후국"),
                        ("lt", "Ras al Chaima"),
                        ("lv", "Rāselhaima"),
                        ("mk", "Рас ел-Хајма"),
                        ("ml", "റ\u{d3e}സ\u{d4d} അൽ ഖൈമ"),
                        ("mr", "रास अल-ख\u{948}माह"),
                        ("ms", "Ras al-Khaimah"),
                        ("nb", "Emiratet Ras al-Khaimah"),
                        ("nl", "Ras al-Khaimah"),
                        ("no", "Emiratet Ras al-Khaimah"),
                        ("pa", "ਰਾਸ ਅਲ-ਖ\u{a3c}\u{a48}ਮਾ"),
                        ("pl", "Ras al-Chajma"),
                        ("pt", "Ras al-Khaimah"),
                        ("ro", "Ras Al-Khaimah"),
                        ("ru", "Рас-эль-Хайма"),
                        ("si", "රස\u{dca} අල\u{dca} කය\u{dd2}ම\u{dcf}හ\u{dca}"),
                        ("sk", "Rás al-Chajmá"),
                        ("sq", "Ras el-Haime"),
                        ("sr", "Рас ел Хајма"),
                        ("sr_Latn", "Ras el Hajma"),
                        ("sv", "Emiratet Ras al-Khaimah"),
                        ("sw", "Ras al-Khaimah"),
                        ("ta", "ரஃஸ\u{bcd} அல\u{bcd}-கைம\u{bbe}"),
                        ("te", "ర\u{c3e}స\u{c4d} అల\u{c4d}-ఖ\u{c48}మ\u{c3e}"),
                        ("th", "ร\u{e31}ฐราสอ\u{e31}ลไคมาห\u{e4c}"),
                        ("tr", "Resü’l-Hayme"),
                        ("uk", "Рас-ель-Хайма"),
                        ("ur", "راس الخیمہ"),
                        ("vi", "Ras al-Khaimah"),
                        ("yo", "Ras al Khaimah"),
                        ("yo_BJ", "Ras al Khaimah"),
                        ("yue", "拉斯海瑪酋長國"),
                        ("yue_Hans", "拉斯海玛酋长国"),
                        ("zh", "拉斯海玛"),
                    ]),
                    unofficial_name_list: ["Ras al-Khaimah", "إمارة رأس الخيمة"].to_vec(),
                },
            ),
            (
                "SH",
                Subdivision {
                    name: "SH",
                    country_alpha2: Alpha2::AE,
                    code: "SH",
                    #[cfg(feature = "geo")]
                    geo: Some(SubdivisionGeo {
                        latitude: Some(25.3575),
                        longitude: Some(55.390833),
                        max_latitude: Some(25.3988264),
                        min_latitude: Some(25.2344614),
                        max_longitude: Some(55.6726397),
                        min_longitude: Some(55.34973),
                    }),
                    comments: None,
                    subdivision_type: SubdivisionType::Emirate,
                    #[cfg(feature = "translations")]
                    translations: HashMap::from([
                        ("ar", "إمارة الشارقة"),
                        ("az", "Şarja"),
                        ("be", "Эмірат Шарджа"),
                        ("bg", "Шарджа"),
                        ("bn", "শ\u{9be}রজ\u{9be}হ আমির\u{9be}ত"),
                        ("ca", "Xarjah"),
                        ("ccp", "𑄥𑄢\u{11134}𑄎𑄦\u{11134}"),
                        ("ceb", "Ash Shāriqah"),
                        ("cs", "Šardžá"),
                        ("da", "Sharjah"),
                        ("de", "Schardscha"),
                        ("el", "Σαρτζάχ Εμιράτε οφ Σαρτζάχ"),
                        ("en", "Sharjah"),
                        ("es", "Sharjah"),
                        ("et", "Ash-Shāriqah’ emiraat"),
                        ("eu", "Xarja"),
                        ("fa", "شارجه"),
                        ("fi", "Šardža"),
                        ("fr", "Charjah"),
                        ("gl", "Emirato de Sharjah"),
                        ("gu", "શારજાહ અમીરાત"),
                        ("he", "שארג׳ה"),
                        ("hi", "शारजाह"),
                        ("hr", "Sharjah (emirat)"),
                        ("hy", "Շարժայի Էմիրություն"),
                        ("id", "Sharjah"),
                        ("it", "Sharja"),
                        ("ja", "シャールジャ"),
                        ("ka", "შარჯის საამირო"),
                        ("kn", "ಶಾರ\u{ccd}ಜ"),
                        ("ko", "샤르자"),
                        ("lt", "Šardža"),
                        ("lv", "Šārdžas emirāts"),
                        ("ml", "ഷ\u{d3e}ർജ"),
                        ("mr", "शारजा अमीरात"),
                        ("ms", "Sharjah"),
                        ("nb", "Emiratet Sharjah"),
                        ("nl", "Sharjah"),
                        ("no", "Emiratet Sharjah"),
                        ("pa", "ਸ\u{a3c}ਾਰਜਾ"),
                        ("pl", "Szardża"),
                        ("pt", "Sharjah"),
                        ("ro", "Sharjah"),
                        ("ru", "Шарджа"),
                        ("si", "ස\u{dcf}ජ\u{dcf} එම\u{dd2}රේට\u{dca}"),
                        ("sk", "Šardžá"),
                        ("sr", "Шарџа"),
                        ("sr_Latn", "Šardža"),
                        ("sv", "Emiratet Sharjah"),
                        ("sw", "Sharjah"),
                        ("ta", "ச\u{bbe}ர\u{bcd}ஜ\u{bbe}"),
                        ("te", "ష\u{c3e}ర\u{c4d}జ\u{c3e} ఎమ\u{c3f}ర\u{c47}ట\u{c4d}"),
                        ("th", "ร\u{e31}ฐชาร\u{e4c}จาห\u{e4c}"),
                        ("tr", "Sharjah Emirliği"),
                        ("uk", "Шарджа"),
                        ("ur", "شارجہ"),
                        ("vi", "Sharjah"),
                        ("yo", "Sharjah"),
                        ("yo_BJ", "Sharjah"),
                        ("yue", "沙迦酋長國"),
                        ("yue_Hans", "沙迦酋长国"),
                        ("zh", "夏尔迦"),
                    ]),
                    unofficial_name_list: ["Ash Shariqah", "إمارة الشارقة\u{651}"].to_vec(),
                },
            ),
            (
                "UQ",
                Subdivision {
                    name: "UQ",
                    country_alpha2: Alpha2::AE,
                    code: "UQ",
                    #[cfg(feature = "geo")]
                    geo: Some(SubdivisionGeo {
                        latitude: Some(25.5204824),
                        longitude: Some(55.7133909),
                        max_latitude: Some(25.6954771),
                        min_latitude: Some(25.323967),
                        max_longitude: Some(55.953869),
                        min_longitude: Some(55.5175201),
                    }),
                    comments: None,
                    subdivision_type: SubdivisionType::Emirate,
                    #[cfg(feature = "translations")]
                    translations: HashMap::from([
                        ("ar", "أم القيوين"),
                        ("be", "Эмірат Ум-эль-Кайвайн"),
                        ("bg", "Ум ал-Куейн"),
                        ("bn", "উম\u{9cd}ম\u{9c1}ল ক\u{9c1}য\u{9bc}\u{9be}ইন"),
                        ("ca", "Umm al-Qaiwain"),
                        (
                            "ccp",
                            "𑄅\u{1112a}𑄟\u{11134} 𑄃𑄣\u{11134}-𑄇\u{1112a}𑄠𑄃\u{11128}𑄚\u{11134}",
                        ),
                        ("ceb", "Umm al Qaywayn"),
                        ("cs", "Umm al-Kuvajn"),
                        ("da", "Umm Al Quwain"),
                        ("de", "Umm al-Qaiwain"),
                        ("el", "Ούμ Αλ Κουβέιν"),
                        ("en", "Umm al-Quwain"),
                        ("es", "Umm al-Qaywayn"),
                        ("et", "Umm al-Qaywayni emiraat"),
                        ("eu", "Umm al-Qaiwain"),
                        ("fa", "ام\u{200c}القوین"),
                        ("fi", "Umm al-Qaiwain"),
                        ("fr", "Oumm al Qaïwaïn"),
                        ("gl", "Emirato de Umm al Qaywayn"),
                        ("gu", "ઉમ અલ-ક\u{ac1}વ\u{ac8}ન"),
                        ("he", "אום אל-קיוין"),
                        ("hi", "उम अल क\u{94d}व\u{948}न"),
                        ("hr", "Umm al-Quwain"),
                        ("hy", "Ումմ ալ-Քուվեյնի Էմիրություն"),
                        ("id", "Umm al-Qaiwain"),
                        ("it", "Umm al-Qaywayn"),
                        ("ka", "უმ-ელ-კაივაინის საამირო"),
                        ("kn", "ಉಮ\u{ccd} ಅಲ\u{ccd} ಕ\u{ccd}ವೈನ\u{ccd}"),
                        ("ko", "움알쿠와인 토후국"),
                        ("lt", "Um al Kuvainas"),
                        ("lv", "Ummelkaivainas emirāts"),
                        ("ml", "ഉം അൽ ക\u{d41}വൈൻ"),
                        ("mr", "उम अल-क\u{941}व\u{948}न"),
                        ("ms", "Umm al-Qaiwain"),
                        ("nb", "Emiratet Umm al-Qaiwain"),
                        ("nl", "Umm al-Qaiwain"),
                        ("no", "Emiratet Umm al-Qaiwain"),
                        ("pa", "ਉਮ ਅਲ-ਕਿਵ\u{a47}ਨ"),
                        ("pl", "Umm al-Kajwajn"),
                        ("pt", "Umm al Qaywayn"),
                        ("ro", "Umm Al-Qaiwain"),
                        ("ru", "Умм-эль-Кайвайн"),
                        ("si", "උම\u{dca} අල\u{dca}-ක\u{dca}වේන\u{dca}"),
                        ("sk", "Umm al-Kuvajn"),
                        ("sr", "Ум ел Кајвејн"),
                        ("sr_Latn", "Um el Kajvejn"),
                        ("sv", "Emiratet Umm al-Qaywayn"),
                        ("sw", "Umm al-Quwain"),
                        ("ta", "உம\u{bcd} அல\u{bcd}-குவைன\u{bcd}"),
                        (
                            "te",
                            "ఉమ\u{c4d} అల\u{c4d}-క\u{c4d}వ\u{c3f}వ\u{c46}య\u{c3f}న\u{c4d}",
                        ),
                        ("th", "ร\u{e31}ฐอ\u{e38}มม\u{e4c}อ\u{e31}ลไกไวน\u{e4c}"),
                        ("tr", "Ummül-Kayveyn Emirliği"),
                        ("uk", "Умм-ель-Кувейн"),
                        ("ur", "ام القوین"),
                        ("vi", "Umm al-Quwain"),
                        ("yo", "Um Al Quwain"),
                        ("yo_BJ", "Um Al Quwain"),
                        ("yue", "歐姆古溫酋長國"),
                        ("yue_Hans", "欧姆古温酋长国"),
                        ("zh", "欧姆古温"),
                    ]),
                    unofficial_name_list: ["Umm al-Quwain", "أم\u{651} القيوين"].to_vec(),
                },
            ),
        ])
    }
}
#[allow(unused_imports)]
use crate::{
    Alpha2, Alpha3, Continent, Country, CurrencyCode, Region, SubRegion, WeekDay, WorldRegion, GEC,
    IOC,
};
#[allow(unused_imports)]
use std::collections::HashMap;
#[cfg(feature = "ae")]
pub fn new() -> Country {
    Country{
        alpha2: Alpha2::AE,
        alpha3: Alpha3::ARE,
        address_format: Some("{{recipient}}\n{{street}}\n{{postalcode}} {{city}}\n{{country}}"),
        continent: Continent::Asia,
        country_code: 971,
        currency_code: CurrencyCode::AED,
        gec: Some(GEC::AE),
        #[cfg(feature = "geo")]
        geo: geo::new(),
        international_prefix: "00",
        ioc: Some(IOC::UAE),
        iso_long_name: "The United Arab Emirates",
        iso_short_name: "United Arab Emirates",
        official_language_list: ["ar"].to_vec(),
        spoken_language_list: ["ar"].to_vec(),
        national_destination_code_length_list: [2].to_vec(),
        national_number_length_list: [7, 8, 9].to_vec(),
        national_prefix: "0",
        nationality: Some("Emirian"),
        number: "784",
        postal_code: false,
        postal_code_format: None,
        region: Some(Region::Asia),
        start_of_week: WeekDay::Monday,
        subregion: Some(SubRegion::WesternAsia),
        un_locode: "AE",
        unofficial_name_list: ["United Arab Emirates", "الإمارات العربية المتحدة", "Vereinigte Arabische Emirate", "Émirats Arabes Unis", "Emiratos Árabes Unidos", "アラブ首長国連邦", "Verenigde Arabische Emiraten"].to_vec(),
        world_region: WorldRegion::EMEA,
        #[cfg(feature = "translations")]
        translations: HashMap::from([("ab", "United Arab Emirates"), ("af", "Verenigde Arabiese Emirate"), ("ak", "United Arab Emirates"), ("am", "ፘተባበሩት ጐረብ ጔሤሳትስ"), ("an", "Emiratos Arabes Unius"), ("ar", "الإمارات العربي\u{651}ة المت\u{651}حدة"), ("as", "ইউন\u{9be}ইটেড আৰৱ ইমিৰেটছ"), ("ay", "United Arab Emirates"), ("az", "Birləşmiş Ərəb Əmirlikləri"), ("ba", "United Arab Emirates"), ("be", "Аб'яднаныя Арабскія Эміраты"), ("bg", "Обединени арабски емирства"), ("bi", "United Arab Emirates"), ("bn", "সংয\u{9c1}ক\u{9cd}ত আরব আমিরশ\u{9be}হী"), ("bn_IN", "সংয\u{9c1}ক\u{9cd}ত আরব আমিরশ\u{9be}হী"), ("br", "Emirelezhioù Arab Unanet"), ("bs", "Ujedinjeni Arapski Emirati"), ("ca", "Unió dels Emirats Àrabs"), ("ce", "Iаьрбийн Цхьаьнакхетта Эмираташ"), ("ch", "United Arab Emirates"), ("cs", "Spojené arabské emiráty"), ("cv", "Iаьрбийн Цхьаьнакхетта Эмираташ"), ("cy", "Emiriaethau Arabaidd Unedig"), ("da", "Forenede Arabiske Emirater"), ("de", "Vereinigte Arabische Emirate"), ("dv", "އ\u{7ac}ކ\u{7aa}ވ\u{7ac}ރ\u{7a8} ޢ\u{7a6}ރ\u{7a6}ބ\u{7a8} އ\u{7a8}މ\u{7a7}ރ\u{7a7}ތ\u{7aa}"), ("dz", "ཡ\u{f74}་ནའ\u{f72}་ཊ\u{f7a}ཊ་ ཨ་རབ་ ཨ\u{f72}་མ\u{f72}་ར\u{f7a}ཊ\u{f72}ས\u{f72}།"), ("ee", "United Arab Emirates"), ("el", "Ηνωμένα Αραβικά Εμιράτα"), ("en", "United Arab Emirates"), ("eo", "Unuiĝintaj Arabaj Emirlandoj"), ("es", "Emiratos Árabes Unidos"), ("et", "Araabia Ühendemiraadid"), ("eu", "Arabiar Emirerri Batuak"), ("fa", "امارات متحده عربی"), ("ff", "United Arab Emirates"), ("fi", "Yhdistyneet arabiemiirikunnat"), ("fo", "Sameindu arabisku emiratini"), ("fr", "Émirats arabes unis"), ("fy", "Feriene Arabyske Emiraten"), ("ga", "Aontas na nÉimíríochtaí Arabacha"), ("gl", "Emiratos Árabes Unidos"), ("gn", "United Arab Emirates"), ("gu", "ય\u{ac1}નાઇટ\u{ac7}ડ આરબ અમીરાત"), ("gv", "Ny h-Emmiraidyn Arabagh Unnaneysit"), ("ha", "Taraiyar larabawa"), ("he", "איחוד האמירויות הערביות"), ("hi", "स\u{902}य\u{941}क\u{94d}त अरब अमीरात"), ("hr", "Ujedinjeni Arapski Emirati"), ("ht", "Emira Arab Ini"), ("hu", "Egyesült Arab Emírségek"), ("hy", "Միացյալ Արաբական Էմիրաթներ"), ("ia", "Emiratos Arabe Unite"), ("id", "Uni Emirat Arab"), ("io", "Unionita Araba Emirati"), ("is", "Sameinuðu arabísku furstadæmin"), ("it", "Emirati Arabi Uniti"), ("iu", "United Arab Emirates"), ("ja", "アラブ首長国連邦"), ("ka", "არაბეთის გაერთიანებული ემირატები"), ("ki", "United Arab Emirates"), ("kk", "Біріккен Араб Әмірліктері"), ("kl", "United Arab Emirates"), ("km", "អារ\u{17c9}ាប\u{17cb}\u{200b}រ\u{17bd}ម"), ("kn", "ಯುನೈಟ\u{cc6}ಡ\u{ccd} ಅರಬ\u{ccd} ಎಮ\u{cbf}ರೇಟ\u{ccd}ಸ\u{ccd}"), ("ko", "아랍에미리트"), ("ku", "Mîrtiyên Ereb ên Yekbuyî"), ("kv", "Ӧтувтчӧм Араб Эмиратъяс"), ("kw", "Pennternasedh Unys Arabek"), ("ky", "Бириккен Араб Эмирликтери"), ("lo", "United Arab Emirates"), ("lt", "Jungtiniai Arabų Emyratai"), ("lv", "Apvienotie Arābu Emirāti"), ("mi", "United Arab Emirates"), ("mk", "Обединети арапски емирати"), ("ml", "ഐക\u{d4d}യ അറബ\u{d4d} എമിറേറ\u{d4d}റ\u{d41}കള\u{d4d}\u{200d}"), ("mn", "Арабын нэгдсэн имерат"), ("mr", "स\u{902}य\u{941}क\u{94d}त अरब अमिराती"), ("ms", "Emiriah Arab Bersatu"), ("mt", "Emirati Għarab Maqgħuda"), ("my", "အာရပ\u{103a}စော\u{103a}ဘ\u{103d}ားများပြည\u{103a}ထောင\u{103a}စ\u{102f}"), ("na", "Emireitit Arabiya"), ("nb", "De forente arabiske emirater"), ("ne", "स\u{902}य\u{941}क\u{94d}त अरब इमिर\u{947}ट\u{94d}स"), ("nl", "Verenigde Arabische Emiraten"), ("nn", "Dei sameinte arabiske emirata"), ("nv", "Ásáí Dineʼé Bikéyah Yázhí Ałhidadiidzooígíí"), ("oc", "Emirats Arabs Units"), ("or", "ସଂଯ\u{b41}କ\u{b4d}ତ ଆରବ ଏମ\u{b3f}ରେଟ"), ("pa", "ਸ\u{a70}ਯ\u{a41}ਕਤ ਰਾਜ ਅਮੀਰਾਤ"), ("pi", "United Arab Emirates"), ("pl", "Zjednoczone Emiraty Arabskie"), ("ps", "عربي متحده امارات"), ("pt", "Emirados Árabes Unidos"), ("pt_BR", "Emirados Árabes Unidos"), ("ro", "Emiratele Arabe Unite"), ("ru", "Объединённые Арабские Эмираты"), ("rw", "Repubulika Nyarabu Zunze Ubumwe"), ("sc", "Emiratos Àrabos Unidos"), ("sd", "گڏيل عرب امارات"), ("si", "එක\u{dca}සත\u{dca} අර\u{dcf}බ\u{dd2} එම\u{dd3}ර\u{dca}"), ("sk", "Spojené arabské emiráty"), ("sl", "Združeni Arabski emirati"), ("so", "Imaaraadka Carabta ee Midoobay"), ("sq", "Emiratet e Bashkuara Arabe"), ("sr", "Уједињени Арапски Емирати"), ("sv", "Förenade Arabemiraten"), ("sw", "Falme za Kiarabu"), ("ta", "ஐக\u{bcd}கிய அர\u{bbe}பிய எமிரேட\u{bcd}சு"), ("te", "యున\u{c48}ట\u{c46}డ\u{c4d} అరబ\u{c4d} ఎమ\u{c3f}ర\u{c47}ట\u{c4d}స\u{c4d}"), ("tg", "Амороти Муттаҳидаи Араб"), ("th", "สหร\u{e31}ฐอาหร\u{e31}บเอม\u{e34}เรตส\u{e4c}"), ("ti", "የተባበሩት አረብ ኤምሬትስ"), ("tk", "Birleşen Arap Emiratlary"), ("tl", "Mga Pinag-isang Arabong Emirado"), ("tr", "Birleşik Arap Emirlikleri"), ("tt", "Берләшкән Гәрәп Әмирлекләре"), ("ug", "ئەرەب بىرلەشمە خەلىپىلىكى"), ("uk", "Об’єднані Арабські Емірати"), ("ur", "متحدہ عرب امارات"), ("uz", "Birlashgan Arab Amirliklari"), ("ve", "United Arab Emirates"), ("vi", "Các Tiểu Vương Quốc A-rập Thống Nhất"), ("wa", "Emirats Arabes Unis"), ("wo", "Imaarati Araab yu Bennoo"), ("xh", "United Arab Emirates"), ("yo", "Àwọn Ẹ\u{301}mírétì Árábù Aṣọ\u{300}kan"), ("zh_CN", "阿联酋"), ("zh_HK", "阿拉伯聯合酋長國"), ("zh_TW", "阿拉伯聯合大公國"), ("zu", "United Arab Emirates")]),
        #[cfg(feature = "subdivisions")]
        subdivisions: subdivisions::new(),
    }
}
