// DO NOT TOUCH THIS FILE. (Auto-generated by `keshvar-code-generator/src/countries.rs`)

// The Territory of American Samoa

#[cfg(all(feature = "as", feature = "constants"))]
pub mod consts {
    #[allow(unused_imports)]
    use crate::{
        Alpha2, Alpha3, Continent, CurrencyCode, Region, SubRegion, WeekDay, WorldRegion, GEC, IOC,
    };

    pub const ADDRESS_FORMAT: Option<&str> = None;
    pub const ALPHA2: Alpha2 = Alpha2::AS;
    pub const ALPHA3: Alpha3 = Alpha3::ASM;
    pub const CONTINENT: Continent = Continent::Australia;
    pub const COUNTRY_CODE: usize = 1;
    pub const CURRENCY_CODE: CurrencyCode = CurrencyCode::USD;
    pub const GEC: Option<GEC> = Some(GEC::AQ);
    pub const INTERNATIONAL_PREFIX: &str = "011";
    pub const IOC: Option<IOC> = Some(IOC::ASA);
    pub const ISO_SHORT_NAME: &str = "American Samoa";
    pub const ISO_LONG_NAME: &str = "The Territory of American Samoa";
    pub const OFFICIAL_LANGUAGE_LIST: &[&str] = &["en", "sm"];
    pub const SPOKEN_LANGUAGE_LIST: &[&str] = &["en", "sm"];
    pub const NATIONAL_DESTINATION_CODE_LENGTH_LIST: &[usize] = &[3];
    pub const NATIONAL_NUMBER_LENGTH_LIST: &[usize] = &[10];
    pub const NATIONAL_PREFIX: &str = "1";
    pub const NATIONALITY: Option<&str> = Some("American Samoan");
    pub const NUMBER: &str = "016";
    pub const POSTAL_CODE: bool = true;
    pub const POSTAL_CODE_FORMAT: Option<&str> = Some("(96799)(?:[ \\-](\\d{4}))?");
    pub const REGION: Option<Region> = Some(Region::Oceania);
    pub const START_DAY_OF_WEEK: WeekDay = WeekDay::Monday;
    pub const SUBREGION: Option<SubRegion> = Some(SubRegion::Polynesia);
    pub const UN_LOCODE: &str = "AS";
    pub const UNOFFICIAL_NAME_LIST: &[&str] = &[
        "American Samoa",
        "Amerikanisch-Samoa",
        "Samoa américaines",
        "Samoa Americana",
        "アメリカ領サモア",
        "Amerikaans Samoa",
    ];
    pub const WORLD_REGION: WorldRegion = WorldRegion::APAC;
    #[cfg(feature = "translations")]
    pub const TRANSLATIONS: &[(&str, &str)] = &[
        ("ab", "American Samoa"),
        ("af", "Amerikaanse Samoa"),
        ("ak", "American Samoa"),
        ("am", "American Samoa"),
        ("an", "Samoa Americana"),
        ("ar", "صاموا الأمريكي\u{651}ة"),
        ("as", "আমেৰিক\u{9be}ন ছ\u{9be}মোআ"),
        ("ay", "American Samoa"),
        ("az", "Amerikan Samoa"),
        ("ba", "American Samoa"),
        ("be", "Амерыканскае Самоа"),
        ("bg", "Американска Самоа"),
        ("bi", "American Samoa"),
        ("bn", "আমেরিক\u{9be}ন স\u{9be}মোয়\u{9be}"),
        ("bn_IN", "আমেরিক\u{9be}ন স\u{9be}মোয়\u{9be}"),
        ("br", "Samoa Amerikan"),
        ("bs", "Američka Samoa"),
        ("ca", "Samoa Americana"),
        ("ce", "Американ Самоа"),
        ("ch", "American Samoa"),
        ("cs", "Americká Samoa"),
        ("cv", "Американ Самоа"),
        ("cy", "American Samoa"),
        ("da", "Amerikansk Samoa"),
        ("de", "Amerikanisch-Samoa"),
        (
            "dv",
            "އ\u{7ac}މ\u{7ac}ރ\u{7a8}ކ\u{7a6}ނ\u{7b0} ސ\u{7a6}މ\u{7af}އ\u{7a7}",
        ),
        ("dz", "ཨ་མ\u{f72}་ར\u{f72}་ཀ\u{f71}ན་ ས་མ\u{f7c}་འ།"),
        ("ee", "American Samoa"),
        ("el", "Αμερικανική Σαμόα"),
        ("en", "American Samoa"),
        ("eo", "Usona Samoo"),
        ("es", "Samoa Estadounidense"),
        ("et", "Ameerika Samoa"),
        ("eu", "Amerikar Samoa"),
        ("fa", "ساموآی آمریکایی"),
        ("ff", "American Samoa"),
        ("fi", "Amerikan Samoa"),
        ("fo", "Sámoa"),
        ("fr", "Samoa américaines"),
        ("fy", "Amerikaansk-Samoa"),
        ("ga", "Samó Meiriceánach"),
        ("gl", "Samoa Americana"),
        ("gn", "American Samoa"),
        ("gu", "અમ\u{ac7}રિકન સામોઆ"),
        ("gv", "American Samoa"),
        ("ha", "American Samoa"),
        ("he", "סמואה האמריקנית"),
        ("hi", "अम\u{947}रिकी समोआ"),
        ("hr", "Američka Samoa"),
        ("ht", "American Samoa"),
        ("hu", "Amerikai Szamoa"),
        ("hy", "Ամերիկյան Սամոա"),
        ("ia", "Samoa American"),
        ("id", "Samoa Amerika"),
        ("io", "Usana Samoa"),
        ("is", "Bandarísku Samóaeyjar"),
        ("it", "Samoa americane"),
        ("iu", "American Samoa"),
        ("ja", "米領サモア"),
        ("ka", "ამერიკული სამოა"),
        ("ki", "American Samoa"),
        ("kk", "Шығыс Самоа (АҚШ)"),
        ("kl", "American Samoa"),
        ("km", "អាមេរ\u{17b7}ក\u{200b}សាម\u{17bc}អា"),
        ("kn", "ಅಮೇರ\u{cbf}ಕನ\u{ccd} ಸಮೋಆ"),
        ("ko", "아메리칸사모아"),
        ("ku", "Samoya Emerîkî"),
        ("kv", "American Samoa"),
        ("kw", "Samoa Amerikan"),
        ("ky", "Америка Самоасы"),
        ("lo", "American Samoa"),
        ("lt", "Amerikos Samoa"),
        ("lv", "Amerikāņu Samoa"),
        ("mi", "Hāmoa Amerikana"),
        ("mk", "Американска Самоа"),
        ("ml", "അമേരിക\u{d4d}കന\u{d4d}\u{200d} സമോവ"),
        ("mn", "Америкын самао"),
        ("mr", "अम\u{947}रिकन समोआ"),
        ("ms", "Samoa Amerika"),
        ("mt", "Samoa Amerikana"),
        ("my", "American Samoa"),
        ("na", "American Samoa"),
        ("nb", "Amerikansk Samoa"),
        ("ne", "अम\u{947}रिकन सामोआ"),
        ("nl", "Amerikaans-Samoa"),
        ("nn", "Amerikansk Samoa"),
        ("nv", "American Samoa"),
        ("oc", "Samoa americana"),
        ("or", "ଆମେର\u{b3f}କୀୟ ସ\u{b3e}ମୋଆ"),
        ("pa", "ਅਮਰੀਕੀ ਸਾਮ\u{a4b}ਨਾ"),
        ("pi", "American Samoa"),
        ("pl", "Samoa Amerykańskie"),
        ("ps", "American Samoa"),
        ("pt", "Samoa Americana"),
        ("pt_BR", "Samoa Americana"),
        ("ro", "Samoa americană"),
        ("ru", "Американские Самоа"),
        ("rw", "Samowa Nyamerika"),
        ("sc", "Samoa Americanas"),
        ("sd", "American Samoa"),
        ("si", "ඇමර\u{dd2}ක\u{dcf}න\u{dd4} සැමෝව\u{dcf}"),
        ("sk", "Americká Samoa"),
        ("sl", "Ameriška Samoa"),
        ("so", "American Samoa"),
        ("sq", "Samoa Amerikane"),
        ("sr", "Америчка Самоа"),
        ("sv", "Amerikanska Samoa"),
        ("sw", "Marekani ya Samoa"),
        ("ta", "அமெரிக\u{bcd}க சமோவ\u{bbe}"),
        ("te", "అమ\u{c47}ర\u{c3f}కన\u{c4d} సమ\u{c4b}ఆ"),
        ("tg", "Самоаи Америка"),
        ("th", "อเมร\u{e34}ก\u{e31}นซาม\u{e31}ว"),
        ("ti", "American Samoa"),
        ("tk", "Samao Amerika"),
        ("tl", "Amerikanong Samowa"),
        ("tr", "Amerikan Samoası"),
        ("tt", "Америкалы Самоа"),
        ("ug", "ئامېرىكىغا قاراشلىق ساموئا"),
        ("uk", "Американське Самоа"),
        ("ur", "امریکی سمووا"),
        ("uz", "Sharqiy Samoa"),
        ("ve", "American Samoa"),
        ("vi", "Xa-mô-a Mỹ"),
        ("wa", "Samowa amerikinne"),
        ("wo", "Samoa gu Aamerig"),
        ("xh", "American Samoa"),
        ("yo", "Sàmóà Amẹ\u{301}ríkà"),
        ("zh_CN", "美属萨摩亚"),
        ("zh_HK", "美屬薩摩亞"),
        ("zh_TW", "美屬薩摩亞"),
        ("zu", "American Samoa"),
    ];
    #[cfg(all(feature = "as", feature = "geo", feature = "constants"))]
    pub mod geo {
        pub const LATITUDE: f64 = -14.270972;
        pub const LONGITUDE: f64 = -170.132217;
        pub const MAX_LATITUDE: f64 = -13.4056506;
        pub const MAX_LONGITUDE: f64 = -169.2059326;
        pub const MIN_LATITUDE: f64 = -14.7217608;
        pub const MIN_LONGITUDE: f64 = -171.0076904;
        pub const NORTHEAST_LATITUDE: f64 = -13.4056506;
        pub const NORTHEAST_LONGITUDE: f64 = -169.2059326;
        pub const SOUTHWEST_LATITUDE: f64 = -14.7217608;
        pub const SOUTHWEST_LONGITUDE: f64 = -171.0076904;
    }
}
#[cfg(all(feature = "as", feature = "geo"))]
pub mod geo {
    use crate::{CountryGeo, CountryGeoBound, CountryGeoBounds};

    pub fn new() -> CountryGeo {
        CountryGeo {
            latitude: -14.270972,
            longitude: -170.132217,
            max_latitude: -13.4056506,
            max_longitude: -169.2059326,
            min_latitude: -14.7217608,
            min_longitude: -171.0076904,
            bounds: CountryGeoBounds {
                northeast: CountryGeoBound {
                    latitude: -13.4056506,
                    longitude: -169.2059326,
                },
                southwest: CountryGeoBound {
                    latitude: -14.7217608,
                    longitude: -171.0076904,
                },
            },
        }
    }
}

#[cfg(all(feature = "as", feature = "subdivisions"))]
pub mod subdivisions {
    #[allow(unused_imports)]
    use crate::{Alpha2, Subdivision, SubdivisionType};
    use std::collections::HashMap;
    // In this state, We do not know if subdivisions have geo or not!
    #[cfg(feature = "geo")]
    #[allow(unused_imports)]
    use crate::SubdivisionGeo;

    pub fn new() -> HashMap<&'static str, Subdivision> {
        HashMap::from([])
    }
}
#[allow(unused_imports)]
use crate::{
    Alpha2, Alpha3, Continent, Country, CurrencyCode, Region, SubRegion, WeekDay, WorldRegion, GEC,
    IOC,
};
#[allow(unused_imports)]
use std::collections::HashMap;
#[cfg(feature = "as")]
pub fn new() -> Country {
    Country {
        alpha2: Alpha2::AS,
        alpha3: Alpha3::ASM,
        address_format: None,
        continent: Continent::Australia,
        country_code: 1,
        currency_code: CurrencyCode::USD,
        gec: Some(GEC::AQ),
        #[cfg(feature = "geo")]
        geo: geo::new(),
        international_prefix: "011",
        ioc: Some(IOC::ASA),
        iso_long_name: "The Territory of American Samoa",
        iso_short_name: "American Samoa",
        official_language_list: ["en", "sm"].to_vec(),
        spoken_language_list: ["en", "sm"].to_vec(),
        national_destination_code_length_list: [3].to_vec(),
        national_number_length_list: [10].to_vec(),
        national_prefix: "1",
        nationality: Some("American Samoan"),
        number: "016",
        postal_code: true,
        postal_code_format: Some("(96799)(?:[ \\-](\\d{4}))?"),
        region: Some(Region::Oceania),
        start_of_week: WeekDay::Monday,
        subregion: Some(SubRegion::Polynesia),
        un_locode: "AS",
        unofficial_name_list: [
            "American Samoa",
            "Amerikanisch-Samoa",
            "Samoa américaines",
            "Samoa Americana",
            "アメリカ領サモア",
            "Amerikaans Samoa",
        ]
        .to_vec(),
        world_region: WorldRegion::APAC,
        #[cfg(feature = "translations")]
        translations: HashMap::from([
            ("ab", "American Samoa"),
            ("af", "Amerikaanse Samoa"),
            ("ak", "American Samoa"),
            ("am", "American Samoa"),
            ("an", "Samoa Americana"),
            ("ar", "صاموا الأمريكي\u{651}ة"),
            ("as", "আমেৰিক\u{9be}ন ছ\u{9be}মোআ"),
            ("ay", "American Samoa"),
            ("az", "Amerikan Samoa"),
            ("ba", "American Samoa"),
            ("be", "Амерыканскае Самоа"),
            ("bg", "Американска Самоа"),
            ("bi", "American Samoa"),
            ("bn", "আমেরিক\u{9be}ন স\u{9be}মোয়\u{9be}"),
            ("bn_IN", "আমেরিক\u{9be}ন স\u{9be}মোয়\u{9be}"),
            ("br", "Samoa Amerikan"),
            ("bs", "Američka Samoa"),
            ("ca", "Samoa Americana"),
            ("ce", "Американ Самоа"),
            ("ch", "American Samoa"),
            ("cs", "Americká Samoa"),
            ("cv", "Американ Самоа"),
            ("cy", "American Samoa"),
            ("da", "Amerikansk Samoa"),
            ("de", "Amerikanisch-Samoa"),
            (
                "dv",
                "އ\u{7ac}މ\u{7ac}ރ\u{7a8}ކ\u{7a6}ނ\u{7b0} ސ\u{7a6}މ\u{7af}އ\u{7a7}",
            ),
            ("dz", "ཨ་མ\u{f72}་ར\u{f72}་ཀ\u{f71}ན་ ས་མ\u{f7c}་འ།"),
            ("ee", "American Samoa"),
            ("el", "Αμερικανική Σαμόα"),
            ("en", "American Samoa"),
            ("eo", "Usona Samoo"),
            ("es", "Samoa Estadounidense"),
            ("et", "Ameerika Samoa"),
            ("eu", "Amerikar Samoa"),
            ("fa", "ساموآی آمریکایی"),
            ("ff", "American Samoa"),
            ("fi", "Amerikan Samoa"),
            ("fo", "Sámoa"),
            ("fr", "Samoa américaines"),
            ("fy", "Amerikaansk-Samoa"),
            ("ga", "Samó Meiriceánach"),
            ("gl", "Samoa Americana"),
            ("gn", "American Samoa"),
            ("gu", "અમ\u{ac7}રિકન સામોઆ"),
            ("gv", "American Samoa"),
            ("ha", "American Samoa"),
            ("he", "סמואה האמריקנית"),
            ("hi", "अम\u{947}रिकी समोआ"),
            ("hr", "Američka Samoa"),
            ("ht", "American Samoa"),
            ("hu", "Amerikai Szamoa"),
            ("hy", "Ամերիկյան Սամոա"),
            ("ia", "Samoa American"),
            ("id", "Samoa Amerika"),
            ("io", "Usana Samoa"),
            ("is", "Bandarísku Samóaeyjar"),
            ("it", "Samoa americane"),
            ("iu", "American Samoa"),
            ("ja", "米領サモア"),
            ("ka", "ამერიკული სამოა"),
            ("ki", "American Samoa"),
            ("kk", "Шығыс Самоа (АҚШ)"),
            ("kl", "American Samoa"),
            ("km", "អាមេរ\u{17b7}ក\u{200b}សាម\u{17bc}អា"),
            ("kn", "ಅಮೇರ\u{cbf}ಕನ\u{ccd} ಸಮೋಆ"),
            ("ko", "아메리칸사모아"),
            ("ku", "Samoya Emerîkî"),
            ("kv", "American Samoa"),
            ("kw", "Samoa Amerikan"),
            ("ky", "Америка Самоасы"),
            ("lo", "American Samoa"),
            ("lt", "Amerikos Samoa"),
            ("lv", "Amerikāņu Samoa"),
            ("mi", "Hāmoa Amerikana"),
            ("mk", "Американска Самоа"),
            ("ml", "അമേരിക\u{d4d}കന\u{d4d}\u{200d} സമോവ"),
            ("mn", "Америкын самао"),
            ("mr", "अम\u{947}रिकन समोआ"),
            ("ms", "Samoa Amerika"),
            ("mt", "Samoa Amerikana"),
            ("my", "American Samoa"),
            ("na", "American Samoa"),
            ("nb", "Amerikansk Samoa"),
            ("ne", "अम\u{947}रिकन सामोआ"),
            ("nl", "Amerikaans-Samoa"),
            ("nn", "Amerikansk Samoa"),
            ("nv", "American Samoa"),
            ("oc", "Samoa americana"),
            ("or", "ଆମେର\u{b3f}କୀୟ ସ\u{b3e}ମୋଆ"),
            ("pa", "ਅਮਰੀਕੀ ਸਾਮ\u{a4b}ਨਾ"),
            ("pi", "American Samoa"),
            ("pl", "Samoa Amerykańskie"),
            ("ps", "American Samoa"),
            ("pt", "Samoa Americana"),
            ("pt_BR", "Samoa Americana"),
            ("ro", "Samoa americană"),
            ("ru", "Американские Самоа"),
            ("rw", "Samowa Nyamerika"),
            ("sc", "Samoa Americanas"),
            ("sd", "American Samoa"),
            ("si", "ඇමර\u{dd2}ක\u{dcf}න\u{dd4} සැමෝව\u{dcf}"),
            ("sk", "Americká Samoa"),
            ("sl", "Ameriška Samoa"),
            ("so", "American Samoa"),
            ("sq", "Samoa Amerikane"),
            ("sr", "Америчка Самоа"),
            ("sv", "Amerikanska Samoa"),
            ("sw", "Marekani ya Samoa"),
            ("ta", "அமெரிக\u{bcd}க சமோவ\u{bbe}"),
            ("te", "అమ\u{c47}ర\u{c3f}కన\u{c4d} సమ\u{c4b}ఆ"),
            ("tg", "Самоаи Америка"),
            ("th", "อเมร\u{e34}ก\u{e31}นซาม\u{e31}ว"),
            ("ti", "American Samoa"),
            ("tk", "Samao Amerika"),
            ("tl", "Amerikanong Samowa"),
            ("tr", "Amerikan Samoası"),
            ("tt", "Америкалы Самоа"),
            ("ug", "ئامېرىكىغا قاراشلىق ساموئا"),
            ("uk", "Американське Самоа"),
            ("ur", "امریکی سمووا"),
            ("uz", "Sharqiy Samoa"),
            ("ve", "American Samoa"),
            ("vi", "Xa-mô-a Mỹ"),
            ("wa", "Samowa amerikinne"),
            ("wo", "Samoa gu Aamerig"),
            ("xh", "American Samoa"),
            ("yo", "Sàmóà Amẹ\u{301}ríkà"),
            ("zh_CN", "美属萨摩亚"),
            ("zh_HK", "美屬薩摩亞"),
            ("zh_TW", "美屬薩摩亞"),
            ("zu", "American Samoa"),
        ]),
        #[cfg(feature = "subdivisions")]
        subdivisions: subdivisions::new(),
    }
}
