// DO NOT TOUCH THIS FILE. (Auto-generated via `code_gen/countries.rs`)

// The Republic of Cameroon

#[cfg(all(feature = "cm", feature = "constants"))]
pub mod consts {
    #[allow(unused_imports)]
    use crate::{Alpha2, Alpha3, Continent, Region, SubRegion, WeekDay, WorldRegion, GEC, IOC};

    pub const ADDRESS_FORMAT: Option<&str> = None;
    pub const ALPHA2: Alpha2 = Alpha2::CM;
    pub const ALPHA3: Alpha3 = Alpha3::CMR;
    pub const CONTINENT: Continent = Continent::Africa;
    pub const COUNTRY_CODE: usize = 237;
    pub const CURRENCY_CODE: &str = "XAF";
    pub const GEC: Option<GEC> = Some(GEC::CM);
    pub const INTERNATIONAL_PREFIX: &str = "00";
    pub const IOC: Option<IOC> = Some(IOC::CMR);
    pub const ISO_SHORT_NAME: &str = "Cameroon";
    pub const ISO_LONG_NAME: &str = "The Republic of Cameroon";
    pub const OFFICIAL_LANGUAGE_LIST: &[&str] = &["en", "fr"];
    pub const SPOKEN_LANGUAGE_LIST: &[&str] = &["en", "fr"];
    pub const NATIONAL_DESTINATION_CODE_LENGTH_LIST: &[usize] = &[2];
    pub const NATIONAL_NUMBER_LENGTH_LIST: &[usize] = &[8];
    pub const NATIONAL_PREFIX: &str = "None";
    pub const NATIONALITY: Option<&str> = Some("Cameroonian");
    pub const NUMBER: &str = "120";
    pub const POSTAL_CODE: bool = false;
    pub const POSTAL_CODE_FORMAT: Option<&str> = None;
    pub const REGION: Option<Region> = Some(Region::Africa);
    pub const START_DAY_OF_WEEK: WeekDay = WeekDay::Monday;
    pub const SUBREGION: Option<SubRegion> = Some(SubRegion::MiddleAfrica);
    pub const UN_LOCODE: &str = "CM";
    pub const UNOFFICIAL_NAME_LIST: &[&str] = &[
        "Cameroon",
        "Kamerun",
        "Cameroun",
        "Camerún",
        "カメルーン",
        "Kameroen",
    ];
    pub const WORLD_REGION: WorldRegion = WorldRegion::EMEA;
    #[cfg(feature = "translations")]
    pub const TRANSLATIONS: &[(&str, &str)] = &[
        ("ab", "Cameroon"),
        ("af", "Kameroen"),
        ("ak", "Cameroon"),
        ("am", "ጢሣሩን"),
        ("an", "Cameroon"),
        ("ar", "الكاميرون"),
        ("as", "কেমেৰ\u{9c1}ণ"),
        ("ay", "Cameroon"),
        ("az", "Kamerun"),
        ("ba", "Cameroon"),
        ("be", "Камерун"),
        ("bg", "Камерун"),
        ("bi", "Cameroon"),
        ("bn", "ক\u{9cd}য\u{9be}মের\u{9c1}ণ"),
        ("bn_IN", "ক\u{9cd}য\u{9be}মের\u{9c1}ণ"),
        ("br", "Kameroun"),
        ("bs", "Kamerun"),
        ("ca", "Camerun"),
        ("ce", "Камерун"),
        ("ch", "Cameroon"),
        ("cs", "Kamerun"),
        ("cv", "Камерун"),
        ("cy", "Cameroon"),
        ("da", "Cameroun"),
        ("de", "Kamerun"),
        ("dv", "ކ\u{7ac}މ\u{7a6}ރ\u{7ab}ނ\u{7b0}"),
        ("dz", "ཀ\u{f7a}་མ\u{f72}་ར\u{f71}\u{f74}ན།"),
        ("ee", "Cameroon"),
        ("el", "Καμερούν"),
        ("en", "Cameroon"),
        ("eo", "Kameruno"),
        ("es", "Camerún"),
        ("et", "Kamerun"),
        ("eu", "Kamerun"),
        ("fa", "کامرون"),
        ("ff", "Kamerun"),
        ("fi", "Kamerun"),
        ("fo", "Kamerun"),
        ("fr", "Cameroun"),
        ("fy", "Kameroen"),
        ("ga", "Camarún"),
        ("gl", "Camerún"),
        ("gn", "Cameroon"),
        ("gu", "ક\u{ac7}મ\u{ac7}ર\u{ac1}ન"),
        ("gv", "Cameroon"),
        ("ha", "Kameru"),
        ("he", "קמרון"),
        ("hi", "क\u{948}मर\u{941}न"),
        ("hr", "Kamerun"),
        ("ht", "Kamewoun"),
        ("hu", "Kamerun"),
        ("hy", "Կամերուն"),
        ("ia", "Camerun"),
        ("id", "Kamerun"),
        ("io", "Kamerun"),
        ("is", "Kamerún"),
        ("it", "Camerun"),
        ("iu", "Cameroon"),
        ("ja", "カメルーン"),
        ("ka", "კამერუნი"),
        ("ki", "Cameroon"),
        ("kk", "Камерун"),
        ("kl", "Cameroon"),
        ("km", "កាមេរ\u{17c9}\u{17bc}ន"),
        ("kn", "ಕ\u{ccd}ಯಾಮರ\u{cc2}ನ\u{ccd}"),
        ("ko", "카메룬"),
        ("ku", "Kamerûn"),
        ("kv", "Cameroon"),
        ("kw", "Kameroun"),
        ("ky", "Камерун"),
        ("lo", "Cameroon"),
        ("lt", "Kamerūnas"),
        ("lv", "Kamerūna"),
        ("mi", "Kamarūna"),
        ("mk", "Камерун"),
        ("ml", "ക\u{d3e}മറ\u{d42}ണ\u{d4d}\u{200d}"),
        ("mn", "Камерун"),
        ("mr", "क\u{945}म\u{947}र\u{942}न"),
        ("ms", "Kamerun"),
        ("mt", "Kamerun"),
        (
            "my",
            "ကင\u{103a}မရ\u{103d}န\u{103a}းန\u{102d}\u{102f}င\u{103a}င\u{1036}",
        ),
        ("na", "Kamerun"),
        ("nb", "Kamerun"),
        ("ne", "क\u{94d}यामर\u{941}न"),
        ("nl", "Kameroen"),
        ("nn", "Kamerun"),
        ("nv", "Táłtłʼááh Chʼosh Daadánígíí Bitooh"),
        ("oc", "Cameron"),
        ("or", "କ\u{b3e}ମେଋନ"),
        ("pa", "ਕ\u{a48}ਮਰ\u{a42}ਨ"),
        ("pi", "क\u{947}म\u{947}र\u{942}न"),
        ("pl", "Kamerun"),
        ("ps", "کامرون"),
        ("pt", "Camarões"),
        ("pt_BR", "Camarões"),
        ("ro", "Camerun"),
        ("ru", "Камерун"),
        ("rw", "Kameruni"),
        ("sc", "Camerùn"),
        ("sd", "Cameroon"),
        ("si", "කැමර\u{dd6}න\u{dca}"),
        ("sk", "Kamerun"),
        ("sl", "Kamerun"),
        ("so", "Kameruun"),
        ("sq", "Kamerun"),
        ("sr", "Камерун"),
        ("sv", "Kamerun"),
        ("sw", "Kamerun"),
        ("ta", "கேமரூன\u{bcd}"),
        ("te", "క\u{c47}మరూన\u{c4d}"),
        ("tg", "Камерун"),
        ("th", "แคเมอร\u{e39}น"),
        ("ti", "ካሜሩን"),
        ("tk", "Kamerun"),
        ("tl", "Kamerun"),
        ("tr", "Kamerun"),
        ("tt", "Камероон"),
        ("ug", "كامېرون"),
        ("uk", "Камерун"),
        ("ur", "کیمرون"),
        ("uz", "Kamerun"),
        ("ve", "Cameroon"),
        ("vi", "Ca-mơ-runh"),
        ("wa", "Camrone"),
        ("wo", "Kameroon"),
        ("xh", "Cameroon"),
        ("yo", "Kamẹrúùnù"),
        ("zh_CN", "喀麦隆"),
        ("zh_HK", "喀麥隆"),
        ("zh_TW", "喀麥隆"),
        ("zu", "IKamerooni"),
    ];
    #[cfg(all(feature = "cm", feature = "geo", feature = "constants"))]
    pub mod geo {
        pub const LATITUDE: f64 = 7.369721999999999;
        pub const LONGITUDE: f64 = 12.354722;
        pub const MAX_LATITUDE: f64 = 13.083335;
        pub const MAX_LONGITUDE: f64 = 16.1944081;
        pub const MIN_LATITUDE: f64 = 1.6559;
        pub const MIN_LONGITUDE: f64 = 8.3936001;
        pub const NORTHEAST_LATITUDE: f64 = 13.083335;
        pub const NORTHEAST_LONGITUDE: f64 = 16.1944081;
        pub const SOUTHWEST_LATITUDE: f64 = 1.6559;
        pub const SOUTHWEST_LONGITUDE: f64 = 8.3936001;
    }
}
#[cfg(all(feature = "cm", feature = "geo"))]
pub mod geo {
    use crate::{CountryGeo, CountryGeoBound, CountryGeoBounds};

    pub fn new() -> CountryGeo {
        CountryGeo {
            latitude: 7.369721999999999,
            longitude: 12.354722,
            max_latitude: 13.083335,
            max_longitude: 16.1944081,
            min_latitude: 1.6559,
            min_longitude: 8.3936001,
            bounds: CountryGeoBounds {
                northeast: CountryGeoBound {
                    latitude: 13.083335,
                    longitude: 16.1944081,
                },
                southwest: CountryGeoBound {
                    latitude: 1.6559,
                    longitude: 8.3936001,
                },
            },
        }
    }
}

#[cfg(all(feature = "cm", feature = "subdivisions"))]
pub mod subdivisions {
    use crate::Subdivision;
    use std::collections::HashMap;
    // In this state, We do not know if subdivisions have geo or not!
    #[cfg(feature = "geo")]
    #[allow(unused_imports)]
    use crate::{Alpha2, SubdivisionGeo, SubdivisionType};

    pub fn new() -> HashMap<&'static str, Subdivision> {
        HashMap::from([
            (
                "AD",
                Subdivision {
                    name: "AD",
                    country_alpha2: Alpha2::CM,
                    code: "AD",
                    #[cfg(feature = "geo")]
                    geo: Some(SubdivisionGeo {
                        latitude: Some(6.9181954),
                        longitude: Some(12.8054753),
                        max_latitude: Some(8.1690449),
                        min_latitude: Some(5.992985),
                        max_longitude: Some(15.2492441),
                        min_longitude: Some(11.173742),
                    }),
                    comments: None,
                    subdivision_type: SubdivisionType::Region,
                    #[cfg(feature = "translations")]
                    translations: HashMap::from([
                        ("ar", "محافظة آداماوا"),
                        ("be", "Рэгіён Адамава"),
                        ("bg", "Адамауа (Камерун)"),
                        ("bn", "আদ\u{9be}ম\u{9be}ওয\u{9bc}\u{9be}"),
                        ("ca", "Regió d’Adamawa"),
                        ("ccp", "𑄃𑄓𑄟𑄤"),
                        ("ceb", "Adamaoua Region"),
                        ("da", "Adamawa"),
                        ("de", "Adamaoua"),
                        ("el", "Ανταμάουα"),
                        ("en", "Adamawa"),
                        ("es", "Región Adamawa"),
                        ("et", "Adamaoua piirkond"),
                        ("fa", "استان آداماوا"),
                        ("fi", "Adamawa"),
                        ("fr", "Région de l’Adamaoua"),
                        ("gu", "આદમાવા"),
                        ("he", "מחוז אדמאווה"),
                        ("hi", "अदामावा"),
                        ("id", "Region Adamawa"),
                        ("it", "regione di Adamaoua"),
                        ("ja", "アダマワ州"),
                        ("ka", "ადამავის რეგიონი"),
                        ("kn", "ಆಡಮಾವಾ"),
                        ("ko", "아다마와 주 (카메룬)"),
                        ("lt", "Adamavos regionas"),
                        ("lv", "Adamavas reģions"),
                        ("ml", "അഡമ\u{d3e}വ\u{d3e}"),
                        ("mr", "आदावा"),
                        ("ms", "Adamawa"),
                        ("nb", "Adamawa"),
                        ("nl", "Adamaoua"),
                        ("no", "Adamawa"),
                        ("pl", "Adamawa (region)"),
                        ("pt", "Adamawa (região dos Camarões)"),
                        ("ro", "Provincia Adamawa"),
                        ("ru", "Адамава (регион Камеруна)"),
                        ("si", "අඩමව\u{dcf}"),
                        ("sv", "Adamaouaregionen"),
                        ("ta", "அடம\u{bbe}வ\u{bbe}"),
                        ("te", "ఆడమ\u{c3e}వ\u{c3e}"),
                        ("th", "ร\u{e31}ฐอดามาวา"),
                        ("tr", "Adamawa Bölgesi"),
                        ("uk", "Адамава"),
                        ("ur", "آداماوا علاقہ"),
                        ("vi", "Adamawa"),
                        ("zh", "阿达马瓦区"),
                    ]),
                    unofficial_name_list: ["Adamawa"].to_vec(),
                },
            ),
            (
                "CE",
                Subdivision {
                    name: "CE",
                    country_alpha2: Alpha2::CM,
                    code: "CE",
                    #[cfg(feature = "geo")]
                    geo: Some(SubdivisionGeo {
                        latitude: Some(4.6298411),
                        longitude: Some(11.7068294),
                        max_latitude: Some(6.262233999999999),
                        min_latitude: Some(3.139809),
                        max_longitude: Some(13.248086),
                        min_longitude: Some(10.2618951),
                    }),
                    comments: None,
                    subdivision_type: SubdivisionType::Region,
                    #[cfg(feature = "translations")]
                    translations: HashMap::from([
                        ("ar", "سنتر"),
                        ("be", "Цэнтральны рэгіён, Камерун"),
                        ("bg", "Централен регион"),
                        ("bn", "সেন\u{9cd}ট\u{9be}র"),
                        ("ca", "Regió Central"),
                        ("ccp", "𑄥𑄬𑄚\u{11134}𑄑𑄢\u{11134}"),
                        ("ceb", "Centre Region"),
                        ("da", "Centre"),
                        ("de", "Centre"),
                        ("el", "Κεντρική Περιφέρεια, Καμερούν"),
                        ("en", "Centre"),
                        ("es", "Región del Centro"),
                        ("et", "Keskpiirkond"),
                        ("fa", "منطقه مرکز"),
                        ("fi", "Centre"),
                        ("fr", "Région du Centre"),
                        ("gu", "ક\u{ac7}ન\u{acd}દ\u{acd}ર"),
                        ("he", "מחוז המרכז"),
                        ("hi", "स\u{947}\u{902}टर"),
                        ("id", "Region Tengah, Kamerun"),
                        ("it", "regione Centrale"),
                        ("ja", "中央州"),
                        ("ka", "ცენტრალური რეგიონი"),
                        ("kn", "ಕೇಂದ\u{ccd}ರ"),
                        ("ko", "중앙 주"),
                        ("lt", "Centrinis regionas"),
                        ("lv", "Centrālais reģions"),
                        ("mr", "स\u{947}\u{902}टर"),
                        ("ms", "Centre"),
                        ("nb", "Centre"),
                        ("nl", "Centre"),
                        ("no", "Centre"),
                        ("pl", "Region Centralny"),
                        ("pt", "Centro"),
                        ("ro", "Provincia Centru, Camerun"),
                        ("ru", "Центральный регион"),
                        ("si", "සෙන\u{dca}ටර\u{dca}"),
                        ("sv", "Centrumregionen"),
                        ("ta", "சென\u{bcd}டர\u{bcd}"),
                        ("te", "స\u{c46}ంటర\u{c4d}"),
                        ("th", "จ\u{e31}งหว\u{e31}ดโอต-โซน"),
                        ("tr", "Merkez Bölgesi"),
                        ("uk", "Центральний регіон"),
                        ("ur", "وسطی علاقہ"),
                        ("vi", "Vùng Miền Trung"),
                        ("yo", "àárín"),
                        ("yo_BJ", "àárín"),
                        ("zh", "中部区"),
                    ]),
                    unofficial_name_list: ["Centre"].to_vec(),
                },
            ),
            (
                "EN",
                Subdivision {
                    name: "EN",
                    country_alpha2: Alpha2::CM,
                    code: "EN",
                    #[cfg(feature = "geo")]
                    geo: Some(SubdivisionGeo {
                        latitude: Some(10.6315589),
                        longitude: Some(14.6587821),
                        max_latitude: Some(12.9797045),
                        min_latitude: Some(9.9244931),
                        max_longitude: Some(15.683687),
                        min_longitude: Some(13.363565),
                    }),
                    comments: None,
                    subdivision_type: SubdivisionType::Region,
                    #[cfg(feature = "translations")]
                    translations: HashMap::from([
                        ("ar", "الشمال الأقصى"),
                        ("be", "Крайні Паўночны рэгіён"),
                        ("bg", "Далечен Север"),
                        ("bn", "ফ\u{9be}র নর\u{9cd}থ"),
                        ("ca", "Regió de l’Extrem Nord"),
                        ("ccp", "𑄜𑄢\u{11134} 𑄚\u{11127}𑄢\u{11133}𑄗\u{11134}"),
                        ("ceb", "Far North Region"),
                        ("da", "Far North Region"),
                        ("de", "Extrême-Nord"),
                        ("el", "Περιφέρεια Απώτερου Βορρά"),
                        ("en", "Far North"),
                        ("es", "Región del Extremo Norte"),
                        ("et", "Kaug-Põhjapiirkond"),
                        ("fa", "منطقه شمال دور"),
                        ("fi", "Extrême-Nord"),
                        ("fr", "Région de l’Extrême-Nord"),
                        ("gu", "ફાર નોર\u{acd}થ"),
                        ("he", "מחוז הצפון הרחוק"),
                        ("hi", "स\u{941}द\u{942}र उत\u{94d}तर"),
                        ("id", "Region Ujung Utara"),
                        ("it", "regione dell’Estremo Nord"),
                        ("ja", "極北州"),
                        ("ka", "უკიდურესი ჩრდილოეთის რეგიონი"),
                        ("kn", "ದ\u{cc2}ರದ ಉತ\u{ccd}ತರ"),
                        ("ko", "극북부 주"),
                        ("lt", "Tolimosios Šiaurės regionas"),
                        ("lv", "Galējo Ziemeļu reģions"),
                        ("mr", "फर नॉर\u{94d}थ"),
                        ("ms", "Far North"),
                        ("nb", "Extrême-Nord"),
                        ("nl", "Extrême-Nord"),
                        ("no", "Extrême-Nord"),
                        ("pl", "Region Dalekiej Północy"),
                        ("pt", "Extremo Norte"),
                        ("ro", "Provincia Extrem Nord"),
                        ("ru", "Крайнесеверный регион"),
                        ("si", "ෆ\u{dcf}ර\u{dca} නොර\u{dca}ත\u{dca}"),
                        ("sv", "Nordligaste regionen"),
                        ("ta", "ப\u{bbe}ர\u{bcd} வடக\u{bcd}கு"),
                        ("te", "ఫ\u{c3e}ర\u{c4d} న\u{c3e}ర\u{c4d}త\u{c4d}"),
                        ("th", "ฟาร\u{e4c} น\u{e47}อท"),
                        ("tr", "Far North Bölgesi"),
                        ("uk", "Крайньопівнічний регіон"),
                        ("ur", "بعید شمالی علاقہ"),
                        ("vi", "Far North"),
                        ("zh", "極北區"),
                    ]),
                    unofficial_name_list: ["Far North"].to_vec(),
                },
            ),
            (
                "ES",
                Subdivision {
                    name: "ES",
                    country_alpha2: Alpha2::CM,
                    code: "ES",
                    #[cfg(feature = "geo")]
                    geo: Some(SubdivisionGeo {
                        latitude: Some(3.950512799999999),
                        longitude: Some(13.914399),
                        max_latitude: Some(6.0856641),
                        min_latitude: Some(1.6525479),
                        max_longitude: Some(16.1921161),
                        min_longitude: Some(12.5253721),
                    }),
                    comments: None,
                    subdivision_type: SubdivisionType::Region,
                    #[cfg(feature = "translations")]
                    translations: HashMap::from([
                        ("ar", "الشرق"),
                        ("be", "Усходні рэгіён"),
                        ("bg", "Източен регион"),
                        ("bn", "ইস\u{9cd}ট"),
                        ("ca", "Regió Est"),
                        ("ccp", "𑄛\u{1112a}𑄇\u{11134}"),
                        ("ceb", "East Region"),
                        ("da", "East"),
                        ("de", "Est"),
                        ("el", "Περιφέρεια Ανατολής, Καμερούν"),
                        ("en", "East"),
                        ("es", "Región del Este"),
                        ("et", "Idapiirkond"),
                        ("fa", "منطقه شرق"),
                        ("fi", "East"),
                        ("fr", "Région de l’Est"),
                        ("gu", "ઇસ\u{acd}ટ"),
                        ("he", "מחוז המזרח"),
                        ("hi", "प\u{942}र\u{94d}व"),
                        ("hy", "Արևելյան շրջան"),
                        ("id", "Region Timur"),
                        ("it", "regione dell’Est"),
                        ("ja", "東部州"),
                        ("ka", "აღმოსავლეთის რეგიონი"),
                        ("kn", "ಪ\u{cc2}ರ\u{ccd}ವ"),
                        ("ko", "동부 주"),
                        ("lt", "Rytų regionas"),
                        ("lv", "Austrumu reģions"),
                        ("mr", "प\u{942}र\u{94d}व"),
                        ("ms", "East"),
                        ("nb", "Est"),
                        ("nl", "Est"),
                        ("no", "Est"),
                        ("pl", "Region Wschodni"),
                        ("pt", "Região Leste"),
                        ("ro", "Regiunea de Est"),
                        ("ru", "Восточный регион"),
                        ("si", "නැගෙනහ\u{dd2}ර"),
                        ("sv", "Östra regionen (region i Kamerun)"),
                        ("ta", "ஈஸ\u{bcd}ட\u{bcd}"),
                        ("te", "తూర\u{c4d}పు"),
                        ("th", "อ\u{e35}ส"),
                        ("tr", "Doğu Bölgesi"),
                        ("uk", "Східний Регіон"),
                        ("ur", "مشرقی علاقہ"),
                        ("vi", "East"),
                        ("yo", "ilà oòrùn"),
                        ("yo_BJ", "ilà oòrùn"),
                        ("zh", "东部区"),
                    ]),
                    unofficial_name_list: ["East"].to_vec(),
                },
            ),
            (
                "LT",
                Subdivision {
                    name: "LT",
                    country_alpha2: Alpha2::CM,
                    code: "LT",
                    #[cfg(feature = "geo")]
                    geo: Some(SubdivisionGeo {
                        latitude: Some(4.1682138),
                        longitude: Some(10.0807298),
                        max_latitude: Some(5.3471799),
                        min_latitude: Some(3.2601088),
                        max_longitude: Some(11.133462),
                        min_longitude: Some(9.328249399999999),
                    }),
                    comments: None,
                    subdivision_type: SubdivisionType::Region,
                    #[cfg(feature = "translations")]
                    translations: HashMap::from([
                        ("ar", "ليتورال"),
                        ("be", "Прыбярэжны рэгіён"),
                        ("bg", "Литорал"),
                        ("bn", "লিট\u{9cd}টোর\u{9be}ল"),
                        ("ca", "Regió Litoral"),
                        ("ccp", "𑄣\u{11128}𑄑\u{1112e}𑄢𑄣\u{11134}"),
                        ("ceb", "Littoral Region"),
                        ("da", "Littoral"),
                        ("de", "Littoral"),
                        ("el", "Λιττοράλ"),
                        ("en", "Littoral"),
                        ("es", "Región del Litoral"),
                        ("et", "Rannikupiirkond"),
                        ("fa", "منطقه لیتورال"),
                        ("fi", "Littoral"),
                        ("fr", "Région du Littoral"),
                        ("gu", "લ\u{ac7}ટોરલ"),
                        ("he", "מחוז החוף"),
                        ("hi", "लिटोरल"),
                        ("hy", "Լիտտորալ"),
                        ("id", "Region Littoral"),
                        ("it", "regione del Litorale"),
                        ("ja", "リトラル州"),
                        ("ka", "სანაპირო რეგიონი"),
                        ("kn", "ಲ\u{cbf}ಟೊರಲ\u{ccd}"),
                        ("ko", "리토랄 주"),
                        ("lt", "Pakrantės regionas"),
                        ("lv", "Piekrastes reģions"),
                        ("mr", "लिट\u{94d}टोर\u{945}ल"),
                        ("ms", "Littoral"),
                        ("nb", "Littoral"),
                        ("nl", "Littoral"),
                        ("no", "Littoral"),
                        ("pl", "Region Nadmorski"),
                        ("pt", "Litoral"),
                        ("ro", "Provincia Litoral"),
                        ("ru", "Прибрежный регион"),
                        ("si", "ල\u{dd2}ට\u{dca}ටොරල\u{dca}"),
                        ("sv", "Kustregionen"),
                        ("ta", "லிட\u{bcd}டோர\u{bbe}ல\u{bcd}"),
                        ("te", "ల\u{c3f}ట\u{c4b}రల\u{c4d}"),
                        ("th", "ล\u{e34}ทโทรอล"),
                        ("tr", "Littoral Bölgesi"),
                        ("uk", "Прибережний регіон"),
                        ("ur", "لیتورال علاقہ"),
                        ("vi", "Littoral"),
                        ("zh", "濱海區"),
                    ]),
                    unofficial_name_list: ["Littoral"].to_vec(),
                },
            ),
            (
                "NO",
                Subdivision {
                    name: "NO",
                    country_alpha2: Alpha2::CM,
                    code: "NO",
                    #[cfg(feature = "geo")]
                    geo: Some(SubdivisionGeo {
                        latitude: Some(8.580901299999999),
                        longitude: Some(13.914399),
                        max_latitude: Some(10.219281),
                        min_latitude: Some(7.029078999999999),
                        max_longitude: Some(15.598204),
                        min_longitude: Some(12.2255),
                    }),
                    comments: None,
                    subdivision_type: SubdivisionType::Region,
                    #[cfg(feature = "translations")]
                    translations: HashMap::from([
                        ("ar", "المنطقة الشمالية، الكاميرون"),
                        ("be", "Паўночны рэгіён"),
                        ("bg", "Северен регион"),
                        ("bn", "নর\u{9cd}থ"),
                        ("ca", "Regió del Nord"),
                        ("ccp", "𑄘\u{11127}𑄊\u{11128}𑄚\u{11134}"),
                        ("ceb", "North Region"),
                        ("da", "North"),
                        ("de", "Nord"),
                        ("el", "Περιφέρεια του Βορρά, Καμερούν"),
                        ("en", "North"),
                        ("es", "Región del Norte"),
                        ("et", "Põhjapiirkond"),
                        ("fa", "منطقه شمال"),
                        ("fi", "North"),
                        ("fr", "Région du Nord"),
                        ("gu", "નોર\u{acd}થ"),
                        ("he", "מחוז הצפון"),
                        ("hi", "उत\u{94d}तर"),
                        ("id", "Region Utara"),
                        ("it", "regione del Nord"),
                        ("ja", "北部州"),
                        ("ka", "ჩრდილოეთის რეგიონი"),
                        ("kn", "ಉತ\u{ccd}ತರ"),
                        ("ko", "북부 주"),
                        ("lt", "Šiaurės regionas"),
                        ("lv", "Ziemeļu reģions"),
                        ("mr", "उत\u{94d}तर"),
                        ("ms", "North"),
                        ("nb", "Nord"),
                        ("nl", "Nord"),
                        ("no", "Nord"),
                        ("pl", "Region Północny"),
                        ("pt", "Região Norte"),
                        ("ro", "Provincia de Nord"),
                        ("ru", "Северный регион"),
                        ("si", "උත\u{dd4}ර\u{dd4}"),
                        ("sv", "Norra regionen (region i Kamerun)"),
                        ("ta", "நோர\u{bcd}த\u{bcd}"),
                        ("te", "ఉత\u{c4d}తర"),
                        ("th", "แถบทางเหน\u{e37}อแคเมอร\u{e39}น"),
                        ("tr", "Kuzey Bölgesi"),
                        ("uk", "Північний регіон"),
                        ("ur", "شمالی علاقہ"),
                        ("vi", "Phía Bắc"),
                        ("yo", "Àríwá"),
                        ("yo_BJ", "Àríwá"),
                        ("zh", "北部區"),
                    ]),
                    unofficial_name_list: ["Bénoué"].to_vec(),
                },
            ),
            (
                "NW",
                Subdivision {
                    name: "NW",
                    country_alpha2: Alpha2::CM,
                    code: "NW",
                    #[cfg(feature = "geo")]
                    geo: Some(SubdivisionGeo {
                        latitude: Some(6.470373899999999),
                        longitude: Some(10.439656),
                        max_latitude: Some(7.1616911),
                        min_latitude: Some(5.733760999999999),
                        max_longitude: Some(11.194967),
                        min_longitude: Some(9.6307759),
                    }),
                    comments: None,
                    subdivision_type: SubdivisionType::Region,
                    #[cfg(feature = "translations")]
                    translations: HashMap::from([
                        ("ar", "إقليم الشمال الغربي"),
                        ("be", "Паўночна-Заходні рэгіён"),
                        ("bg", "Северозападен регион"),
                        ("bn", "নর\u{9cd}থওয\u{9bc}েস\u{9cd}ট"),
                        ("ca", "Regió del Nord-oest"),
                        ("ccp", "𑄘\u{11127}𑄊\u{11128}𑄚\u{1112e}𑄘\u{11128}"),
                        ("ceb", "North-West Region"),
                        ("da", "Northwest"),
                        ("de", "Nord-Ouest"),
                        ("el", "Βορειοδυτική Περιφέρεια, Καμερούν"),
                        ("en", "Northwest"),
                        ("es", "Región del Noroeste"),
                        ("et", "Loodepiirkond"),
                        ("fa", "منطقه شمال غربی"),
                        ("fi", "Luoteisalue"),
                        ("fr", "Région du Nord-Ouest"),
                        ("gu", "નોર\u{acd}થવ\u{ac7}સ\u{acd}ટ"),
                        ("he", "מחוז צפון-מערב"),
                        ("hi", "उत\u{94d}तरप\u{942}र\u{94d}व"),
                        ("id", "Region Barat Laut"),
                        ("it", "regione del Nordovest"),
                        ("ja", "北西州"),
                        ("ka", "ჩრდილო-დასავლეთის რეგიონი"),
                        (
                            "kn",
                            "ವಾಯುವ\u{ccd}ಯ ಕ\u{ccd}ಯಾಮರ\u{cc2}ನ\u{ccd} ಪ\u{ccd}ರದೇಶ",
                        ),
                        ("ko", "북서부 주"),
                        ("lt", "Šiaurės Vakarų regionas"),
                        ("lv", "Ziemeļrietumu reģions"),
                        ("mr", "नॉर\u{94d}थव\u{947}स\u{94d}ट"),
                        ("ms", "Northwest"),
                        ("nb", "Nord-Ouest"),
                        ("nl", "Nord-Ouest"),
                        ("no", "Nord-Ouest"),
                        ("pl", "Region Północno-Zachodni"),
                        ("pt", "Noroeste"),
                        ("ro", "Provincia de Nord-Vest"),
                        ("ru", "Северо-Западный регион"),
                        ("si", "වයඹ"),
                        ("sv", "Nordvästra regionen"),
                        ("ta", "நர\u{bcd}தவ\u{bcd}ஸ\u{bcd}ட\u{bcd}"),
                        ("te", "వ\u{c3e}యవ\u{c4d}యం"),
                        ("th", "นอร\u{e4c}ทเวสต\u{e4c}"),
                        ("tr", "Kuzeybatı Bölgesi"),
                        ("uk", "Північно-Західний регіон"),
                        ("ur", "شمال مغربی علاقہ"),
                        ("vi", "Vùng Tây Bắc"),
                        ("zh", "西北區"),
                    ]),
                    unofficial_name_list: ["North-West"].to_vec(),
                },
            ),
            (
                "OU",
                Subdivision {
                    name: "OU",
                    country_alpha2: Alpha2::CM,
                    code: "OU",
                    #[cfg(feature = "geo")]
                    geo: Some(SubdivisionGeo {
                        latitude: Some(5.4638158),
                        longitude: Some(10.8000051),
                        max_latitude: Some(6.2716239),
                        min_latitude: Some(4.897807999999999),
                        max_longitude: Some(11.3210561),
                        min_longitude: Some(9.881679),
                    }),
                    comments: None,
                    subdivision_type: SubdivisionType::Region,
                    #[cfg(feature = "translations")]
                    translations: HashMap::from([
                        ("ar", "الغرب"),
                        ("be", "Заходні рэгіён, Камерун"),
                        ("bn", "ওয\u{9bc}েস\u{9cd}ট"),
                        ("ca", "Regió Oest"),
                        ("ccp", "𑄛\u{11127}𑄏\u{11128}𑄟\u{11134}"),
                        ("ceb", "West Region"),
                        ("da", "Vest Region"),
                        ("de", "Ouest"),
                        ("el", "Δυτική Περιφέρεια, Καμερούν"),
                        ("en", "West"),
                        ("es", "Región del Oeste"),
                        ("et", "Läänepiirkond"),
                        ("fa", "منطقه غرب"),
                        ("fi", "West"),
                        ("fr", "Région de l’Ouest"),
                        ("gu", "વ\u{ac7}સ\u{acd}ટ"),
                        ("he", "מחוז המערב"),
                        ("hi", "पश\u{94d}चिम"),
                        ("hy", "Արևմտյան շրջան"),
                        ("id", "Region Barat, Kamerun"),
                        ("it", "regione dell’Ovest"),
                        ("ja", "西部州"),
                        ("ka", "დასავლეთის რეგიონი"),
                        ("kn", "ಪಶ\u{ccd}ಚ\u{cbf}ಮ"),
                        ("ko", "서부 주"),
                        ("lt", "Vakarų regionas"),
                        ("lv", "Rietumu reģions"),
                        ("mr", "पश\u{94d}चिम"),
                        ("ms", "West Region, Cameroon"),
                        ("nb", "Ouest"),
                        ("nl", "Ouest"),
                        ("no", "Ouest"),
                        ("pl", "Region Zachodni"),
                        ("pt", "Oeste"),
                        ("ro", "Provincia de Vest, Camerun"),
                        ("ru", "Западный регион"),
                        ("si", "බස\u{dca}න\u{dcf}හ\u{dd2}ර"),
                        ("sv", "Västra regionen"),
                        ("ta", "வெஸ\u{bcd}ட\u{bcd}"),
                        ("te", "పశ\u{c4d}చ\u{c3f}మ"),
                        ("th", "เวส"),
                        ("tr", "Batı Bölgesi"),
                        ("uk", "Західний регіон"),
                        ("ur", "مغربی علاقہ"),
                        ("vi", "Khu vực Phía Tây"),
                        ("yo", "ìwọ\u{300} oòrùn"),
                        ("yo_BJ", "ìwɔ\u{300} oòrùn"),
                        ("zh", "西部区"),
                    ]),
                    unofficial_name_list: ["West"].to_vec(),
                },
            ),
            (
                "SU",
                Subdivision {
                    name: "SU",
                    country_alpha2: Alpha2::CM,
                    code: "SU",
                    #[cfg(feature = "geo")]
                    geo: Some(SubdivisionGeo {
                        latitude: Some(2.7202832),
                        longitude: Some(11.7068294),
                        max_latitude: Some(3.6768781),
                        min_latitude: Some(2.1588319),
                        max_longitude: Some(13.681523),
                        min_longitude: Some(9.820998),
                    }),
                    comments: None,
                    subdivision_type: SubdivisionType::Region,
                    #[cfg(feature = "translations")]
                    translations: HashMap::from([
                        ("ar", "جنوب"),
                        ("be", "Паўднёвы рэгіён"),
                        ("bn", "দক\u{9cd}ষিন/স\u{9be}উথ"),
                        ("ca", "Regió del Sud"),
                        ("ccp", "𑄘\u{11127}𑄊\u{11128}𑄚\u{11134}"),
                        ("ceb", "South Region"),
                        ("da", "Syd Region"),
                        ("de", "Sud"),
                        ("el", "Περιφέρεια του Νότου, Καμερούν"),
                        ("en", "South"),
                        ("es", "Región del Sur"),
                        ("et", "Lõunapiirkond"),
                        ("fa", "منطقه جنوب"),
                        ("fi", "South"),
                        ("fr", "Région du Sud"),
                        ("gu", "દક\u{acd}ષિણ"),
                        ("he", "מחוז הדרום"),
                        ("hi", "दक\u{94d}षिण"),
                        ("id", "Region Selatan"),
                        ("it", "regione del Sud"),
                        ("ja", "南部州"),
                        ("ka", "სამხრეთის რეგიონი"),
                        ("kn", "ದಕ\u{ccd}ಷ\u{cbf}ಣ"),
                        ("ko", "남부 주"),
                        ("lt", "Pietų regionas"),
                        ("lv", "Dienvidu reģions"),
                        ("mr", "दक\u{94d}षिण"),
                        ("ms", "South Region, Cameroon"),
                        ("nb", "Sud"),
                        ("nl", "Sud"),
                        ("no", "Sud"),
                        ("pl", "Region Południowy"),
                        ("pt", "Região Sul"),
                        ("ro", "Provincia de Sud"),
                        ("ru", "Южный регион"),
                        ("si", "දක\u{dd4}ණ"),
                        ("sv", "Södra regionen (region i Kamerun)"),
                        ("ta", "சவுத\u{bcd}"),
                        ("te", "దక\u{c4d}ష\u{c3f}ణ"),
                        ("th", "เซาท\u{e4c}"),
                        ("tr", "Güney Bölgesi"),
                        ("uk", "Південий регіон"),
                        ("ur", "جنوبی علاقہ"),
                        ("vi", "Khu vực Phía Nam"),
                        ("yo", "Gúúsù"),
                        ("yo_BJ", "Gúúsù"),
                        ("zh", "南部区"),
                    ]),
                    unofficial_name_list: ["South"].to_vec(),
                },
            ),
            (
                "SW",
                Subdivision {
                    name: "SW",
                    country_alpha2: Alpha2::CM,
                    code: "SW",
                    #[cfg(feature = "geo")]
                    geo: Some(SubdivisionGeo {
                        latitude: Some(5.1573493),
                        longitude: Some(9.367308399999999),
                        max_latitude: Some(6.530783899999999),
                        min_latitude: Some(3.9221987),
                        max_longitude: Some(10.15105),
                        min_longitude: Some(8.4947634),
                    }),
                    comments: None,
                    subdivision_type: SubdivisionType::Region,
                    #[cfg(feature = "translations")]
                    translations: HashMap::from([
                        ("ar", "جنوب غرب"),
                        ("be", "Паўднёва-Заходні рэгіён, Камерун"),
                        ("bn", "স\u{9be}উথওয\u{9bc}েস\u{9cd}ট"),
                        ("ca", "Regió del Sud-oest"),
                        ("ccp", "𑄘\u{11127}𑄊\u{11128}𑄚\u{1112e}𑄘\u{11128}"),
                        ("ceb", "South-West Region"),
                        ("da", "Sydvest region"),
                        ("de", "Sud-Ouest"),
                        ("el", "Νοτιοδυτική Περιφέρεια, Καμερούν"),
                        ("en", "Southwest"),
                        ("es", "Región del Sudoeste"),
                        ("et", "Edelapiirkond"),
                        ("fa", "منطقه جنوب غربی"),
                        ("fi", "Southwest"),
                        ("fr", "Région du Sud-Ouest"),
                        ("gu", "સાઉથવ\u{ac7}સ\u{acd}ટ"),
                        ("he", "מחוז דרום-מערב"),
                        ("hi", "दक\u{94d}षिण पश\u{94d}चिम"),
                        ("hy", "Հարավարևմտյան շրջան"),
                        ("id", "Region Barat Daya, Kamerun"),
                        ("it", "regione del Sudovest"),
                        ("ja", "南西州"),
                        ("ka", "სამხრეთ-დასავლეთის რეგიონი"),
                        ("kn", "ನೈಋತ\u{ccd}ಯ"),
                        ("ko", "남서부 주"),
                        ("lt", "Pietvakarių regionas"),
                        ("lv", "Dienvidrietumu reģions"),
                        ("mr", "साऊथव\u{947}स\u{94d}ट"),
                        ("ms", "Southwest"),
                        ("nb", "Sud-Ouest"),
                        ("nl", "Sud-Ouest"),
                        ("no", "Sud-Ouest"),
                        ("pl", "Region Południowo-Zachodni"),
                        ("pt", "Sudoeste"),
                        ("ro", "Provincia de Sud-Vest, Camerun"),
                        ("ru", "Юго-Западный регион"),
                        ("si", "දක\u{dd4}ණ\u{dd4} බටහ\u{dd2}ර"),
                        ("sv", "Sydvästra regionen (region i Kamerun)"),
                        ("ta", "சௌதவெஸ\u{bcd}ட\u{bcd}"),
                        ("te", "వ\u{c3e}యవ\u{c4d}య"),
                        ("th", "เซาร\u{e4c}ทเวส"),
                        ("tr", "Güneybatı Bölgesi"),
                        ("uk", "Південно-Західний регіон"),
                        ("ur", "جنوب مغربی علاقہ"),
                        ("vi", "Vùng Tây Nam"),
                        ("zh", "西南区"),
                    ]),
                    unofficial_name_list: ["South-West"].to_vec(),
                },
            ),
        ])
    }
}
#[allow(unused_imports)]
use crate::{
    Alpha2, Alpha3, Continent, Country, Region, SubRegion, WeekDay, WorldRegion, GEC, IOC,
};
#[allow(unused_imports)]
use std::collections::HashMap;
#[cfg(feature = "cm")]
pub fn new() -> Country {
    Country {
        alpha2: Alpha2::CM,
        alpha3: Alpha3::CMR,
        address_format: None,
        continent: Continent::Africa,
        country_code: 237,
        currency_code: "XAF",
        gec: Some(GEC::CM),
        #[cfg(feature = "geo")]
        geo: geo::new(),
        international_prefix: "00",
        ioc: Some(IOC::CMR),
        iso_long_name: "The Republic of Cameroon",
        iso_short_name: "Cameroon",
        official_language_list: ["en", "fr"].to_vec(),
        spoken_language_list: ["en", "fr"].to_vec(),
        national_destination_code_length_list: [2].to_vec(),
        national_number_length_list: [8].to_vec(),
        national_prefix: "None",
        nationality: Some("Cameroonian"),
        number: "120",
        postal_code: false,
        postal_code_format: None,
        region: Some(Region::Africa),
        start_of_week: WeekDay::Monday,
        subregion: Some(SubRegion::MiddleAfrica),
        un_locode: "CM",
        unofficial_name_list: [
            "Cameroon",
            "Kamerun",
            "Cameroun",
            "Camerún",
            "カメルーン",
            "Kameroen",
        ]
        .to_vec(),
        world_region: WorldRegion::EMEA,
        #[cfg(feature = "translations")]
        translations: HashMap::from([
            ("ab", "Cameroon"),
            ("af", "Kameroen"),
            ("ak", "Cameroon"),
            ("am", "ጢሣሩን"),
            ("an", "Cameroon"),
            ("ar", "الكاميرون"),
            ("as", "কেমেৰ\u{9c1}ণ"),
            ("ay", "Cameroon"),
            ("az", "Kamerun"),
            ("ba", "Cameroon"),
            ("be", "Камерун"),
            ("bg", "Камерун"),
            ("bi", "Cameroon"),
            ("bn", "ক\u{9cd}য\u{9be}মের\u{9c1}ণ"),
            ("bn_IN", "ক\u{9cd}য\u{9be}মের\u{9c1}ণ"),
            ("br", "Kameroun"),
            ("bs", "Kamerun"),
            ("ca", "Camerun"),
            ("ce", "Камерун"),
            ("ch", "Cameroon"),
            ("cs", "Kamerun"),
            ("cv", "Камерун"),
            ("cy", "Cameroon"),
            ("da", "Cameroun"),
            ("de", "Kamerun"),
            ("dv", "ކ\u{7ac}މ\u{7a6}ރ\u{7ab}ނ\u{7b0}"),
            ("dz", "ཀ\u{f7a}་མ\u{f72}་ར\u{f71}\u{f74}ན།"),
            ("ee", "Cameroon"),
            ("el", "Καμερούν"),
            ("en", "Cameroon"),
            ("eo", "Kameruno"),
            ("es", "Camerún"),
            ("et", "Kamerun"),
            ("eu", "Kamerun"),
            ("fa", "کامرون"),
            ("ff", "Kamerun"),
            ("fi", "Kamerun"),
            ("fo", "Kamerun"),
            ("fr", "Cameroun"),
            ("fy", "Kameroen"),
            ("ga", "Camarún"),
            ("gl", "Camerún"),
            ("gn", "Cameroon"),
            ("gu", "ક\u{ac7}મ\u{ac7}ર\u{ac1}ન"),
            ("gv", "Cameroon"),
            ("ha", "Kameru"),
            ("he", "קמרון"),
            ("hi", "क\u{948}मर\u{941}न"),
            ("hr", "Kamerun"),
            ("ht", "Kamewoun"),
            ("hu", "Kamerun"),
            ("hy", "Կամերուն"),
            ("ia", "Camerun"),
            ("id", "Kamerun"),
            ("io", "Kamerun"),
            ("is", "Kamerún"),
            ("it", "Camerun"),
            ("iu", "Cameroon"),
            ("ja", "カメルーン"),
            ("ka", "კამერუნი"),
            ("ki", "Cameroon"),
            ("kk", "Камерун"),
            ("kl", "Cameroon"),
            ("km", "កាមេរ\u{17c9}\u{17bc}ន"),
            ("kn", "ಕ\u{ccd}ಯಾಮರ\u{cc2}ನ\u{ccd}"),
            ("ko", "카메룬"),
            ("ku", "Kamerûn"),
            ("kv", "Cameroon"),
            ("kw", "Kameroun"),
            ("ky", "Камерун"),
            ("lo", "Cameroon"),
            ("lt", "Kamerūnas"),
            ("lv", "Kamerūna"),
            ("mi", "Kamarūna"),
            ("mk", "Камерун"),
            ("ml", "ക\u{d3e}മറ\u{d42}ണ\u{d4d}\u{200d}"),
            ("mn", "Камерун"),
            ("mr", "क\u{945}म\u{947}र\u{942}न"),
            ("ms", "Kamerun"),
            ("mt", "Kamerun"),
            (
                "my",
                "ကင\u{103a}မရ\u{103d}န\u{103a}းန\u{102d}\u{102f}င\u{103a}င\u{1036}",
            ),
            ("na", "Kamerun"),
            ("nb", "Kamerun"),
            ("ne", "क\u{94d}यामर\u{941}न"),
            ("nl", "Kameroen"),
            ("nn", "Kamerun"),
            ("nv", "Táłtłʼááh Chʼosh Daadánígíí Bitooh"),
            ("oc", "Cameron"),
            ("or", "କ\u{b3e}ମେଋନ"),
            ("pa", "ਕ\u{a48}ਮਰ\u{a42}ਨ"),
            ("pi", "क\u{947}म\u{947}र\u{942}न"),
            ("pl", "Kamerun"),
            ("ps", "کامرون"),
            ("pt", "Camarões"),
            ("pt_BR", "Camarões"),
            ("ro", "Camerun"),
            ("ru", "Камерун"),
            ("rw", "Kameruni"),
            ("sc", "Camerùn"),
            ("sd", "Cameroon"),
            ("si", "කැමර\u{dd6}න\u{dca}"),
            ("sk", "Kamerun"),
            ("sl", "Kamerun"),
            ("so", "Kameruun"),
            ("sq", "Kamerun"),
            ("sr", "Камерун"),
            ("sv", "Kamerun"),
            ("sw", "Kamerun"),
            ("ta", "கேமரூன\u{bcd}"),
            ("te", "క\u{c47}మరూన\u{c4d}"),
            ("tg", "Камерун"),
            ("th", "แคเมอร\u{e39}น"),
            ("ti", "ካሜሩን"),
            ("tk", "Kamerun"),
            ("tl", "Kamerun"),
            ("tr", "Kamerun"),
            ("tt", "Камероон"),
            ("ug", "كامېرون"),
            ("uk", "Камерун"),
            ("ur", "کیمرون"),
            ("uz", "Kamerun"),
            ("ve", "Cameroon"),
            ("vi", "Ca-mơ-runh"),
            ("wa", "Camrone"),
            ("wo", "Kameroon"),
            ("xh", "Cameroon"),
            ("yo", "Kamẹrúùnù"),
            ("zh_CN", "喀麦隆"),
            ("zh_HK", "喀麥隆"),
            ("zh_TW", "喀麥隆"),
            ("zu", "IKamerooni"),
        ]),
        #[cfg(feature = "subdivisions")]
        subdivisions: subdivisions::new(),
    }
}
