// DO NOT TOUCH THIS FILE. (Auto-generated via `code_gen/countries.rs`)

// The Republic of Guinea-Bissau

#[cfg(all(feature = "gw", feature = "constants"))]
pub mod consts {
    #[allow(unused_imports)]
    use crate::{Alpha2, Alpha3, Continent, Region, SubRegion, WeekDay, WorldRegion, GEC};

    pub const ADDRESS_FORMAT: Option<&str> = None;
    pub const ALPHA2: Alpha2 = Alpha2::GW;
    pub const ALPHA3: Alpha3 = Alpha3::GNB;
    pub const CONTINENT: Continent = Continent::Africa;
    pub const COUNTRY_CODE: usize = 245;
    pub const CURRENCY_CODE: &str = "XOF";
    pub const GEC: Option<GEC> = Some(GEC::PU);
    pub const INTERNATIONAL_PREFIX: &str = "00";
    pub const IOC: Option<&str> = Some("GBS");
    pub const ISO_SHORT_NAME: &str = "Guinea-Bissau";
    pub const ISO_LONG_NAME: &str = "The Republic of Guinea-Bissau";
    pub const OFFICIAL_LANGUAGE_LIST: &[&str] = &["pt"];
    pub const SPOKEN_LANGUAGE_LIST: &[&str] = &["pt"];
    pub const NATIONAL_DESTINATION_CODE_LENGTH_LIST: &[usize] = &[2];
    pub const NATIONAL_NUMBER_LENGTH_LIST: &[usize] = &[7];
    pub const NATIONAL_PREFIX: &str = "None";
    pub const NATIONALITY: Option<&str> = Some("Guinea-Bissauan");
    pub const NUMBER: &str = "624";
    pub const POSTAL_CODE: bool = true;
    pub const POSTAL_CODE_FORMAT: Option<&str> = Some("\\d{4}");
    pub const REGION: Option<Region> = Some(Region::Africa);
    pub const START_DAY_OF_WEEK: WeekDay = WeekDay::Monday;
    pub const SUBREGION: Option<SubRegion> = Some(SubRegion::WesternAfrica);
    pub const UN_LOCODE: &str = "GW";
    pub const UNOFFICIAL_NAME_LIST: &[&str] = &[
        "Guinea-Bissau",
        "Guinée-Bissau",
        "ギニアビサウ",
        "Guinee-Bissau",
        "Guinea Bissau",
    ];
    pub const WORLD_REGION: WorldRegion = WorldRegion::EMEA;
    #[cfg(feature = "translations")]
    pub const TRANSLATIONS: &[(&str, &str)] = &[
        ("ab", "Guinea-Bissau"),
        ("af", "Guinee-Bissau"),
        ("ak", "Guinea-Bissau"),
        ("am", "ቢሳፅ"),
        ("an", "Guinea-Bissau"),
        ("ar", "غينيا بيساو"),
        ("as", "গিনি-বিছ\u{9be}উ"),
        ("ay", "Guinea-Bissau"),
        ("az", "Qvineya Bissau"),
        ("ba", "Guinea-Bissau"),
        ("be", "Гвінея-Бісау"),
        ("bg", "Гвинея-Бисау"),
        ("bi", "Guinea-Bissau"),
        ("bn", "গিনি-বিস\u{9be}উ"),
        ("bn_IN", "গিনি-বিস\u{9be}উ"),
        ("br", "Ginea-Bissau"),
        ("bs", "Gvineja Bisau"),
        ("ca", "Guinea Bissau"),
        ("ce", "Гвине-Бисау"),
        ("ch", "Guinea-Bissau"),
        ("cs", "Guinea-Bissau"),
        ("cv", "Гвине-Бисау"),
        ("cy", "Guinea-Bissau"),
        ("da", "Guinea-Bissau"),
        ("de", "Guinea-Bissau"),
        ("dv", "ގ\u{7a9}ނ\u{7a9}-ބ\u{7a8}ސ\u{7a7}އ\u{7ab}"),
        ("dz", "ག\u{f72}་ན\u{f72}་-བ\u{f72}་སའ\u{f7c}།"),
        ("ee", "Guinea-Bissau"),
        ("el", "Γουινέα-Μπισσάου"),
        ("en", "Guinea-Bissau"),
        ("eo", "Gvineo Bisaŭa"),
        ("es", "Guinea-Bisáu"),
        ("et", "Guinea-Bissau"),
        ("eu", "Ginea Bissau"),
        ("fa", "گینه\u{654} بیسائو"),
        ("ff", "Gine-Bisaawo"),
        ("fi", "Guinea-Bissau"),
        ("fo", "Guinea Bissau"),
        ("fr", "Guinée-Bissau"),
        ("fy", "Guinee-Bissau"),
        ("ga", "An Ghuine-Bhissau"),
        ("gl", "Guinea-Bissau"),
        ("gn", "Guinea-Bissau"),
        ("gu", "ગિએના-બિસાઉ"),
        ("gv", "Yn Ghuinea-Bissau"),
        ("ha", "Guinea-Bissau"),
        ("he", "גינאה ביסאו"),
        ("hi", "गिनी-बिसाऊ"),
        ("hr", "Gvineja Bisau"),
        ("ht", "Gine-Bisao"),
        ("hu", "Bissau-Guinea"),
        ("hy", "Գվինեա-Բիսաու"),
        ("ia", "Guinea-Bissau"),
        ("id", "Guinea-Bissau"),
        ("io", "Guinea Bisau"),
        ("is", "Gínea-Bissá"),
        ("it", "Guinea-Bissau"),
        ("iu", "Guinea-Bissau"),
        ("ja", "ギニアビサウ"),
        ("ka", "გვინეა-ბისაუ"),
        ("ki", "Guinea-Bissau"),
        ("kk", "Гвинея-Бисау"),
        ("kl", "Guinea-Bissau"),
        ("km", "ហ\u{17d2}គ\u{17b8}ណេប\u{17ca}\u{17b8}សៅ"),
        ("kn", "ಗ\u{cbf}ನೀ-ಬ\u{cbf}ಸ\u{ccd}ಸೋ"),
        ("ko", "기니비사우"),
        ("ku", "Gîneya Bisoî"),
        ("kv", "Guinea-Bissau"),
        ("kw", "Gyni-Bissaw"),
        ("ky", "Гвинея-Бисау"),
        ("lo", "Guinea-Bissau"),
        ("lt", "Bisau Gvinėja"),
        ("lv", "Gvineja-Bisava"),
        ("mi", "Kini Pihō"),
        ("mk", "Гвинеја-Бисау"),
        ("ml", "ഗിനിയ-ബിസ\u{d4d}സ\u{d3e}വ\u{d41}"),
        ("mn", "Guinea-Bissau"),
        ("mr", "गिनी-बिसाव"),
        ("ms", "Guinea Bissau"),
        ("mt", "Ginea-Bissaw"),
        (
            "my",
            "ဂင\u{103a}းန\u{102e}ဗစ\u{103a}ဆောန\u{102d}\u{102f}င\u{103a}င\u{1036}",
        ),
        ("na", "Gini-Bitau"),
        ("nb", "Guinea-Bissau"),
        ("ne", "गिइनि बिसाउ"),
        ("nl", "Guinee-Bissau"),
        ("nn", "Guinea-Bissau"),
        ("nv", "Gíní Bisó"),
        ("oc", "Guinèa-Bissau"),
        ("or", "ଗ\u{b3f}ନୀ-ବ\u{b3f}ସ\u{b41}"),
        ("pa", "ਗ\u{a41}ਨ\u{a47}ਆ-ਬਿਸਾਉ"),
        ("pi", "गिनी-बिसो"),
        ("pl", "Gwinea Bissau"),
        ("ps", "Guinea-Bissau"),
        ("pt", "Guiné-Bissáu"),
        ("pt_BR", "Guiné-Bissau"),
        ("ro", "Guinea-Bissau"),
        ("ru", "Гвинея-Бисау"),
        ("rw", "Guneya-Biso"),
        ("sc", "Guinea-Bissau"),
        ("sd", "Guinea-Bissau"),
        ("si", "ග\u{dd2}න\u{dd2}ය\u{dcf}-බ\u{dd2}සව\u{dca}"),
        ("sk", "Guinea-Bissau"),
        ("sl", "Gvineja Bissau"),
        ("so", "Guinea-Bissau"),
        ("sq", "Guinea-Bisau"),
        ("sr", "Гвинеја-Бисао"),
        ("sv", "Guinea-Bissau"),
        ("sw", "Guinea-Bissau"),
        ("ta", "கினி-ப\u{bc0}சோ"),
        ("te", "గ\u{c3f}న\u{c40}-బ\u{c3f}స\u{c3e}వ"),
        ("tg", "Гвинея-Бисау"),
        ("th", "ก\u{e34}น\u{e35}บ\u{e34}สเซา"),
        ("ti", "ቢሳዎ"),
        ("tk", "Gwineýa-Bisau"),
        ("tl", "Guinea-Bissau"),
        ("tr", "Gine-Bissau"),
        ("tt", "Gуинеа-Биссау"),
        ("ug", "گىۋىنېيە بىسسائۇ"),
        ("uk", "Гвінея-Бісау"),
        ("ur", "گنی بساؤ"),
        ("uz", "Gvineya-Bissau"),
        ("ve", "Guinea-Bissau"),
        ("vi", "Ghi-nê Bi-xau"),
        ("wa", "Guinêye-Bissaw"),
        ("wo", "Ginne Bisaawóo"),
        ("xh", "Guinea-Bissau"),
        ("yo", "Guinea-Bissau"),
        ("zh_CN", "几内亚比绍"),
        ("zh_HK", "畿內亞比紹"),
        ("zh_TW", "幾內亞比索"),
        ("zu", "IGini Bisawu"),
    ];
    #[cfg(all(feature = "gw", feature = "geo", feature = "constants"))]
    pub mod geo {
        pub const LATITUDE: f64 = 11.803749;
        pub const LONGITUDE: f64 = -15.180413;
        pub const MAX_LATITUDE: f64 = 12.6869468;
        pub const MAX_LONGITUDE: f64 = -13.6265235;
        pub const MIN_LATITUDE: f64 = 10.7146;
        pub const MIN_LONGITUDE: f64 = -16.9518999;
        pub const NORTHEAST_LATITUDE: f64 = 12.6869468;
        pub const NORTHEAST_LONGITUDE: f64 = -13.6265235;
        pub const SOUTHWEST_LATITUDE: f64 = 10.7146;
        pub const SOUTHWEST_LONGITUDE: f64 = -16.9518999;
    }
}
#[cfg(all(feature = "gw", feature = "geo"))]
pub mod geo {
    use crate::{CountryGeo, CountryGeoBound, CountryGeoBounds};

    pub fn new() -> CountryGeo {
        CountryGeo {
            latitude: 11.803749,
            longitude: -15.180413,
            max_latitude: 12.6869468,
            max_longitude: -13.6265235,
            min_latitude: 10.7146,
            min_longitude: -16.9518999,
            bounds: CountryGeoBounds {
                northeast: CountryGeoBound {
                    latitude: 12.6869468,
                    longitude: -13.6265235,
                },
                southwest: CountryGeoBound {
                    latitude: 10.7146,
                    longitude: -16.9518999,
                },
            },
        }
    }
}

#[cfg(all(feature = "gw", feature = "subdivisions"))]
pub mod subdivisions {
    use crate::Subdivision;
    use std::collections::HashMap;
    // In this state, We do not know if subdivisions have geo or not!
    #[cfg(feature = "geo")]
    #[allow(unused_imports)]
    use crate::{Alpha2, SubdivisionGeo, SubdivisionType};

    pub fn new() -> HashMap<&'static str, Subdivision> {
        HashMap::from([
            (
                "BA",
                Subdivision {
                    name: "BA",
                    country_alpha2: Alpha2::GW,
                    code: "BA",
                    #[cfg(feature = "geo")]
                    geo: Some(SubdivisionGeo {
                        latitude: Some(12.171944),
                        longitude: Some(-14.6575),
                        max_latitude: Some(12.2007357),
                        min_latitude: Some(12.1559758),
                        max_longitude: Some(-14.6261502),
                        min_longitude: Some(-14.6747733),
                    }),
                    comments: None,
                    subdivision_type: SubdivisionType::Region,
                    #[cfg(feature = "translations")]
                    translations: HashMap::from([
                        ("ar", "محافظة بافاتا"),
                        ("bg", "Бафата"),
                        ("bn", "বোফ\u{9be}ত\u{9be} অঞ\u{9cd}চল"),
                        ("ca", "Regió de Bafatá"),
                        ("ccp", "𑄝𑄜𑄑"),
                        ("ceb", "Bafatá"),
                        ("cs", "Bafatá"),
                        ("da", "Bafatá Region"),
                        ("de", "Region Bafatá"),
                        ("el", "Μπαφατά"),
                        ("en", "Bafatá"),
                        ("es", "Región de Bafatá"),
                        ("fi", "Bafatán alue"),
                        ("fr", "Région Bafatá"),
                        ("gu", "બફતા પ\u{acd}રદ\u{ac7}શ"),
                        ("hi", "बफाटा क\u{94d}ष\u{947}त\u{94d}र"),
                        ("id", "Wilayah Bafatá"),
                        ("it", "regione di Bafatá"),
                        ("ja", "バファタ州"),
                        ("kn", "ಬಫಾಟಾ ಪ\u{ccd}ರದೇಶ"),
                        ("ko", "바파타 주"),
                        ("lt", "Bafatos regionas"),
                        ("lv", "Bafatas reģions"),
                        ("mr", "बाफता प\u{94d}रद\u{947}श"),
                        ("ms", "Bafata Region"),
                        ("nb", "Bafatá"),
                        ("nl", "Bafatá"),
                        ("no", "Bafatá"),
                        ("pl", "Region Bafatá"),
                        ("pt", "Bafatá (região)"),
                        ("ro", "Regiunea Bafatá"),
                        ("ru", "Бафата"),
                        ("si", "බෆ\u{dcf}ට\u{dcf} කල\u{dcf}පය"),
                        ("sv", "Bafatá (region)"),
                        ("ta", "ப\u{bbe}ப\u{bbe}ட பகுதி"),
                        ("te", "బఫ\u{c3e}ట\u{c3e} ప\u{c4d}ర\u{c3e}ంతం"),
                        ("th", "เขตบาฟาตา"),
                        ("tr", "Bafata Bölgesi"),
                        ("uk", "Бафата"),
                        ("ur", "بافاتا ریجن"),
                        ("vi", "Khu vực Bafatá"),
                        ("zh", "巴法塔區"),
                    ]),
                    unofficial_name_list: ["Bafatá"].to_vec(),
                },
            ),
            (
                "BL",
                Subdivision {
                    name: "BL",
                    country_alpha2: Alpha2::GW,
                    code: "BL",
                    #[cfg(feature = "geo")]
                    geo: Some(SubdivisionGeo {
                        latitude: Some(11.5770712),
                        longitude: Some(-15.4800382),
                        max_latitude: Some(11.5904801),
                        min_latitude: Some(11.5640396),
                        max_longitude: Some(-15.4710599),
                        min_longitude: Some(-15.4946602),
                    }),
                    comments: None,
                    subdivision_type: SubdivisionType::Region,
                    #[cfg(feature = "translations")]
                    translations: HashMap::from([
                        ("ar", "إقليم بولاما"),
                        ("bg", "Болама"),
                        ("bn", "ব\u{9c1}ল\u{9be}ম\u{9be} অঞ\u{9cd}চল"),
                        ("ca", "Regió de Bolama"),
                        ("ccp", "𑄝\u{11127}𑄣𑄟"),
                        ("ceb", "Bolama"),
                        ("cs", "Bolama"),
                        ("da", "Bolama Region"),
                        ("de", "Bolama"),
                        ("el", "Μπολάμα"),
                        ("en", "Bolama"),
                        ("es", "Región de Bolama"),
                        ("et", "Bolama piirkond"),
                        ("fi", "Bolaman alue"),
                        ("fr", "Bolama-Bijagos"),
                        ("gu", "બોલમા પ\u{acd}રદ\u{ac7}શ"),
                        ("hi", "बोलामा प\u{94d}रद\u{947}श"),
                        ("id", "Wilayah Bolama"),
                        ("it", "regione di Bolama"),
                        ("ja", "ボラマ州"),
                        ("kn", "ಬೋಲಾಮಾ ಪ\u{ccd}ರದೇಶ"),
                        ("ko", "볼라마 주"),
                        ("lt", "Bolamos regionas"),
                        ("lv", "Bolamas reģions"),
                        ("mr", "बोलमा प\u{94d}रद\u{947}श"),
                        ("ms", "Bolama Region"),
                        ("nb", "Bolama"),
                        ("nl", "Bolama"),
                        ("no", "Bolama"),
                        ("pl", "Region Bolama"),
                        ("pt", "Bolama"),
                        ("ro", "Regiunea Bolama"),
                        ("ru", "Болама"),
                        ("si", "බොලම\u{dcf} කල\u{dcf}පය"),
                        ("sv", "Bolama-Bijagós"),
                        ("ta", "போல\u{bbe}ம\u{bbe} பகுதி"),
                        ("te", "బ\u{c4a}ల\u{c3e}మ\u{c3e} ప\u{c4d}ర\u{c3e}ంతం"),
                        ("th", "โบลามา"),
                        ("tr", "Bolama Bölgesi"),
                        ("uk", "Болама"),
                        ("ur", "بولاما ریجن"),
                        ("vi", "Khu vực Bolama"),
                        ("zh", "博拉馬區"),
                    ]),
                    unofficial_name_list: ["Bolama"].to_vec(),
                },
            ),
            (
                "BM",
                Subdivision {
                    name: "BM",
                    country_alpha2: Alpha2::GW,
                    code: "BM",
                    #[cfg(feature = "geo")]
                    geo: Some(SubdivisionGeo {
                        latitude: Some(11.8529061),
                        longitude: Some(-15.7351171),
                        max_latitude: Some(12.026648),
                        min_latitude: Some(11.7364393),
                        max_longitude: Some(-15.6145911),
                        min_longitude: Some(-15.9681988),
                    }),
                    comments: None,
                    subdivision_type: SubdivisionType::Region,
                    #[cfg(feature = "translations")]
                    translations: HashMap::from([
                        ("ar", "إقليم بيومبو"),
                        ("bg", "Биомбо"),
                        ("bn", "ব\u{9be}য\u{9bc}োম\u{9cd}ব\u{9c1} অঞ\u{9cd}চল"),
                        ("ca", "Regió de Biombo"),
                        ("ccp", "𑄝\u{1112d}𑄃\u{1112e}𑄟\u{11134}𑄝\u{1112e}"),
                        ("ceb", "Biombo"),
                        ("cs", "Biombo"),
                        ("da", "Biombo Region"),
                        ("de", "Region Biombo"),
                        ("el", "Μπιόμπο"),
                        ("en", "Biombo"),
                        ("es", "Región de Biombo"),
                        ("fi", "Biombon alue"),
                        ("fr", "Biombo"),
                        ("gu", "બિમ\u{acd}બો પ\u{acd}રદ\u{ac7}શ"),
                        ("hi", "बिओम\u{94d}बो प\u{94d}रद\u{947}श"),
                        ("id", "Wilayah Biombo"),
                        ("it", "regione di Biombo"),
                        ("ja", "ビオンボ州"),
                        ("kn", "ಬಯೋಂಬೊ ಪ\u{ccd}ರದೇಶ"),
                        ("ko", "비옴부 주"),
                        ("lt", "Biombo regionas"),
                        ("lv", "Biombo reģions"),
                        ("mr", "जीवपो प\u{94d}रद\u{947}श"),
                        ("ms", "Biombo Region"),
                        ("nb", "Biombo"),
                        ("nl", "Biombo"),
                        ("no", "Biombo"),
                        ("pl", "Region Biombo"),
                        ("pt", "Biombo"),
                        ("ro", "Regiunea Biombo"),
                        ("ru", "Биомбо"),
                        ("si", "බයෝම\u{dca}බෝ කල\u{dcf}පය"),
                        ("sv", "Biombo"),
                        ("ta", "பியம\u{bcd}போ பகுதி"),
                        ("te", "బయ\u{c3e}ంబ\u{c4b} ప\u{c4d}ర\u{c3e}ంతం"),
                        ("th", "เขตบ\u{e34}บอมโบ"),
                        ("tr", "Biombo Region"),
                        ("uk", "Біомбо"),
                        ("ur", "بیومبو ریجن"),
                        ("vi", "Khu vực Biombo"),
                        ("zh", "比翁博區"),
                    ]),
                    unofficial_name_list: ["Biombo"].to_vec(),
                },
            ),
            (
                "BS",
                Subdivision {
                    name: "BS",
                    country_alpha2: Alpha2::GW,
                    code: "BS",
                    #[cfg(feature = "geo")]
                    geo: Some(SubdivisionGeo {
                        latitude: Some(11.8816553),
                        longitude: Some(-15.6177942),
                        max_latitude: Some(11.9180031),
                        min_latitude: Some(11.8207819),
                        max_longitude: Some(-15.5579567),
                        min_longitude: Some(-15.6621402),
                    }),
                    comments: None,
                    subdivision_type: SubdivisionType::AutonomousSector,
                    #[cfg(feature = "translations")]
                    translations: HashMap::from([
                        ("af", "Bissau"),
                        ("am", "ቢሳው"),
                        ("ar", "بيساو"),
                        ("az", "Bisau"),
                        ("be", "Бісау"),
                        ("bg", "Бисау"),
                        ("bn", "বিস\u{9be}উ"),
                        ("bs", "Bissau"),
                        ("ca", "Bissau"),
                        ("ccp", "𑄝\u{11128}𑄥\u{1112a}𑄅\u{1112a}"),
                        ("ceb", "Bissau Region"),
                        ("cs", "Bissau"),
                        ("cy", "Bissau"),
                        ("da", "Bissau"),
                        ("de", "Bissau"),
                        ("el", "Μπισσάου"),
                        ("en", "Bissau"),
                        ("es", "Bisáu"),
                        ("et", "Bissau"),
                        ("eu", "Bissau"),
                        ("fa", "بیسائو"),
                        ("fi", "Bissau"),
                        ("fr", "Bissau"),
                        ("ga", "Bissau"),
                        ("gl", "Bissau"),
                        ("gu", "બિસ\u{acd}સૌ"),
                        ("he", "ביסאו"),
                        ("hi", "बिसाउ"),
                        ("hr", "Bissau"),
                        ("hu", "Bissau"),
                        ("hy", "Բիսաու"),
                        ("id", "Bissau"),
                        ("is", "Bissá"),
                        ("it", "Bissau"),
                        ("ja", "ビサウ"),
                        ("jv", "Bissau"),
                        ("ka", "ბისაუ"),
                        ("kk", "Бисау"),
                        ("kn", "ಬ\u{cbf}ಸ\u{ccc}"),
                        ("ko", "비사우"),
                        ("ky", "Бисау"),
                        ("lt", "Bisau"),
                        ("lv", "Bisava"),
                        ("mk", "Бисао"),
                        ("mn", "Биссау"),
                        ("mr", "बिसाउ"),
                        ("ms", "Bissau"),
                        ("nb", "Bissau"),
                        ("nl", "Bissau"),
                        ("no", "Bissau"),
                        ("pa", "ਬਿਸਾਊ"),
                        ("pl", "Bissau"),
                        ("pt", "Bissau"),
                        ("ro", "Bissau"),
                        ("ru", "Бисау"),
                        ("si", "බ\u{dd2}සව\u{dd4}"),
                        ("sk", "Bissau"),
                        ("sl", "Bissau"),
                        ("so", "Bissau"),
                        ("sq", "Bissau"),
                        ("sr", "Бисао"),
                        ("sr_Latn", "Bisao"),
                        ("sv", "Bissau"),
                        ("sw", "Bisau"),
                        ("ta", "பிச\u{bbe}வு"),
                        ("te", "బ\u{c3f}స\u{c3e}వు"),
                        ("th", "บ\u{e34}สเซา"),
                        ("tk", "Bissau"),
                        ("tr", "Bissau"),
                        ("uk", "Бісау"),
                        ("ur", "بساؤ"),
                        ("uz", "Bisau"),
                        ("vi", "Bissau"),
                        ("yo", "Bissau"),
                        ("yo_BJ", "Bissau"),
                        ("yue", "比紹"),
                        ("yue_Hans", "比绍"),
                        ("zh", "比绍"),
                    ]),
                    unofficial_name_list: ["Bissau"].to_vec(),
                },
            ),
            (
                "CA",
                Subdivision {
                    name: "CA",
                    country_alpha2: Alpha2::GW,
                    code: "CA",
                    #[cfg(feature = "geo")]
                    geo: Some(SubdivisionGeo {
                        latitude: Some(12.2732631),
                        longitude: Some(-16.1669156),
                        max_latitude: Some(12.2793106),
                        min_latitude: Some(12.2542116),
                        max_longitude: Some(-16.1526919),
                        min_longitude: Some(-16.1758661),
                    }),
                    comments: None,
                    subdivision_type: SubdivisionType::Region,
                    #[cfg(feature = "translations")]
                    translations: HashMap::from([
                        ("ar", "اقليم كاشيو"),
                        ("bg", "Кашеу"),
                        ("bn", "ক\u{9be}চেউ অঞ\u{9cd}চল"),
                        ("ca", "Regió de Cacheu"),
                        ("ccp", "𑄇𑄬𑄌𑄬𑄅\u{1112a}"),
                        ("ceb", "Cacheu Region"),
                        ("cs", "Cacheu"),
                        ("da", "Cacheu Region"),
                        ("de", "Cacheu"),
                        ("el", "Κάτσεου"),
                        ("en", "Cacheu"),
                        ("es", "Región de Cacheu"),
                        ("fi", "Cacheun alue"),
                        ("fr", "Cacheu"),
                        ("gu", "ક\u{ac8}ચ\u{ac1} પ\u{acd}રદ\u{ac7}શ"),
                        ("hi", "क\u{948}झ\u{942} प\u{94d}रद\u{947}श"),
                        ("id", "Wilayah Cacheu"),
                        ("it", "regione di Cacheu"),
                        ("ja", "カシェウ州"),
                        ("kn", "ಕ\u{ccd}ಯಾಚ\u{cc6} ಪ\u{ccd}ರದೇಶ"),
                        ("ko", "카셰우 주"),
                        ("lt", "Kašeu regionas"),
                        ("lv", "Kašeu reģions"),
                        ("mr", "कच\u{947}\u{942} प\u{94d}रद\u{947}श"),
                        ("ms", "Cacheu Region"),
                        ("nb", "Cacheu"),
                        ("nl", "Cacheu"),
                        ("no", "Cacheu"),
                        ("pl", "Region Cacheu"),
                        ("pt", "Cacheu"),
                        ("ro", "Regiunea Cacheu"),
                        ("ru", "Кашеу"),
                        ("si", "ක\u{dcf}ච\u{dd4} කල\u{dcf}පය"),
                        ("sv", "Cacheu"),
                        ("ta", "க\u{bbe}சு பகுதி"),
                        ("te", "క\u{c4d}య\u{c3e}షూ ప\u{c4d}ర\u{c3e}ంతం"),
                        ("th", "เขตแคช\u{e39}"),
                        ("tr", "Cacheu"),
                        ("uk", "Регіон Кашеу"),
                        ("ur", "کاشیو علاقہ"),
                        ("vi", "Khu vực Cacheu"),
                        ("zh", "卡謝烏區"),
                    ]),
                    unofficial_name_list: ["Cacheo"].to_vec(),
                },
            ),
            (
                "GA",
                Subdivision {
                    name: "GA",
                    country_alpha2: Alpha2::GW,
                    code: "GA",
                    #[cfg(feature = "geo")]
                    geo: Some(SubdivisionGeo {
                        latitude: Some(11.8962488),
                        longitude: Some(-14.1001326),
                        max_latitude: Some(12.6777339),
                        min_latitude: Some(11.56273),
                        max_longitude: Some(-13.6365221),
                        min_longitude: Some(-14.570715),
                    }),
                    comments: None,
                    subdivision_type: SubdivisionType::Region,
                    #[cfg(feature = "translations")]
                    translations: HashMap::from([
                        ("ar", "لإقلين غابو"),
                        ("bg", "Габу"),
                        ("bn", "গ\u{9be}ব\u{9c1} অঞ\u{9cd}চল"),
                        ("ca", "Regió de Gabú"),
                        ("ccp", "𑄉𑄝\u{1112a}"),
                        ("cs", "Gabú"),
                        ("da", "Gabú Region"),
                        ("de", "Gabú"),
                        ("el", "Γκαμπού"),
                        ("en", "Gabú"),
                        ("es", "Región de Gabú"),
                        ("fi", "Gabún alue"),
                        ("fr", "Gabu"),
                        ("gu", "ગ\u{ac7}બ\u{ac2} પ\u{acd}રદ\u{ac7}શ"),
                        ("hi", "गाब\u{942} क\u{94d}ष\u{947}त\u{94d}र"),
                        ("id", "Wilayah Gabú"),
                        ("it", "regione di Gabú"),
                        ("ja", "ガブ州"),
                        ("kn", "ಗಾಬು ಪ\u{ccd}ರದೇಶ"),
                        ("ko", "가부 주"),
                        ("lt", "Gabu regionas"),
                        ("lv", "Gabu reģions"),
                        ("mr", "ग\u{945}ब\u{942} प\u{94d}रद\u{947}श"),
                        ("ms", "Gabu Region"),
                        ("nb", "Gabú"),
                        ("nl", "Gabú"),
                        ("no", "Gabú"),
                        ("pl", "Region Gabú"),
                        ("pt", "Gabu"),
                        ("ro", "Regiunea Gabú"),
                        ("ru", "Габу"),
                        ("si", "ග\u{dcf}බ\u{dd4} ප\u{dca}\u{200d}ර\u{dcf}න\u{dca}තය"),
                        ("sv", "Gabú"),
                        ("ta", "க\u{bbe}பி பகுதி"),
                        ("te", "గ\u{c3e}బు ప\u{c4d}ర\u{c3e}ంతం"),
                        ("th", "เขตกาบ\u{e39}"),
                        ("tr", "Gabu Bölgesi"),
                        ("uk", "Регіон Габу"),
                        ("ur", "گابو علاقہ"),
                        ("vi", "Khu vực Gabú"),
                        ("zh", "加布區"),
                    ]),
                    unofficial_name_list: ["Gabú"].to_vec(),
                },
            ),
            (
                "L",
                Subdivision {
                    name: "L",
                    country_alpha2: Alpha2::GW,
                    code: "L",
                    #[cfg(feature = "geo")]
                    geo: None,
                    comments: None,
                    subdivision_type: SubdivisionType::Province,
                    #[cfg(feature = "translations")]
                    translations: HashMap::from([
                        ("ccp", "𑄣𑄬𑄌\u{11134}𑄑𑄬"),
                        ("de", "Provinz Leste"),
                        ("en", "Leste"),
                    ]),
                    unofficial_name_list: [].to_vec(),
                },
            ),
            (
                "N",
                Subdivision {
                    name: "N",
                    country_alpha2: Alpha2::GW,
                    code: "N",
                    #[cfg(feature = "geo")]
                    geo: None,
                    comments: None,
                    subdivision_type: SubdivisionType::Province,
                    #[cfg(feature = "translations")]
                    translations: HashMap::from([
                        ("ccp", "𑄚\u{11127}𑄢\u{11134}𑄑𑄬"),
                        ("de", "Provinz Norte"),
                        ("en", "Norte"),
                    ]),
                    unofficial_name_list: [].to_vec(),
                },
            ),
            (
                "OI",
                Subdivision {
                    name: "OI",
                    country_alpha2: Alpha2::GW,
                    code: "OI",
                    #[cfg(feature = "geo")]
                    geo: Some(SubdivisionGeo {
                        latitude: Some(12.2760709),
                        longitude: Some(-15.3131185),
                        max_latitude: Some(12.680788),
                        min_latitude: Some(11.890556),
                        max_longitude: Some(-14.841685),
                        min_longitude: Some(-15.765291),
                    }),
                    comments: None,
                    subdivision_type: SubdivisionType::Region,
                    #[cfg(feature = "translations")]
                    translations: HashMap::from([
                        ("ar", "إقليم أويو"),
                        ("bg", "Ойо"),
                        ("bn", "ওইও অঞ\u{9cd}চল"),
                        ("ca", "Regió d’Oio"),
                        ("ccp", "𑄃\u{1112e}𑄃\u{11130}"),
                        ("ceb", "Oio Region"),
                        ("cs", "Oio"),
                        ("da", "Oio Region"),
                        ("de", "Region Oio"),
                        ("el", "Οίο"),
                        ("en", "Oio"),
                        ("es", "Región de Oio"),
                        ("et", "Oio piirkond"),
                        ("fi", "Oion alue"),
                        ("fr", "Oio"),
                        ("gu", "ઓઈઓ પ\u{acd}રદ\u{ac7}શ"),
                        ("hi", "ओइओ क\u{94d}ष\u{947}त\u{94d}र"),
                        ("id", "Wilayah Oio"),
                        ("it", "regione di Oio"),
                        ("ja", "オイオ州"),
                        ("kn", "ಓಯೊ ಪ\u{ccd}ರದೇಶ"),
                        ("ko", "오이우 주"),
                        ("lt", "Ojo regionas"),
                        ("lv", "Oio reģions"),
                        ("mr", "ऑओ प\u{94d}रद\u{947}श"),
                        ("ms", "Oio Region"),
                        ("nb", "Oio"),
                        ("nl", "Oio"),
                        ("no", "Oio"),
                        ("pl", "Region Oio"),
                        ("pt", "Oio"),
                        ("ro", "Regiunea Oio"),
                        ("ru", "Ойо"),
                        ("si", "ඔය\u{dd2}ඕ කල\u{dcf}පය"),
                        ("sv", "Oio"),
                        ("ta", "ஒய\u{bcd}யோ பகுதி"),
                        ("te", "ఓయ\u{c3f}య\u{c4b} ప\u{c4d}ర\u{c3e}ంతం"),
                        ("th", "เขตโอไอโอ"),
                        ("tr", "Oio Bölgesi"),
                        ("uk", "Ойо"),
                        ("ur", "ویو ریجن"),
                        ("vi", "Khu vực Oio"),
                        ("zh", "奧約區"),
                    ]),
                    unofficial_name_list: ["Oio"].to_vec(),
                },
            ),
            (
                "QU",
                Subdivision {
                    name: "QU",
                    country_alpha2: Alpha2::GW,
                    code: "QU",
                    #[cfg(feature = "geo")]
                    geo: Some(SubdivisionGeo {
                        latitude: Some(11.795562),
                        longitude: Some(-15.1726816),
                        max_latitude: Some(11.9419759),
                        min_latitude: Some(11.3275232),
                        max_longitude: Some(-14.8287029),
                        min_longitude: Some(-15.6142401),
                    }),
                    comments: None,
                    subdivision_type: SubdivisionType::Region,
                    #[cfg(feature = "translations")]
                    translations: HashMap::from([
                        ("ar", "إقليم كوينارا"),
                        ("bg", "Кинара"),
                        ("bn", "কিন\u{9be}র\u{9be} অঞ\u{9cd}চল"),
                        ("ca", "Regió de Quinara"),
                        ("ccp", "𑄇\u{1112d}\u{1112a}𑄚𑄢"),
                        ("ceb", "Quinara"),
                        ("cs", "Quinara"),
                        ("da", "Quinara Region"),
                        ("de", "Region Quinara"),
                        ("el", "Κουινάρα"),
                        ("en", "Quinara"),
                        ("es", "Región de Quinara"),
                        ("fi", "Quinaran alue"),
                        ("fr", "Quinara"),
                        ("gl", "Quinara"),
                        ("gu", "ક\u{acd}વિનારા પ\u{acd}રદ\u{ac7}શ"),
                        ("hi", "क\u{94d}विनारा क\u{94d}ष\u{947}त\u{94d}र"),
                        ("id", "Wilayah Quinara"),
                        ("it", "regione di Quinara"),
                        ("ja", "キナラ州"),
                        ("kn", "ಕ\u{ccd}ವ\u{cbf}ನಾರ ಪ\u{ccd}ರದೇಶ"),
                        ("ko", "키나라 주"),
                        ("lt", "Kinaros regionas"),
                        ("lv", "Kinaras reģions"),
                        ("mr", "क\u{94d}य\u{941}इनारा प\u{94d}रद\u{947}श"),
                        ("ms", "Quinara Region"),
                        ("nb", "Quinara"),
                        ("nl", "Quinara"),
                        ("no", "Quinara"),
                        ("pl", "Region Quinara"),
                        ("pt", "Quinara"),
                        ("ro", "Regiunea Quinara"),
                        ("ru", "Кинара"),
                        ("si", "ක\u{dd4}ය\u{dd2}න\u{dcf}ර\u{dcf} කල\u{dcf}පය"),
                        ("sv", "Quinara"),
                        ("ta", "குயினர\u{bbe} பகுதி"),
                        ("te", "క\u{c4d}వ\u{c3f}న\u{c3e}ర\u{c3e} ప\u{c4d}ర\u{c3e}ంతం"),
                        ("th", "ค\u{e34}วนารา"),
                        ("tr", "Quinara Bölgesi"),
                        ("uk", "Регіон Кінара"),
                        ("ur", "کوینارا علاقہ"),
                        ("vi", "Khu vực Quinara"),
                        ("zh", "基納拉區"),
                    ]),
                    unofficial_name_list: ["Quinara"].to_vec(),
                },
            ),
            (
                "S",
                Subdivision {
                    name: "S",
                    country_alpha2: Alpha2::GW,
                    code: "S",
                    #[cfg(feature = "geo")]
                    geo: None,
                    comments: None,
                    subdivision_type: SubdivisionType::Province,
                    #[cfg(feature = "translations")]
                    translations: HashMap::from([
                        ("ccp", "𑄥𑄣\u{11134}"),
                        ("de", "Provinz Sul"),
                        ("en", "Sul"),
                    ]),
                    unofficial_name_list: [].to_vec(),
                },
            ),
            (
                "TO",
                Subdivision {
                    name: "TO",
                    country_alpha2: Alpha2::GW,
                    code: "TO",
                    #[cfg(feature = "geo")]
                    geo: Some(SubdivisionGeo {
                        latitude: Some(11.300838),
                        longitude: Some(-15.409939),
                        max_latitude: None,
                        min_latitude: None,
                        max_longitude: None,
                        min_longitude: None,
                    }),
                    comments: None,
                    subdivision_type: SubdivisionType::Region,
                    #[cfg(feature = "translations")]
                    translations: HashMap::from([
                        ("ar", "إقليم تومبالي"),
                        ("bg", "Томбали"),
                        ("bn", "ত\u{9c1}ম\u{9cd}ব\u{9be}লি অঞ\u{9cd}চল"),
                        ("ca", "Regió de Tombali"),
                        ("ccp", "𑄑𑄟\u{11134}𑄝𑄣\u{11128}"),
                        ("ceb", "Tombali"),
                        ("cs", "Tombali (region)"),
                        ("da", "Tombali Region"),
                        ("de", "Region Tombali"),
                        ("el", "Τόμπαλι"),
                        ("en", "Tombali"),
                        ("es", "Región de Tombali"),
                        ("fi", "Tombalin alue"),
                        ("fr", "Tombali"),
                        ("gu", "ટોમ\u{acd}બાલી પ\u{acd}રદ\u{ac7}શ"),
                        ("hi", "टॉम\u{94d}बाली क\u{94d}ष\u{947}त\u{94d}र"),
                        ("id", "TombaliWilayah"),
                        ("it", "regione di Tombali"),
                        ("ja", "トンバリ州"),
                        ("kn", "ಟೋಂಬಲ\u{cbf} ಪ\u{ccd}ರದೇಶ"),
                        ("ko", "톰발리 주"),
                        ("lt", "Tombali regionas"),
                        ("lv", "Tombali reģions"),
                        ("mr", "टोम\u{94d}बाली प\u{94d}रद\u{947}श"),
                        ("ms", "Tombali Region"),
                        ("nb", "Tombali"),
                        ("nl", "Tombali"),
                        ("no", "Tombali"),
                        ("pl", "Region Tombali"),
                        ("pt", "Tombali"),
                        ("ro", "Regiunea Tombali"),
                        ("ru", "Томбали"),
                        ("si", "ටොම\u{dca}බල\u{dd2} කල\u{dcf}පය"),
                        ("sv", "Tombali"),
                        ("ta", "டொம\u{bcd}பலி பகுதி"),
                        ("te", "ట\u{c4b}ంబ\u{c3e}ల\u{c3f} ప\u{c4d}ర\u{c3e}ంతం"),
                        ("th", "ทอมบาล\u{e35}"),
                        ("tr", "Tombali Bölgesi"),
                        ("uk", "Район Томбалі"),
                        ("ur", "تومبالی ریجن"),
                        ("vi", "Khu vực Tombali"),
                        ("zh", "通巴利區"),
                    ]),
                    unofficial_name_list: ["Tombali"].to_vec(),
                },
            ),
        ])
    }
}
#[allow(unused_imports)]
use crate::{Alpha2, Alpha3, Continent, Country, Region, SubRegion, WeekDay, WorldRegion, GEC};
#[allow(unused_imports)]
use std::collections::HashMap;
#[cfg(feature = "gw")]
pub fn new() -> Country {
    Country {
        alpha2: Alpha2::GW,
        alpha3: Alpha3::GNB,
        address_format: None,
        continent: Continent::Africa,
        country_code: 245,
        currency_code: "XOF",
        gec: Some(GEC::PU),
        #[cfg(feature = "geo")]
        geo: geo::new(),
        international_prefix: "00",
        ioc: Some("GBS"),
        iso_long_name: "The Republic of Guinea-Bissau",
        iso_short_name: "Guinea-Bissau",
        official_language_list: ["pt"].to_vec(),
        spoken_language_list: ["pt"].to_vec(),
        national_destination_code_length_list: [2].to_vec(),
        national_number_length_list: [7].to_vec(),
        national_prefix: "None",
        nationality: Some("Guinea-Bissauan"),
        number: "624",
        postal_code: true,
        postal_code_format: Some("\\d{4}"),
        region: Some(Region::Africa),
        start_of_week: WeekDay::Monday,
        subregion: Some(SubRegion::WesternAfrica),
        un_locode: "GW",
        unofficial_name_list: [
            "Guinea-Bissau",
            "Guinée-Bissau",
            "ギニアビサウ",
            "Guinee-Bissau",
            "Guinea Bissau",
        ]
        .to_vec(),
        world_region: WorldRegion::EMEA,
        #[cfg(feature = "translations")]
        translations: HashMap::from([
            ("ab", "Guinea-Bissau"),
            ("af", "Guinee-Bissau"),
            ("ak", "Guinea-Bissau"),
            ("am", "ቢሳፅ"),
            ("an", "Guinea-Bissau"),
            ("ar", "غينيا بيساو"),
            ("as", "গিনি-বিছ\u{9be}উ"),
            ("ay", "Guinea-Bissau"),
            ("az", "Qvineya Bissau"),
            ("ba", "Guinea-Bissau"),
            ("be", "Гвінея-Бісау"),
            ("bg", "Гвинея-Бисау"),
            ("bi", "Guinea-Bissau"),
            ("bn", "গিনি-বিস\u{9be}উ"),
            ("bn_IN", "গিনি-বিস\u{9be}উ"),
            ("br", "Ginea-Bissau"),
            ("bs", "Gvineja Bisau"),
            ("ca", "Guinea Bissau"),
            ("ce", "Гвине-Бисау"),
            ("ch", "Guinea-Bissau"),
            ("cs", "Guinea-Bissau"),
            ("cv", "Гвине-Бисау"),
            ("cy", "Guinea-Bissau"),
            ("da", "Guinea-Bissau"),
            ("de", "Guinea-Bissau"),
            ("dv", "ގ\u{7a9}ނ\u{7a9}-ބ\u{7a8}ސ\u{7a7}އ\u{7ab}"),
            ("dz", "ག\u{f72}་ན\u{f72}་-བ\u{f72}་སའ\u{f7c}།"),
            ("ee", "Guinea-Bissau"),
            ("el", "Γουινέα-Μπισσάου"),
            ("en", "Guinea-Bissau"),
            ("eo", "Gvineo Bisaŭa"),
            ("es", "Guinea-Bisáu"),
            ("et", "Guinea-Bissau"),
            ("eu", "Ginea Bissau"),
            ("fa", "گینه\u{654} بیسائو"),
            ("ff", "Gine-Bisaawo"),
            ("fi", "Guinea-Bissau"),
            ("fo", "Guinea Bissau"),
            ("fr", "Guinée-Bissau"),
            ("fy", "Guinee-Bissau"),
            ("ga", "An Ghuine-Bhissau"),
            ("gl", "Guinea-Bissau"),
            ("gn", "Guinea-Bissau"),
            ("gu", "ગિએના-બિસાઉ"),
            ("gv", "Yn Ghuinea-Bissau"),
            ("ha", "Guinea-Bissau"),
            ("he", "גינאה ביסאו"),
            ("hi", "गिनी-बिसाऊ"),
            ("hr", "Gvineja Bisau"),
            ("ht", "Gine-Bisao"),
            ("hu", "Bissau-Guinea"),
            ("hy", "Գվինեա-Բիսաու"),
            ("ia", "Guinea-Bissau"),
            ("id", "Guinea-Bissau"),
            ("io", "Guinea Bisau"),
            ("is", "Gínea-Bissá"),
            ("it", "Guinea-Bissau"),
            ("iu", "Guinea-Bissau"),
            ("ja", "ギニアビサウ"),
            ("ka", "გვინეა-ბისაუ"),
            ("ki", "Guinea-Bissau"),
            ("kk", "Гвинея-Бисау"),
            ("kl", "Guinea-Bissau"),
            ("km", "ហ\u{17d2}គ\u{17b8}ណេប\u{17ca}\u{17b8}សៅ"),
            ("kn", "ಗ\u{cbf}ನೀ-ಬ\u{cbf}ಸ\u{ccd}ಸೋ"),
            ("ko", "기니비사우"),
            ("ku", "Gîneya Bisoî"),
            ("kv", "Guinea-Bissau"),
            ("kw", "Gyni-Bissaw"),
            ("ky", "Гвинея-Бисау"),
            ("lo", "Guinea-Bissau"),
            ("lt", "Bisau Gvinėja"),
            ("lv", "Gvineja-Bisava"),
            ("mi", "Kini Pihō"),
            ("mk", "Гвинеја-Бисау"),
            ("ml", "ഗിനിയ-ബിസ\u{d4d}സ\u{d3e}വ\u{d41}"),
            ("mn", "Guinea-Bissau"),
            ("mr", "गिनी-बिसाव"),
            ("ms", "Guinea Bissau"),
            ("mt", "Ginea-Bissaw"),
            (
                "my",
                "ဂင\u{103a}းန\u{102e}ဗစ\u{103a}ဆောန\u{102d}\u{102f}င\u{103a}င\u{1036}",
            ),
            ("na", "Gini-Bitau"),
            ("nb", "Guinea-Bissau"),
            ("ne", "गिइनि बिसाउ"),
            ("nl", "Guinee-Bissau"),
            ("nn", "Guinea-Bissau"),
            ("nv", "Gíní Bisó"),
            ("oc", "Guinèa-Bissau"),
            ("or", "ଗ\u{b3f}ନୀ-ବ\u{b3f}ସ\u{b41}"),
            ("pa", "ਗ\u{a41}ਨ\u{a47}ਆ-ਬਿਸਾਉ"),
            ("pi", "गिनी-बिसो"),
            ("pl", "Gwinea Bissau"),
            ("ps", "Guinea-Bissau"),
            ("pt", "Guiné-Bissáu"),
            ("pt_BR", "Guiné-Bissau"),
            ("ro", "Guinea-Bissau"),
            ("ru", "Гвинея-Бисау"),
            ("rw", "Guneya-Biso"),
            ("sc", "Guinea-Bissau"),
            ("sd", "Guinea-Bissau"),
            ("si", "ග\u{dd2}න\u{dd2}ය\u{dcf}-බ\u{dd2}සව\u{dca}"),
            ("sk", "Guinea-Bissau"),
            ("sl", "Gvineja Bissau"),
            ("so", "Guinea-Bissau"),
            ("sq", "Guinea-Bisau"),
            ("sr", "Гвинеја-Бисао"),
            ("sv", "Guinea-Bissau"),
            ("sw", "Guinea-Bissau"),
            ("ta", "கினி-ப\u{bc0}சோ"),
            ("te", "గ\u{c3f}న\u{c40}-బ\u{c3f}స\u{c3e}వ"),
            ("tg", "Гвинея-Бисау"),
            ("th", "ก\u{e34}น\u{e35}บ\u{e34}สเซา"),
            ("ti", "ቢሳዎ"),
            ("tk", "Gwineýa-Bisau"),
            ("tl", "Guinea-Bissau"),
            ("tr", "Gine-Bissau"),
            ("tt", "Gуинеа-Биссау"),
            ("ug", "گىۋىنېيە بىسسائۇ"),
            ("uk", "Гвінея-Бісау"),
            ("ur", "گنی بساؤ"),
            ("uz", "Gvineya-Bissau"),
            ("ve", "Guinea-Bissau"),
            ("vi", "Ghi-nê Bi-xau"),
            ("wa", "Guinêye-Bissaw"),
            ("wo", "Ginne Bisaawóo"),
            ("xh", "Guinea-Bissau"),
            ("yo", "Guinea-Bissau"),
            ("zh_CN", "几内亚比绍"),
            ("zh_HK", "畿內亞比紹"),
            ("zh_TW", "幾內亞比索"),
            ("zu", "IGini Bisawu"),
        ]),
        #[cfg(feature = "subdivisions")]
        subdivisions: subdivisions::new(),
    }
}
