// DO NOT TOUCH THIS FILE. (Auto-generated via `code_gen/countries.rs`)

// The Hashemite Kingdom of Jordan

#[cfg(all(feature = "jo", feature = "constants"))]
pub mod consts {
    #[allow(unused_imports)]
    use crate::{Alpha2, Alpha3, Continent, Region, SubRegion, WeekDay, WorldRegion, GEC, IOC};

    pub const ADDRESS_FORMAT: Option<&str> =
        Some("{{recipient}}\n{{street}}\n{{postalcode}} {{city}}\n{{country}}");
    pub const ALPHA2: Alpha2 = Alpha2::JO;
    pub const ALPHA3: Alpha3 = Alpha3::JOR;
    pub const CONTINENT: Continent = Continent::Asia;
    pub const COUNTRY_CODE: usize = 962;
    pub const CURRENCY_CODE: &str = "JOD";
    pub const GEC: Option<GEC> = Some(GEC::JO);
    pub const INTERNATIONAL_PREFIX: &str = "00";
    pub const IOC: Option<IOC> = Some(IOC::JOR);
    pub const ISO_SHORT_NAME: &str = "Jordan";
    pub const ISO_LONG_NAME: &str = "The Hashemite Kingdom of Jordan";
    pub const OFFICIAL_LANGUAGE_LIST: &[&str] = &["ar"];
    pub const SPOKEN_LANGUAGE_LIST: &[&str] = &["ar"];
    pub const NATIONAL_DESTINATION_CODE_LENGTH_LIST: &[usize] = &[2];
    pub const NATIONAL_NUMBER_LENGTH_LIST: &[usize] = &[8, 9];
    pub const NATIONAL_PREFIX: &str = "0";
    pub const NATIONALITY: Option<&str> = Some("Jordanian");
    pub const NUMBER: &str = "400";
    pub const POSTAL_CODE: bool = true;
    pub const POSTAL_CODE_FORMAT: Option<&str> = Some("\\d{5}");
    pub const REGION: Option<Region> = Some(Region::Asia);
    pub const START_DAY_OF_WEEK: WeekDay = WeekDay::Sunday;
    pub const SUBREGION: Option<SubRegion> = Some(SubRegion::WesternAsia);
    pub const UN_LOCODE: &str = "JO";
    pub const UNOFFICIAL_NAME_LIST: &[&str] = &[
        "Jordan",
        "الأردن",
        "Jordanien",
        "Jordanie",
        "Jordania",
        "ヨルダン",
        "Jordanië",
    ];
    pub const WORLD_REGION: WorldRegion = WorldRegion::EMEA;
    #[cfg(feature = "translations")]
    pub const TRANSLATIONS: &[(&str, &str)] = &[
        ("ab", "Jordan"),
        ("af", "Jordanië"),
        ("ak", "Jordan"),
        ("am", "ጆሴ፣ን"),
        ("an", "Jordan"),
        ("ar", "الأردن"),
        ("as", "জৰ\u{9cd}ড\u{9be}ন"),
        ("ay", "Jordan"),
        ("az", "İordaniya"),
        ("ba", "Jordan"),
        ("be", "Іарданія"),
        ("bg", "Йордания"),
        ("bi", "Jordan"),
        ("bn", "জর\u{9cd}ড\u{9be}ন"),
        ("bn_IN", "জর\u{9cd}ড\u{9be}ন"),
        ("br", "Jordania"),
        ("bs", "Jordan"),
        ("ca", "Jordània"),
        ("ce", "Урдан"),
        ("ch", "Jordan"),
        ("cs", "Jordánsko"),
        ("cv", "Урдан"),
        ("cy", "Gwlad Yr Iorddonen"),
        ("da", "Jordan"),
        ("de", "Jordanien"),
        ("dv", "އ\u{7aa}ރ\u{7aa}ދ\u{7aa}ނ\u{7b0}"),
        ("dz", "ཇ\u{f7c}ར་ཌན།"),
        ("ee", "Jordan"),
        ("el", "Ιορδανία"),
        ("en", "Jordan"),
        ("eo", "Jordanio"),
        ("es", "Jordania"),
        ("et", "Jordaania"),
        ("eu", "Jordania"),
        ("fa", "اردن"),
        ("ff", "Jordan"),
        ("fi", "Jordania"),
        ("fo", "Jordan"),
        ("fr", "Jordanie"),
        ("fy", "Jordaanje"),
        ("ga", "An Iordáin"),
        ("gl", "Xordania"),
        ("gn", "Jordan"),
        ("gu", "જોર\u{acd}ડન"),
        ("gv", "Yn Jordaan"),
        ("ha", "Jordan"),
        ("he", "ירדן"),
        ("hi", "जॉर\u{94d}डन"),
        ("hr", "Jordan"),
        ("ht", "Jòdani"),
        ("hu", "Jordánia"),
        ("hy", "Հորդանան"),
        ("ia", "Jordania"),
        ("id", "Yordania"),
        ("io", "Jordania"),
        ("is", "Jórdanía"),
        ("it", "Giordania"),
        ("iu", "Jordan"),
        ("ja", "ヨルダン"),
        ("ka", "იორდანია"),
        ("ki", "Jordan"),
        ("kk", "Иордания"),
        ("kl", "Jordan"),
        ("km", "ហ\u{17d2}ស\u{17ca}កដង\u{17cb}"),
        ("kn", "ಜೋರ\u{ccd}ಡಾನ\u{ccd}"),
        ("ko", "요르단"),
        ("ku", "Urdin"),
        ("kv", "Иордания"),
        ("kw", "Jordan"),
        ("ky", "Иордания"),
        ("lo", "Jordan"),
        ("lt", "Jordanija"),
        ("lv", "Jordānija"),
        ("mi", "Jordan"),
        ("mk", "Џордан"),
        ("ml", "ജോര\u{d4d}\u{200d}ഡ\u{d3e}ന\u{d4d}\u{200d}"),
        ("mn", "Ёрдан"),
        ("mr", "जॉर\u{94d}डन"),
        ("ms", "Jordan"),
        ("mt", "Ġordan"),
        (
            "my",
            "ဂျော\u{103a}ဒန\u{103a}န\u{102d}\u{102f}င\u{103a}င\u{1036}",
        ),
        ("na", "Djordan"),
        ("nb", "Jordan"),
        ("ne", "जोर\u{94d}डन"),
        ("nl", "Jordanië"),
        ("nn", "Jordan"),
        ("nv", "Jordan"),
        ("oc", "Jordania"),
        ("or", "ଜୋର\u{b4d}ଡ\u{b3e}ନ"),
        ("pa", "ਜਾਰਡਨ"),
        ("pi", "जार\u{94d}डन"),
        ("pl", "Jordania"),
        ("ps", "اردن"),
        ("pt", "Jordânia"),
        ("pt_BR", "Jordânia"),
        ("ro", "Iordania"),
        ("ru", "Иордания"),
        ("rw", "Yorudani"),
        ("sc", "Giordània"),
        ("sd", "اردن"),
        ("si", "ජෝර\u{dca}ද\u{dcf}නය"),
        ("sk", "Jordánsko"),
        ("sl", "Jordanija"),
        ("so", "Urdun"),
        ("sq", "Jordani"),
        ("sr", "Јордан"),
        ("sv", "Jordanien"),
        ("sw", "Jordan"),
        ("ta", "ஜோர\u{bcd}ட\u{bbe}ன\u{bcd}"),
        ("te", "జ\u{c4b}ర\u{c4d}డ\u{c3e}న\u{c4d}"),
        ("tg", "Ҷордон"),
        ("th", "จอร\u{e4c}แดน"),
        ("ti", "ጆርዳን"),
        ("tk", "Iordan"),
        ("tl", "Jordan"),
        ("tr", "Ürdün"),
        ("tt", "Жордан"),
        ("ug", "ئىيوردانىيە"),
        ("uk", "Йорданія"),
        ("ur", "اردن"),
        ("uz", "Iordaniya"),
        ("ve", "Jordan"),
        ("vi", "Gi-oa-đanh"),
        ("wa", "Djordaneye"),
        ("wo", "Jordaani"),
        ("xh", "Jordan"),
        ("yo", "Jọ\u{301}rdánì"),
        ("zh_CN", "约旦"),
        ("zh_HK", "約旦"),
        ("zh_TW", "約旦"),
        ("zu", "Jordan"),
    ];
    #[cfg(all(feature = "jo", feature = "geo", feature = "constants"))]
    pub mod geo {
        pub const LATITUDE: f64 = 30.585164;
        pub const LONGITUDE: f64 = 36.238414;
        pub const MAX_LATITUDE: f64 = 33.374735;
        pub const MAX_LONGITUDE: f64 = 39.301154;
        pub const MIN_LATITUDE: f64 = 29.1850361;
        pub const MIN_LONGITUDE: f64 = 34.9441001;
        pub const NORTHEAST_LATITUDE: f64 = 33.374735;
        pub const NORTHEAST_LONGITUDE: f64 = 39.301154;
        pub const SOUTHWEST_LATITUDE: f64 = 29.1850361;
        pub const SOUTHWEST_LONGITUDE: f64 = 34.9441001;
    }
}
#[cfg(all(feature = "jo", feature = "geo"))]
pub mod geo {
    use crate::{CountryGeo, CountryGeoBound, CountryGeoBounds};

    pub fn new() -> CountryGeo {
        CountryGeo {
            latitude: 30.585164,
            longitude: 36.238414,
            max_latitude: 33.374735,
            max_longitude: 39.301154,
            min_latitude: 29.1850361,
            min_longitude: 34.9441001,
            bounds: CountryGeoBounds {
                northeast: CountryGeoBound {
                    latitude: 33.374735,
                    longitude: 39.301154,
                },
                southwest: CountryGeoBound {
                    latitude: 29.1850361,
                    longitude: 34.9441001,
                },
            },
        }
    }
}

#[cfg(all(feature = "jo", feature = "subdivisions"))]
pub mod subdivisions {
    use crate::Subdivision;
    use std::collections::HashMap;
    // In this state, We do not know if subdivisions have geo or not!
    #[cfg(feature = "geo")]
    #[allow(unused_imports)]
    use crate::{Alpha2, SubdivisionGeo, SubdivisionType};

    pub fn new() -> HashMap<&'static str, Subdivision> {
        HashMap::from([
            (
                "AJ",
                Subdivision {
                    name: "AJ",
                    country_alpha2: Alpha2::JO,
                    code: "AJ",
                    #[cfg(feature = "geo")]
                    geo: Some(SubdivisionGeo {
                        latitude: Some(32.2561926),
                        longitude: Some(35.6969984),
                        max_latitude: Some(32.40349),
                        min_latitude: Some(32.158034),
                        max_longitude: Some(35.904965),
                        min_longitude: Some(35.606699),
                    }),
                    comments: None,
                    subdivision_type: SubdivisionType::Governorate,
                    #[cfg(feature = "translations")]
                    translations: HashMap::from([
                        ("ar", "عجلون"),
                        ("bn", "আজল\u{9c1}ন গভর\u{9cd}নোরেট"),
                        ("ca", "Governació d’Ajlun"),
                        ("ccp", "𑄃𑄌\u{11134}𑄣𑄅\u{1112a}𑄚\u{11134}"),
                        ("da", "Ajloun Governorate"),
                        ("de", "Gouvernement Adschlun"),
                        ("el", "Ατζλούν Γκοβερνοράτε"),
                        ("en", "Ajloun"),
                        ("es", "Gobernación de Ajlun"),
                        ("eu", "Ajlun Gobernazioa"),
                        ("fa", "استان عجلون"),
                        ("fi", "Ajlun"),
                        ("fr", "subdivision d’Ajlun"),
                        ("gu", "અજલોન ગવર\u{acd}નોર\u{ac7}ટ"),
                        ("he", "עג׳לון"),
                        ("hi", "अजल\u{941}न"),
                        ("hu", "Adzslún kormányzóság"),
                        ("hy", "Աջլունի մարզ"),
                        ("id", "Kegubernuran Ajloun"),
                        ("it", "governatorato di Ajlun"),
                        ("ja", "アジュルン県"),
                        ("kn", "ಅಜ\u{ccd}ಲೊನ\u{ccd} ಗವರ\u{ccd}ನೇಟ\u{ccd}"),
                        ("ko", "아질룬 주"),
                        ("lt", "Adžluno muchafaza"),
                        ("lv", "Adžlūnas muhāfaza"),
                        ("mr", "अजलॉन गव\u{94d}हर\u{94d}नोर\u{947}ट"),
                        ("ms", "Ajloun Governorate"),
                        ("nb", "Ailoun"),
                        ("nl", "Ajlun"),
                        ("no", "Ailoun"),
                        ("pl", "Adżlun (muhafaza)"),
                        ("pt", "Governorato de Ajloun"),
                        ("ro", "Guvernoratul Ajloun"),
                        ("ru", "Аджлун (мухафаза)"),
                        ("si", "අජ\u{dca}ලොඋන\u{dca} පළ\u{dcf}ත"),
                        ("sq", "Governorati Ajloun"),
                        ("sv", "Ajlun (guvernement)"),
                        ("ta", "அஜலூன\u{bcd} கோவெர\u{bcd}னோரே"),
                        (
                            "te",
                            "అజ\u{c4d}\u{200c}ల\u{c4c}న\u{c4d} గవర\u{c4d}నర\u{c47}ట\u{c4d}",
                        ),
                        ("th", "อ\u{e31}จล\u{e38}น โกเวอโนเรท"),
                        ("tr", "Ajloun Yönetimi"),
                        ("uk", "Муніципалітет Аджлун"),
                        ("ur", "محافظہ عجلون"),
                        ("vi", "Tỉnh Ajloun"),
                        ("zh", "阿傑隆省"),
                    ]),
                    unofficial_name_list: ["Ajloan", "Ajlun"].to_vec(),
                },
            ),
            (
                "AM",
                Subdivision {
                    name: "AM",
                    country_alpha2: Alpha2::JO,
                    code: "AM",
                    #[cfg(feature = "geo")]
                    geo: Some(SubdivisionGeo {
                        latitude: Some(31.9565783),
                        longitude: Some(35.9456951),
                        max_latitude: None,
                        min_latitude: None,
                        max_longitude: None,
                        min_longitude: None,
                    }),
                    comments: None,
                    subdivision_type: SubdivisionType::Governorate,
                    #[cfg(feature = "translations")]
                    translations: HashMap::from([
                        ("ar", "محافظة العاصمة"),
                        ("be", "Аман"),
                        ("bn", "আম\u{9cd}ম\u{9be}ন গভর\u{9cd}নোরেট"),
                        ("ca", "Governació d’Amman"),
                        ("ccp", "𑄃𑄟\u{11127}𑄚\u{11134}"),
                        ("da", "Amman Governorate"),
                        ("de", "Gouvernement Amman"),
                        ("el", "Αμάν"),
                        ("en", "Amman"),
                        ("es", "Gobernación de Ammán"),
                        ("eu", "Amman Gobernazioa"),
                        ("fa", "عمان (استان)"),
                        ("fi", "Amman (kuvernoraatti)"),
                        ("fr", "subdivision d’Amman"),
                        ("gu", "અમ\u{acd}માન ગવર\u{acd}નોર\u{ac7}ટ"),
                        ("he", "מחוז עמאן"),
                        ("hi", "अम\u{94d}मान गवर\u{94d}नर\u{947}ट"),
                        ("hu", "Főváros kormányzóság (Jordánia)"),
                        ("hy", "Ամմանի մարզ"),
                        ("id", "Amman Governorate"),
                        ("it", "governatorato di Amman"),
                        ("ja", "アンマン県"),
                        ("kn", "ಅಮ\u{ccd}ಮನ\u{ccd} ಗವರ\u{ccd}ನೇಟ\u{ccd}"),
                        ("ko", "암만 주"),
                        ("lt", "Amano muchafaza"),
                        ("lv", "Ammānas muhāfaza"),
                        ("mr", "अम\u{94d}मन गव\u{94d}हर\u{94d}नोर\u{947}ट"),
                        ("ms", "Amman Governorate"),
                        ("nb", "Amman Governorate"),
                        ("nl", "Amman"),
                        ("no", "Amman Governorate"),
                        ("pl", "Amman (muhafaza)"),
                        ("pt", "Amã (província)"),
                        ("ro", "Guvernoratul Amman"),
                        ("ru", "Амман"),
                        ("si", "අම\u{dca}ම\u{dcf}න\u{dca} පළ\u{dcf}ත"),
                        ("sv", "Amman (guvernement)"),
                        ("ta", "அம\u{bcd}மன\u{bcd} கோவெர\u{bcd}னோர\u{bbe}ட\u{bcd}"),
                        ("te", "అమ\u{c4d}మన\u{c4d} గవర\u{c4d}నర\u{c47}ట\u{c4d}"),
                        ("th", "ท\u{e34}นห\u{e4c} อ\u{e31}มมาน"),
                        ("tr", "Başkent ili"),
                        ("uk", "Мугафаза Амман"),
                        ("ur", "محافظہ عمان"),
                        ("vi", "Tỉnh Amman"),
                        ("zh", "安曼省"),
                    ]),
                    unofficial_name_list: ["Amman"].to_vec(),
                },
            ),
            (
                "AQ",
                Subdivision {
                    name: "AQ",
                    country_alpha2: Alpha2::JO,
                    code: "AQ",
                    #[cfg(feature = "geo")]
                    geo: Some(SubdivisionGeo {
                        latitude: Some(29.5319199),
                        longitude: Some(35.0060842),
                        max_latitude: None,
                        min_latitude: None,
                        max_longitude: None,
                        min_longitude: None,
                    }),
                    comments: None,
                    subdivision_type: SubdivisionType::Governorate,
                    #[cfg(feature = "translations")]
                    translations: HashMap::from([
                        ("ar", "العقبة"),
                        ("bn", "আক\u{9be}ব\u{9be} গভর\u{9cd}নোরেট"),
                        ("ccp", "𑄃𑄇\u{1112a}𑄝"),
                        ("ceb", "Aqaba"),
                        ("da", "Aqaba Governorate"),
                        ("de", "Aqaba"),
                        ("el", "Ακάμπα Γκοβερνοράτε"),
                        ("en", "Aqaba"),
                        ("es", "Gobernación de Aqaba"),
                        ("eu", "Aqaba Gobernazioa"),
                        ("fa", "استان عقبه"),
                        ("fr", "subdivision d’Aqaba"),
                        ("gu", "ઍકાબા ગવર\u{acd}નર\u{ac7}ટ"),
                        ("he", "עקבה"),
                        ("hi", "अकाबा गवर\u{94d}नर\u{947}ट"),
                        ("hu", "Akaba kormányzóság"),
                        ("hy", "Ակաբայի մարզ"),
                        ("id", "Aqaba Governorate"),
                        ("it", "governatorato di Aqaba"),
                        ("ja", "アカバ県"),
                        ("kn", "ಅಖಾಬಾ ಗವರ\u{ccd}ನೇಟ\u{ccd}"),
                        ("ko", "아카바 주"),
                        ("lt", "Akabos muchafaza"),
                        ("lv", "Akabas muhāfaza"),
                        ("mr", "अकाबा गव\u{94d}हर\u{94d}नोर\u{947}ट"),
                        ("ms", "Aqaba Governorate"),
                        ("nb", "Aqaba Givernorate"),
                        ("nl", "Akaba"),
                        ("no", "Aqaba Givernorate"),
                        ("pl", "Akaba"),
                        ("pt", "Governorado de Aqaba"),
                        ("ro", "Guvernoratul Aqaba"),
                        ("ru", "Акаба"),
                        ("si", "අකබ\u{dcf} පළ\u{dcf}ත"),
                        ("sv", "Akaba"),
                        ("ta", "அகிஆப\u{bbe} கோவெர\u{bcd}னோரேட\u{bcd}"),
                        ("te", "అక\u{c3e}బ\u{c3e} గవర\u{c4d}నర\u{c47}ట\u{c4d}"),
                        ("th", "เขตการปกครองอควาบา"),
                        ("tr", "Aqaba Yönetimi"),
                        ("uk", "Муніципалітет Акаба"),
                        ("ur", "محافظہ عقبہ"),
                        ("vi", "Tỉnh Aqaba"),
                        ("zh", "亞喀巴省"),
                    ]),
                    unofficial_name_list: ["Akaba", "Aqaba", "Aqqaba", "al-Aqaba"].to_vec(),
                },
            ),
            (
                "AT",
                Subdivision {
                    name: "AT",
                    country_alpha2: Alpha2::JO,
                    code: "AT",
                    #[cfg(feature = "geo")]
                    geo: Some(SubdivisionGeo {
                        latitude: Some(30.83583299999999),
                        longitude: Some(35.612222),
                        max_latitude: None,
                        min_latitude: None,
                        max_longitude: None,
                        min_longitude: None,
                    }),
                    comments: None,
                    subdivision_type: SubdivisionType::Governorate,
                    #[cfg(feature = "translations")]
                    translations: HashMap::from([
                        ("ar", "الطفيلة"),
                        ("bn", "ত\u{9be}ফিল\u{9be}হ গভর\u{9cd}নোরেট"),
                        ("ccp", "𑄑𑄜\u{11128}𑄣𑄦\u{11134}"),
                        ("da", "Tafilah Governorate"),
                        ("de", "Gouvernement at-Tafila"),
                        ("el", "Ταφιλάχ Γκοβερνοράτε"),
                        ("en", "Tafilah"),
                        ("es", "Gobernación de Tafila"),
                        ("eu", "Tafilah Gobernazioa"),
                        ("fa", "طفیله"),
                        ("fi", "At Tafilah"),
                        ("fr", "Gouvernorat de Tafilah"),
                        ("gu", "તાફીલા ગવર\u{acd}નોર\u{ac7}ટ"),
                        ("he", "טפילה"),
                        ("hi", "तफिला गवर\u{94d}नर\u{947}ट"),
                        ("hu", "Tafíla kormányzóság"),
                        ("hy", "Ալ-Տաֆիլայի մարզ"),
                        ("id", "Kegubernuran Tafilah"),
                        ("it", "governatorato di al-Tafila"),
                        ("ja", "タフィラ県"),
                        ("kn", "ಟಫ\u{cbf}ಲಾ ಗವರ\u{ccd}ನೇಟ\u{ccd}"),
                        ("ko", "타필라 주"),
                        ("lt", "Tafilos muchafaza"),
                        ("lv", "Tafilas muhāfaza"),
                        ("mr", "ताफीला गव\u{94d}हर\u{94d}नोर\u{947}ट"),
                        ("ms", "Tafilah Governorate"),
                        ("nb", "Tafilah Governorate"),
                        ("nl", "Tafilah"),
                        ("no", "Tafilah Governorate"),
                        ("pl", "At-Tafila"),
                        ("pt", "Governamento de Tafilah"),
                        ("ro", "Guvernoratul Tafilah"),
                        ("ru", "Эт-Тафила"),
                        ("si", "ටෆ\u{dd2}ල\u{dcf} පළ\u{dcf}ත"),
                        ("sv", "Tafilah"),
                        ("ta", "டபில\u{bbe}ஹ\u{bcd} கோவெர\u{bcd}னோகைட\u{bcd}"),
                        ("te", "ట\u{c3e}ఫ\u{c3f}ల\u{c3e} గవర\u{c4d}నర\u{c47}ట\u{c4d}"),
                        ("th", "ทาฟ\u{e34}ล\u{e4a}ะห\u{e4c} กอฟเวอโนเลท"),
                        ("tr", "Tafilah Yönetimi"),
                        ("uk", "Муніципалітет Тафіла"),
                        ("ur", "محافظہ طفیلہ"),
                        ("vi", "Tỉnh Tafilah"),
                        ("zh", "塔菲拉省"),
                    ]),
                    unofficial_name_list: ["Tafiela", "Tafileh", "at-Tafilah"].to_vec(),
                },
            ),
            (
                "AZ",
                Subdivision {
                    name: "AZ",
                    country_alpha2: Alpha2::JO,
                    code: "AZ",
                    #[cfg(feature = "geo")]
                    geo: Some(SubdivisionGeo {
                        latitude: Some(31.7515118),
                        longitude: Some(36.8680791),
                        max_latitude: Some(32.196324),
                        min_latitude: Some(31.49364899999999),
                        max_longitude: Some(37.780864),
                        min_longitude: Some(35.8889939),
                    }),
                    comments: None,
                    subdivision_type: SubdivisionType::Governorate,
                    #[cfg(feature = "translations")]
                    translations: HashMap::from([
                        ("ar", "الزرقاء"),
                        ("bn", "জ\u{9be}রক\u{9be} গভর\u{9cd}নোরেট"),
                        ("ca", "Governació de Zarqa"),
                        ("ccp", "𑄎𑄢\u{11134}𑄇"),
                        ("da", "Zarqa Governorate"),
                        ("de", "Gouvernement Zarqa"),
                        ("el", "Ζάρκα"),
                        ("en", "Zarqa"),
                        ("es", "Gobernación de Zarká"),
                        ("eu", "Zarqa Gobernazioa"),
                        ("fa", "زرقاء"),
                        ("fi", "Az Zarqa"),
                        ("fr", "subdivision de Zarqa"),
                        ("gu", "ઝારકા ગવર\u{acd}નોર\u{ac7}ટ"),
                        ("he", "מחוז זרקא"),
                        ("hi", "ज\u{93c}ारका गवर\u{94d}नर\u{947}ट"),
                        ("hu", "Zarká kormányzóság"),
                        ("id", "Kegubernuran Zarqa"),
                        ("it", "governatorato di al-Zarqa"),
                        ("ja", "ザルカ県"),
                        ("kn", "ಝರ\u{ccd}ಖಾ ಗವರ\u{ccd}ನೇಟ\u{ccd}"),
                        ("ko", "자르카 주"),
                        ("lt", "Zarkos muchafaza"),
                        ("lv", "Zerkas muhāfaza"),
                        ("mr", "झर\u{94d}क गव\u{94d}हर\u{94d}नोर\u{947}ट"),
                        ("ms", "Zarqa Governorate"),
                        ("nb", "Zarqa"),
                        ("nl", "Zarka"),
                        ("no", "Zarqa"),
                        ("pl", "Az-Zarka"),
                        ("pt", "Governorado de Zarqa"),
                        ("ro", "Guvernoratul Zarqa"),
                        ("ru", "Эз-Зарка"),
                        ("si", "සරක\u{dcf} පළ\u{dcf}ත"),
                        ("sv", "Zarqa"),
                        ("ta", "ச\u{bbe}ர\u{bcd}கிய\u{bbe} கோவெர\u{bcd}னோரே"),
                        ("te", "జర\u{c4d}ఖ\u{c3e} గవర\u{c4d}నర\u{c47}ట\u{c4d}"),
                        ("th", "ซาร\u{e4c}กา"),
                        ("tr", "Zarqa Yönetimi"),
                        ("uk", "Муніципалітет Ез-Зарка"),
                        ("ur", "محافظہ زرقاء"),
                        ("vi", "Tỉnh Zarqa"),
                        ("zh", "扎爾卡省"),
                    ]),
                    unofficial_name_list: ["Zarka", "Zarqa", "Zerka"].to_vec(),
                },
            ),
            (
                "BA",
                Subdivision {
                    name: "BA",
                    country_alpha2: Alpha2::JO,
                    code: "BA",
                    #[cfg(feature = "geo")]
                    geo: Some(SubdivisionGeo {
                        latitude: Some(31.9676039),
                        longitude: Some(35.6095474),
                        max_latitude: Some(32.183978),
                        min_latitude: Some(31.6735621),
                        max_longitude: Some(35.934166),
                        min_longitude: Some(35.519307),
                    }),
                    comments: None,
                    subdivision_type: SubdivisionType::Governorate,
                    #[cfg(feature = "translations")]
                    translations: HashMap::from([
                        ("ar", "البلقاء"),
                        ("bn", "ব\u{9be}ল\u{9cd}ক\u{9be} গভর\u{9cd}নোরেট"),
                        ("ca", "Al-Balqa"),
                        ("ccp", "𑄝\u{11127}𑄣\u{11134}𑄇"),
                        ("da", "Balqa Governorate"),
                        ("de", "Gouvernement al-Balqa"),
                        ("el", "Μπάλγκα"),
                        ("en", "Balqa"),
                        ("es", "Gobernación de Balqa’"),
                        ("eu", "Balqa Gobernazioa"),
                        ("fa", "بلقاء"),
                        ("fi", "Al Balqa’"),
                        ("fr", "subdivision de Balqa"),
                        ("gu", "બાલ\u{acd}કા ગવર\u{acd}નોર\u{ac7}ટ"),
                        ("he", "בלקא"),
                        ("hi", "बालका गवर\u{94d}नर\u{947}ट"),
                        ("hu", "Balká kormányzóság"),
                        ("id", "Balqa Governorate"),
                        ("it", "governatorato di Balqa"),
                        ("ja", "バルカ県"),
                        ("kn", "ಬಲ\u{ccd}ಕಾ ಗವರ\u{ccd}ನೇಟ\u{ccd}"),
                        ("ko", "발카 주"),
                        ("lt", "Balkos muchafaza"),
                        ("lv", "Balkas muhāfaza"),
                        ("mr", "बालका गव\u{94d}हर\u{94d}नोर\u{947}ट"),
                        ("ms", "Balqa Governorate"),
                        ("nb", "Balqa"),
                        ("nl", "Balka"),
                        ("no", "Balqa"),
                        ("pl", "Al-Balka"),
                        ("pt", "Balqa"),
                        ("ro", "Guvernoratul Balqa"),
                        ("ru", "Эль-Балка"),
                        (
                            "si",
                            "බල\u{dca}ක\u{dcf} පර\u{dd2}ප\u{dcf}ලන කොට\u{dca}ට\u{dcf}ශය",
                        ),
                        ("sq", "Governorati Balqa"),
                        ("sv", "Balqa"),
                        ("ta", "ப\u{bbe}லகிய\u{bbe} கோவெர\u{bcd}னோரே"),
                        ("te", "బ\u{c3e}ల\u{c4d}ఖ\u{c3e} గవర\u{c4d}నర\u{c47}ట\u{c4d}"),
                        ("th", "เขตผ\u{e39}\u{e49}ว\u{e48}าบ\u{e31}ลกา"),
                        ("tr", "Balqa Yönetimi"),
                        ("uk", "Муніципалітет Ель-Балка"),
                        ("ur", "محافظہ بلقاء"),
                        ("vi", "Tỉnh Balqa"),
                        ("zh", "拜勒加省"),
                    ]),
                    unofficial_name_list: ["Al Balqa'"].to_vec(),
                },
            ),
            (
                "IR",
                Subdivision {
                    name: "IR",
                    country_alpha2: Alpha2::JO,
                    code: "IR",
                    #[cfg(feature = "geo")]
                    geo: Some(SubdivisionGeo {
                        latitude: Some(32.5454418),
                        longitude: Some(35.8571532),
                        max_latitude: None,
                        min_latitude: None,
                        max_longitude: None,
                        min_longitude: None,
                    }),
                    comments: None,
                    subdivision_type: SubdivisionType::Governorate,
                    #[cfg(feature = "translations")]
                    translations: HashMap::from([
                        ("ar", "إربد"),
                        ("bn", "ইরবিদ গভর\u{9cd}নোরেট"),
                        ("ca", "Governació d’Irbid"),
                        ("ccp", "𑄃\u{11128}𑄢\u{11134}𑄝\u{11128}𑄖\u{11134}"),
                        ("ceb", "Irbid"),
                        ("da", "Irbid Governorate"),
                        ("de", "Gouvernement Irbid"),
                        ("el", "Ιρμπίντ Γκοβερνοράτε"),
                        ("en", "Irbid"),
                        ("es", "Gobernación de Irbid"),
                        ("eu", "Irbid Gobernazioa"),
                        ("fa", "استان اربد"),
                        ("fi", "Irbid"),
                        ("fr", "subdivision d’Irbid"),
                        ("gu", "ઇરબિડ ગવર\u{acd}નોર\u{ac7}ટ"),
                        ("he", "מחוז אירביד"),
                        ("hi", "आइरबिड गवर\u{94d}नर\u{947}ट"),
                        ("hu", "Irbid kormányzóság"),
                        ("hy", "Իրբիդի մարզ"),
                        ("id", "Irbid Governorate"),
                        ("it", "governatorato di Irbid"),
                        ("ja", "イルビド県"),
                        ("kn", "ಇರ\u{ccd}ಬ\u{cbf}ಡ\u{ccd} ಗವರ\u{ccd}ನೇಟ\u{ccd}"),
                        ("ko", "이르비드 주"),
                        ("lt", "Irbido muchafaza"),
                        ("lv", "Irbidas muhāfaza"),
                        ("mr", "इर\u{94d}बिड गव\u{94d}हर\u{94d}नोर\u{947}ट"),
                        ("ms", "Irbid Governorate"),
                        ("nb", "Irbid"),
                        ("nl", "Irbid"),
                        ("no", "Irbid"),
                        ("pl", "Irbid"),
                        ("pt", "Governorado de Irbid"),
                        ("ro", "Guvernoratul Irbid"),
                        ("ru", "Ирбид"),
                        ("si", "ඉර\u{dca}බ\u{dd2}ඩ\u{dca} පළ\u{dcf}ත"),
                        ("sq", "Governorati i Irbidit"),
                        ("sv", "Irbid"),
                        ("ta", "இர\u{bcd}பிட\u{bcd} கோவெர\u{bcd}னோர\u{bbe}ட\u{bcd}"),
                        (
                            "te",
                            "ఇర\u{c4d}బ\u{c3f}డ\u{c4d} గవర\u{c4d}నర\u{c47}ట\u{c4d}",
                        ),
                        ("th", "อ\u{e31}ลบ\u{e34}ด ย\u{e31}นต\u{e34}ม\u{e35}"),
                        ("tr", "Irbid Yönetimi"),
                        ("uk", "Муніципалітет Ірбід"),
                        ("ur", "محافظہ اربد"),
                        ("vi", "Tỉnh Irbid"),
                        ("zh", "伊爾比德省"),
                    ]),
                    unofficial_name_list: ["Irbit"].to_vec(),
                },
            ),
            (
                "JA",
                Subdivision {
                    name: "JA",
                    country_alpha2: Alpha2::JO,
                    code: "JA",
                    #[cfg(feature = "geo")]
                    geo: Some(SubdivisionGeo {
                        latitude: Some(32.2769016),
                        longitude: Some(35.9055502),
                        max_latitude: None,
                        min_latitude: None,
                        max_longitude: None,
                        min_longitude: None,
                    }),
                    comments: None,
                    subdivision_type: SubdivisionType::Governorate,
                    #[cfg(feature = "translations")]
                    translations: HashMap::from([
                        ("ar", "جرش"),
                        ("bn", "জ\u{9be}র\u{9be}শ গভর\u{9cd}নোরেট"),
                        ("ccp", "𑄎𑄬𑄢𑄌\u{11134}"),
                        ("ceb", "Jarash"),
                        ("da", "Jerash Governorate"),
                        ("de", "Gouvernement Dscharasch"),
                        ("el", "Τζέρας"),
                        ("en", "Jerash"),
                        ("es", "Gobernación de Gerasa"),
                        ("eu", "Jerax Gobernazioa"),
                        ("fa", "استان جرش"),
                        ("fi", "Jarash"),
                        ("fr", "subdivision de Jerash"),
                        ("gu", "જરાશ ગવર\u{acd}નોર\u{ac7}ટ"),
                        ("he", "מחוז ג׳רש"),
                        ("hi", "ज\u{947}राश"),
                        ("hu", "Dzseras kormányzóság"),
                        ("hy", "Ջարաշի մարզ"),
                        ("id", "Kegubernuran Jerash"),
                        ("it", "governatorato di Jerash"),
                        ("ja", "ジェラシュ県"),
                        ("kn", "ಜ\u{cc6}ರಾಶ\u{ccd} ಗವರ\u{ccd}ನೇಟ\u{ccd}"),
                        ("ko", "제라시 주"),
                        ("lt", "Džarašo muchafaza"),
                        ("lv", "Džerasas muhāfaza"),
                        ("mr", "ज\u{947}र\u{947}श गव\u{94d}हर\u{94d}नोर\u{947}ट"),
                        ("ms", "Jerash Governorate"),
                        ("nb", "Jerash"),
                        ("nl", "Jerash"),
                        ("no", "Jerash"),
                        ("pl", "Dżarasz (muhafaza)"),
                        ("pt", "Governorado de Gérasa"),
                        ("ro", "Guvernoratul Jerash"),
                        ("ru", "Джараш"),
                        ("si", "ජෙර\u{dcf}ෂ\u{dca} පළ\u{dcf}ත"),
                        ("sq", "Governorati Jerash"),
                        ("sv", "Jerash"),
                        ("ta", "ஜெர\u{bbe}ஷ\u{bcd} கோவெர\u{bcd}னோரே"),
                        ("te", "జ\u{c46}ర\u{c3e}ష\u{c4d} గవర\u{c4d}నర\u{c47}ట\u{c4d}"),
                        ("th", "เจราช โกเวอโนเรท"),
                        ("tr", "Jerash Yönetimi"),
                        ("uk", "Муніципалітет Джараш"),
                        ("ur", "محافظہ جرش"),
                        ("vi", "Tỉnh Jerash"),
                        ("zh", "傑拉什省"),
                    ]),
                    unofficial_name_list: ["Jarash", "Jerash"].to_vec(),
                },
            ),
            (
                "KA",
                Subdivision {
                    name: "KA",
                    country_alpha2: Alpha2::JO,
                    code: "KA",
                    #[cfg(feature = "geo")]
                    geo: Some(SubdivisionGeo {
                        latitude: Some(31.1648059),
                        longitude: Some(35.7618824),
                        max_latitude: None,
                        min_latitude: None,
                        max_longitude: None,
                        min_longitude: None,
                    }),
                    comments: None,
                    subdivision_type: SubdivisionType::Governorate,
                    #[cfg(feature = "translations")]
                    translations: HashMap::from([
                        ("ar", "الكرك"),
                        ("bn", "ক\u{9be}র\u{9be}ক গভর\u{9cd}নোরেট"),
                        ("ca", "Governació de Karak"),
                        ("ccp", "𑄇𑄬𑄢\u{11127}𑄇\u{11134}"),
                        ("ceb", "Al Karak"),
                        ("da", "Kerak"),
                        ("de", "Gouvernement Karak"),
                        ("el", "Καράκ Γκοβερνοράτε"),
                        ("en", "Karak"),
                        ("es", "Gobernación de Karak"),
                        ("eu", "Karak Gobernazioa"),
                        ("fa", "استان کرک"),
                        ("fi", "Al Karak"),
                        ("fr", "subdivision de Karak"),
                        ("gu", "કરાક ગવર\u{acd}નોર\u{ac7}ટ"),
                        ("he", "מחוז כרכ"),
                        ("hi", "करक गवर\u{94d}नर\u{947}ट"),
                        ("hu", "Karak kormányzóság"),
                        ("id", "Karak Governorate"),
                        ("it", "governatorato di al-Karak"),
                        ("ja", "カラク県"),
                        ("kn", "ಕರಾಕ\u{ccd} ಗವರ\u{ccd}ನೇಟ\u{ccd}"),
                        ("ko", "카라크 주"),
                        ("lt", "Karako muchafaza"),
                        ("lv", "Kerākas muhāfaza"),
                        ("mr", "कराक गव\u{94d}हर\u{94d}नोर\u{947}ट"),
                        ("ms", "Karak Governorate"),
                        ("nb", "Karak Governorate"),
                        ("nl", "Kerak"),
                        ("no", "Karak Governorate"),
                        ("pl", "Al-Karak"),
                        ("pt", "Karak"),
                        ("ro", "Guvernoratul Karak"),
                        ("ru", "Эль-Карак"),
                        ("si", "කරක\u{dca} පළ\u{dcf}ත"),
                        ("sv", "Karak"),
                        ("ta", "கரக\u{bcd} கோவெர\u{bcd}னோரேட\u{bcd}"),
                        (
                            "te",
                            "క\u{c3e}ర\u{c4d}డ\u{200c}క\u{c4d} గవర\u{c4d}నర\u{c47}ట\u{c4d}",
                        ),
                        ("th", "เขตการปกครองการ\u{e31}ก"),
                        ("tr", "Karak Yönetimi"),
                        ("uk", "Муніципалітет Карак"),
                        ("ur", "محافظہ کرک"),
                        ("vi", "Khu vực hành chính Karak"),
                        ("zh", "卡拉克省"),
                    ]),
                    unofficial_name_list: ["Karak", "Kerak"].to_vec(),
                },
            ),
            (
                "MA",
                Subdivision {
                    name: "MA",
                    country_alpha2: Alpha2::JO,
                    code: "MA",
                    #[cfg(feature = "geo")]
                    geo: Some(SubdivisionGeo {
                        latitude: Some(32.3616821),
                        longitude: Some(36.2193362),
                        max_latitude: None,
                        min_latitude: None,
                        max_longitude: None,
                        min_longitude: None,
                    }),
                    comments: None,
                    subdivision_type: SubdivisionType::Governorate,
                    #[cfg(feature = "translations")]
                    translations: HashMap::from([
                        ("ar", "المفرق"),
                        ("bn", "ম\u{9be}ফ\u{9cd}র\u{9be}ক গভর\u{9cd}নোরেট"),
                        ("ccp", "𑄟𑄜\u{11133}𑄢𑄇\u{11134}"),
                        ("ceb", "Al Mafraq"),
                        ("da", "Mafraq Governorate"),
                        ("de", "Gouvernement Mafraq"),
                        ("el", "Μάφρακ"),
                        ("en", "Mafraq"),
                        ("es", "Gobernación de Mafraq"),
                        ("eu", "Mafraq Gobernazioa"),
                        ("fa", "مفرق"),
                        ("fi", "Al Mafraq"),
                        ("fr", "subdivision de Mafraq"),
                        ("gu", "મફ\u{acd}રાક ગવર\u{acd}નોર\u{ac7}ટ"),
                        ("he", "מחוז מפרק"),
                        ("hi", "माफराक गवर\u{94d}नर\u{947}ट"),
                        ("hu", "Mafrak kormányzóság"),
                        ("hy", "Ալ-Մաֆրակի մարզ"),
                        ("id", "Mafraq Governorate"),
                        ("it", "governatorato di Mafraq"),
                        ("ja", "マフラク県"),
                        ("kn", "ಮಾಫ\u{ccd}ರಾಕ\u{ccd} ಗವರ\u{ccd}ನೇಟ\u{ccd}"),
                        ("ko", "마프라크 주"),
                        ("lt", "Mafrako muchafaza"),
                        ("lv", "Mefrakas muhāfaza"),
                        ("mr", "मफ\u{94d}राक गव\u{94d}हर\u{94d}नोर\u{947}ट"),
                        ("ms", "Mafraq Governorate"),
                        ("nb", "Magraq"),
                        ("nl", "Mafrak"),
                        ("no", "Magraq"),
                        ("pl", "Al-Mafrak"),
                        ("pt", "Mafraq"),
                        ("ro", "Guvernoratul Mafraq"),
                        ("ru", "Эль-Мафрак"),
                        (
                            "si",
                            "මෆ\u{dca}ර\u{dcf}ක\u{dca} පර\u{dd2}ප\u{dcf}ලන කොට\u{dca}ට\u{dcf}ශය",
                        ),
                        ("sq", "Governorati Mafrak"),
                        ("sv", "Mafraq"),
                        ("ta", "மபிர\u{bbe}க\u{bcd} கோவெர\u{bcd}னோரே"),
                        (
                            "te",
                            "మఫ\u{c4d}ర\u{c3e}క\u{c4d} గవర\u{c4d}నర\u{c47}ట\u{c4d}",
                        ),
                        ("th", "เขตผ\u{e39}\u{e49}ว\u{e48}ามาฟราค"),
                        ("tr", "Mafraq Yönetimi"),
                        ("uk", "Муніципалітет Ель-Мафрак"),
                        ("ur", "محافظہ مفرق"),
                        ("vi", "Tỉnh Mafraq"),
                        ("zh", "馬弗拉克省"),
                    ]),
                    unofficial_name_list: ["Mafraq"].to_vec(),
                },
            ),
            (
                "MD",
                Subdivision {
                    name: "MD",
                    country_alpha2: Alpha2::JO,
                    code: "MD",
                    #[cfg(feature = "geo")]
                    geo: Some(SubdivisionGeo {
                        latitude: Some(31.71954),
                        longitude: Some(35.794109),
                        max_latitude: None,
                        min_latitude: None,
                        max_longitude: None,
                        min_longitude: None,
                    }),
                    comments: None,
                    subdivision_type: SubdivisionType::Governorate,
                    #[cfg(feature = "translations")]
                    translations: HashMap::from([
                        ("ar", "مادبا"),
                        ("bn", "ম\u{9be}দ\u{9be}ব\u{9be} গভর\u{9cd}নোরেট"),
                        ("ca", "Governació de Madaba"),
                        ("ccp", "𑄟𑄓𑄝"),
                        ("da", "Madaba Governorate"),
                        ("de", "Gouvernement Madaba"),
                        ("el", "Μαντάμπα Γκοβερνοράτε"),
                        ("en", "Madaba"),
                        ("es", "Gobernación de Madaba"),
                        ("eu", "Madaba Gobernazioa"),
                        ("fa", "استان مادبا"),
                        ("fi", "Madaba"),
                        ("fr", "subdivision de Madaba"),
                        ("gu", "મડાબા ગવર\u{acd}નોર\u{ac7}ટ"),
                        ("he", "מחוז מידבא"),
                        ("hi", "मदाबा गवर\u{94d}नर\u{947}ट"),
                        ("hu", "Mádaba kormányzóság"),
                        ("hy", "Մադաբայի մարզ"),
                        ("id", "Madaba Governorate"),
                        ("it", "governatorato di Madaba"),
                        ("ja", "マダバ県"),
                        ("kn", "ಮಡಬಾ ಗವರ\u{ccd}ನೇಟ\u{ccd}"),
                        ("ko", "마다바 주"),
                        ("lt", "Madabos muchafaza"),
                        ("lv", "Mādebas muhāfaza"),
                        ("mr", "माडाबा गव\u{94d}हर\u{94d}नोर\u{947}ट"),
                        ("ms", "Madaba Governorate"),
                        ("nb", "Madaba Governorate"),
                        ("nl", "Madaba"),
                        ("no", "Madaba Governorate"),
                        ("pl", "Madaba"),
                        ("pt", "Madaba"),
                        ("ro", "Guvernoratul Madaba"),
                        ("ru", "Мадаба"),
                        ("si", "මඩබ\u{dcf} පළ\u{dcf}ත"),
                        ("sv", "Madaba (guvernement)"),
                        ("ta", "மத\u{bbe}ப\u{bbe} கோவெர\u{bcd}னோகைட\u{bcd}"),
                        ("te", "మడ\u{c3e}బ\u{c3e} గవర\u{c4d}నర\u{c47}ట\u{c4d}"),
                        ("th", "มาดาบา กอฟเวอโนเลท"),
                        ("tr", "Madaba Yönetimi"),
                        ("uk", "Муніципалітет Мадаба"),
                        ("ur", "محافظہ مادبا"),
                        ("vi", "Tỉnh Madaba"),
                        ("zh", "馬代巴省"),
                    ]),
                    unofficial_name_list: ["Madaba", "Maʿdaba", "Maʿdabâ"].to_vec(),
                },
            ),
            (
                "MN",
                Subdivision {
                    name: "MN",
                    country_alpha2: Alpha2::JO,
                    code: "MN",
                    #[cfg(feature = "geo")]
                    geo: Some(SubdivisionGeo {
                        latitude: Some(30.1949577),
                        longitude: Some(35.7342418),
                        max_latitude: None,
                        min_latitude: None,
                        max_longitude: None,
                        min_longitude: None,
                    }),
                    comments: None,
                    subdivision_type: SubdivisionType::Governorate,
                    #[cfg(feature = "translations")]
                    translations: HashMap::from([
                        ("ar", "معان"),
                        ("bn", "ম\u{9be}‘আন গভ\u{9be}র\u{9cd}নোরেট"),
                        ("ccp", "𑄟\u{11133}𑄃𑄚\u{11134}"),
                        ("da", "Ma’in Governorate"),
                        ("de", "Ma’an Governorate"),
                        ("el", "Μαάν Γκοβερνοράτε"),
                        ("en", "Ma’an"),
                        ("es", "Gobernación de Ma’an"),
                        ("eu", "Ma’an Gobernazioa"),
                        ("fa", "استان معان"),
                        ("fi", "Ma’an"),
                        ("fr", "subdivision de Ma’an"),
                        ("gu", "મા\u{a82}ન ગવર\u{acd}નોર\u{ac7}ટ"),
                        ("he", "מחוז מעאן"),
                        ("hi", "मान गवर\u{94d}नर\u{947}ट"),
                        ("hu", "Maán kormányzóság"),
                        ("hy", "Մաանի մարզ"),
                        ("id", "Ma’an"),
                        ("it", "governatorato di Ma’an"),
                        ("ja", "マアーン県"),
                        ("kn", "ಮಾಯಾನ\u{ccd} ಗವರ\u{ccd}ನೇಟ\u{ccd}"),
                        ("ko", "마안 주"),
                        ("lt", "Maano muchafaza"),
                        ("lv", "Maānas muhāfaza"),
                        ("mr", "मान गोव\u{94d}हर\u{94d}नोर\u{947}ट"),
                        ("ms", "Pentadbiran Ma’an"),
                        ("nb", "Maan Governorate"),
                        ("nl", "Ma’an"),
                        ("no", "Maan Governorate"),
                        ("pl", "Ma’an"),
                        ("pt", "Governadoria Maan"),
                        ("ro", "Guvernoratul Ma’an"),
                        ("ru", "Маан"),
                        ("si", "ම\u{dcf}න\u{dca} පළ\u{dcf}ත"),
                        ("sv", "Ma’an"),
                        ("ta", "ம\u{bbe}ன\u{bcd} கோவெர\u{bcd}னோரேட\u{bcd}"),
                        ("te", "మ\u{c3e}న\u{c4d} గవర\u{c4d}నర\u{c47}ట\u{c4d}"),
                        ("th", "เขตการปกครองมาย\u{e31}น"),
                        ("tr", "Ma’an Valiliği"),
                        ("uk", "Муніципалітет Маан"),
                        ("ur", "محافظہ معان"),
                        ("vi", "Tỉnh Ma’an"),
                        ("zh", "馬安省"),
                    ]),
                    unofficial_name_list: ["Maan", "Maʿan"].to_vec(),
                },
            ),
        ])
    }
}
#[allow(unused_imports)]
use crate::{
    Alpha2, Alpha3, Continent, Country, Region, SubRegion, WeekDay, WorldRegion, GEC, IOC,
};
#[allow(unused_imports)]
use std::collections::HashMap;
#[cfg(feature = "jo")]
pub fn new() -> Country {
    Country {
        alpha2: Alpha2::JO,
        alpha3: Alpha3::JOR,
        address_format: Some("{{recipient}}\n{{street}}\n{{postalcode}} {{city}}\n{{country}}"),
        continent: Continent::Asia,
        country_code: 962,
        currency_code: "JOD",
        gec: Some(GEC::JO),
        #[cfg(feature = "geo")]
        geo: geo::new(),
        international_prefix: "00",
        ioc: Some(IOC::JOR),
        iso_long_name: "The Hashemite Kingdom of Jordan",
        iso_short_name: "Jordan",
        official_language_list: ["ar"].to_vec(),
        spoken_language_list: ["ar"].to_vec(),
        national_destination_code_length_list: [2].to_vec(),
        national_number_length_list: [8, 9].to_vec(),
        national_prefix: "0",
        nationality: Some("Jordanian"),
        number: "400",
        postal_code: true,
        postal_code_format: Some("\\d{5}"),
        region: Some(Region::Asia),
        start_of_week: WeekDay::Sunday,
        subregion: Some(SubRegion::WesternAsia),
        un_locode: "JO",
        unofficial_name_list: [
            "Jordan",
            "الأردن",
            "Jordanien",
            "Jordanie",
            "Jordania",
            "ヨルダン",
            "Jordanië",
        ]
        .to_vec(),
        world_region: WorldRegion::EMEA,
        #[cfg(feature = "translations")]
        translations: HashMap::from([
            ("ab", "Jordan"),
            ("af", "Jordanië"),
            ("ak", "Jordan"),
            ("am", "ጆሴ፣ን"),
            ("an", "Jordan"),
            ("ar", "الأردن"),
            ("as", "জৰ\u{9cd}ড\u{9be}ন"),
            ("ay", "Jordan"),
            ("az", "İordaniya"),
            ("ba", "Jordan"),
            ("be", "Іарданія"),
            ("bg", "Йордания"),
            ("bi", "Jordan"),
            ("bn", "জর\u{9cd}ড\u{9be}ন"),
            ("bn_IN", "জর\u{9cd}ড\u{9be}ন"),
            ("br", "Jordania"),
            ("bs", "Jordan"),
            ("ca", "Jordània"),
            ("ce", "Урдан"),
            ("ch", "Jordan"),
            ("cs", "Jordánsko"),
            ("cv", "Урдан"),
            ("cy", "Gwlad Yr Iorddonen"),
            ("da", "Jordan"),
            ("de", "Jordanien"),
            ("dv", "އ\u{7aa}ރ\u{7aa}ދ\u{7aa}ނ\u{7b0}"),
            ("dz", "ཇ\u{f7c}ར་ཌན།"),
            ("ee", "Jordan"),
            ("el", "Ιορδανία"),
            ("en", "Jordan"),
            ("eo", "Jordanio"),
            ("es", "Jordania"),
            ("et", "Jordaania"),
            ("eu", "Jordania"),
            ("fa", "اردن"),
            ("ff", "Jordan"),
            ("fi", "Jordania"),
            ("fo", "Jordan"),
            ("fr", "Jordanie"),
            ("fy", "Jordaanje"),
            ("ga", "An Iordáin"),
            ("gl", "Xordania"),
            ("gn", "Jordan"),
            ("gu", "જોર\u{acd}ડન"),
            ("gv", "Yn Jordaan"),
            ("ha", "Jordan"),
            ("he", "ירדן"),
            ("hi", "जॉर\u{94d}डन"),
            ("hr", "Jordan"),
            ("ht", "Jòdani"),
            ("hu", "Jordánia"),
            ("hy", "Հորդանան"),
            ("ia", "Jordania"),
            ("id", "Yordania"),
            ("io", "Jordania"),
            ("is", "Jórdanía"),
            ("it", "Giordania"),
            ("iu", "Jordan"),
            ("ja", "ヨルダン"),
            ("ka", "იორდანია"),
            ("ki", "Jordan"),
            ("kk", "Иордания"),
            ("kl", "Jordan"),
            ("km", "ហ\u{17d2}ស\u{17ca}កដង\u{17cb}"),
            ("kn", "ಜೋರ\u{ccd}ಡಾನ\u{ccd}"),
            ("ko", "요르단"),
            ("ku", "Urdin"),
            ("kv", "Иордания"),
            ("kw", "Jordan"),
            ("ky", "Иордания"),
            ("lo", "Jordan"),
            ("lt", "Jordanija"),
            ("lv", "Jordānija"),
            ("mi", "Jordan"),
            ("mk", "Џордан"),
            ("ml", "ജോര\u{d4d}\u{200d}ഡ\u{d3e}ന\u{d4d}\u{200d}"),
            ("mn", "Ёрдан"),
            ("mr", "जॉर\u{94d}डन"),
            ("ms", "Jordan"),
            ("mt", "Ġordan"),
            (
                "my",
                "ဂျော\u{103a}ဒန\u{103a}န\u{102d}\u{102f}င\u{103a}င\u{1036}",
            ),
            ("na", "Djordan"),
            ("nb", "Jordan"),
            ("ne", "जोर\u{94d}डन"),
            ("nl", "Jordanië"),
            ("nn", "Jordan"),
            ("nv", "Jordan"),
            ("oc", "Jordania"),
            ("or", "ଜୋର\u{b4d}ଡ\u{b3e}ନ"),
            ("pa", "ਜਾਰਡਨ"),
            ("pi", "जार\u{94d}डन"),
            ("pl", "Jordania"),
            ("ps", "اردن"),
            ("pt", "Jordânia"),
            ("pt_BR", "Jordânia"),
            ("ro", "Iordania"),
            ("ru", "Иордания"),
            ("rw", "Yorudani"),
            ("sc", "Giordània"),
            ("sd", "اردن"),
            ("si", "ජෝර\u{dca}ද\u{dcf}නය"),
            ("sk", "Jordánsko"),
            ("sl", "Jordanija"),
            ("so", "Urdun"),
            ("sq", "Jordani"),
            ("sr", "Јордан"),
            ("sv", "Jordanien"),
            ("sw", "Jordan"),
            ("ta", "ஜோர\u{bcd}ட\u{bbe}ன\u{bcd}"),
            ("te", "జ\u{c4b}ర\u{c4d}డ\u{c3e}న\u{c4d}"),
            ("tg", "Ҷордон"),
            ("th", "จอร\u{e4c}แดน"),
            ("ti", "ጆርዳን"),
            ("tk", "Iordan"),
            ("tl", "Jordan"),
            ("tr", "Ürdün"),
            ("tt", "Жордан"),
            ("ug", "ئىيوردانىيە"),
            ("uk", "Йорданія"),
            ("ur", "اردن"),
            ("uz", "Iordaniya"),
            ("ve", "Jordan"),
            ("vi", "Gi-oa-đanh"),
            ("wa", "Djordaneye"),
            ("wo", "Jordaani"),
            ("xh", "Jordan"),
            ("yo", "Jọ\u{301}rdánì"),
            ("zh_CN", "约旦"),
            ("zh_HK", "約旦"),
            ("zh_TW", "約旦"),
            ("zu", "Jordan"),
        ]),
        #[cfg(feature = "subdivisions")]
        subdivisions: subdivisions::new(),
    }
}
