// DO NOT TOUCH THIS FILE. (Auto-generated via `code_gen/countries.rs`)

// The Republic of Kenya

#[cfg(all(feature = "ke", feature = "constants"))]
pub mod consts {
    #[allow(unused_imports)]
    use crate::{Alpha2, Alpha3, Continent, Region, SubRegion, WeekDay, WorldRegion, GEC, IOC};

    pub const ADDRESS_FORMAT: Option<&str> = None;
    pub const ALPHA2: Alpha2 = Alpha2::KE;
    pub const ALPHA3: Alpha3 = Alpha3::KEN;
    pub const CONTINENT: Continent = Continent::Africa;
    pub const COUNTRY_CODE: usize = 254;
    pub const CURRENCY_CODE: &str = "KES";
    pub const GEC: Option<GEC> = Some(GEC::KE);
    pub const INTERNATIONAL_PREFIX: &str = "000";
    pub const IOC: Option<IOC> = Some(IOC::KEN);
    pub const ISO_SHORT_NAME: &str = "Kenya";
    pub const ISO_LONG_NAME: &str = "The Republic of Kenya";
    pub const OFFICIAL_LANGUAGE_LIST: &[&str] = &["en", "sw"];
    pub const SPOKEN_LANGUAGE_LIST: &[&str] = &["en", "sw"];
    pub const NATIONAL_DESTINATION_CODE_LENGTH_LIST: &[usize] = &[2];
    pub const NATIONAL_NUMBER_LENGTH_LIST: &[usize] = &[9];
    pub const NATIONAL_PREFIX: &str = "0";
    pub const NATIONALITY: Option<&str> = Some("Kenyan");
    pub const NUMBER: &str = "404";
    pub const POSTAL_CODE: bool = true;
    pub const POSTAL_CODE_FORMAT: Option<&str> = Some("\\d{5}");
    pub const REGION: Option<Region> = Some(Region::Africa);
    pub const START_DAY_OF_WEEK: WeekDay = WeekDay::Monday;
    pub const SUBREGION: Option<SubRegion> = Some(SubRegion::EasternAfrica);
    pub const UN_LOCODE: &str = "KE";
    pub const UNOFFICIAL_NAME_LIST: &[&str] = &["Kenya", "Kenia", "ケニア"];
    pub const WORLD_REGION: WorldRegion = WorldRegion::EMEA;
    #[cfg(feature = "translations")]
    pub const TRANSLATIONS: &[(&str, &str)] = &[
        ("ab", "Kenya"),
        ("af", "Kenia"),
        ("ak", "Kenya"),
        ("am", "ኬንያ"),
        ("an", "Kenya"),
        ("ar", "كينيا"),
        ("as", "কেনিয়\u{9be}"),
        ("ay", "Kenya"),
        ("az", "Kenya"),
        ("ba", "Kenya"),
        ("be", "Кенія"),
        ("bg", "Кения"),
        ("bi", "Kenya"),
        ("bn", "কেনিয়\u{9be}"),
        ("bn_IN", "কেনিয়\u{9be}"),
        ("br", "Kenya"),
        ("bs", "Kenija"),
        ("ca", "Kenya"),
        ("ce", "Кени"),
        ("ch", "Kenya"),
        ("cs", "Keňa"),
        ("cv", "Кени"),
        ("cy", "Kenya"),
        ("da", "Kenya"),
        ("de", "Kenia"),
        ("dv", "ކ\u{7ac}ނ\u{7b0}ޔ\u{7a7}"),
        ("dz", "ཀ\u{f7a}ན་ཡ།"),
        ("ee", "Kenya"),
        ("el", "Κένυα"),
        ("en", "Kenya"),
        ("eo", "Kenjo"),
        ("es", "Kenia"),
        ("et", "Kenya"),
        ("eu", "Kenya"),
        ("fa", "کنیا"),
        ("ff", "Kenya"),
        ("fi", "Kenia"),
        ("fo", "Kenja"),
        ("fr", "Kenya"),
        ("fy", "Kenya"),
        ("ga", "An Chéinia"),
        ("gl", "Quenia"),
        ("gn", "Kenya"),
        ("gu", "ક\u{ac7}ન\u{acd}યા"),
        ("gv", "Yn Cheinney"),
        ("ha", "Kenya"),
        ("he", "קניה"),
        ("hi", "कीनिया"),
        ("hr", "Kenija"),
        ("ht", "Kenya"),
        ("hu", "Kenya"),
        ("hy", "Քենիա"),
        ("ia", "Kenya"),
        ("id", "Kenya"),
        ("io", "Kenia"),
        ("is", "Kenía"),
        ("it", "Kenya"),
        ("iu", "Kenya"),
        ("ja", "ケニア"),
        ("ka", "კენია"),
        ("ki", "Kenya"),
        ("kk", "Кения"),
        ("kl", "Kenya"),
        ("km", "កេនយ\u{17c9}ា"),
        ("kn", "ಕೀನ\u{ccd}ಯಾ"),
        ("ko", "케냐"),
        ("ku", "Kenya"),
        ("kv", "Kenya"),
        ("kw", "Kenya"),
        ("ky", "Кения"),
        ("lo", "Kenya"),
        ("lt", "Kenija"),
        ("lv", "Kenija"),
        ("mi", "Kēnia"),
        ("mk", "Кенија"),
        ("ml", "കെനിയ"),
        ("mn", "Кениа"),
        ("mr", "क\u{947}निया"),
        ("ms", "Kenya"),
        ("mt", "Kenja"),
        ("my", "ကင\u{103a}ညာန\u{102d}\u{102f}င\u{103a}င\u{1036}"),
        ("na", "Keniya"),
        ("nb", "Kenya"),
        ("ne", "क\u{947}न\u{94d}या"),
        ("nl", "Kenia"),
        ("nn", "Kenya"),
        ("nv", "Kenya"),
        ("oc", "Kenya"),
        ("or", "କେନ\u{b3f}ୟ\u{b3e}"),
        ("pa", "ਕੀਨੀਆ"),
        ("pi", "क\u{947}न\u{94d}या"),
        ("pl", "Kenia"),
        ("ps", "کېنيا"),
        ("pt", "Quénia"),
        ("pt_BR", "Quênia"),
        ("ro", "Kenia"),
        ("ru", "Кения"),
        ("rw", "Kenya"),
        ("sc", "Kènya"),
        ("sd", "Kenya"),
        ("si", "කෙන\u{dca}ය\u{dcf}ව"),
        ("sk", "Keňa"),
        ("sl", "Kenija"),
        ("so", "Kiiniya"),
        ("sq", "Kenia"),
        ("sr", "Кенија"),
        ("sv", "Kenya"),
        ("sw", "Kenya"),
        ("ta", "கென\u{bcd}ய\u{bbe}"),
        ("te", "క\u{c46}న\u{c4d}య\u{c3e}"),
        ("tg", "Кения"),
        ("th", "เคนยา"),
        ("ti", "ኬንያ"),
        ("tk", "Keniýa"),
        ("tl", "Kenya"),
        ("tr", "Kenya"),
        ("tt", "Кениа"),
        ("ug", "كېنىيە"),
        ("uk", "Кенія"),
        ("ur", "کینیا"),
        ("uz", "Keniya"),
        ("ve", "Kenya"),
        ("vi", "Khi-ni-a"),
        ("wa", "Kenia"),
        ("wo", "Kenya"),
        ("xh", "Kenya"),
        ("yo", "Kẹ\u{301}nyà"),
        ("zh_CN", "肯尼亚"),
        ("zh_HK", "肯雅"),
        ("zh_TW", "肯亞"),
        ("zu", "IKenya"),
    ];
    #[cfg(all(feature = "ke", feature = "geo", feature = "constants"))]
    pub mod geo {
        pub const LATITUDE: f64 = -0.023559;
        pub const LONGITUDE: f64 = 37.906193;
        pub const MAX_LATITUDE: f64 = 5.033420899999999;
        pub const MAX_LONGITUDE: f64 = 41.9069449;
        pub const MIN_LATITUDE: f64 = -4.724299999999999;
        pub const MIN_LONGITUDE: f64 = 33.90982109999999;
        pub const NORTHEAST_LATITUDE: f64 = 5.033420899999999;
        pub const NORTHEAST_LONGITUDE: f64 = 41.9069449;
        pub const SOUTHWEST_LATITUDE: f64 = -4.724299999999999;
        pub const SOUTHWEST_LONGITUDE: f64 = 33.90982109999999;
    }
}
#[cfg(all(feature = "ke", feature = "geo"))]
pub mod geo {
    use crate::{CountryGeo, CountryGeoBound, CountryGeoBounds};

    pub fn new() -> CountryGeo {
        CountryGeo {
            latitude: -0.023559,
            longitude: 37.906193,
            max_latitude: 5.033420899999999,
            max_longitude: 41.9069449,
            min_latitude: -4.724299999999999,
            min_longitude: 33.90982109999999,
            bounds: CountryGeoBounds {
                northeast: CountryGeoBound {
                    latitude: 5.033420899999999,
                    longitude: 41.9069449,
                },
                southwest: CountryGeoBound {
                    latitude: -4.724299999999999,
                    longitude: 33.90982109999999,
                },
            },
        }
    }
}

#[cfg(all(feature = "ke", feature = "subdivisions"))]
pub mod subdivisions {
    use crate::Subdivision;
    use std::collections::HashMap;
    // In this state, We do not know if subdivisions have geo or not!
    #[cfg(feature = "geo")]
    #[allow(unused_imports)]
    use crate::{Alpha2, SubdivisionGeo, SubdivisionType};

    pub fn new() -> HashMap<&'static str, Subdivision> {
        HashMap::from([
            (
                "01",
                Subdivision {
                    name: "01",
                    country_alpha2: Alpha2::KE,
                    code: "01",
                    #[cfg(feature = "geo")]
                    geo: None,
                    comments: None,
                    subdivision_type: SubdivisionType::County,
                    #[cfg(feature = "translations")]
                    translations: HashMap::from([
                        ("ccp", "𑄝𑄢\u{11128}\u{11101}𑄉\u{1112e}"),
                        ("ceb", "Baringo"),
                        ("de", "Baringo County"),
                        ("en", "Baringo"),
                        ("es", "Condado de Baringo"),
                        ("fa", "شهرستان بارینگو"),
                        ("ja", "バリンゴ (カウンティ)"),
                        ("ko", "바링고 현"),
                        ("nb", "Baringo fylke"),
                        ("nl", "Baringo"),
                        ("no", "Baringo fylke"),
                        ("ru", "Баринго"),
                        ("sv", "Baringo"),
                        ("sw", "Wilaya ya Baringo"),
                        ("ur", "بارنگو کاؤنٹی"),
                        ("vi", "Baringo"),
                        ("zh", "巴林戈郡"),
                    ]),
                    unofficial_name_list: [].to_vec(),
                },
            ),
            (
                "02",
                Subdivision {
                    name: "02",
                    country_alpha2: Alpha2::KE,
                    code: "02",
                    #[cfg(feature = "geo")]
                    geo: None,
                    comments: None,
                    subdivision_type: SubdivisionType::County,
                    #[cfg(feature = "translations")]
                    translations: HashMap::from([
                        ("ccp", "𑄝\u{11127}𑄟𑄬𑄖\u{11134}"),
                        ("ceb", "Bomet (lalawigan)"),
                        ("de", "Bomet County"),
                        ("en", "Bomet"),
                        ("es", "Condado de Bomet"),
                        ("fa", "شهرستان بومت"),
                        ("ja", "ボメット (カウンティ)"),
                        ("ko", "보메트 현"),
                        ("nb", "Bomet (distrikt)"),
                        ("nl", "Bomet"),
                        ("no", "Bomet (distrikt)"),
                        ("sv", "Bomet (distrikt)"),
                        ("sw", "Wilaya ya Bomet"),
                        ("ur", "بومت کاؤنٹی"),
                        ("vi", "Bomet"),
                        ("zh", "博美特郡"),
                    ]),
                    unofficial_name_list: [].to_vec(),
                },
            ),
            (
                "03",
                Subdivision {
                    name: "03",
                    country_alpha2: Alpha2::KE,
                    code: "03",
                    #[cfg(feature = "geo")]
                    geo: None,
                    comments: None,
                    subdivision_type: SubdivisionType::County,
                    #[cfg(feature = "translations")]
                    translations: HashMap::from([
                        ("ccp", "𑄝𑄚\u{11134}𑄉\u{1112e}𑄟"),
                        ("de", "Bungoma County"),
                        ("en", "Bungoma"),
                        ("es", "Condado de Bungoma"),
                        ("fa", "شهرستان بونگوما"),
                        ("fi", "Bungoman piirikunta"),
                        ("fr", "Bungoma (comté du Kenya)"),
                        ("ja", "ブンゴマ (カウンティ)"),
                        ("ko", "붕고마 현"),
                        ("nb", "Bungoma fylke"),
                        ("nl", "Bungoma County"),
                        ("no", "Bungoma fylke"),
                        ("sv", "Bungoma"),
                        ("sw", "Wilaya ya Bungoma"),
                        ("ur", "بونگوما کاؤنٹی"),
                        ("vi", "Bungoma"),
                        ("zh", "邦戈馬郡"),
                    ]),
                    unofficial_name_list: [].to_vec(),
                },
            ),
            (
                "04",
                Subdivision {
                    name: "04",
                    country_alpha2: Alpha2::KE,
                    code: "04",
                    #[cfg(feature = "geo")]
                    geo: None,
                    comments: None,
                    subdivision_type: SubdivisionType::County,
                    #[cfg(feature = "translations")]
                    translations: HashMap::from([
                        ("ca", "Busia"),
                        ("ccp", "𑄝\u{11128}𑄅\u{1112a}𑄥\u{11128}𑄠"),
                        ("ceb", "Busia"),
                        ("de", "Busia County"),
                        ("en", "Busia"),
                        ("es", "Condado de Busia"),
                        ("fa", "شهرستان بوسیا"),
                        ("fr", "Busia"),
                        ("ja", "ブシア (カウンティ)"),
                        ("ko", "부시아 현"),
                        ("nb", "Busia fylke"),
                        ("nl", "Busia"),
                        ("no", "Busia fylke"),
                        ("ru", "Бусиа (округ, Кения)"),
                        ("sv", "Busia (distrikt i Kenya)"),
                        ("sw", "Wilaya ya Busia, Kenya"),
                        ("ur", "بوسیا کاؤنٹی"),
                        ("vi", "Busia"),
                        ("zh", "布希亞郡"),
                    ]),
                    unofficial_name_list: [].to_vec(),
                },
            ),
            (
                "05",
                Subdivision {
                    name: "05",
                    country_alpha2: Alpha2::KE,
                    code: "05",
                    #[cfg(feature = "geo")]
                    geo: None,
                    comments: None,
                    subdivision_type: SubdivisionType::County,
                    #[cfg(feature = "translations")]
                    translations: HashMap::from([
                        ("ccp", "𑄃𑄬𑄣\u{11134}𑄉𑄬𑄃\u{1112e}-𑄟𑄢𑄇\u{11134}𑄤𑄬𑄖\u{11134}"),
                        ("de", "Elgeyo-Marakwet County"),
                        ("en", "Elgeyo-Marakwet"),
                        ("es", "Condado de Elgeyo-Marakwet"),
                        ("ko", "엘게요마라퀘트 현"),
                        ("nb", "Elgeyo-Marakwet fylke"),
                        ("nl", "Elgeyo-Marakwet County"),
                        ("no", "Elgeyo-Marakwet fylke"),
                        ("ur", "ایلگیو-ماراکوت کاؤنٹی"),
                        ("zh", "埃爾格約-馬拉奎特郡"),
                    ]),
                    unofficial_name_list: [].to_vec(),
                },
            ),
            (
                "06",
                Subdivision {
                    name: "06",
                    country_alpha2: Alpha2::KE,
                    code: "06",
                    #[cfg(feature = "geo")]
                    geo: None,
                    comments: None,
                    subdivision_type: SubdivisionType::County,
                    #[cfg(feature = "translations")]
                    translations: HashMap::from([
                        ("ccp", "𑄃𑄬𑄟\u{11134}𑄝\u{1112a}"),
                        ("ceb", "Embu (lalawigan)"),
                        ("de", "Embu County"),
                        ("en", "Embu"),
                        ("es", "Condado de Embu"),
                        ("fa", "شهرستان امبو"),
                        ("fi", "Embun piirikunta"),
                        ("it", "Contea di Embu"),
                        ("ja", "エンブ (カウンティ)"),
                        ("ko", "엠부 현"),
                        ("nb", "Embu fylke"),
                        ("nl", "Embu"),
                        ("no", "Embu fylke"),
                        ("sv", "Embu (distrikt)"),
                        ("sw", "Wilaya ya Embu"),
                        ("ur", "عمبو کاؤنٹی"),
                        ("vi", "Embu"),
                        ("zh", "恩布郡"),
                    ]),
                    unofficial_name_list: [].to_vec(),
                },
            ),
            (
                "07",
                Subdivision {
                    name: "07",
                    country_alpha2: Alpha2::KE,
                    code: "07",
                    #[cfg(feature = "geo")]
                    geo: None,
                    comments: None,
                    subdivision_type: SubdivisionType::County,
                    #[cfg(feature = "translations")]
                    translations: HashMap::from([
                        ("ca", "Comtat de Garissa"),
                        ("ccp", "𑄉𑄢\u{11128}𑄥"),
                        ("ceb", "Garissa"),
                        ("de", "Garissa County"),
                        ("en", "Garissa"),
                        ("es", "Condado de Garissa"),
                        ("fa", "شهرستان گاریسا"),
                        ("fr", "Garissa"),
                        ("it", "Contea di Garissa"),
                        ("ja", "ガリッサ (カウンティ)"),
                        ("ko", "가리사 현"),
                        ("nb", "Garissa (distrikt)"),
                        ("nl", "Garissa"),
                        ("no", "Garissa (distrikt)"),
                        ("ru", "Гарисса (округ)"),
                        ("sv", "Garissa (distrikt)"),
                        ("sw", "Wilaya ya Garissa"),
                        ("ur", "گاریسا کاؤنٹی"),
                        ("vi", "Garissa"),
                        ("zh", "加里薩郡"),
                    ]),
                    unofficial_name_list: [].to_vec(),
                },
            ),
            (
                "08",
                Subdivision {
                    name: "08",
                    country_alpha2: Alpha2::KE,
                    code: "08",
                    #[cfg(feature = "geo")]
                    geo: None,
                    comments: None,
                    subdivision_type: SubdivisionType::County,
                    #[cfg(feature = "translations")]
                    translations: HashMap::from([
                        ("ccp", "𑄦\u{1112e}𑄟 𑄝𑄬"),
                        ("ceb", "Homa Bay (lalawigan)"),
                        ("de", "Homa Bay County"),
                        ("en", "Homa Bay"),
                        ("es", "Condado de Homa Bay"),
                        ("fa", "شهرستان خلیج هوما"),
                        ("fr", "Homa Bay (district du Kenya)"),
                        ("ja", "ホマ・ベイ (カウンティ)"),
                        ("ko", "호마베이 현"),
                        ("nb", "Homa Bay fylke"),
                        ("nl", "Homa Bay"),
                        ("no", "Homa Bay fylke"),
                        ("pl", "Wilaya ya Homa Bay"),
                        ("sv", "Homa Bay (distrikt)"),
                        ("sw", "Wilaya ya Homa Bay"),
                        ("ur", "ہوما بے کاؤنٹی"),
                        ("vi", "Homa Bay"),
                        ("zh", "霍馬灣郡"),
                    ]),
                    unofficial_name_list: [].to_vec(),
                },
            ),
            (
                "09",
                Subdivision {
                    name: "09",
                    country_alpha2: Alpha2::KE,
                    code: "09",
                    #[cfg(feature = "geo")]
                    geo: None,
                    comments: None,
                    subdivision_type: SubdivisionType::County,
                    #[cfg(feature = "translations")]
                    translations: HashMap::from([
                        ("ccp", "𑄃\u{1112d}𑄥\u{11128}𑄃\u{1112e}𑄣\u{1112e}"),
                        ("ceb", "Isiolo"),
                        ("de", "Isiolo County"),
                        ("en", "Isiolo"),
                        ("es", "Condado de Isiolo"),
                        ("fa", "شهرستان ایسیولو"),
                        ("it", "Contea di Isiolo"),
                        ("ja", "イシオロ (カウンティ)"),
                        ("ko", "이시올로 현"),
                        ("nb", "Isiolo fylke"),
                        ("nl", "Isiolo"),
                        ("no", "Isiolo fylke"),
                        ("sv", "Isiolo"),
                        ("sw", "Wilaya ya Isiolo"),
                        ("ur", "اسیولو کاؤنٹی"),
                        ("vi", "Isiolo"),
                        ("zh", "伊希約洛郡"),
                    ]),
                    unofficial_name_list: [].to_vec(),
                },
            ),
            (
                "10",
                Subdivision {
                    name: "10",
                    country_alpha2: Alpha2::KE,
                    code: "10",
                    #[cfg(feature = "geo")]
                    geo: None,
                    comments: None,
                    subdivision_type: SubdivisionType::County,
                    #[cfg(feature = "translations")]
                    translations: HashMap::from([
                        ("ccp", "𑄇𑄎\u{11128}𑄠𑄓\u{1112e}"),
                        ("ceb", "Kajiado (lalawigan)"),
                        ("de", "Kajiado County"),
                        ("en", "Kajiado"),
                        ("es", "Condado de Kajiado"),
                        ("fa", "شهرستان کاجیادو"),
                        ("fr", "Kajiado (comté du Kenya)"),
                        ("ja", "カジアド (カウンティ)"),
                        ("ko", "카지아도 현"),
                        ("nb", "Kajiado fylke"),
                        ("nl", "Kajiado"),
                        ("no", "Kajiado fylke"),
                        ("pt", "Distrito de Kajiado"),
                        ("sv", "Kajiado"),
                        ("sw", "Wilaya ya Kajiado"),
                        ("ur", "کاجیادو کاؤنٹی"),
                        ("vi", "Kajiado"),
                        ("zh", "卡耶亞多郡"),
                    ]),
                    unofficial_name_list: [].to_vec(),
                },
            ),
            (
                "11",
                Subdivision {
                    name: "11",
                    country_alpha2: Alpha2::KE,
                    code: "11",
                    #[cfg(feature = "geo")]
                    geo: None,
                    comments: None,
                    subdivision_type: SubdivisionType::County,
                    #[cfg(feature = "translations")]
                    translations: HashMap::from([
                        ("ccp", "𑄇𑄇𑄟𑄬𑄉"),
                        ("ceb", "Kakamega"),
                        ("de", "Kakamega County"),
                        ("en", "Kakamega"),
                        ("es", "Condado de Kakamega"),
                        ("fa", "شهرستان کاکامگا"),
                        ("fi", "Kakamegan piirikunta"),
                        ("fr", "Kakamega"),
                        ("ja", "カカメガ (カウンティ)"),
                        ("ko", "카카메가 현"),
                        ("nb", "Kakamega fylke"),
                        ("nl", "Kakamega"),
                        ("no", "Kakamega fylke"),
                        ("sv", "Kakamega (distrikt)"),
                        ("sw", "Wilaya ya Kakamega"),
                        ("ur", "کاکامیگا کاؤنٹی"),
                        ("vi", "Kakamega"),
                        ("zh", "卡卡梅加郡"),
                    ]),
                    unofficial_name_list: [].to_vec(),
                },
            ),
            (
                "12",
                Subdivision {
                    name: "12",
                    country_alpha2: Alpha2::KE,
                    code: "12",
                    #[cfg(feature = "geo")]
                    geo: None,
                    comments: None,
                    subdivision_type: SubdivisionType::County,
                    #[cfg(feature = "translations")]
                    translations: HashMap::from([
                        ("ccp", "𑄇𑄬𑄢\u{11128}𑄌\u{1112e}"),
                        ("ceb", "Kericho"),
                        ("de", "Kericho County"),
                        ("en", "Kericho"),
                        ("es", "Condado de Kericho"),
                        ("fa", "شهرستان کریچو"),
                        ("fi", "Kerichon piirikunta"),
                        ("ja", "ケリチョ (カウンティ)"),
                        ("ko", "케리초 현"),
                        ("nb", "Kericho fylke"),
                        ("nl", "Kericho"),
                        ("no", "Kericho fylke"),
                        ("sv", "Kericho (distrikt)"),
                        ("sw", "Wilaya ya Kericho"),
                        ("ur", "کیریچو کاؤنٹی"),
                        ("vi", "Kericho"),
                        ("zh", "凱里喬郡"),
                    ]),
                    unofficial_name_list: [].to_vec(),
                },
            ),
            (
                "13",
                Subdivision {
                    name: "13",
                    country_alpha2: Alpha2::KE,
                    code: "13",
                    #[cfg(feature = "geo")]
                    geo: None,
                    comments: None,
                    subdivision_type: SubdivisionType::County,
                    #[cfg(feature = "translations")]
                    translations: HashMap::from([
                        ("ccp", "𑄇\u{11128}𑄠𑄟\u{11134}𑄝\u{1112a}"),
                        ("ceb", "Kiambu"),
                        ("de", "Kiambu County"),
                        ("en", "Kiambu"),
                        ("es", "Condado de Kiambu"),
                        ("fa", "شهرستان کیامبو"),
                        ("fi", "Kiambun piirikunta"),
                        ("it", "Distretto di Kiambu"),
                        ("ja", "キアンブ (カウンティ)"),
                        ("ko", "키암부 현"),
                        ("nb", "Kiambu fylke"),
                        ("nl", "Kiambu"),
                        ("no", "Kiambu fylke"),
                        ("sv", "Kiambu"),
                        ("sw", "Wilaya ya Kiambu"),
                        ("ur", "کیامبو کاؤنٹی"),
                        ("vi", "Kiambu"),
                        ("zh", "基安布郡"),
                    ]),
                    unofficial_name_list: [].to_vec(),
                },
            ),
            (
                "14",
                Subdivision {
                    name: "14",
                    country_alpha2: Alpha2::KE,
                    code: "14",
                    #[cfg(feature = "geo")]
                    geo: None,
                    comments: None,
                    subdivision_type: SubdivisionType::County,
                    #[cfg(feature = "translations")]
                    translations: HashMap::from([
                        ("ccp", "𑄇\u{11128}𑄣\u{11128}𑄜\u{11128}"),
                        ("ceb", "Kilifi"),
                        ("de", "Kilifi County"),
                        ("en", "Kilifi"),
                        ("es", "Distrito de Kilifi"),
                        ("fa", "شهرستان کیلیفی"),
                        ("fi", "Kilifin piirikunta"),
                        ("fr", "Kilifi"),
                        ("it", "Distretto di Kilifi"),
                        ("ja", "キリフィ (カウンティ)"),
                        ("ko", "킬리피 현"),
                        ("nb", "Kilifi fylke"),
                        ("nl", "Kilifi"),
                        ("no", "Kilifi fylke"),
                        ("sv", "Kilifi (distrikt)"),
                        ("sw", "Wilaya ya Kilifi"),
                        ("ur", "کیلیفی کاؤنٹی"),
                        ("vi", "Kilifi"),
                        ("zh", "基利菲县"),
                    ]),
                    unofficial_name_list: [].to_vec(),
                },
            ),
            (
                "15",
                Subdivision {
                    name: "15",
                    country_alpha2: Alpha2::KE,
                    code: "15",
                    #[cfg(feature = "geo")]
                    geo: None,
                    comments: None,
                    subdivision_type: SubdivisionType::County,
                    #[cfg(feature = "translations")]
                    translations: HashMap::from([
                        ("ccp", "𑄇\u{11128}𑄢\u{11128}𑄚\u{11128}𑄠𑄉"),
                        ("ceb", "Kirinyaga"),
                        ("de", "Kirinyaga County"),
                        ("en", "Kirinyaga"),
                        ("es", "Condado de Kirinyaga"),
                        ("fa", "شهرستان کیرینیاگا"),
                        ("fi", "Kirinyagan piirikunta"),
                        ("he", "קריניאגה"),
                        ("it", "Distretto di Kirinyaga"),
                        ("ja", "キリーニャガ (カウンティ)"),
                        ("ko", "키리니아가 현"),
                        ("nb", "Kirinyaga fylke"),
                        ("nl", "Kirinyaga"),
                        ("no", "Kirinyaga fylke"),
                        ("sv", "Kirinyaga"),
                        ("sw", "Wilaya ya Kirinyaga"),
                        ("ur", "کیرینیاگا کاؤنٹی"),
                        ("zh", "基里尼亞加郡"),
                    ]),
                    unofficial_name_list: [].to_vec(),
                },
            ),
            (
                "16",
                Subdivision {
                    name: "16",
                    country_alpha2: Alpha2::KE,
                    code: "16",
                    #[cfg(feature = "geo")]
                    geo: None,
                    comments: None,
                    subdivision_type: SubdivisionType::County,
                    #[cfg(feature = "translations")]
                    translations: HashMap::from([
                        ("ccp", "𑄇\u{11128}𑄥\u{11133}𑄦\u{11128}"),
                        ("ceb", "Kisii"),
                        ("de", "Kisii County"),
                        ("en", "Kisii"),
                        ("es", "Condado de Kisii"),
                        ("fa", "شهرستان کیسی"),
                        ("fi", "Kisiin piirikunta"),
                        ("fr", "Kisii"),
                        ("ja", "キシイ県"),
                        ("ko", "키시 현"),
                        ("nb", "Kisii (distrikt)"),
                        ("nl", "Kisii"),
                        ("no", "Kisii (distrikt)"),
                        ("pt", "Kisii (distrito)"),
                        ("ro", "Kisii"),
                        ("ru", "Кисии"),
                        ("sv", "Kisii (distrikt)"),
                        ("sw", "Wilaya ya Kisii Kati"),
                        ("ur", "کیسیی کاؤنٹی"),
                        ("zh", "基西郡"),
                    ]),
                    unofficial_name_list: [].to_vec(),
                },
            ),
            (
                "17",
                Subdivision {
                    name: "17",
                    country_alpha2: Alpha2::KE,
                    code: "17",
                    #[cfg(feature = "geo")]
                    geo: None,
                    comments: None,
                    subdivision_type: SubdivisionType::County,
                    #[cfg(feature = "translations")]
                    translations: HashMap::from([
                        ("ar", "منطقة كيزيمو"),
                        ("ccp", "𑄇\u{11128}𑄥\u{1112a}𑄟\u{1112a}"),
                        ("ceb", "Kisumu"),
                        ("de", "Kisumu County"),
                        ("en", "Kisumu"),
                        ("es", "Condado de Kisumu"),
                        ("fa", "شهرستان کیسومو"),
                        ("fr", "Kisumu (district du Kenya)"),
                        ("ja", "キスム (カウンティ)"),
                        ("ko", "키수무 현"),
                        ("nb", "Kisumu fylke"),
                        ("nl", "Kisumu"),
                        ("no", "Kisumu fylke"),
                        ("pt", "Kisumu (distrito)"),
                        ("sv", "Kisumu (distrikt)"),
                        ("sw", "Wilaya ya Kisumu"),
                        ("ur", "کسیمو کاؤنٹی"),
                        ("vi", "Kisumu"),
                        ("zh", "基蘇木郡"),
                    ]),
                    unofficial_name_list: [].to_vec(),
                },
            ),
            (
                "18",
                Subdivision {
                    name: "18",
                    country_alpha2: Alpha2::KE,
                    code: "18",
                    #[cfg(feature = "geo")]
                    geo: None,
                    comments: None,
                    subdivision_type: SubdivisionType::County,
                    #[cfg(feature = "translations")]
                    translations: HashMap::from([
                        ("ccp", "𑄇\u{11128}𑄑\u{1112d}\u{1112a}"),
                        ("ceb", "Kitui"),
                        ("da", "Kitui"),
                        ("de", "Kitui County"),
                        ("en", "Kitui"),
                        ("es", "Condado de Kitui"),
                        ("fa", "شهرستان کیتوی"),
                        ("fi", "Kituin piirikunta"),
                        ("fr", "Comté de Kitui"),
                        ("ja", "キツイ (カウンティ)"),
                        ("ko", "키투이 현"),
                        ("nb", "Kitui fylke"),
                        ("nl", "Kitui"),
                        ("no", "Kitui fylke"),
                        ("sv", "Kitui"),
                        ("sw", "Wilaya ya Kitui"),
                        ("ur", "کیتوئی کاؤنٹی"),
                        ("vi", "Kitui"),
                        ("zh", "基圖伊郡"),
                    ]),
                    unofficial_name_list: [].to_vec(),
                },
            ),
            (
                "19",
                Subdivision {
                    name: "19",
                    country_alpha2: Alpha2::KE,
                    code: "19",
                    #[cfg(feature = "geo")]
                    geo: None,
                    comments: None,
                    subdivision_type: SubdivisionType::County,
                    #[cfg(feature = "translations")]
                    translations: HashMap::from([
                        ("ccp", "𑄇𑄬𑄤𑄣𑄬"),
                        ("ceb", "Kwale"),
                        ("de", "Kwale County"),
                        ("en", "Kwale"),
                        ("es", "Condado de Kwale"),
                        ("fa", "شهرستان کوالی"),
                        ("fr", "Kwale"),
                        ("it", "Distretto di Kwale"),
                        ("ja", "クワレ (カウンティ)"),
                        ("ko", "콸레 현"),
                        ("nb", "Kwale fylke"),
                        ("nl", "Kwale"),
                        ("no", "Kwale fylke"),
                        ("sv", "Kwale"),
                        ("sw", "Wilaya ya Kwale"),
                        ("ur", "کوالے کاؤنٹی"),
                        ("vi", "Kwale"),
                        ("zh", "夸勒郡"),
                    ]),
                    unofficial_name_list: [].to_vec(),
                },
            ),
            (
                "20",
                Subdivision {
                    name: "20",
                    country_alpha2: Alpha2::KE,
                    code: "20",
                    #[cfg(feature = "geo")]
                    geo: None,
                    comments: None,
                    subdivision_type: SubdivisionType::County,
                    #[cfg(feature = "translations")]
                    translations: HashMap::from([
                        ("bg", "Лаикипиа"),
                        ("ccp", "𑄣\u{1112d}𑄇\u{11128}𑄛\u{11128}𑄠"),
                        ("ceb", "Laikipia"),
                        ("de", "Laikipia County"),
                        ("en", "Laikipia"),
                        ("es", "Condado de Laikipia"),
                        ("fa", "شهرستان لایکیپیا"),
                        ("hy", "Լայկիպիա"),
                        ("it", "Distretto di Laikipia"),
                        ("ja", "ライキピア (カウンティ)"),
                        ("ko", "라이키피아 현"),
                        ("nb", "Laikipia fylke"),
                        ("nl", "Laikipia"),
                        ("no", "Laikipia fylke"),
                        ("ru", "Лайкипиа"),
                        ("sv", "Laikipia"),
                        ("sw", "Wilaya ya Laikipia"),
                        ("ur", "لائکی پیا کاؤنٹی"),
                        ("vi", "Laikipia"),
                        ("zh", "萊基皮亞郡"),
                    ]),
                    unofficial_name_list: [].to_vec(),
                },
            ),
            (
                "21",
                Subdivision {
                    name: "21",
                    country_alpha2: Alpha2::KE,
                    code: "21",
                    #[cfg(feature = "geo")]
                    geo: None,
                    comments: None,
                    subdivision_type: SubdivisionType::County,
                    #[cfg(feature = "translations")]
                    translations: HashMap::from([
                        ("ca", "Districte de Lamu"),
                        ("ccp", "𑄣𑄟\u{11134}𑄝\u{1112a}"),
                        ("ceb", "Lamu District"),
                        ("en", "Lamu"),
                        ("es", "Condado de Lamu"),
                        ("fa", "شهرستان لامو"),
                        ("fr", "Lamu"),
                        ("it", "Contea di Lamu"),
                        ("ja", "ラム (カウンティ)"),
                        ("ko", "라무 현"),
                        ("nb", "Lamu fylke"),
                        ("nl", "Lamu"),
                        ("no", "Lamu fylke"),
                        ("sv", "Lamu"),
                        ("sw", "Wilaya ya Lamu"),
                        ("ur", "لامو کاؤنٹی"),
                        ("vi", "Lamu"),
                        ("zh", "拉穆郡"),
                    ]),
                    unofficial_name_list: [].to_vec(),
                },
            ),
            (
                "22",
                Subdivision {
                    name: "22",
                    country_alpha2: Alpha2::KE,
                    code: "22",
                    #[cfg(feature = "geo")]
                    geo: None,
                    comments: None,
                    subdivision_type: SubdivisionType::County,
                    #[cfg(feature = "translations")]
                    translations: HashMap::from([
                        ("ccp", "𑄟\u{11133}𑄠𑄌𑄇\u{1112e}𑄌\u{11134}"),
                        ("ceb", "Machakos (kapital sa lalawigan)"),
                        ("de", "Machakos District"),
                        ("en", "Machakos"),
                        ("es", "Condado de Machakos"),
                        ("fa", "شهرستان ماچاکوس"),
                        ("fi", "Machakosin piirikunta"),
                        ("ja", "マチャコス (カウンティ)"),
                        ("ko", "마차코스 현"),
                        ("nb", "Machakos fylke"),
                        ("nl", "Machakos"),
                        ("no", "Machakos fylke"),
                        ("sv", "Machakos (distrikt)"),
                        ("sw", "Wilaya ya Machakos"),
                        ("ur", "ماچاکوس کاؤنٹی"),
                        ("vi", "Machakos"),
                        ("zh", "馬查科斯郡"),
                    ]),
                    unofficial_name_list: [].to_vec(),
                },
            ),
            (
                "23",
                Subdivision {
                    name: "23",
                    country_alpha2: Alpha2::KE,
                    code: "23",
                    #[cfg(feature = "geo")]
                    geo: None,
                    comments: None,
                    subdivision_type: SubdivisionType::County,
                    #[cfg(feature = "translations")]
                    translations: HashMap::from([
                        ("ccp", "𑄟𑄇\u{1112a}𑄠𑄬𑄚\u{11128}"),
                        ("ceb", "Makueni"),
                        ("de", "Makueni District"),
                        ("en", "Makueni"),
                        ("es", "Condado de Makueni"),
                        ("fr", "Makueni"),
                        ("ja", "マクエニ (カウンティ)"),
                        ("ko", "마쿠에니 현"),
                        ("nb", "Makueni fylke"),
                        ("nl", "Makueni"),
                        ("no", "Makueni fylke"),
                        ("sv", "Makueni"),
                        ("sw", "Wilaya ya Makueni"),
                        ("ur", "ماکوینی کاؤنٹی"),
                        ("vi", "Makueni"),
                        ("zh", "馬瓜尼郡"),
                    ]),
                    unofficial_name_list: [].to_vec(),
                },
            ),
            (
                "24",
                Subdivision {
                    name: "24",
                    country_alpha2: Alpha2::KE,
                    code: "24",
                    #[cfg(feature = "geo")]
                    geo: None,
                    comments: None,
                    subdivision_type: SubdivisionType::County,
                    #[cfg(feature = "translations")]
                    translations: HashMap::from([
                        ("ccp", "𑄟𑄚\u{11134}𑄓𑄬𑄢"),
                        ("ceb", "Mandera (lalawigan)"),
                        ("de", "Mandera District"),
                        ("en", "Mandera"),
                        ("es", "Condado de Mandera"),
                        ("fi", "Manderan piirikunta"),
                        ("it", "Contea di Mandera"),
                        ("ja", "マンデラ (カウンティ)"),
                        ("ko", "만데라 현"),
                        ("nb", "Mandera fylke"),
                        ("nl", "Mandera"),
                        ("no", "Mandera fylke"),
                        ("sv", "Mandera"),
                        ("sw", "Wilaya ya Mandera"),
                        ("ur", "ماندیرا کاؤنٹی"),
                        ("vi", "Mandera"),
                        ("zh", "曼德拉郡"),
                    ]),
                    unofficial_name_list: [].to_vec(),
                },
            ),
            (
                "25",
                Subdivision {
                    name: "25",
                    country_alpha2: Alpha2::KE,
                    code: "25",
                    #[cfg(feature = "geo")]
                    geo: None,
                    comments: None,
                    subdivision_type: SubdivisionType::County,
                    #[cfg(feature = "translations")]
                    translations: HashMap::from([
                        ("ccp", "𑄟𑄢\u{11134}𑄥𑄝\u{11128}𑄖\u{11134}"),
                        ("ceb", "Marsabit"),
                        ("de", "Marsabit District"),
                        ("en", "Marsabit"),
                        ("es", "Marsabit"),
                        ("fa", "شهرستان مارسابیت"),
                        ("fr", "Marsabit"),
                        ("it", "Contea di Marsabit"),
                        ("ja", "マルサビット (カウンティ)"),
                        ("ko", "마르사비트 현"),
                        ("nb", "Marsabit fylke"),
                        ("nl", "Marsabit"),
                        ("no", "Marsabit fylke"),
                        ("pl", "Marsabit"),
                        ("sv", "Marsabit"),
                        ("sw", "Wilaya ya Marsabit"),
                        ("ur", "مارسابیت کاؤنٹی"),
                        ("vi", "Marsabit"),
                        ("zh", "馬薩比特郡"),
                    ]),
                    unofficial_name_list: [].to_vec(),
                },
            ),
            (
                "26",
                Subdivision {
                    name: "26",
                    country_alpha2: Alpha2::KE,
                    code: "26",
                    #[cfg(feature = "geo")]
                    geo: None,
                    comments: None,
                    subdivision_type: SubdivisionType::County,
                    #[cfg(feature = "translations")]
                    translations: HashMap::from([
                        ("ccp", "𑄟𑄬𑄢\u{1112a}"),
                        ("ceb", "Meru"),
                        ("en", "Meru"),
                        ("es", "Condado de Meru"),
                        ("fi", "Merun piirikunta"),
                        ("it", "Contea di Meru"),
                        ("ja", "メルー (カウンティ)"),
                        ("ko", "메루 현"),
                        ("nb", "Meru fylke"),
                        ("nl", "Meru County"),
                        ("no", "Meru fylke"),
                        ("sv", "Meru (län)"),
                        ("sw", "Kaunti ya Meru"),
                        ("ur", "میرو کاؤنٹی"),
                        ("zh", "梅魯郡"),
                    ]),
                    unofficial_name_list: [].to_vec(),
                },
            ),
            (
                "27",
                Subdivision {
                    name: "27",
                    country_alpha2: Alpha2::KE,
                    code: "27",
                    #[cfg(feature = "geo")]
                    geo: None,
                    comments: None,
                    subdivision_type: SubdivisionType::County,
                    #[cfg(feature = "translations")]
                    translations: HashMap::from([
                        ("ccp", "𑄟\u{11128}𑄉\u{1112e}𑄢\u{11128}"),
                        ("ceb", "Migori (lalawigan)"),
                        ("de", "Migori District"),
                        ("en", "Migori"),
                        ("es", "Condado de Migori"),
                        ("fr", "Migori"),
                        ("ja", "ミゴリ (カウンティ)"),
                        ("ko", "미고리 현"),
                        ("nb", "Migori fylke"),
                        ("nl", "Migori"),
                        ("no", "Migori fylke"),
                        ("pt", "Migori"),
                        ("sv", "Migori"),
                        ("sw", "Wilaya ya Migori"),
                        ("uk", "Мігорі (округ)"),
                        ("ur", "میگوری کاؤنٹی"),
                        ("vi", "Migori"),
                        ("zh", "米戈利郡"),
                    ]),
                    unofficial_name_list: [].to_vec(),
                },
            ),
            (
                "28",
                Subdivision {
                    name: "28",
                    country_alpha2: Alpha2::KE,
                    code: "28",
                    #[cfg(feature = "geo")]
                    geo: None,
                    comments: None,
                    subdivision_type: SubdivisionType::County,
                    #[cfg(feature = "translations")]
                    translations: HashMap::from([
                        ("be", "Мамбаса"),
                        ("ccp", "𑄟\u{11127}𑄟\u{11134}𑄝𑄥"),
                        ("ceb", "Mombasa"),
                        ("de", "Mombasa District"),
                        ("en", "Mombasa"),
                        ("es", "Condado de Mombasa"),
                        ("fi", "Mombasan piirikunta"),
                        ("fr", "Mombasa District"),
                        ("it", "Contea di Mombasa"),
                        ("ja", "モンバサ (カウンティ)"),
                        ("ko", "몸바사 현"),
                        ("nb", "Mombasa fylke"),
                        ("nl", "Mombasa District"),
                        ("no", "Mombasa fylke"),
                        ("pt", "Condado de Mombaça"),
                        ("ru", "Момбаса"),
                        ("sw", "Wilaya ya Mombasa"),
                        ("ur", "ممباسا کاؤنٹی"),
                        ("vi", "Mombasa"),
                        ("zh", "蒙巴萨县"),
                    ]),
                    unofficial_name_list: [].to_vec(),
                },
            ),
            (
                "29",
                Subdivision {
                    name: "29",
                    country_alpha2: Alpha2::KE,
                    code: "29",
                    #[cfg(feature = "geo")]
                    geo: None,
                    comments: None,
                    subdivision_type: SubdivisionType::County,
                    #[cfg(feature = "translations")]
                    translations: HashMap::from([
                        ("ccp", "𑄟\u{1112a}𑄢\u{11101}‘𑄃"),
                        ("ceb", "Murang’A"),
                        ("de", "Murang’a District"),
                        ("en", "Murang’a"),
                        ("es", "Condado de Muranga"),
                        ("fi", "Murangan piirikunta"),
                        ("it", "Distretto di Muranga"),
                        ("ja", "ムランガ (カウンティ)"),
                        ("ko", "무랑가 현"),
                        ("nl", "Muranga"),
                        ("ru", "Муранга"),
                        ("sv", "Muranga"),
                        ("sw", "Wilaya ya Murang’a"),
                        ("ur", "مورانگا کاؤنٹی"),
                        ("vi", "Murang’a"),
                        ("zh", "穆蘭卡郡"),
                    ]),
                    unofficial_name_list: [].to_vec(),
                },
            ),
            (
                "30",
                Subdivision {
                    name: "30",
                    country_alpha2: Alpha2::KE,
                    code: "30",
                    #[cfg(feature = "geo")]
                    geo: Some(SubdivisionGeo {
                        latitude: Some(-1.286577),
                        longitude: Some(36.82193669999999),
                        max_latitude: None,
                        min_latitude: None,
                        max_longitude: None,
                        min_longitude: None,
                    }),
                    comments: None,
                    subdivision_type: SubdivisionType::County,
                    #[cfg(feature = "translations")]
                    translations: HashMap::from([
                        ("ar", "مقاطعة نايروبي"),
                        ("be", "Найробі"),
                        ("bn", "ন\u{9be}ইরোবি"),
                        (
                            "ccp",
                            "𑄚\u{1112d}𑄢\u{1112e}𑄝\u{11128} 𑄇𑄅\u{1112a}𑄚\u{11134}𑄑\u{11128}",
                        ),
                        ("ceb", "Nairobi"),
                        ("da", "Nairobi County"),
                        ("de", "Nairobi"),
                        ("el", "Ναϊρόμπι"),
                        ("en", "Nairobi County"),
                        ("es", "Nairobi"),
                        ("et", "Nairobi maakond"),
                        ("fi", "Nairobin piirikunta"),
                        ("fr", "Nairobi"),
                        ("gu", "ન\u{ac8}રોબી કાઉન\u{acd}ટી"),
                        ("hi", "न\u{948}रोबी काउ\u{902}टी"),
                        ("id", "Nairobi County"),
                        ("it", "Contea di Nairobi"),
                        ("ja", "ナイロビ (カウンティ)"),
                        ("kn", "ನೈರೋಬ\u{cbf} ಕ\u{ccc}ಂಟ\u{cbf}"),
                        ("ko", "나이로비 현"),
                        ("lt", "Nairobio sritis"),
                        ("lv", "Nairobi province"),
                        ("mr", "न\u{948}रोबी काउ\u{902}टी"),
                        ("ms", "Nairobi County"),
                        ("nb", "Nairobi fylke"),
                        ("nl", "Nairobi County"),
                        ("no", "Nairobi fylke"),
                        ("pl", "Powiat Nairobi"),
                        ("pt", "Nairobi"),
                        ("ru", "Найроби"),
                        (
                            "si",
                            "නය\u{dd2}රෝබ\u{dd2} ප\u{dca}\u{200d}ර\u{dcf}න\u{dca}තය",
                        ),
                        ("sv", "Nairobi County"),
                        ("ta", "நைரோபி கவுண\u{bcd}டி"),
                        ("te", "న\u{c48}ర\u{c4b}బ\u{c3f} క\u{c4c}ంట\u{c40}"),
                        ("th", "ไนโรบ\u{e35}"),
                        ("tr", "Nairobi County"),
                        ("uk", "Округ Найробі"),
                        ("ur", "نیروبی کاؤنٹی"),
                        ("vi", "Hạt Nairobi"),
                        ("zh", "內羅畢郡"),
                    ]),
                    unofficial_name_list: ["Nairobi Municipality"].to_vec(),
                },
            ),
            (
                "31",
                Subdivision {
                    name: "31",
                    country_alpha2: Alpha2::KE,
                    code: "31",
                    #[cfg(feature = "geo")]
                    geo: None,
                    comments: None,
                    subdivision_type: SubdivisionType::County,
                    #[cfg(feature = "translations")]
                    translations: HashMap::from([
                        ("ccp", "𑄚𑄇\u{1112a}𑄢\u{1112a}"),
                        ("ceb", "Nakuru (lalawigan)"),
                        ("de", "Nakuru District"),
                        ("en", "Nakuru"),
                        ("es", "Condado de Nakuru"),
                        ("fi", "Nakurun piirikunta"),
                        ("fr", "Nakuru"),
                        ("hy", "Նակուրու շրջան"),
                        ("ja", "ナクル (カウンティ)"),
                        ("ko", "나쿠루 현"),
                        ("nb", "Nakuru fylke"),
                        ("nl", "Nakuru"),
                        ("no", "Nakuru fylke"),
                        ("sv", "Nakuru"),
                        ("sw", "Wilaya ya Nakuru"),
                        ("uk", "округ Накуру"),
                        ("ur", "ناکورو کاؤنٹی"),
                        ("vi", "Nakuru"),
                        ("zh", "納庫魯郡"),
                    ]),
                    unofficial_name_list: [].to_vec(),
                },
            ),
            (
                "32",
                Subdivision {
                    name: "32",
                    country_alpha2: Alpha2::KE,
                    code: "32",
                    #[cfg(feature = "geo")]
                    geo: None,
                    comments: None,
                    subdivision_type: SubdivisionType::County,
                    #[cfg(feature = "translations")]
                    translations: HashMap::from([
                        ("ccp", "𑄚𑄚\u{11134}𑄓\u{11128}"),
                        ("ceb", "Nandi North District"),
                        ("de", "Nandi District"),
                        ("en", "Nandi"),
                        ("es", "Distrito Nandi"),
                        ("fi", "Nandin piirikunta"),
                        ("fr", "District de Nandi"),
                        ("he", "מחוז ננדי"),
                        ("ja", "ナンディ (カウンティ)"),
                        ("ko", "난디 현"),
                        ("nb", "Nandi fylke"),
                        ("nl", "Nandi"),
                        ("no", "Nandi fylke"),
                        ("ru", "Нанди (округ)"),
                        ("sl", "Kipsamo, Nandi"),
                        ("sv", "Nandi (distrikt)"),
                        ("sw", "Wilaya ya Nandi"),
                        ("ur", "ناندی کاؤنٹی"),
                        ("vi", "Nandi"),
                        ("zh", "南迪郡"),
                    ]),
                    unofficial_name_list: [].to_vec(),
                },
            ),
            (
                "33",
                Subdivision {
                    name: "33",
                    country_alpha2: Alpha2::KE,
                    code: "33",
                    #[cfg(feature = "geo")]
                    geo: None,
                    comments: None,
                    subdivision_type: SubdivisionType::County,
                    #[cfg(feature = "translations")]
                    translations: HashMap::from([
                        ("ccp", "𑄚𑄢\u{1112e}𑄇\u{11134}"),
                        ("ceb", "Narok"),
                        ("de", "Narok District"),
                        ("en", "Narok"),
                        ("es", "Condado de Narok"),
                        ("ja", "ナロク (カウンティ)"),
                        ("ko", "나로크 현"),
                        ("nb", "Narok fylke"),
                        ("nl", "Narok"),
                        ("no", "Narok fylke"),
                        ("sv", "Narok"),
                        ("sw", "Wilaya ya Narok"),
                        ("ur", "ناروک کاؤنٹی"),
                        ("vi", "Narok"),
                        ("zh", "納羅克郡"),
                    ]),
                    unofficial_name_list: [].to_vec(),
                },
            ),
            (
                "34",
                Subdivision {
                    name: "34",
                    country_alpha2: Alpha2::KE,
                    code: "34",
                    #[cfg(feature = "geo")]
                    geo: None,
                    comments: None,
                    subdivision_type: SubdivisionType::County,
                    #[cfg(feature = "translations")]
                    translations: HashMap::from([
                        ("ccp", "𑄚\u{11128}𑄠𑄟\u{11128}𑄢"),
                        ("ceb", "Nyamira (lalawigan)"),
                        ("de", "Nyamira District"),
                        ("en", "Nyamira"),
                        ("es", "Condado de Nyamira"),
                        ("fr", "Nyamira"),
                        ("ja", "ニャミラ県"),
                        ("ko", "니아미라 현"),
                        ("nb", "Nyamira fylke"),
                        ("nl", "Nyamira"),
                        ("no", "Nyamira fylke"),
                        ("sv", "Nyamira"),
                        ("sw", "Wilaya ya Nyamira"),
                        ("ur", "نیامیرا کاؤنٹی"),
                        ("vi", "Nyamira"),
                        ("zh", "尼亞米拉郡"),
                    ]),
                    unofficial_name_list: [].to_vec(),
                },
            ),
            (
                "35",
                Subdivision {
                    name: "35",
                    country_alpha2: Alpha2::KE,
                    code: "35",
                    #[cfg(feature = "geo")]
                    geo: None,
                    comments: None,
                    subdivision_type: SubdivisionType::County,
                    #[cfg(feature = "translations")]
                    translations: HashMap::from([
                        ("ccp", "𑄚𑄠𑄚\u{11134}𑄓𑄢\u{1112a}𑄠"),
                        ("ceb", "Nyandarua (lalawigan sa Kenya)"),
                        ("de", "Nyandarua District"),
                        ("en", "Nyandarua"),
                        ("es", "Condado de Nyandarua"),
                        ("fi", "Nyandaruan piirikunta"),
                        ("fr", "District de Nyandarua"),
                        ("it", "Distretto di Nyandarua"),
                        ("ja", "ニャンダルア (カウンティ)"),
                        ("ko", "니안다루아 현"),
                        ("nb", "Nyandarua fylke"),
                        ("nl", "Nyandarua"),
                        ("no", "Nyandarua fylke"),
                        ("sv", "Nyandarua"),
                        ("sw", "Wilaya ya Nyandarua"),
                        ("ur", "نیانداروا کاؤنٹی"),
                        ("vi", "Nyandarua"),
                        ("zh", "年達魯阿郡"),
                    ]),
                    unofficial_name_list: [].to_vec(),
                },
            ),
            (
                "36",
                Subdivision {
                    name: "36",
                    country_alpha2: Alpha2::KE,
                    code: "36",
                    #[cfg(feature = "geo")]
                    geo: None,
                    comments: None,
                    subdivision_type: SubdivisionType::County,
                    #[cfg(feature = "translations")]
                    translations: HashMap::from([
                        ("be", "акруга Ньеры"),
                        ("ccp", "𑄚\u{11128}𑄠𑄢\u{11128}"),
                        ("ceb", "Nyeri (lalawigan)"),
                        ("de", "Nyeri District"),
                        ("en", "Nyeri"),
                        ("es", "Condado de Nyeri"),
                        ("fi", "Nyerin piirikunta"),
                        ("fr", "Nyeri District"),
                        ("it", "Distretto di Nyeri"),
                        ("ja", "ニエリ (カウンティ)"),
                        ("ko", "니에리 현"),
                        ("nb", "Nyeri fylke"),
                        ("nl", "Nyeri"),
                        ("no", "Nyeri fylke"),
                        ("pt", "Nyeri"),
                        ("sv", "Nyeri"),
                        ("sw", "Wilaya ya Nyeri"),
                        ("ur", "نیئری کاؤنٹی"),
                        ("vi", "Nyeri"),
                        ("zh", "涅里郡"),
                    ]),
                    unofficial_name_list: [].to_vec(),
                },
            ),
            (
                "37",
                Subdivision {
                    name: "37",
                    country_alpha2: Alpha2::KE,
                    code: "37",
                    #[cfg(feature = "geo")]
                    geo: None,
                    comments: None,
                    subdivision_type: SubdivisionType::County,
                    #[cfg(feature = "translations")]
                    translations: HashMap::from([
                        ("bg", "Самбуру"),
                        ("ccp", "𑄥𑄟\u{11134}𑄝\u{1112a}𑄢\u{1112a}"),
                        ("ceb", "Samburu"),
                        ("de", "Samburu District"),
                        ("en", "Samburu"),
                        ("es", "Condado de Samburu"),
                        ("it", "Distretto di Samburu"),
                        ("ja", "サンブル (カウンティ)"),
                        ("ko", "삼부루 현"),
                        ("nb", "Samburu fylke"),
                        ("nl", "Samburu"),
                        ("no", "Samburu fylke"),
                        ("sv", "Samburu"),
                        ("sw", "Wilaya ya Samburu"),
                        ("ur", "سامبورو کاؤنٹی"),
                        ("vi", "Samburu"),
                        ("zh", "桑布盧郡"),
                    ]),
                    unofficial_name_list: [].to_vec(),
                },
            ),
            (
                "38",
                Subdivision {
                    name: "38",
                    country_alpha2: Alpha2::KE,
                    code: "38",
                    #[cfg(feature = "geo")]
                    geo: None,
                    comments: None,
                    subdivision_type: SubdivisionType::County,
                    #[cfg(feature = "translations")]
                    translations: HashMap::from([
                        ("ccp", "𑄥\u{11128}𑄠\u{11133}𑄦"),
                        ("ceb", "Siaya"),
                        ("de", "Siaya County"),
                        ("en", "Siaya"),
                        ("es", "Distrito de Siaya"),
                        ("fr", "Siaya"),
                        ("ja", "シアヤ"),
                        ("ko", "시아야 현"),
                        ("nb", "Siaya fylke"),
                        ("nl", "Siaya"),
                        ("no", "Siaya fylke"),
                        ("pt", "Siaya (distrito)"),
                        ("sv", "Siaya (distrikt)"),
                        ("sw", "Wilaya ya Siaya"),
                        ("ur", "سیایا کاؤنٹی"),
                        ("vi", "Siaya"),
                        ("zh", "夏亞郡"),
                    ]),
                    unofficial_name_list: [].to_vec(),
                },
            ),
            (
                "39",
                Subdivision {
                    name: "39",
                    country_alpha2: Alpha2::KE,
                    code: "39",
                    #[cfg(feature = "geo")]
                    geo: None,
                    comments: None,
                    subdivision_type: SubdivisionType::County,
                    #[cfg(feature = "translations")]
                    translations: HashMap::from([
                        ("ccp", "𑄑\u{1112d}𑄑-𑄑𑄞𑄬𑄑"),
                        ("ceb", "Taita Taveta"),
                        ("en", "Taita-Taveta"),
                        ("es", "Taita-Taveta"),
                        ("fr", "Taita-Taveta"),
                        ("it", "Contea di Taita-Taveta"),
                        ("ko", "타이타타베타 현"),
                        ("nb", "Taita-Taveta fylke"),
                        ("nl", "Taita Taveta"),
                        ("no", "Taita-Taveta fylke"),
                        ("sv", "Taita-Taveta"),
                        ("sw", "Wilaya ya Taita-Taveta"),
                        ("ur", "تائتا-تاویتا کاؤنٹی"),
                        ("zh", "泰塔塔維塔郡"),
                    ]),
                    unofficial_name_list: [].to_vec(),
                },
            ),
            (
                "40",
                Subdivision {
                    name: "40",
                    country_alpha2: Alpha2::KE,
                    code: "40",
                    #[cfg(feature = "geo")]
                    geo: None,
                    comments: None,
                    subdivision_type: SubdivisionType::County,
                    #[cfg(feature = "translations")]
                    translations: HashMap::from([
                        ("ccp", "𑄑𑄚\u{11134} 𑄢\u{11128}𑄞𑄢\u{11134}"),
                        ("ceb", "Tana River"),
                        ("de", "Tana River District"),
                        ("en", "Tana River"),
                        ("es", "Condado del Río Tana"),
                        ("it", "Contea di Tana River"),
                        ("ja", "タナ・リバー (カウンティ)"),
                        ("ko", "타나리버 현"),
                        ("nb", "Tana River fylke"),
                        ("nl", "Tana River"),
                        ("no", "Tana River fylke"),
                        ("sv", "Tana River"),
                        ("sw", "Wilaya ya Mto Tana"),
                        ("ur", "دریائے تانا کاؤنٹی"),
                        ("vi", "Tana River"),
                        ("zh", "塔納河郡"),
                    ]),
                    unofficial_name_list: [].to_vec(),
                },
            ),
            (
                "41",
                Subdivision {
                    name: "41",
                    country_alpha2: Alpha2::KE,
                    code: "41",
                    #[cfg(feature = "geo")]
                    geo: None,
                    comments: None,
                    subdivision_type: SubdivisionType::County,
                    #[cfg(feature = "translations")]
                    translations: HashMap::from([
                        ("ccp", "𑄗𑄢𑄇-𑄚\u{11128}𑄗\u{11128}"),
                        ("ceb", "Tharaka - Nithi"),
                        ("en", "Tharaka-Nithi"),
                        ("es", "Condado de Tharaka-Nithi"),
                        ("it", "Contea di Tharaka-Nithi"),
                        ("ko", "타라카니티 현"),
                        ("nb", "Tharaka-Nithi fylke"),
                        ("nl", "Tharaka-Nithi"),
                        ("no", "Tharaka-Nithi fylke"),
                        ("sv", "Tharaka"),
                        ("sw", "Wilaya ya Tharaka"),
                        ("ur", "تھاراکا-نیتھی کاؤنٹی"),
                        ("vi", "Tharaka"),
                        ("zh", "薩拉卡尼蒂郡"),
                    ]),
                    unofficial_name_list: [].to_vec(),
                },
            ),
            (
                "42",
                Subdivision {
                    name: "42",
                    country_alpha2: Alpha2::KE,
                    code: "42",
                    #[cfg(feature = "geo")]
                    geo: None,
                    comments: None,
                    subdivision_type: SubdivisionType::County,
                    #[cfg(feature = "translations")]
                    translations: HashMap::from([
                        (
                            "ccp",
                            "𑄑\u{11133}𑄢𑄚\u{11134}𑄥\u{11134} 𑄎\u{1112e}𑄃\u{11128}𑄠",
                        ),
                        ("ceb", "Trans Nzoia"),
                        ("de", "Trans-Nzoia District"),
                        ("en", "Trans Nzoia"),
                        ("es", "Condado de Trans-Nzoia"),
                        ("et", "Trans Nzoia"),
                        ("fr", "District de Trans-Nzoia"),
                        ("ja", "トランス・ンゾイア (カウンティ)"),
                        ("ko", "트랜스은조이아 현"),
                        ("nb", "Trans-Nzoia fylke"),
                        ("nl", "Trans-Nzoia"),
                        ("no", "Trans-Nzoia fylke"),
                        ("sv", "Trans-Nzoia"),
                        ("sw", "Wilaya ya Trans-Nzoia"),
                        ("ur", "ٹرانس-نزویا کاؤنٹی"),
                        ("vi", "Trans Nzoia"),
                        ("zh", "特蘭斯-恩佐亞郡"),
                    ]),
                    unofficial_name_list: [].to_vec(),
                },
            ),
            (
                "43",
                Subdivision {
                    name: "43",
                    country_alpha2: Alpha2::KE,
                    code: "43",
                    #[cfg(feature = "geo")]
                    geo: None,
                    comments: None,
                    subdivision_type: SubdivisionType::County,
                    #[cfg(feature = "translations")]
                    translations: HashMap::from([
                        ("ccp", "𑄑\u{1112a}𑄢\u{11134}𑄇𑄚"),
                        ("ceb", "Turkana"),
                        ("de", "Turkana District"),
                        ("en", "Turkana"),
                        ("es", "Condado de Turkana"),
                        ("fa", "شهرستان تورکانا"),
                        ("fi", "Turkana"),
                        ("fr", "Turkana"),
                        ("id", "Kabupaten Turkana"),
                        ("ja", "トゥルカナ (カウンティ)"),
                        ("ko", "투르카나 현"),
                        ("nb", "Turkana"),
                        ("nl", "Turkana"),
                        ("no", "Turkana"),
                        ("sv", "Turkana"),
                        ("sw", "Wilaya ya Turkana"),
                        ("ur", "ترکانا کاؤنٹی"),
                        ("vi", "Turkana"),
                        ("zh", "圖爾卡納郡"),
                    ]),
                    unofficial_name_list: [].to_vec(),
                },
            ),
            (
                "44",
                Subdivision {
                    name: "44",
                    country_alpha2: Alpha2::KE,
                    code: "44",
                    #[cfg(feature = "geo")]
                    geo: None,
                    comments: None,
                    subdivision_type: SubdivisionType::County,
                    #[cfg(feature = "translations")]
                    translations: HashMap::from([
                        (
                            "ccp",
                            "𑄅\u{1112a}𑄠𑄥\u{11128}𑄚\u{11134} 𑄉\u{11128}𑄥\u{1112a}",
                        ),
                        ("ceb", "Uasin Gishu"),
                        ("de", "Uasin Gishu District"),
                        ("en", "Uasin Gishu"),
                        ("es", "Condado de Uasin Gishu"),
                        ("fa", "یوسین گیشو"),
                        ("it", "Distretto di Uasin Gishu"),
                        ("ja", "ウアシン・ギシュ (カウンティ)"),
                        ("ko", "우아신기슈 현"),
                        ("nb", "Uasin Gishu fylke"),
                        ("nl", "Uasin Gishu"),
                        ("no", "Uasin Gishu fylke"),
                        ("sv", "Uasin Gishu"),
                        ("sw", "Wilaya ya Uasin Gishu"),
                        ("ur", "یواسین گیشو گاؤنٹی"),
                        ("vi", "Uasin Gishu"),
                        ("zh", "瓦辛基蘇郡"),
                    ]),
                    unofficial_name_list: [].to_vec(),
                },
            ),
            (
                "45",
                Subdivision {
                    name: "45",
                    country_alpha2: Alpha2::KE,
                    code: "45",
                    #[cfg(feature = "geo")]
                    geo: None,
                    comments: None,
                    subdivision_type: SubdivisionType::County,
                    #[cfg(feature = "translations")]
                    translations: HashMap::from([
                        ("bg", "Вихига"),
                        ("ccp", "𑄞\u{11128}𑄦\u{11128}𑄉"),
                        ("ceb", "Vihiga"),
                        ("de", "Vihiga District"),
                        ("en", "Vihiga"),
                        ("es", "Condado de Vihiga"),
                        ("ja", "ヴィヒガ (カウンティ)"),
                        ("ko", "비히가 현"),
                        ("nb", "Vihiga fylke"),
                        ("nl", "Vihiga"),
                        ("no", "Vihiga fylke"),
                        ("sv", "Vihiga"),
                        ("sw", "Wilaya ya Vihiga"),
                        ("ur", "ویہیگا کاؤنٹی"),
                        ("vi", "Vihiga"),
                        ("zh", "韋希加郡"),
                    ]),
                    unofficial_name_list: [].to_vec(),
                },
            ),
            (
                "46",
                Subdivision {
                    name: "46",
                    country_alpha2: Alpha2::KE,
                    code: "46",
                    #[cfg(feature = "geo")]
                    geo: None,
                    comments: None,
                    subdivision_type: SubdivisionType::County,
                    #[cfg(feature = "translations")]
                    translations: HashMap::from([
                        ("ccp", "𑄤𑄎\u{11128}𑄢\u{11134}"),
                        ("ceb", "Wajir"),
                        ("de", "Wajir District"),
                        ("en", "Wajir"),
                        ("es", "Condado de Wajir"),
                        ("it", "Contea di Wajir"),
                        ("ja", "ワジール (カウンティ)"),
                        ("ko", "와지르 현"),
                        ("nb", "Wajir fylke"),
                        ("nl", "Wajir"),
                        ("no", "Wajir fylke"),
                        ("sv", "Wajir"),
                        ("sw", "Wilaya ya Wajir"),
                        ("ur", "واجیر کاؤنٹی"),
                        ("vi", "Wajir"),
                        ("zh", "瓦吉爾郡"),
                    ]),
                    unofficial_name_list: [].to_vec(),
                },
            ),
            (
                "47",
                Subdivision {
                    name: "47",
                    country_alpha2: Alpha2::KE,
                    code: "47",
                    #[cfg(feature = "geo")]
                    geo: None,
                    comments: None,
                    subdivision_type: SubdivisionType::County,
                    #[cfg(feature = "translations")]
                    translations: HashMap::from([
                        ("ccp", "𑄤𑄠𑄬𑄌\u{11134} 𑄛\u{11127}𑄇\u{1112e}𑄖\u{11134}"),
                        ("ceb", "West Pokot"),
                        ("de", "West Pokot District"),
                        ("en", "West Pokot"),
                        ("es", "Condado de West Pokot"),
                        ("ja", "ウェスト・ポコット (カウンティ)"),
                        ("ko", "서포코트 현"),
                        ("nb", "West Pokot"),
                        ("nl", "West-Pokot"),
                        ("no", "West Pokot"),
                        ("sv", "Västra Pokot"),
                        ("sw", "Wilaya ya Pokot Magharibi"),
                        ("ur", "مغربی پوکوت کاؤنٹی"),
                        ("vi", "West Pokot"),
                        ("zh", "西波克特郡"),
                    ]),
                    unofficial_name_list: [].to_vec(),
                },
            ),
        ])
    }
}
#[allow(unused_imports)]
use crate::{
    Alpha2, Alpha3, Continent, Country, Region, SubRegion, WeekDay, WorldRegion, GEC, IOC,
};
#[allow(unused_imports)]
use std::collections::HashMap;
#[cfg(feature = "ke")]
pub fn new() -> Country {
    Country {
        alpha2: Alpha2::KE,
        alpha3: Alpha3::KEN,
        address_format: None,
        continent: Continent::Africa,
        country_code: 254,
        currency_code: "KES",
        gec: Some(GEC::KE),
        #[cfg(feature = "geo")]
        geo: geo::new(),
        international_prefix: "000",
        ioc: Some(IOC::KEN),
        iso_long_name: "The Republic of Kenya",
        iso_short_name: "Kenya",
        official_language_list: ["en", "sw"].to_vec(),
        spoken_language_list: ["en", "sw"].to_vec(),
        national_destination_code_length_list: [2].to_vec(),
        national_number_length_list: [9].to_vec(),
        national_prefix: "0",
        nationality: Some("Kenyan"),
        number: "404",
        postal_code: true,
        postal_code_format: Some("\\d{5}"),
        region: Some(Region::Africa),
        start_of_week: WeekDay::Monday,
        subregion: Some(SubRegion::EasternAfrica),
        un_locode: "KE",
        unofficial_name_list: ["Kenya", "Kenia", "ケニア"].to_vec(),
        world_region: WorldRegion::EMEA,
        #[cfg(feature = "translations")]
        translations: HashMap::from([
            ("ab", "Kenya"),
            ("af", "Kenia"),
            ("ak", "Kenya"),
            ("am", "ኬንያ"),
            ("an", "Kenya"),
            ("ar", "كينيا"),
            ("as", "কেনিয়\u{9be}"),
            ("ay", "Kenya"),
            ("az", "Kenya"),
            ("ba", "Kenya"),
            ("be", "Кенія"),
            ("bg", "Кения"),
            ("bi", "Kenya"),
            ("bn", "কেনিয়\u{9be}"),
            ("bn_IN", "কেনিয়\u{9be}"),
            ("br", "Kenya"),
            ("bs", "Kenija"),
            ("ca", "Kenya"),
            ("ce", "Кени"),
            ("ch", "Kenya"),
            ("cs", "Keňa"),
            ("cv", "Кени"),
            ("cy", "Kenya"),
            ("da", "Kenya"),
            ("de", "Kenia"),
            ("dv", "ކ\u{7ac}ނ\u{7b0}ޔ\u{7a7}"),
            ("dz", "ཀ\u{f7a}ན་ཡ།"),
            ("ee", "Kenya"),
            ("el", "Κένυα"),
            ("en", "Kenya"),
            ("eo", "Kenjo"),
            ("es", "Kenia"),
            ("et", "Kenya"),
            ("eu", "Kenya"),
            ("fa", "کنیا"),
            ("ff", "Kenya"),
            ("fi", "Kenia"),
            ("fo", "Kenja"),
            ("fr", "Kenya"),
            ("fy", "Kenya"),
            ("ga", "An Chéinia"),
            ("gl", "Quenia"),
            ("gn", "Kenya"),
            ("gu", "ક\u{ac7}ન\u{acd}યા"),
            ("gv", "Yn Cheinney"),
            ("ha", "Kenya"),
            ("he", "קניה"),
            ("hi", "कीनिया"),
            ("hr", "Kenija"),
            ("ht", "Kenya"),
            ("hu", "Kenya"),
            ("hy", "Քենիա"),
            ("ia", "Kenya"),
            ("id", "Kenya"),
            ("io", "Kenia"),
            ("is", "Kenía"),
            ("it", "Kenya"),
            ("iu", "Kenya"),
            ("ja", "ケニア"),
            ("ka", "კენია"),
            ("ki", "Kenya"),
            ("kk", "Кения"),
            ("kl", "Kenya"),
            ("km", "កេនយ\u{17c9}ា"),
            ("kn", "ಕೀನ\u{ccd}ಯಾ"),
            ("ko", "케냐"),
            ("ku", "Kenya"),
            ("kv", "Kenya"),
            ("kw", "Kenya"),
            ("ky", "Кения"),
            ("lo", "Kenya"),
            ("lt", "Kenija"),
            ("lv", "Kenija"),
            ("mi", "Kēnia"),
            ("mk", "Кенија"),
            ("ml", "കെനിയ"),
            ("mn", "Кениа"),
            ("mr", "क\u{947}निया"),
            ("ms", "Kenya"),
            ("mt", "Kenja"),
            ("my", "ကင\u{103a}ညာန\u{102d}\u{102f}င\u{103a}င\u{1036}"),
            ("na", "Keniya"),
            ("nb", "Kenya"),
            ("ne", "क\u{947}न\u{94d}या"),
            ("nl", "Kenia"),
            ("nn", "Kenya"),
            ("nv", "Kenya"),
            ("oc", "Kenya"),
            ("or", "କେନ\u{b3f}ୟ\u{b3e}"),
            ("pa", "ਕੀਨੀਆ"),
            ("pi", "क\u{947}न\u{94d}या"),
            ("pl", "Kenia"),
            ("ps", "کېنيا"),
            ("pt", "Quénia"),
            ("pt_BR", "Quênia"),
            ("ro", "Kenia"),
            ("ru", "Кения"),
            ("rw", "Kenya"),
            ("sc", "Kènya"),
            ("sd", "Kenya"),
            ("si", "කෙන\u{dca}ය\u{dcf}ව"),
            ("sk", "Keňa"),
            ("sl", "Kenija"),
            ("so", "Kiiniya"),
            ("sq", "Kenia"),
            ("sr", "Кенија"),
            ("sv", "Kenya"),
            ("sw", "Kenya"),
            ("ta", "கென\u{bcd}ய\u{bbe}"),
            ("te", "క\u{c46}న\u{c4d}య\u{c3e}"),
            ("tg", "Кения"),
            ("th", "เคนยา"),
            ("ti", "ኬንያ"),
            ("tk", "Keniýa"),
            ("tl", "Kenya"),
            ("tr", "Kenya"),
            ("tt", "Кениа"),
            ("ug", "كېنىيە"),
            ("uk", "Кенія"),
            ("ur", "کینیا"),
            ("uz", "Keniya"),
            ("ve", "Kenya"),
            ("vi", "Khi-ni-a"),
            ("wa", "Kenia"),
            ("wo", "Kenya"),
            ("xh", "Kenya"),
            ("yo", "Kẹ\u{301}nyà"),
            ("zh_CN", "肯尼亚"),
            ("zh_HK", "肯雅"),
            ("zh_TW", "肯亞"),
            ("zu", "IKenya"),
        ]),
        #[cfg(feature = "subdivisions")]
        subdivisions: subdivisions::new(),
    }
}
