// DO NOT TOUCH THIS FILE. (Auto-generated by `keshvar-code-generator/src/countries.rs`)

//! A module for country `The Democratic Socialist Republic of Sri Lanka`

#[cfg(all(feature = "lk", feature = "constants"))]
/// A module to access all constant country data for `The Democratic Socialist Republic of Sri Lanka`.
///
/// Note that to use this module, `constant` feature should be enabled.
pub mod consts {
    #[allow(unused_imports)]
    use crate::{
        Alpha2, Alpha3, Continent, CurrencyCode, DistanceUnit, Region, SubRegion, WeekDay,
        WorldRegion, GEC, IOC,
    };

    pub const ADDRESS_FORMAT: Option<&str> = None;
    pub const ALPHA2: Alpha2 = Alpha2::LK;
    pub const ALPHA3: Alpha3 = Alpha3::LKA;
    pub const CONTINENT: Continent = Continent::Asia;
    pub const COUNTRY_CODE: usize = 94;
    pub const CURRENCY_CODE: CurrencyCode = CurrencyCode::LKR;
    pub const GEC: Option<GEC> = Some(GEC::CE);
    pub const INTERNATIONAL_PREFIX: Option<&str> = Some("00");
    pub const IOC: Option<IOC> = Some(IOC::SRI);
    pub const ISO_SHORT_NAME: &str = "Sri Lanka";
    pub const ISO_LONG_NAME: &str = "The Democratic Socialist Republic of Sri Lanka";
    pub const OFFICIAL_LANGUAGE_LIST: Option<&[&str]> = Some(&["si", "ta"]);
    pub const SPOKEN_LANGUAGE_LIST: Option<&[&str]> = Some(&["si", "ta"]);
    pub const NATIONAL_DESTINATION_CODE_LENGTH_LIST: Option<&[usize]> = Some(&[2]);
    pub const NATIONAL_NUMBER_LENGTH_LIST: Option<&[usize]> = Some(&[10]);
    pub const NATIONAL_PREFIX: Option<&str> = Some("0");
    pub const NATIONALITY: Option<&str> = Some("Sri Lankan");
    pub const NUMBER: &str = "144";
    pub const POSTAL_CODE: bool = true;
    pub const POSTAL_CODE_FORMAT: Option<&str> = Some("\\d{5}");
    pub const REGION: Option<Region> = Some(Region::Asia);
    pub const START_DAY_OF_WEEK: WeekDay = WeekDay::Monday;
    pub const SUBREGION: Option<SubRegion> = Some(SubRegion::SouthernAsia);
    pub const UN_LOCODE: &str = "LK";
    pub const UN_MEMBER: bool = true;
    pub const UNOFFICIAL_NAME_LIST: &[&str] = &["Sri Lanka", "スリランカ"];
    pub const VEHICLE_REGISTRATION_CODE: Option<&str> = Some("CL");
    pub const WORLD_REGION: WorldRegion = WorldRegion::APAC;
    pub const G7_MEMBER: bool = false;
    pub const G20_MEMBER: bool = false;
    pub const EU_MEMBER: bool = false;
    pub const EEA_MEMBER: bool = false;
    pub const NANP_PREFIX: Option<&str> = None;
    pub const DISTANCE_UNIT: DistanceUnit = DistanceUnit::Km;
    pub const POPULATION: Option<u64> = Some(22181000);
    #[cfg(feature = "emojis")]
    pub const EMOJI: &str = "🇱🇰";
    #[cfg(feature = "translations")]
    pub const TRANSLATIONS: &[(&str, &str)] = &[
        ("ab", "Sri Lanka"),
        ("af", "Sri Lanka"),
        ("ak", "Sri Lanka"),
        ("am", "ሽሪ ላንካ"),
        ("an", "Sri Lanka"),
        ("ar", "سريلانكا"),
        ("as", "শ\u{9cd}ৰীলঙ\u{9cd}ক\u{9be}"),
        ("ay", "Sri Lanka"),
        ("az", "Şri Lanka"),
        ("ba", "Sri Lanka"),
        ("be", "Шры-Ланка"),
        ("bg", "Шри Ланка"),
        ("bi", "Sri Lanka"),
        ("bn", "শ\u{9cd}রীলঙ\u{9cd}ক\u{9be}"),
        ("bn_IN", "শ\u{9cd}রীলঙ\u{9cd}ক\u{9be}"),
        ("br", "Sri Lanka"),
        ("bs", "Šri Lanka"),
        ("ca", "Sri Lanka"),
        ("ce", "Шри-Ланка"),
        ("ch", "Sri Lanka"),
        ("cs", "Šrí Lanka"),
        ("cv", "Шри-Ланка"),
        ("cy", "Sri Lanka"),
        ("da", "Sri Lanka"),
        ("de", "Sri Lanka"),
        ("dv", "އ\u{7ae}ޅ\u{7aa}ދ\u{7ab}ކ\u{7a6}ރ\u{7a6}"),
        ("dz", "ས\u{f72}་ར\u{f72}་ལང་ཀ།(ཤ\u{fb2}\u{f72}་ལང\u{f90}་)"),
        ("ee", "Sri Lanka"),
        ("el", "Σρι Λάνκα"),
        ("en", "Sri Lanka"),
        ("eo", "Sri-Lanko"),
        ("es", "Sri Lanka"),
        ("et", "Sri Lanka"),
        ("eu", "Sri Lanka"),
        ("fa", "سری\u{200c}لانکا"),
        ("ff", "Sri Lanka"),
        ("fi", "Sri Lanka"),
        ("fo", "Sri Lanka"),
        ("fr", "Sri Lanka"),
        ("fy", "Sry Lanka"),
        ("ga", "Srí Lanca"),
        ("gl", "Sri Lanka"),
        ("gn", "Sri Lanka"),
        ("gu", "શ\u{acd}રી લ\u{a82}કા"),
        ("gv", "Sri Lanka"),
        ("ha", "Sri Lanka"),
        ("he", "סרי לנקה"),
        ("hi", "श\u{94d}रील\u{902}का"),
        ("hr", "Šri Lanka"),
        ("ht", "Srilanka"),
        ("hu", "Srí Lanka"),
        ("hy", "Շրի Լանկա"),
        ("ia", "Sri Lanka"),
        ("id", "Sri Lanka"),
        ("io", "Sri-Lanka"),
        ("is", "Srí Lanka"),
        ("it", "Sri Lanka"),
        ("iu", "Sri Lanka"),
        ("ja", "スリランカ"),
        ("ka", "შრი-ლანკა"),
        ("ki", "Sri Lanka"),
        ("kk", "Шри-Ланка"),
        ("kl", "Sri Lanka"),
        ("km", "ស\u{17d2}រ\u{17b8}លង\u{17d2}កា"),
        ("kn", "ಶ\u{ccd}ರ\u{cc0}ಲಂಕಾ"),
        ("ko", "스리랑카"),
        ("ku", "Srî Lanka"),
        ("kv", "Шри-Ланка"),
        ("kw", "Shri Lanka"),
        ("ky", "Шри-Ланка"),
        ("lo", "ປະເທດສ\u{eb5}ລ\u{eb1}ງກາ"),
        ("lt", "Šri Lanka"),
        ("lv", "Šrilanka"),
        ("mi", "Hiri Rānaka"),
        ("mk", "Шри Ланка"),
        ("ml", "ശ\u{d4d}രീലങ\u{d4d}ക"),
        ("mn", "Шри Ланка"),
        ("mr", "श\u{94d}री ल\u{902}का"),
        ("ms", "Sri Lanka"),
        ("mt", "Sri Lanka"),
        (
            "my",
            "သ\u{102e}ရ\u{102d}လင\u{103a}\u{1039}ကာန\u{102d}\u{102f}င\u{103a}င\u{1036}",
        ),
        ("na", "Sri Lanka"),
        ("nb", "Sri Lanka"),
        ("ne", "श\u{94d}री लङ\u{94d}का"),
        ("nl", "Sri Lanka"),
        ("nn", "Sri Lanka"),
        ("nv", "Naakaii Dootłʼizhí Bikéyah Dah Naaʼeełígíí"),
        ("oc", "Sri Lanka"),
        ("or", "ଶ\u{b4d}ରୀଲଙ\u{b4d}କ\u{b3e}"),
        ("pa", "ਸ\u{a4d}ਰੀਲ\u{a70}ਕਾ"),
        ("pi", "श\u{94d}रीलङ\u{94d}का"),
        ("pl", "Sri Lanka"),
        ("ps", "سریلانکا"),
        ("pt", "Sri Lanka"),
        ("pt_BR", "Sri Lanka"),
        ("ro", "Sri Lanka"),
        ("ru", "Шри-Ланка"),
        ("rw", "Siri Lanka"),
        ("sc", "Sri Lanka"),
        ("sd", "سريلنڪا"),
        ("si", "ශ\u{dca}\u{200d}ර\u{dd3} ලංක\u{dcf}ව"),
        ("sk", "Srí Lanka"),
        ("sl", "Šrilanka"),
        ("so", "Siirilaanka"),
        ("sq", "Sri Lankë"),
        ("sr", "Шри Ланка"),
        ("sv", "Sri Lanka"),
        ("sw", "Sri Lanka"),
        ("ta", "இலங\u{bcd}கை"),
        ("te", "శ\u{c4d}ర\u{c40}లంక"),
        ("tg", "Князигарии Лихтенштейн"),
        ("th", "ศร\u{e35}ล\u{e31}งกา"),
        ("ti", "ስሪ ላንካ"),
        ("tk", "Şri-Lanka"),
        ("tl", "Sri Lanka"),
        ("tr", "Sri Lanka"),
        ("tt", "Шри Ланка"),
        ("ug", "سىرىلانكا"),
        ("uk", "Шрі-Ланка"),
        ("ur", "سری لنکا"),
        ("uz", "Shri-Lanka"),
        ("ve", "Sri Lanka"),
        ("vi", "Tích Lan"),
        ("wa", "Sri Lanka"),
        ("wo", "Siri Laaŋka"),
        ("xh", "Sri Lanka"),
        ("yo", "Sri Lanka"),
        ("zh_CN", "斯里兰卡"),
        ("zh_HK", "斯里蘭卡"),
        ("zh_TW", "斯里蘭卡"),
        ("zu", "Sri Lanka"),
    ];
    #[cfg(all(feature = "lk", feature = "geo", feature = "constants"))]
    /// GEO data as constants
    pub mod geo {
        pub const LATITUDE: f64 = 7.873053999999999;
        pub const LONGITUDE: f64 = 80.77179699999999;
        pub const MAX_LATITUDE: f64 = 10.03377;
        pub const MAX_LONGITUDE: f64 = 82.14479999999999;
        pub const MIN_LATITUDE: f64 = 5.6816;
        pub const MIN_LONGITUDE: f64 = 79.26769999999999;
        pub const NORTHEAST_LATITUDE: f64 = 10.03377;
        pub const NORTHEAST_LONGITUDE: f64 = 82.14479999999999;
        pub const SOUTHWEST_LATITUDE: f64 = 5.6816;
        pub const SOUTHWEST_LONGITUDE: f64 = 79.26769999999999;
    }
}
#[cfg(all(feature = "lk", feature = "geo"))]
/// GEO module for this country.
pub mod geo {
    use crate::{CountryGeo, CountryGeoBound, CountryGeoBounds};

    /// GEO information for this country.
    pub fn new() -> CountryGeo {
        CountryGeo {
            latitude: 7.873053999999999,
            longitude: 80.77179699999999,
            max_latitude: 10.03377,
            max_longitude: 82.14479999999999,
            min_latitude: 5.6816,
            min_longitude: 79.26769999999999,
            bounds: CountryGeoBounds {
                northeast: CountryGeoBound {
                    latitude: 10.03377,
                    longitude: 82.14479999999999,
                },
                southwest: CountryGeoBound {
                    latitude: 5.6816,
                    longitude: 79.26769999999999,
                },
            },
        }
    }
}

#[cfg(all(feature = "lk", feature = "subdivisions"))]
/// Subdivision module for this country.
pub mod subdivisions {
    #[allow(unused_imports)]
    use crate::{Alpha2, Subdivision, SubdivisionType};
    use std::collections::HashMap;
    // In this state, We do not know if subdivisions have geo or not!
    #[cfg(feature = "geo")]
    #[allow(unused_imports)]
    use crate::SubdivisionGeo;

    /// Subdivisions for this country.
    pub fn new() -> HashMap<&'static str, Subdivision> {
        HashMap::from(
            [

                (
                    "1",
                    Subdivision{
                        name: "බස\u{dca}න\u{dcf}හ\u{dd2}ර පළ\u{dcf}ත, ශ\u{dca} ර\u{dd3} ලංක\u{dcf}ව",
                        country_alpha2: Alpha2::LK,
                        code: "1",
                        #[cfg(feature = "geo")]
                        geo: None,
                        comments: None,
                        subdivision_type: SubdivisionType::Province,
                        #[cfg(feature = "translations")]
                        translations: HashMap::from([("ar", "المقاطعة الغربية (سريلانكا)"), ("be", "Заходняя правінцыя"), ("bg", "Западна провинция"), ("bn", "পশ\u{9cd}চিম\u{9be}ঞ\u{9cd}চল প\u{9cd}রদেশ"), ("ca", "província de l’Oest"), ("ccp", "𑄃\u{1112e}𑄠𑄬𑄌\u{11134}𑄑𑄢\u{11134}𑄚\u{11134}"), ("ceb", "Western Province"), ("cy", "Talaith y Gorllewin"), ("de", "Westprovinz"), ("el", "Δυτική επαρχία"), ("en", "Western"), ("es", "Provincia Oeste"), ("fa", "استان غربی، سری\u{200c}لانکا"), ("fi", "Sri Lankan läntinen provinssi"), ("fr", "Province de l’Ouest"), ("hi", "पश\u{94d}चिमी प\u{94d}रान\u{94d}त"), ("hy", "Արևմտյան նահանգ"), ("id", "Provinsi Barat, Sri Lanka"), ("it", "provincia Occidentale"), ("ja", "西部州"), ("ka", "დასავლეთი პროვინცია"), ("ko", "서부 주"), ("mr", "पश\u{94d}चिम प\u{94d}रा\u{902}त"), ("nl", "Westelijke Provincie"), ("pl", "Prowincja Zachodnia"), ("pt", "Província Ocidental"), ("ru", "Западная провинция"), ("si", "බස\u{dca}න\u{dcf}හ\u{dd2}ර පළ\u{dcf}ත, ශ\u{dca} ර\u{dd3} ලංක\u{dcf}ව"), ("sv", "Västprovinsen, Sri Lanka"), ("ta", "மேல\u{bcd} ம\u{bbe}க\u{bbe}ணம\u{bcd}"), ("tr", "Batı Eyaleti"), ("uk", "Західна провінція"), ("ur", "مغربی صوبہ، سری لنکا"), ("zh", "西部省")]),
                        unofficial_name_list: [].to_vec(),
                    }
                ),
                (
                    "11",
                    Subdivision{
                        name: "Colombo",
                        country_alpha2: Alpha2::LK,
                        code: "11",
                        #[cfg(feature = "geo")]
                        geo: Some(SubdivisionGeo{latitude: Some(6.9270786), longitude: Some(79.861243), max_latitude: Some(6.980584400000001), min_latitude: Some(6.8625113), max_longitude: Some(79.8900852), min_longitude: Some(79.8225192)}),
                        comments: None,
                        subdivision_type: SubdivisionType::District,
                        #[cfg(feature = "translations")]
                        translations: HashMap::from([("ar", "مديرية كولومبو"), ("be", "Каломба"), ("bn", "কলম\u{9cd}বো জেল\u{9be}"), ("ca", "Districte de Colombo"), ("ccp", "𑄇\u{11127}𑄣\u{11127}𑄟\u{11134}𑄝\u{1112e}"), ("ceb", "Colombo District"), ("cy", "Ardal Colombo"), ("de", "Colombo"), ("el", "Διαμέρισμα του Κολόμπο"), ("en", "Colombo"), ("es", "Distrito de Colombo"), ("fa", "ناحیه کلمبو"), ("fi", "Colombon piirikunta"), ("fr", "Colombo"), ("hi", "कोलम\u{94d}बो"), ("id", "Distrik Kolombo"), ("it", "Distretto di Colombo"), ("ja", "コロンボ県"), ("ka", "კოლომბოს ოლქი"), ("ko", "콜롬보 구"), ("mk", "Коломбо"), ("ml", "കൊളംബോ ജില\u{d4d}ല"), ("mr", "कोल\u{902}बो जिल\u{94d}हा"), ("nb", "Colombo"), ("nl", "Colombo"), ("no", "Colombo"), ("pl", "Kolombo (dystrykt)"), ("ru", "Коломбо"), ("si", "කොළඹ ද\u{dd2}ස\u{dca}ත\u{dca} ර\u{dd2}ක\u{dca}කය"), ("sv", "Colombo"), ("ta", "கொழும\u{bcd}பு ம\u{bbe}வட\u{bcd}டம\u{bcd}"), ("uk", "Коломбо"), ("ur", "کولمبو ضلع"), ("zh", "可倫坡區")]),
                        unofficial_name_list: ["Colombo", "Colombo", "Kolamba"].to_vec(),
                    }
                ),
                (
                    "12",
                    Subdivision{
                        name: "Gampaha",
                        country_alpha2: Alpha2::LK,
                        code: "12",
                        #[cfg(feature = "geo")]
                        geo: Some(SubdivisionGeo{latitude: Some(7.0873101), longitude: Some(80.01436559999999), max_latitude: Some(7.1068408), min_latitude: Some(7.056004499999999), max_longitude: Some(80.0507641), min_longitude: Some(79.9738622)}),
                        comments: None,
                        subdivision_type: SubdivisionType::District,
                        #[cfg(feature = "translations")]
                        translations: HashMap::from([("ar", "مقاطعة جامباها"), ("bn", "গ\u{9be}ম\u{9cd}প\u{9be}হ\u{9be} জেল\u{9be}"), ("ccp", "𑄉𑄟\u{11134}𑄛𑄦"), ("ceb", "Gampaha District"), ("da", "Gampaha District"), ("de", "Gampaha"), ("el", "Γκαμπάχα"), ("en", "Gampaha"), ("es", "Distrito de Gampaha"), ("fa", "ناحیه گامپاها"), ("fi", "Gampahan piirikunta"), ("fr", "Gampaha"), ("gu", "ગમ\u{acd}પાહા જિલ\u{acd}લો"), ("hi", "गम\u{94d}पाह जिला"), ("id", "Distrik Gampaha"), ("it", "Distretto di Gampaha"), ("ja", "ガンパハ県"), ("ka", "გამპაჰის ოლქი"), ("kn", "ಗಾಂಪಹ ಜ\u{cbf}ಲ\u{ccd}ಲ\u{cc6}"), ("ko", "감파하 구"), ("lt", "Gampachos sritis"), ("lv", "Gampahas distrikts"), ("ml", "ഗമ\u{d4d}പഹ ജില\u{d4d}ല"), ("mr", "गम\u{94d}पहा जिल\u{94d}हा"), ("ms", "Gampaha District"), ("nb", "Gampaha distrikt"), ("nl", "Gampaha"), ("no", "Gampaha distrikt"), ("pl", "Dystrykt Gampaha"), ("pt", "Distrito de Gampaha"), ("ru", "округ Гампаха"), ("si", "ගම\u{dca}පහ පර\u{dd2}ප\u{dcf}ලන ද\u{dd2}ස\u{dca}ත\u{dca}\u{200d}ර\u{dd2}ක\u{dca}කය"), ("sv", "Gampaha"), ("ta", "கம\u{bcd}பக\u{bbe} ம\u{bbe}வட\u{bcd}டம\u{bcd}"), ("te", "గంప\u{c3e}హ\u{c3e} జ\u{c3f}ల\u{c4d}ల\u{c3e}"), ("th", "เขตค\u{e31}มปาฮา"), ("tr", "Gampaha District"), ("uk", "Гампаха"), ("ur", "گامپاہا ضلع"), ("vi", "Quận Gampaha"), ("zh", "加姆珀哈區")]),
                        unofficial_name_list: ["Gampaha"].to_vec(),
                    }
                ),
                (
                    "13",
                    Subdivision{
                        name: "Kalutara",
                        country_alpha2: Alpha2::LK,
                        code: "13",
                        #[cfg(feature = "geo")]
                        geo: Some(SubdivisionGeo{latitude: Some(6.5894162), longitude: Some(79.98081429999999), max_latitude: Some(6.617802699999999), min_latitude: Some(6.5570948), max_longitude: Some(79.9956179), min_longitude: Some(79.9578743)}),
                        comments: None,
                        subdivision_type: SubdivisionType::District,
                        #[cfg(feature = "translations")]
                        translations: HashMap::from([("ar", "مقاطعة كالوتارا"), ("bn", "ক\u{9c1}লোট\u{9be}র\u{9be} জেল\u{9be}"), ("ccp", "𑄇𑄣\u{1112a}𑄑𑄢"), ("ceb", "Kalutara District"), ("da", "Kalutara District"), ("de", "Kalutara"), ("el", "Καλουτάρα"), ("en", "Kalutara"), ("es", "Distrito de Kalutara"), ("fa", "ناحیه کالوتارا"), ("fi", "Kalutaran piirikunta"), ("fr", "Kalutara"), ("gu", "કાલ\u{ac1}તરા જિલ\u{acd}લો"), ("hi", "कल\u{941}तारा जिला"), ("id", "Distrik Kalutara"), ("it", "Distretto di Kalutara"), ("ja", "カルタラ県"), ("ka", "კალუტარის ოლქი"), ("kn", "ಕರುತಾರ ಜ\u{cbf}ಲ\u{ccd}ಲ\u{cc6}"), ("ko", "칼루타라 구"), ("lt", "Kalutaros apskritis"), ("lv", "Kalutaras distrikts"), ("ml", "കല\u{d41}ത\u{d3e}ര ജില\u{d4d}ല"), ("mr", "काल\u{941}तारा जिल\u{94d}हा"), ("ms", "Kalutara District"), ("nb", "Kalutara"), ("nl", "Kalutara"), ("no", "Kalutara"), ("pl", "Kalutara District"), ("pt", "Kulatra"), ("ru", "Калутара"), ("si", "කළ\u{dd4}තර පර\u{dd2}ප\u{dcf}ලන ද\u{dd2}ස\u{dca}ත\u{dca}\u{200d}ර\u{dd2}ක\u{dca}කය"), ("sv", "Kalutara District"), ("ta", "களுத\u{bcd}துறை ம\u{bbe}வட\u{bcd}டம\u{bcd}"), ("te", "క\u{c3e}లుట\u{c3e}ర\u{c3e} జ\u{c3f}ల\u{c4d}ల\u{c3e}"), ("th", "กาล\u{e38}ตารา"), ("tr", "Kalutara District"), ("uk", "Калутара"), ("ur", "کالوتارا ضلع"), ("vi", "Quận Kalutara"), ("zh", "卡盧特勒區")]),
                        unofficial_name_list: ["Kalutara"].to_vec(),
                    }
                ),
                (
                    "2",
                    Subdivision{
                        name: "මධ\u{dca}\u{200d}යම පළ\u{dcf}ත, ශ\u{dca}\u{200d}ර\u{dd3} ලංක\u{dcf}ව",
                        country_alpha2: Alpha2::LK,
                        code: "2",
                        #[cfg(feature = "geo")]
                        geo: None,
                        comments: None,
                        subdivision_type: SubdivisionType::Province,
                        #[cfg(feature = "translations")]
                        translations: HashMap::from([("ar", "المقاطعة الوسطى (سريلانكا)"), ("bg", "Централна провинция (Шри Ланка)"), ("bn", "মধ\u{9cd}য\u{9be}ঞ\u{9cd}চল প\u{9cd}রদেশ"), ("ca", "Província Central"), ("ccp", "𑄥𑄬𑄚\u{11134}𑄑\u{11133}𑄢𑄣\u{11134}"), ("ceb", "Central Province"), ("de", "Zentralprovinz"), ("el", "Κεντρική επαρχία"), ("en", "Central"), ("es", "Provincia Central"), ("fa", "استان مرکزی (سری\u{200c}لانکا)"), ("fi", "Sri Lankan keskinen provinssi"), ("fr", "Province du Centre"), ("gl", "Provincia Central"), ("hi", "मध\u{94d}य प\u{94d}रान\u{94d}त"), ("id", "Provinsi Tengah, Sri Lanka"), ("it", "provincia Centrale"), ("ja", "中部州"), ("ka", "ცენტრალური პროვინცია"), ("ko", "중부 주 (스리랑카)"), ("mr", "मध\u{94d}य प\u{94d}रा\u{902}त, श\u{94d}रील\u{902}का"), ("nl", "Centrale Provincie"), ("pl", "Prowincja Centralna (Sri Lanka)"), ("pt", "Província Central"), ("ru", "Центральная провинция (Шри-Ланка)"), ("si", "මධ\u{dca}\u{200d}යම පළ\u{dcf}ත, ශ\u{dca}\u{200d}ර\u{dd3} ලංක\u{dcf}ව"), ("sv", "Centralprovinsen, Sri Lanka"), ("ta", "மத\u{bcd}திய ம\u{bbe}க\u{bbe}ணம\u{bcd}"), ("uk", "Центральна провінція"), ("ur", "وسطی صوبہ، سری لنکا"), ("vi", "Tỉnh Trung Tâm, Sri Lanka"), ("zh", "中央省 (斯里蘭卡)")]),
                        unofficial_name_list: [].to_vec(),
                    }
                ),
                (
                    "21",
                    Subdivision{
                        name: "Kandy",
                        country_alpha2: Alpha2::LK,
                        code: "21",
                        #[cfg(feature = "geo")]
                        geo: Some(SubdivisionGeo{latitude: Some(7.2905715), longitude: Some(80.6337262), max_latitude: Some(7.330587100000001), min_latitude: Some(7.258503500000001), max_longitude: Some(80.6596685), min_longitude: Some(80.5918944)}),
                        comments: None,
                        subdivision_type: SubdivisionType::District,
                        #[cfg(feature = "translations")]
                        translations: HashMap::from([("ar", "مديرية كاندي"), ("ca", "Kandy"), ("ccp", "𑄇𑄚\u{11134}𑄓\u{11128}"), ("ceb", "Kandy District"), ("de", "Kandy"), ("en", "Kandy"), ("es", "Distrito de Kandy"), ("fa", "ناحیه کندی"), ("fi", "Kandyn piirikunta"), ("fr", "Kandy"), ("hi", "क\u{948}\u{902}डी जिला"), ("id", "Distrik Kandy"), ("it", "Distretto di Kandy"), ("ja", "キャンディ県"), ("ka", "კანდის ოლქი"), ("ko", "캔디 구"), ("ml", "ക\u{d57}ണ\u{d4d}ടി ജില\u{d4d}ല"), ("mr", "क\u{901}डी जिल\u{94d}हा"), ("nl", "Kandy"), ("pl", "Kandy"), ("ru", "Канди"), ("si", "මහන\u{dd4}වර ද\u{dd2}ස\u{dca}ත\u{dca} ර\u{dd2}ක\u{dca}කය"), ("sv", "Kandy"), ("ta", "கண\u{bcd}டி ம\u{bbe}வட\u{bcd}டம\u{bcd}"), ("uk", "Канді"), ("ur", "کینڈی ضلع"), ("zh", "康提區")]),
                        unofficial_name_list: ["Maha Nuwara", "Mahe Nuwara"].to_vec(),
                    }
                ),
                (
                    "22",
                    Subdivision{
                        name: "Matale",
                        country_alpha2: Alpha2::LK,
                        code: "22",
                        #[cfg(feature = "geo")]
                        geo: Some(SubdivisionGeo{latitude: Some(7.467465), longitude: Some(80.6234161), max_latitude: Some(7.481389), min_latitude: Some(7.4352836), max_longitude: Some(80.65166459999999), min_longitude: Some(80.6057453)}),
                        comments: None,
                        subdivision_type: SubdivisionType::District,
                        #[cfg(feature = "translations")]
                        translations: HashMap::from([("ar", "مقاطعة ماتال"), ("bn", "ম\u{9be}ত\u{9be}লে জেল\u{9be}"), ("ca", "Matale"), ("ccp", "𑄟𑄖𑄣𑄬"), ("ceb", "Matale District"), ("da", "Matale District"), ("de", "Matale"), ("el", "Ματάλε"), ("en", "Matale"), ("es", "Distrito de Matale"), ("fa", "ناحیه متاله"), ("fi", "Matalen piirikunta"), ("fr", "Matale"), ("gu", "માતલ\u{ac7} જિલ\u{acd}લો"), ("hi", "मातल\u{947} जिला"), ("id", "Distrik Matale"), ("it", "Distretto di Matale"), ("ja", "マータレー県"), ("ka", "მატალეს ოლქი"), ("kn", "ಮಟಲ\u{cc6} ಜ\u{cbf}ಲ\u{ccd}ಲ\u{cc6}"), ("ko", "마탈레 구"), ("lt", "Matalės apskritis"), ("lv", "Matale distrikts"), ("ml", "മ\u{d3e}തലെ ജില\u{d4d}ല"), ("mr", "मातल\u{947} जिल\u{94d}हा"), ("ms", "Matale District"), ("nb", "Matale distrikt"), ("nl", "Matale"), ("no", "Matale distrikt"), ("pl", "Matale"), ("pt", "Distrito Matale"), ("ru", "Матале"), ("si", "ම\u{dcf}තලේ පර\u{dd2}ප\u{dcf}ලන ද\u{dd2}ස\u{dca}ත\u{dca} ර\u{dd2}ක\u{dca}කය"), ("sl", "Okrožje Matale"), ("sv", "Matale"), ("ta", "ம\u{bbe}த\u{bcd}தளை ம\u{bbe}வட\u{bcd}டம\u{bcd}"), ("te", "మట\u{c3e}ల\u{c46} జ\u{c3f}ల\u{c4d}ల\u{c3e}"), ("th", "มะตะเล"), ("tr", "Matale District"), ("uk", "Матале"), ("ur", "ماتالے ضلع"), ("vi", "Quận Matale"), ("zh", "馬特萊區")]),
                        unofficial_name_list: ["Matale"].to_vec(),
                    }
                ),
                (
                    "23",
                    Subdivision{
                        name: "Nuwara Eliya",
                        country_alpha2: Alpha2::LK,
                        code: "23",
                        #[cfg(feature = "geo")]
                        geo: Some(SubdivisionGeo{latitude: Some(6.9543992), longitude: Some(80.7824012), max_latitude: Some(6.9898532), min_latitude: Some(6.912879200000001), max_longitude: Some(80.8216953), min_longitude: Some(80.7401987)}),
                        comments: None,
                        subdivision_type: SubdivisionType::District,
                        #[cfg(feature = "translations")]
                        translations: HashMap::from([("ar", "مقاطعة نوارا إليا"), ("bn", "নৌয\u{9bc}\u{9be}র\u{9be} এলিয\u{9bc}\u{9be} জেল\u{9be}"), ("ca", "Nuwara Eliya"), ("ccp", "𑄚\u{11127}𑄤𑄢 𑄃\u{11128}𑄣\u{11128}𑄠"), ("ceb", "Nuwara Eliya District"), ("da", "Nuwara Eliya District"), ("de", "Nuwara Eliya"), ("el", "Νουβάρα Ελίγια"), ("en", "Nuwara Eliya"), ("es", "Distrito de Nuwara Eliya"), ("fa", "ناحیه نووارا الییا"), ("fi", "Nuwara Eliyan piirikunta"), ("fr", "Nuwara Eliya"), ("gu", "ન\u{ac1}વારા એલિયા જિલ\u{acd}લો"), ("hi", "न\u{941}वारा एलीया जिला"), ("id", "Distrik Nuwara Eliya"), ("it", "Distretto di Nuwara Eliya"), ("ja", "ヌワラ・エリヤ県"), ("ka", "ნუვარა-ელიას ოლქი"), ("kn", "ನುವಾರಾ ಎಲ\u{cbf}ಯಾ ಜ\u{cbf}ಲ\u{ccd}ಲ\u{cc6}"), ("ko", "누와라엘리야 구"), ("lt", "Nuvara Elijos apskritis"), ("lv", "Nuvaras Elijas distrikts"), ("ml", "ന\u{d41}വ\u{d3e}ര ഏലിയ ജില\u{d4d}ല"), ("mr", "न\u{942}वरा एलिया जिल\u{94d}हा"), ("ms", "Nuwara Eliya District"), ("nb", "Nuware Eliya Distrikt"), ("nl", "Nuwara Eliya"), ("no", "Nuware Eliya Distrikt"), ("pl", "Nuwara Elija"), ("pt", "Nuwara Eliya"), ("ru", "Нувара-Элия"), ("si", "න\u{dd4}වරඑළ\u{dd2}ය පර\u{dd2}ප\u{dcf}ලන ද\u{dd2}ස\u{dca}ත\u{dca}\u{200d}ර\u{dd2}ක\u{dca}කය"), ("sv", "Nuwara Eliya"), ("ta", "நுவரெலிய\u{bbe} ம\u{bbe}வட\u{bcd}டம\u{bcd}"), ("te", "నువ\u{c3e}ర\u{c3e} ఎల\u{c3f}య\u{c3e} జ\u{c3f}ల\u{c4d}ల\u{c3e}"), ("th", "น\u{e38}วาราเอล\u{e34}ยา"), ("tr", "Nuwaya Eliya District"), ("uk", "Нувара-Елія"), ("ur", "نووارا الییا ضلع"), ("vi", "Quận Nuwara Eliya"), ("zh", "努沃勒埃利耶區")]),
                        unofficial_name_list: ["Nuwara Eliya"].to_vec(),
                    }
                ),
                (
                    "3",
                    Subdivision{
                        name: "දක\u{dd4}ණ\u{dd4} පළ\u{dcf}ත",
                        country_alpha2: Alpha2::LK,
                        code: "3",
                        #[cfg(feature = "geo")]
                        geo: None,
                        comments: None,
                        subdivision_type: SubdivisionType::Province,
                        #[cfg(feature = "translations")]
                        translations: HashMap::from([("ar", "المقاطعة الجنوبية (سريلانكا)"), ("bg", "Южна провинция"), ("bn", "দক\u{9cd}ষিণ\u{9be}ঞ\u{9cd}চল প\u{9cd}রদেশ"), ("ccp", "𑄘\u{11127}𑄊\u{11128}𑄚\u{11134}𑄟𑄬𑄇\u{11134}𑄈𑄬"), ("ceb", "Southern Province"), ("de", "Südprovinz"), ("el", "Νότια επαρχία"), ("en", "Southern"), ("es", "Provincia Sur"), ("fa", "استان جنوبی (سری\u{200c}لانکا)"), ("fi", "Sri Lankan eteläinen provinssi"), ("fr", "Province du Sud"), ("hi", "दक\u{94d}षिणी प\u{94d}रान\u{94d}त"), ("id", "Provinsi Selatan, Sri Lanka"), ("it", "provincia Meridionale"), ("ja", "南部州"), ("ka", "სამხრეთი პროვინცია"), ("ko", "남부 주"), ("ml", "തെക\u{d4d}കൻ പ\u{d4d}രവിശ\u{d4d}യ"), ("mr", "दक\u{94d}षिण प\u{94d}रा\u{902}त"), ("nl", "Zuidelijke Provincie"), ("pl", "Prowincja Południowa"), ("pt", "Província do Sul (Sri Lanka)"), ("ru", "Южная провинция"), ("si", "දක\u{dd4}ණ\u{dd4} පළ\u{dcf}ත"), ("sv", "Sydprovinsen, Sri Lanka"), ("ta", "தென\u{bcd} ம\u{bbe}க\u{bbe}ணம\u{bcd}"), ("uk", "Південна провінція"), ("ur", "جنوبی صوبہ، سری لنکا"), ("zh", "南部省")]),
                        unofficial_name_list: [].to_vec(),
                    }
                ),
                (
                    "31",
                    Subdivision{
                        name: "Galle",
                        country_alpha2: Alpha2::LK,
                        code: "31",
                        #[cfg(feature = "geo")]
                        geo: Some(SubdivisionGeo{latitude: Some(6.0535185), longitude: Some(80.2209773), max_latitude: Some(6.0881332), min_latitude: Some(6.0236819), max_longitude: Some(80.2518654), min_longitude: Some(80.1721287)}),
                        comments: None,
                        subdivision_type: SubdivisionType::District,
                        #[cfg(feature = "translations")]
                        translations: HashMap::from([("ar", "مقاطعة جالي"), ("bn", "গ\u{9be}লে জেল\u{9be}"), ("ca", "Galle"), ("ccp", "𑄉𑄣𑄬"), ("ceb", "Galle District"), ("da", "Galle District"), ("de", "Galle"), ("el", "Γκάλε"), ("en", "Galle"), ("es", "Distrito de Galle"), ("fa", "ناحیه گاله"), ("fi", "Gallen piirikunta"), ("fr", "Galle"), ("gu", "ગ\u{ac7}લ જિલ\u{acd}લો"), ("hi", "गाल\u{947} जिला"), ("id", "Distrik Galle"), ("it", "Distretto di Galle"), ("ja", "ゴール県"), ("ka", "გალეს ოლქი"), ("kn", "ಗಾಲ\u{ccd}ಲ\u{cc6} ಜ\u{cbf}ಲ\u{ccd}ಲ\u{cc6}"), ("ko", "갈 구"), ("lt", "Galės apskritis"), ("lv", "Galles distrikts"), ("ml", "ഗ\u{d3e}ലി ജില\u{d4d}ല"), ("mr", "गाल\u{94d}ल जिल\u{94d}हा"), ("ms", "Galle District"), ("nb", "Galle"), ("nl", "Galle"), ("no", "Galle"), ("pl", "Dystrykt Galle"), ("pt", "Galle"), ("ru", "Галле"), ("si", "ග\u{dcf}ල\u{dca}ල පර\u{dd2}ප\u{dcf}ලන ද\u{dd2}ස\u{dca}ත\u{dca}\u{200d}ර\u{dd2}ක\u{dca}කය"), ("sv", "Galle"), ("ta", "க\u{bbe}லி ம\u{bbe}வட\u{bcd}டம\u{bcd}"), ("te", "గల\u{c4d}ల\u{c46} జ\u{c3f}ల\u{c4d}ల\u{c3e}"), ("th", "โมเย\u{e47}น ชาร\u{e35}"), ("tr", "Galle District"), ("uk", "Ґалле"), ("ur", "گال ضلع"), ("vi", "Quận Galle"), ("zh", "加勒區")]),
                        unofficial_name_list: ["Gālla"].to_vec(),
                    }
                ),
                (
                    "32",
                    Subdivision{
                        name: "Matara",
                        country_alpha2: Alpha2::LK,
                        code: "32",
                        #[cfg(feature = "geo")]
                        geo: Some(SubdivisionGeo{latitude: Some(5.95492), longitude: Some(80.5549561), max_latitude: Some(5.9693241), min_latitude: Some(5.9346603), max_longitude: Some(80.59724539999999), min_longitude: Some(80.50425059999999)}),
                        comments: None,
                        subdivision_type: SubdivisionType::District,
                        #[cfg(feature = "translations")]
                        translations: HashMap::from([("ar", "مقاطعة ماتارا"), ("bn", "ম\u{9be}ত\u{9be}র\u{9be} জেল\u{9be}"), ("ccp", "𑄟𑄖𑄢"), ("ceb", "Matara District"), ("da", "Matara District"), ("de", "Matara (Distrikt)"), ("el", "Μάταρα"), ("en", "Matara"), ("es", "Distrito de Matara (Sri Lanka)"), ("fa", "ناحیه ماتارا"), ("fi", "Mataran piirikunta"), ("fr", "Matara (district)"), ("gu", "માતારા જિલ\u{acd}લો"), ("hi", "मटारा ज\u{93c}िला"), ("id", "Matara, Sri Lanka"), ("it", "Distretto di Matara"), ("ja", "マータラ県"), ("ka", "მატარის ოლქი"), ("kn", "ಮಟರಾ ಜ\u{cbf}ಲ\u{ccd}ಲ\u{cc6}"), ("ko", "마타라 구"), ("lt", "Mataros apskritis"), ("lv", "Mataras distrikts"), ("ml", "മ\u{d3e}ത\u{d4d}ത\u{d3e}ര ജില\u{d4d}ല"), ("mr", "मातरा जिल\u{94d}हा"), ("ms", "Matara District"), ("nb", "Matara"), ("nl", "Matara (district)"), ("no", "Matara"), ("pl", "Matara"), ("pt", "Matara"), ("ru", "Матара"), ("si", "ම\u{dcf}තර ද\u{dd2}ස\u{dca}ත\u{dca}\u{200d}ර\u{dd2}ක\u{dca}කය"), ("sv", "Matara (distrikt)"), ("ta", "ம\u{bbe}த\u{bcd}தறை ம\u{bbe}வட\u{bcd}டம\u{bcd}"), ("te", "మట\u{c3e}ర\u{c3e} జ\u{c3f}ల\u{c4d}ల\u{c3e}"), ("th", "มาทาร\u{e48}า"), ("tr", "Matara District"), ("uk", "Матара"), ("ur", "ماتارا ضلع"), ("vi", "Quận Matara"), ("zh", "馬特勒區")]),
                        unofficial_name_list: ["Matara"].to_vec(),
                    }
                ),
                (
                    "33",
                    Subdivision{
                        name: "Hambantota",
                        country_alpha2: Alpha2::LK,
                        code: "33",
                        #[cfg(feature = "geo")]
                        geo: Some(SubdivisionGeo{latitude: Some(6.131742099999999), longitude: Some(81.1085744), max_latitude: Some(6.172768899999999), min_latitude: Some(6.1097056), max_longitude: Some(81.1655759), min_longitude: Some(81.0677156)}),
                        comments: None,
                        subdivision_type: SubdivisionType::District,
                        #[cfg(feature = "translations")]
                        translations: HashMap::from([("ar", "مقاطعة هامبانتوتا"), ("bn", "হ\u{9be}ম\u{9cd}ব\u{9be}নট\u{9c1}ট\u{9be} জেল\u{9be}"), ("ca", "Hambantota"), ("ccp", "𑄦𑄟\u{11134}𑄝𑄚\u{11134}𑄑\u{1112e}𑄑"), ("ceb", "Hambantota District"), ("da", "Hambantota District"), ("de", "Hambantota"), ("el", "Χαμπαντότα"), ("en", "Hambantota"), ("es", "Distrito de Hambantota"), ("fa", "ناحیه هامبانتوتا"), ("fi", "Hambantotan piirikunta"), ("fr", "district d’Hambantota"), ("gu", "હમ\u{acd}બાન\u{acd}ટોટા જિલ\u{acd}લો"), ("hi", "हम\u{94d}बन\u{94d}तोट’ जिला"), ("id", "Distrik Hambantota"), ("it", "Distretto di Hambantota"), ("ja", "ハンバントタ県"), ("ka", "ჰამბანტოტის ოლქი"), ("kn", "ಹಂಬಂತ\u{ccb}ಟ ಜ\u{cbf}ಲ\u{ccd}ಲ\u{cc6}"), ("ko", "함반토타 구"), ("lt", "Hambantotos apskritis"), ("lv", "Hambantotas distrikts"), ("ml", "ഹംമ\u{d4d}പൻതോട\u{d4d}ട ജില\u{d4d}ല"), ("mr", "हम\u{94d}बन\u{94d}टोट जिल\u{94d}हा"), ("ms", "Hambantota District"), ("nb", "Hambantota"), ("nl", "Hambantota"), ("no", "Hambantota"), ("pl", "Dystrykt Hambantota"), ("pt", "Hambantota"), ("ru", "Хамбантота"), ("si", "හම\u{dca}බන\u{dca}තොට පර\u{dd2}ප\u{dcf}ලන ද\u{dd2}ස\u{dca}ත\u{dca}\u{200d}ර\u{dd2}ක\u{dca}කය"), ("sv", "Hambantota distriktet"), ("ta", "அம\u{bcd}ப\u{bbe}ந\u{bcd}தோட\u{bcd}டை ம\u{bbe}வட\u{bcd}டம\u{bcd}"), ("te", "హ\u{c3e}ంబ\u{c3e}ంట\u{c4b}ట\u{c3e} జ\u{c3f}ల\u{c4d}ల\u{c3e}"), ("th", "เขตแฮมบ\u{e31}นโตตา"), ("tr", "Hambantota District"), ("uk", "Хамбантота"), ("ur", "ہامبانتوتا ضلع"), ("vi", "Quận Hambantota"), ("zh", "漢班托特區")]),
                        unofficial_name_list: ["Hambantota"].to_vec(),
                    }
                ),
                (
                    "4",
                    Subdivision{
                        name: "උත\u{dd4}ර\u{dd4} පළ\u{dcf}ත",
                        country_alpha2: Alpha2::LK,
                        code: "4",
                        #[cfg(feature = "geo")]
                        geo: None,
                        comments: None,
                        subdivision_type: SubdivisionType::Province,
                        #[cfg(feature = "translations")]
                        translations: HashMap::from([("ar", "المقاطعة الشمالية (سريلانكا)"), ("bg", "Северна провинция"), ("bn", "উত\u{9cd}তর\u{9be}ঞ\u{9cd}চল প\u{9cd}রদেশ"), ("ca", "Província del Nord"), ("ccp", "𑄅\u{1112a}𑄖\u{11133}𑄦\u{11127}𑄢\u{11134}𑄟𑄬𑄇\u{11134}𑄈𑄬"), ("ceb", "Northern Province (lalawigan sa Sri Lanka)"), ("de", "Nordprovinz"), ("el", "Βόρεια επαρχία"), ("en", "Northern"), ("es", "Provincia Norte"), ("fa", "استان شمالی (سری\u{200c}لانکا)"), ("fi", "Sri Lankan pohjoinen provinssi"), ("fr", "Province du Nord"), ("he", "מחוז הצפון"), ("hi", "उत\u{94d}तरी प\u{94d}रान\u{94d}त, श\u{94d}रील\u{902}का"), ("id", "Provinsi Utara, Sri Lanka"), ("it", "provincia Settentrionale"), ("ja", "北部州"), ("ka", "ჩრდილოეთი პროვინცია"), ("ko", "북부 주"), ("ml", "വടക\u{d4d}കൻ പ\u{d4d}രവിശ\u{d4d}യ, ശ\u{d4d}രീലങ\u{d4d}ക"), ("mr", "उत\u{94d}तर प\u{94d}रा\u{902}त, श\u{94d}रील\u{902}का"), ("nl", "Noordelijke Provincie"), ("pl", "Prowincja Północna"), ("pt", "Província do Norte"), ("ru", "Северная провинция"), ("si", "උත\u{dd4}ර\u{dd4} පළ\u{dcf}ත"), ("sv", "Nordprovinsen, Sri Lanka"), ("ta", "வட ம\u{bbe}க\u{bbe}ணம\u{bcd}, இலங\u{bcd}கை"), ("uk", "Північна провінція"), ("ur", "شمالی صوبہ، سری لنکا"), ("vi", "Tỉnh Phía Bắc, Sri Lanka"), ("zh", "北部省")]),
                        unofficial_name_list: [].to_vec(),
                    }
                ),
                (
                    "41",
                    Subdivision{
                        name: "Jaffna",
                        country_alpha2: Alpha2::LK,
                        code: "41",
                        #[cfg(feature = "geo")]
                        geo: Some(SubdivisionGeo{latitude: Some(9.6614981), longitude: Some(80.02554649999999), max_latitude: Some(9.6938708), min_latitude: Some(9.6461028), max_longitude: Some(80.0578452), min_longitude: Some(79.9990243)}),
                        comments: None,
                        subdivision_type: SubdivisionType::District,
                        #[cfg(feature = "translations")]
                        translations: HashMap::from([("ar", "مديرية جافنا"), ("ca", "Districte de Jaffna"), ("ccp", "𑄎𑄛\u{11134}𑄚"), ("ceb", "Jaffna District"), ("de", "Jaffna"), ("en", "Jaffna"), ("es", "Distrito de Jaffna"), ("fa", "ناحیه جفنا"), ("fi", "Jaffnan piirikunta"), ("fr", "Jaffna"), ("hi", "जफ\u{93c}ना जिला"), ("it", "Distretto di Jaffna"), ("ja", "ジャフナ県"), ("ka", "ჯაფნის ოლქი"), ("ko", "자프나 구"), ("ml", "ജ\u{d3e}ഫ\u{d4d}ന ജില\u{d4d}ല"), ("mr", "जाफना जिल\u{94d}हा"), ("nb", "Jaffna"), ("nl", "Jaffna"), ("no", "Jaffna"), ("pl", "Dżafna"), ("pt", "Distrito de Jaffna"), ("ru", "округ Джафна"), ("si", "ය\u{dcf}පනය පර\u{dd2}ප\u{dcf}ලන ද\u{dd2}ස\u{dca}ත\u{dca}\u{200d}ර\u{dd2}ක\u{dca}කය"), ("sv", "Jaffna"), ("ta", "ய\u{bbe}ழ\u{bcd}ப\u{bcd}ப\u{bbe}ண ம\u{bbe}வட\u{bcd}டம\u{bcd}"), ("uk", "Джафна"), ("ur", "جففناضلع"), ("zh", "賈夫納區")]),
                        unofficial_name_list: ["Yapnaya", "Yāpanaya"].to_vec(),
                    }
                ),
                (
                    "42",
                    Subdivision{
                        name: "Kilinochchi",
                        country_alpha2: Alpha2::LK,
                        code: "42",
                        #[cfg(feature = "geo")]
                        geo: Some(SubdivisionGeo{latitude: Some(9.3802886), longitude: Some(80.3769999), max_latitude: Some(9.4173529), min_latitude: Some(9.3365197), max_longitude: Some(80.435114), min_longitude: Some(80.3180948)}),
                        comments: None,
                        subdivision_type: SubdivisionType::District,
                        #[cfg(feature = "translations")]
                        translations: HashMap::from([("ar", "مقاطعة كيلينوتشي"), ("bn", "ক\u{9cd}লিনোক\u{9be}চি জেল\u{9be}"), ("ccp", "𑄇\u{11128}𑄣\u{11128}𑄚\u{1112e}𑄌\u{11134}𑄌\u{11128}"), ("ceb", "Kilinochchi District"), ("da", "Kilinochchi"), ("de", "Kilinochchi"), ("el", "Κιλινότσι"), ("en", "Kilinochchi"), ("es", "Distrito de Kilinochchi"), ("fa", "ناحیه کیلینوچی"), ("fi", "Kilinochchin piirikunta"), ("fr", "Kilinochchi"), ("gu", "કિલિનોચ\u{acd}ચી જિલ\u{acd}લો"), ("hi", "किलिनोच\u{94d}चि जिला"), ("id", "Distrik Kilinochchi"), ("it", "Distretto di Kilinochchi"), ("ja", "キリノッチ県"), ("ka", "კილინოჩის ოლქი"), ("kn", "ಕ\u{cbf}ಲ\u{cbf}ನ\u{cca}ಚ\u{ccd}ಚ\u{cbf} ಜ\u{cbf}ಲ\u{ccd}ಲ\u{cc6}"), ("ko", "킬리노치치 구"), ("lt", "Kilinočio apskritis"), ("lv", "Kilinoči distrikts"), ("ml", "കില\u{d4d}ലിനോച\u{d4d}ചി ജില\u{d4d}ല"), ("mr", "किलिनोच\u{94d}ची जिल\u{94d}हा"), ("ms", "Kilinochchi District"), ("nb", "Kilinochchi"), ("nl", "Kilinochchi"), ("no", "Kilinochchi"), ("pl", "Kilinoćći"), ("pt", "Kilinochchi"), ("ru", "Килиноччи"), ("si", "ක\u{dd2}ල\u{dd2}නොච\u{dca}ච\u{dd2} ද\u{dd2}ස\u{dca}ත\u{dca}\u{200d}ර\u{dd2}ක\u{dca}කය"), ("sv", "Kilinochchi"), ("ta", "கிளிநொச\u{bcd}சி ம\u{bbe}வட\u{bcd}டம\u{bcd}"), ("te", "క\u{c3f}ల\u{c3f}న\u{c4b}చ\u{c4d}చ\u{c3f} జ\u{c3f}ల\u{c4d}ల\u{c3e}"), ("th", "เขตค\u{e34}ล\u{e34}โนชช\u{e35}"), ("tr", "Kilinochchi District"), ("uk", "Кіліноччі"), ("ur", "کیلینوچچی ضلع"), ("vi", "Quận Kilinochchi"), ("zh", "基利諾奇區")]),
                        unofficial_name_list: ["Kilinochchi"].to_vec(),
                    }
                ),
                (
                    "43",
                    Subdivision{
                        name: "Mannar",
                        country_alpha2: Alpha2::LK,
                        code: "43",
                        #[cfg(feature = "geo")]
                        geo: Some(SubdivisionGeo{latitude: Some(8.9893222), longitude: Some(79.8800832), max_latitude: Some(9.0290349), min_latitude: Some(8.9625776), max_longitude: Some(79.92742539999999), min_longitude: Some(79.8438262)}),
                        comments: None,
                        subdivision_type: SubdivisionType::District,
                        #[cfg(feature = "translations")]
                        translations: HashMap::from([("ar", "مقاطعة منار"), ("bn", "ম\u{9be}ন\u{9be}র জেল\u{9be}"), ("ccp", "𑄟𑄚𑄢\u{11134}"), ("ceb", "Mannar District"), ("da", "Mannar District"), ("de", "Mannar"), ("el", "Μάνναρ"), ("en", "Mannar"), ("es", "Distrito de Mannar"), ("fa", "ناحیه منار"), ("fi", "Mannarin piirikunta"), ("fr", "Mannar"), ("gu", "મન\u{acd}નાર જિલ\u{acd}લો"), ("hi", "मन\u{94d}नार जिला"), ("id", "Distrik Mannar"), ("it", "Distretto di Mannar"), ("ja", "マンナール県"), ("ka", "მანარის ოლქი"), ("kn", "ಮನ\u{ccd}ನಾರ\u{ccd} ಜ\u{cbf}ಲ\u{ccd}ಲ\u{cc6}"), ("ko", "만나르 구"), ("lt", "Manaro apskritis"), ("lv", "Mannaras distrikts"), ("ml", "മന\u{d4d}ന\u{d3e}ർ ജില\u{d4d}ല"), ("mr", "मन\u{94d}नार जिल\u{94d}हा"), ("ms", "Mannar District"), ("nb", "Mannar distrikt"), ("nl", "Mannar"), ("no", "Mannar distrikt"), ("pl", "Mannar"), ("pt", "Distrito de Mannar"), ("ru", "Маннар"), ("si", "මන\u{dca}න\u{dcf}රම\u{dca} ද\u{dd2}ස\u{dca}ත\u{dca}\u{200d}ර\u{dd2}ක\u{dca}කය"), ("sv", "Mannar"), ("ta", "மன\u{bcd}ன\u{bbe}ர\u{bcd} ம\u{bbe}வட\u{bcd}டம\u{bcd}"), ("te", "మన\u{c4d}న\u{c3e}ర\u{c4d} జ\u{c3f}ల\u{c4d}ల\u{c3e}"), ("th", "เขตม\u{e31}นนาร\u{e4c}"), ("tr", "Mannar District"), ("uk", "Маннар"), ("ur", "مانار ضلع"), ("vi", "Quận Mannar"), ("zh", "馬納爾區")]),
                        unofficial_name_list: ["Manar", "Mannar", "Mannerama"].to_vec(),
                    }
                ),
                (
                    "44",
                    Subdivision{
                        name: "Vavuniya",
                        country_alpha2: Alpha2::LK,
                        code: "44",
                        #[cfg(feature = "geo")]
                        geo: Some(SubdivisionGeo{latitude: Some(8.7381572), longitude: Some(80.47714719999999), max_latitude: Some(8.8204055), min_latitude: Some(8.6835302), max_longitude: Some(80.5478097), min_longitude: Some(80.42717449999999)}),
                        comments: None,
                        subdivision_type: SubdivisionType::District,
                        #[cfg(feature = "translations")]
                        translations: HashMap::from([("ar", "مديرية فافونيا"), ("ccp", "𑄞𑄞\u{1112a}𑄚\u{11128}𑄠"), ("ceb", "Vavuniya District"), ("de", "Vavuniya"), ("el", "Επαρχία Βαβουνίγια"), ("en", "Vavuniya"), ("es", "Distrito de Vavuniya"), ("fa", "منطقه\u{654} واوونیا"), ("fi", "Vavuniyan piirikunta"), ("fr", "Vavuniya"), ("hi", "वाव\u{941}निया जिला"), ("id", "Distrik Vavuniya"), ("it", "Distretto di Vavuniya"), ("ja", "バブニヤ県"), ("ka", "ვავუნიიის ოლქი"), ("ko", "바부니야 구"), ("ml", "വ\u{d3e}വ\u{d41}നിയ ജില\u{d4d}ല"), ("mr", "वाव\u{941}नीया जिल\u{94d}हा"), ("nl", "Vavuniya"), ("pl", "Wawunija"), ("ru", "Вавуния"), ("si", "වව\u{dd4}න\u{dd2}ය\u{dcf} පර\u{dd2}ප\u{dcf}ලන ද\u{dd2}ස\u{dca}ත\u{dca}\u{200d}ර\u{dd2}ක\u{dca}කය"), ("sv", "Vavuniya"), ("ta", "வவுனிய\u{bbe} ம\u{bbe}வட\u{bcd}டம\u{bcd}"), ("uk", "Вавунія"), ("ur", "واوونییا ضلع"), ("zh", "瓦武尼亞區")]),
                        unofficial_name_list: ["Vavuniyāwa"].to_vec(),
                    }
                ),
                (
                    "45",
                    Subdivision{
                        name: "Mullaittivu",
                        country_alpha2: Alpha2::LK,
                        code: "45",
                        #[cfg(feature = "geo")]
                        geo: Some(SubdivisionGeo{latitude: Some(9.2670911), longitude: Some(80.81424799999999), max_latitude: Some(9.2764461), min_latitude: Some(9.2588919), max_longitude: Some(80.8227488), min_longitude: Some(80.8070613)}),
                        comments: None,
                        subdivision_type: SubdivisionType::District,
                        #[cfg(feature = "translations")]
                        translations: HashMap::from([("ar", "مقاطعة مولايتيفو"), ("bn", "মোল\u{9be}ইতিবো জেল\u{9be}"), ("ca", "Mullaitivu"), ("ccp", "𑄟\u{1112a}𑄣\u{1112d}𑄑\u{11128}𑄞\u{1112a}"), ("ceb", "Mullaitivu District"), ("da", "Mullaitivu District"), ("de", "Mullaitivu"), ("el", "Μουλαϊτιβούν"), ("en", "Mullaitivu"), ("es", "Distrito de Mullaitivu"), ("fa", "ناحیه مولایتیوو"), ("fi", "Mullaitivun piirikunta"), ("fr", "Mullaitivu"), ("gu", "મ\u{ac1}લ\u{acd}લતિવ\u{ac1} જિલ\u{acd}લો"), ("hi", "म\u{941}ल\u{948}तिव\u{941} जिला"), ("id", "Distrik Mullaitivu"), ("it", "Distretto di Mullaitivu"), ("ja", "ムッライッティーヴー県"), ("ka", "მულაიტივუს ოლქი"), ("kn", "ಮುಲ\u{ccd}ಲತ\u{cbf}ವು ಜ\u{cbf}ಲ\u{ccd}ಲ\u{cc6}"), ("ko", "물라이티부 구"), ("lt", "Mulaitivo apskritis"), ("lv", "Mullaitivu distrikts"), ("ml", "മ\u{d41}ല\u{d4d}ലൈടിവ\u{d4d} ജില\u{d4d}ല"), ("mr", "म\u{941}ल\u{948}तीव\u{942} जिल\u{94d}हा"), ("ms", "Mullaitivu District"), ("nb", "Mullaittivu"), ("nl", "Mullaitivu"), ("no", "Mullaittivu"), ("pl", "Mullajttiwu"), ("pt", "Mullaittivu"), ("ru", "Муллайтиву"), ("si", "ම\u{dd4}ලත\u{dd2}ව\u{dca} පර\u{dd2}ප\u{dcf}ලන ද\u{dd2}ස\u{dca}ත\u{dca}\u{200d}ර\u{dd2}ක\u{dca}කය"), ("sv", "Mullaitivu"), ("ta", "முல\u{bcd}லைத\u{bcd}த\u{bc0}வு ம\u{bbe}வட\u{bcd}டம\u{bcd}"), ("te", "ముల\u{c3e}య\u{c3f}ట\u{c3f}వు జ\u{c3f}ల\u{c4d}ల\u{c3e}"), ("th", "ม\u{e39}ลไลท\u{e34}ว\u{e39}"), ("tr", "Mullaitivu District"), ("uk", "Муллайтіву"), ("ur", "مولایتیوو ضلع"), ("vi", "Quận Mullaitivu"), ("zh", "穆萊蒂武區")]),
                        unofficial_name_list: ["Mulativu"].to_vec(),
                    }
                ),
                (
                    "5",
                    Subdivision{
                        name: "නැගෙනහ\u{dd2}ර පළ\u{dcf}ත, ශ\u{dca} ර\u{dd3} ලංක\u{dcf}ව",
                        country_alpha2: Alpha2::LK,
                        code: "5",
                        #[cfg(feature = "geo")]
                        geo: None,
                        comments: None,
                        subdivision_type: SubdivisionType::Province,
                        #[cfg(feature = "translations")]
                        translations: HashMap::from([("ar", "المقاطعة الشرقية (سريلانكا)"), ("bg", "Източна провинция"), ("bn", "প\u{9c2}র\u{9cd}ব\u{9be}ঞ\u{9cd}চল প\u{9cd}রদেশ"), ("ccp", "𑄛\u{1112a}𑄇\u{11134}𑄟𑄬𑄇\u{11134}𑄈𑄬"), ("ceb", "Eastern Province (lalawigan sa Sri Lanka)"), ("de", "Ostprovinz"), ("el", "Ανατολική επαρχία"), ("en", "Eastern"), ("es", "Provincia del Este"), ("fa", "استان شرقی (سری\u{200c}لانکا)"), ("fi", "Sri Lankan itäinen provinssi"), ("fr", "Province de l’Est"), ("he", "מחוז המזרח"), ("hi", "प\u{942}र\u{94d}वी प\u{94d}रान\u{94d}त"), ("id", "Provinsi Timur, Sri Lanka"), ("it", "provincia Orientale"), ("ja", "東部州"), ("ka", "აღმოსავლეთი პროვინცია"), ("ko", "동부 주"), ("mr", "प\u{942}र\u{94d}व प\u{94d}रा\u{902}त"), ("nl", "Oostelijke Provincie"), ("pl", "Prowincja Wschodnia"), ("pt", "Este"), ("ro", "Provincia de Est"), ("ru", "Восточная провинция"), ("si", "නැගෙනහ\u{dd2}ර පළ\u{dcf}ත, ශ\u{dca} ර\u{dd3} ලංක\u{dcf}ව"), ("sv", "Östprovinsen, Sri Lanka"), ("ta", "கிழக\u{bcd}கு ம\u{bbe}க\u{bbe}ணம\u{bcd}"), ("uk", "Східна провінція"), ("ur", "مشرقی صوبہ، سری لنکا"), ("vi", "Tỉnh Phía Đông"), ("zh", "東部省")]),
                        unofficial_name_list: [].to_vec(),
                    }
                ),
                (
                    "51",
                    Subdivision{
                        name: "Batticaloa",
                        country_alpha2: Alpha2::LK,
                        code: "51",
                        #[cfg(feature = "geo")]
                        geo: Some(SubdivisionGeo{latitude: Some(7.730997100000001), longitude: Some(81.6747295), max_latitude: Some(7.770829999999999), min_latitude: Some(7.6971701), max_longitude: Some(81.706103), min_longitude: Some(81.65085909999999)}),
                        comments: None,
                        subdivision_type: SubdivisionType::District,
                        #[cfg(feature = "translations")]
                        translations: HashMap::from([("ar", "مديرية باتيكالوا"), ("ca", "Batticaloa"), ("ccp", "𑄝𑄖\u{11133}𑄦\u{11128}𑄇𑄣\u{11131}"), ("ceb", "Batticaloa District"), ("de", "Batticaloa (Distrikt)"), ("en", "Batticaloa"), ("es", "Distrito de Batticaloa"), ("fa", "ناحیه باتیکالوا"), ("fi", "Batticaloan piirikunta"), ("fr", "Batticaloa (district)"), ("hi", "बट\u{94d}टिकलोआ जिला"), ("id", "Distrik Batticaloa"), ("it", "Distretto di Batticaloa"), ("ja", "バッティカロア県"), ("ka", "ბატიკალოის ოლქი"), ("ko", "바티칼로아 구"), ("ml", "മട\u{d4d}ടക\u{d4d}കളപ\u{d4d}പ\u{d4d} ജില\u{d4d}ല"), ("mr", "बट\u{94d}टिकलोआ जिल\u{94d}हा"), ("nb", "Batticaloa (distrikt)"), ("nl", "Batticaloa"), ("no", "Batticaloa (distrikt)"), ("pl", "Madakalapuwa"), ("ru", "Баттикалоа"), ("si", "මඩකලප\u{dd4}ව පර\u{dd2}ප\u{dcf}ලන ද\u{dd2}ස\u{dca}ත\u{dca}\u{200d}ර\u{dd2}ක\u{dca}කය"), ("sv", "Batticaloa District (distrikt i Sri Lanka)"), ("ta", "மட\u{bcd}டக\u{bcd}களப\u{bcd}பு ம\u{bbe}வட\u{bcd}டம\u{bcd}"), ("uk", "Баттікалоа"), ("ur", "باٹیکالوا ضلع"), ("zh", "拜蒂克洛區")]),
                        unofficial_name_list: ["Mad\u{328}akalpūwa"].to_vec(),
                    }
                ),
                (
                    "52",
                    Subdivision{
                        name: "Ampara",
                        country_alpha2: Alpha2::LK,
                        code: "52",
                        #[cfg(feature = "geo")]
                        geo: Some(SubdivisionGeo{latitude: Some(7.301756300000001), longitude: Some(81.6747295), max_latitude: Some(7.3171365), min_latitude: Some(7.2753244), max_longitude: Some(81.70905599999999), min_longitude: Some(81.6450047)}),
                        comments: None,
                        subdivision_type: SubdivisionType::District,
                        #[cfg(feature = "translations")]
                        translations: HashMap::from([("ar", "مقاطعة أمبارا"), ("bn", "আমপ\u{9be}র\u{9be} জেল\u{9be}"), ("ca", "Amparai"), ("ccp", "𑄃𑄟\u{11134}𑄛𑄢"), ("ceb", "Ampara District"), ("da", "Ampara District"), ("de", "Ampara (Distrikt)"), ("el", "Αμπάρα"), ("en", "Ampara"), ("es", "Distrito de Ampara"), ("fa", "بخش امپرا"), ("fi", "Amparan piirikunta"), ("fr", "Ampara (district)"), ("gu", "એમ\u{acd}પારા જિલ\u{acd}લો"), ("hi", "अम\u{94d}पार’ जिला"), ("id", "Distrik Ampara"), ("it", "Distretto di Ampara"), ("ja", "アンパーラ県"), ("ka", "ამპარის ოლქი"), ("kn", "ಅಂಪಾರ ಜ\u{cbf}ಲ\u{ccd}ಲ\u{cc6}"), ("ko", "암파라 구"), ("lt", "Amparos apskritis"), ("lv", "Amparas distrikts"), ("ml", "അമ\u{d4d}പ\u{d3e}റ ജില\u{d4d}ല"), ("mr", "अ\u{902}पारा जिल\u{94d}हा"), ("ms", "Ampara District"), ("nb", "Ampara"), ("nl", "Ampara"), ("no", "Ampara"), ("pl", "Ampara"), ("pt", "Ampara"), ("ru", "округ Ампара"), ("si", "අම\u{dca}ප\u{dcf}ර පර\u{dd2}ප\u{dcf}ලන ද\u{dd2}ස\u{dca}ත\u{dca}\u{200d}ර\u{dd2}ක\u{dca}කය"), ("sv", "Ampara District (distrikt i Sri Lanka)"), ("ta", "அம\u{bcd}ப\u{bbe}றை ம\u{bbe}வட\u{bcd}டம\u{bcd}"), ("te", "అంప\u{c3e}ర\u{c3e} జ\u{c3f}ల\u{c4d}ల\u{c3e}"), ("th", "เขตอ\u{e31}มปารา"), ("tr", "Ampara District"), ("uk", "Ампара"), ("ur", "امپارا ضلع"), ("vi", "Quận Ampara"), ("zh", "安帕賴區")]),
                        unofficial_name_list: ["Ampara"].to_vec(),
                    }
                ),
                (
                    "53",
                    Subdivision{
                        name: "Trincomalee",
                        country_alpha2: Alpha2::LK,
                        code: "53",
                        #[cfg(feature = "geo")]
                        geo: Some(SubdivisionGeo{latitude: Some(8.5922), longitude: Some(81.19679579999999), max_latitude: Some(8.6231144), min_latitude: Some(8.5433042), max_longitude: Some(81.2461119), min_longitude: Some(81.18032149999999)}),
                        comments: None,
                        subdivision_type: SubdivisionType::District,
                        #[cfg(feature = "translations")]
                        translations: HashMap::from([("ar", "مديرية ترينكومالي"), ("ca", "Trincomalee"), ("ccp", "𑄑\u{11133}𑄢\u{11128}𑄚\u{11134}𑄇\u{1112e}𑄟𑄣\u{11128}"), ("ceb", "Trincomalee District"), ("de", "Trincomalee"), ("en", "Trincomalee"), ("es", "Distrito de Trincomalee"), ("fa", "ناحیه ترینکومالی"), ("fi", "Trincomaleen piirikunta"), ("fr", "Trinquemalay"), ("hi", "त\u{94d}रि\u{902}कोन\u{94d}माली जिला"), ("it", "Distretto di Trincomalee"), ("ja", "トリンコマリー県"), ("ka", "ტრინკომალეეს ოლქი"), ("ko", "트링코말리 구"), ("ml", "ട\u{d4d}രിങ\u{d4d}കോമ\u{d3e}ലി ജില\u{d4d}ല"), ("mr", "त\u{94d}रि\u{902}कोमली जिल\u{94d}हा"), ("nb", "Trincomalee"), ("nl", "Trincomalee"), ("no", "Trincomalee"), ("pl", "Trikunamalaja"), ("ru", "Тринкомали округ"), ("si", "ත\u{dca}\u{200d}ර\u{dd2}ක\u{dd4}ණ\u{dcf}මල ද\u{dd2}ස\u{dca}ත\u{dca}\u{200d}ර\u{dd2}ක\u{dca}කය"), ("sv", "Trincomalee District (distrikt i Sri Lanka)"), ("ta", "திருகோணமலை ம\u{bbe}வட\u{bcd}டம\u{bcd}"), ("uk", "Трінкомалі"), ("ur", "ترینکومالی ضلع"), ("zh", "亭可馬里區")]),
                        unofficial_name_list: ["Tirikunāmalaya", "Trinkomali"].to_vec(),
                    }
                ),
                (
                    "6",
                    Subdivision{
                        name: "වයඹ පළ\u{dcf}ත, ශ\u{dca}\u{200d}ර\u{dd3} ලංක\u{dcf}ව",
                        country_alpha2: Alpha2::LK,
                        code: "6",
                        #[cfg(feature = "geo")]
                        geo: None,
                        comments: None,
                        subdivision_type: SubdivisionType::Province,
                        #[cfg(feature = "translations")]
                        translations: HashMap::from([("ar", "المقاطعة الشمالية الغربية (سريلانكا)"), ("bg", "Северозападна провинция"), ("bn", "উত\u{9cd}তর পশ\u{9cd}চিম\u{9be}ঞ\u{9cd}চল প\u{9cd}রদেশ"), ("ccp", "𑄅\u{1112a}𑄖\u{11133}𑄦\u{11127}𑄢\u{11134} 𑄛\u{11127}𑄏\u{11128}𑄟\u{11134}𑄟𑄬𑄇\u{11134}𑄈𑄬"), ("ceb", "North Western Province"), ("de", "Nordwestprovinz"), ("el", "Βορειοδυτική επαρχία"), ("en", "North Western"), ("es", "Provincia Noroeste"), ("fa", "استان شمال غربی، سری\u{200c}لانکا"), ("fi", "Sri Lankan luoteisprovinssi"), ("fr", "Province du Nord-Ouest"), ("hi", "उत\u{94d}तर पश\u{94d}चिमी प\u{94d}रान\u{94d}त"), ("id", "Provinsi Barat Laut, Sri Lanka"), ("it", "provincia Nord-Occidentale"), ("ja", "北西部州"), ("ka", "ჩრდილო-დასავლეთი პროვინცია"), ("ko", "북서부 주"), ("mr", "वायव\u{94d}य प\u{94d}रा\u{902}त"), ("nl", "Noordwestelijke Provincie"), ("pl", "Prowincja Północno-Zachodnia"), ("pt", "Noroeste"), ("ru", "Северо-Западная провинция"), ("si", "වයඹ පළ\u{dcf}ත, ශ\u{dca}\u{200d}ර\u{dd3} ලංක\u{dcf}ව"), ("sv", "Nordvästprovinsen, Sri Lanka"), ("ta", "வடமேல\u{bcd} ம\u{bbe}க\u{bbe}ணம\u{bcd}"), ("uk", "Північно-Західна провінція"), ("ur", "شمال مغربی صوبہ، سری لنکا"), ("zh", "西北省")]),
                        unofficial_name_list: [].to_vec(),
                    }
                ),
                (
                    "61",
                    Subdivision{
                        name: "Kurunegala",
                        country_alpha2: Alpha2::LK,
                        code: "61",
                        #[cfg(feature = "geo")]
                        geo: Some(SubdivisionGeo{latitude: Some(7.472981299999999), longitude: Some(80.3547286), max_latitude: Some(7.529148800000001), min_latitude: Some(7.432091900000001), max_longitude: Some(80.4164028), min_longitude: Some(80.29915799999999)}),
                        comments: None,
                        subdivision_type: SubdivisionType::District,
                        #[cfg(feature = "translations")]
                        translations: HashMap::from([("ar", "مقاطعة كورونيغالا"), ("bn", "ক\u{9c1}রোনগেল\u{9be} জেল\u{9be}"), ("ccp", "𑄇\u{1112a}𑄢\u{1112a}𑄚𑄬𑄉𑄣"), ("ceb", "Kurunegala District"), ("da", "Kurunegala District"), ("de", "Kurunegala"), ("el", "Κουρουνεγκάλα"), ("en", "Kurunegala"), ("es", "Distrito de Kurunegala"), ("fa", "ناحیه کورونیگالا"), ("fi", "Kurunegalan kaupunginosa"), ("fr", "Kurunegala"), ("gu", "ક\u{ac1}ર\u{ac1}ન\u{ac7}ગલા જિલ\u{acd}લો"), ("hi", "क\u{941}र\u{941}न\u{947}गल’ जिला"), ("id", "Distrik Kurunegala"), ("it", "Distretto di Kurunegala"), ("ja", "クルネーガラ県"), ("ka", "კურუნეგალის ოლქი"), ("kn", "ಕುಲ\u{ccd}ಲ\u{cc2}ರು ಜ\u{cbf}ಲ\u{ccd}ಲ\u{cc6}"), ("ko", "쿠루네갈라 구"), ("lt", "Kurunegalos apskritis"), ("lv", "Kurunegalas distrikts"), ("ml", "ക\u{d41}റ\u{d41}നേഗല ജില\u{d4d}ല"), ("mr", "क\u{941}र\u{941}न\u{947}गला जिल\u{94d}हा"), ("ms", "Kurunegala District"), ("nb", "Kurunegala distrikt"), ("nl", "Kurunegala"), ("no", "Kurunegala distrikt"), ("pl", "Dystrykt Kurunegala"), ("pt", "Distrito de Kurunegala"), ("ru", "Курунегала"), ("si", "ක\u{dd4}ර\u{dd4}ණෑගල ද\u{dd2}ස\u{dca}ත\u{dca} ර\u{dd2}ක\u{dca}කය"), ("sv", "Kurunegala"), ("ta", "குருந\u{bbe}கல\u{bcd} ம\u{bbe}வட\u{bcd}டம\u{bcd}"), ("te", "కురున\u{c46}గ\u{c47}ల\u{c3e} జ\u{c3f}ల\u{c4d}ల\u{c3e}"), ("th", "เขตค\u{e38}ร\u{e38}นกาลา"), ("tr", "Kurunegala District"), ("uk", "Курунегала"), ("ur", "کرنیگالا ضلع"), ("vi", "Quận Kurunegala"), ("zh", "庫魯內格勒區")]),
                        unofficial_name_list: ["Kurunegala"].to_vec(),
                    }
                ),
                (
                    "62",
                    Subdivision{
                        name: "Puttalam",
                        country_alpha2: Alpha2::LK,
                        code: "62",
                        #[cfg(feature = "geo")]
                        geo: Some(SubdivisionGeo{latitude: Some(8.0402828), longitude: Some(79.84087869999999), max_latitude: Some(8.069724899999999), min_latitude: Some(7.9910674), max_longitude: Some(79.8573579), min_longitude: Some(79.8081207)}),
                        comments: None,
                        subdivision_type: SubdivisionType::District,
                        #[cfg(feature = "translations")]
                        translations: HashMap::from([("ar", "مقاطعة بوتالام"), ("bn", "পোত\u{9be}ল\u{9be}ম জেল\u{9be}"), ("ccp", "𑄛\u{1112a}𑄑𑄣𑄟\u{11134}"), ("ceb", "Puttalam District"), ("da", "Puttalam District"), ("de", "Puttalam"), ("el", "Πουτταλάμ"), ("en", "Puttalam"), ("es", "Distrito de Puttalam"), ("fa", "ناحیه پوتالام"), ("fi", "Puttalamin piirikunta"), ("fr", "Puttalam"), ("gu", "પ\u{ac1}ટ\u{acd}ટલમ જિલ\u{acd}લો"), ("hi", "प\u{941}त\u{94d}तलम जिला"), ("id", "Distrik Puttalam"), ("it", "Distretto di Puttalam"), ("ja", "プッタラム県"), ("ka", "პუტალამის ოლქი"), ("kn", "ಪುಟ\u{ccd}ಟಲಮ\u{ccd} ಜ\u{cbf}ಲ\u{ccd}ಲ\u{cc6}"), ("ko", "푸탈람 구"), ("lt", "Putalamo apskritis"), ("lv", "Puttalamas distrikts"), ("ml", "പ\u{d41}ത\u{d4d}തലം ജില\u{d4d}ല"), ("mr", "पत\u{94d}तलम जिल\u{94d}हा"), ("ms", "Puttalam District"), ("nb", "Puttalam distrikt"), ("nl", "Puttalam"), ("no", "Puttalam distrikt"), ("pl", "Dystrykt Puttalam"), ("pt", "Distrito de Puttalam"), ("ru", "Путталам"), ("si", "ප\u{dd4}ත\u{dca}තලම ද\u{dd2}ස\u{dca}ත\u{dca}\u{200d}ර\u{dd2}ක\u{dca}කය"), ("sv", "Puttalam District (distrikt i Sri Lanka)"), ("ta", "புத\u{bcd}தளம\u{bcd}"), ("te", "పుట\u{c4d}ట\u{c3e}లం జ\u{c3f}ల\u{c4d}ల\u{c3e}"), ("th", "เขตป\u{e38}ตตาล\u{e31}ม"), ("tr", "Puttalam District"), ("uk", "Путталам"), ("ur", "پوٹالام ضلع"), ("vi", "Quận Puttalam"), ("zh", "普塔勒姆區")]),
                        unofficial_name_list: ["Puttalam"].to_vec(),
                    }
                ),
                (
                    "7",
                    Subdivision{
                        name: "උත\u{dd4}ර\u{dd4} මැද පළ\u{dcf}ත",
                        country_alpha2: Alpha2::LK,
                        code: "7",
                        #[cfg(feature = "geo")]
                        geo: None,
                        comments: None,
                        subdivision_type: SubdivisionType::Province,
                        #[cfg(feature = "translations")]
                        translations: HashMap::from([("ar", "المقاطعة الشمالية الوسطى (سريلانكا)"), ("bg", "Северна централна провинция"), ("bn", "উত\u{9cd}তর মধ\u{9cd}য\u{9be}ঞ\u{9cd}চল প\u{9cd}রদেশ"), ("ccp", "𑄅\u{1112a}𑄖\u{11133}𑄦\u{11127}𑄢\u{11134} 𑄥𑄬𑄚\u{11134}𑄑\u{11133}𑄢𑄣\u{11134}"), ("ceb", "North Central Province"), ("de", "Nördliche Zentralprovinz"), ("el", "Βορειοκεντρική επαρχία"), ("en", "North Central"), ("es", "Provincia Central del Norte"), ("fa", "استان شمال مرکزی، سری\u{200c}لانکا"), ("fi", "Sri Lankan keskipohjoinen provinssi"), ("fr", "Province du Centre-Nord"), ("hi", "उत\u{94d}तरी मध\u{94d}य प\u{94d}रान\u{94d}त"), ("id", "Provinsi Tengah Utara, Sri Lanka"), ("it", "provincia Centro-Settentrionale"), ("ja", "北中部州"), ("ka", "ჩრდილო-ცენტრალური პროვინცია"), ("ko", "중북부 주"), ("mr", "उत\u{94d}तर मध\u{94d}य प\u{94d}रा\u{902}त"), ("nl", "Noordelijke Centrale Provincie"), ("pl", "Prowincja Północno-Środkowa"), ("pt", "Centro-Norte"), ("ru", "Северо-Центральная провинция"), ("si", "උත\u{dd4}ර\u{dd4} මැද පළ\u{dcf}ත"), ("sv", "Norra centralprovinsen"), ("ta", "வடமத\u{bcd}திய ம\u{bbe}க\u{bbe}ணம\u{bcd}"), ("uk", "Північно-Центральна провінція"), ("ur", "شمال وسطی صوبہ، سری لنکا"), ("vi", "Tỉnh Trung Bắc"), ("zh", "北中省")]),
                        unofficial_name_list: [].to_vec(),
                    }
                ),
                (
                    "71",
                    Subdivision{
                        name: "Anuradhapura",
                        country_alpha2: Alpha2::LK,
                        code: "71",
                        #[cfg(feature = "geo")]
                        geo: Some(SubdivisionGeo{latitude: Some(8.3451852), longitude: Some(80.38813329999999), max_latitude: Some(8.4107342), min_latitude: Some(8.2595695), max_longitude: Some(80.46818379999999), min_longitude: Some(80.33786769999999)}),
                        comments: None,
                        subdivision_type: SubdivisionType::District,
                        #[cfg(feature = "translations")]
                        translations: HashMap::from([("ar", "مديرية انورادهابورا"), ("ca", "Anuradhapura"), ("ccp", "𑄃𑄚\u{1112a}𑄢𑄙𑄛\u{1112a}𑄢\u{11134}"), ("ceb", "Anuradhapura District"), ("de", "Anuradhapura (Distrikt)"), ("en", "Anuradhapura"), ("es", "Distrito de Anuradhapura"), ("fa", "ناحیه انورادهاپورا"), ("fi", "Anuradhapuran piirikunta"), ("fr", "Anuradhapura (district)"), ("hi", "अन\u{941}राधप\u{941}र’"), ("it", "Distretto di Anuradhapura"), ("ja", "アヌラーダプラ県"), ("ka", "ანურადჰაპურის ოლქი"), ("ko", "아누라다푸라 구"), ("ml", "അന\u{d41}ര\u{d3e}ധപ\u{d41}രം"), ("mr", "अन\u{941}राधप\u{942}रा जिल\u{94d}हा"), ("nl", "Anuradhapura"), ("pl", "Anuradhapura"), ("ru", "Анурадхапура"), ("si", "අන\u{dd4}ර\u{dcf}ධප\u{dd4}ර පර\u{dd2}ප\u{dcf}ලන ද\u{dd2}ස\u{dca}ත\u{dca}\u{200d}ර\u{dd2}ක\u{dca}කය"), ("sv", "Anuradhapura (distrikt)"), ("ta", "அனுர\u{bbe}தபுரம\u{bcd} ம\u{bbe}வட\u{bcd}டம\u{bcd}"), ("uk", "Анурадхапура"), ("ur", "انورادھاپورہ ضلع"), ("zh", "阿努拉德普勒區")]),
                        unofficial_name_list: ["Anuradhapur", "Anurādhapūraya"].to_vec(),
                    }
                ),
                (
                    "72",
                    Subdivision{
                        name: "Polonnaruwa",
                        country_alpha2: Alpha2::LK,
                        code: "72",
                        #[cfg(feature = "geo")]
                        geo: Some(SubdivisionGeo{latitude: Some(7.932635799999999), longitude: Some(81.00368209999999), max_latitude: Some(7.9761928), min_latitude: Some(7.892033799999999), max_longitude: Some(81.0447693), min_longitude: Some(80.9670067)}),
                        comments: None,
                        subdivision_type: SubdivisionType::District,
                        #[cfg(feature = "translations")]
                        translations: HashMap::from([("ar", "مقاطعة بولوناروا"), ("bn", "পোলোন\u{9be}রোয\u{9bc}\u{9be} জেল\u{9be}"), ("ca", "Polonnaruwa"), ("ccp", "𑄛\u{11127}𑄣\u{11127}𑄚𑄢\u{1112a}𑄤"), ("ceb", "Polonnaruwa District"), ("da", "Polonnaruwa District"), ("de", "Polonnaruwa"), ("el", "Πολοναρούβα"), ("en", "Polonnaruwa"), ("es", "Distrito de Polonnaruwa"), ("fa", "ناحیه پولونارووا"), ("fi", "Polonnaruwan piirikunta"), ("fr", "Polonnaruwa"), ("gu", "પોલોનાર\u{ac1}વા જિલ\u{acd}લો"), ("he", "נפת פולונארווה"), ("hi", "पोलोनार\u{941}वा जिला"), ("id", "Distrik Polonnaruwa"), ("it", "Distretto di Polonnaruwa"), ("ja", "ポロンナルワ県"), ("ka", "პოლონარუვის ოლქი"), ("kn", "ಪ\u{cca}ಲ\u{cca}ನರುವಾ ಜ\u{cbf}ಲ\u{ccd}ಲ\u{cc6}"), ("ko", "폴론나루와 구"), ("lt", "Plonaruvos apskritis"), ("lv", "Polonnaruvas distrikts"), ("ml", "പോളൊന\u{d4d}ന\u{d3e}ര\u{d41}വ ജില\u{d4d}ല"), ("mr", "पोलोन\u{94d}नार\u{941}वा जिल\u{94d}हा"), ("ms", "Polonnaruwa District"), ("nb", "Polinnaruwa distrikt"), ("nl", "Polonnaruwa"), ("no", "Polinnaruwa distrikt"), ("pl", "Polonnaruwa"), ("pt", "Distrito de Polonnaruwa"), ("ru", "округ Полоннарува"), ("si", "පොළොන\u{dca}නර\u{dd4}ව ද\u{dd2}ස\u{dca}ත\u{dca}\u{200d}ර\u{dd2}ක\u{dca}කය"), ("sv", "Polonnaruwa"), ("ta", "பொலன\u{bcd}னறுவை ம\u{bbe}வட\u{bcd}டம\u{bcd}"), ("te", "ప\u{c4b}ల\u{c4b}న\u{c3e}రువ\u{c3e} జ\u{c3f}ల\u{c4d}ల\u{c3e}"), ("th", "เขตโปลอนนาร\u{e39}นว\u{e4c}"), ("tr", "Polonnaruwa District"), ("uk", "Полоннарува"), ("ur", "پولونارووا ضلع"), ("vi", "Quận Polonnaruwa"), ("zh", "波隆納魯沃區")]),
                        unofficial_name_list: ["Polonaruwa", "Polunnaruwa"].to_vec(),
                    }
                ),
                (
                    "8",
                    Subdivision{
                        name: "ඌව පළ\u{dcf}ත",
                        country_alpha2: Alpha2::LK,
                        code: "8",
                        #[cfg(feature = "geo")]
                        geo: None,
                        comments: None,
                        subdivision_type: SubdivisionType::Province,
                        #[cfg(feature = "translations")]
                        translations: HashMap::from([("ar", "مقاطعة يوفا"), ("bg", "Ува"), ("bn", "উভ\u{9be} প\u{9cd}রদেশ"), ("ca", "Província de Uva"), ("ccp", "𑄅\u{1112a}𑄞"), ("ceb", "Province of Uva"), ("cy", "Talaith Uva"), ("de", "Uva"), ("el", "Επαρχία της Ούβα"), ("en", "Uva"), ("es", "Provincia de Uva"), ("fa", "استان یووا"), ("fi", "Uva"), ("fr", "Province d’Uva"), ("he", "מחוז אובה"), ("hi", "उवा प\u{94d}रान\u{94d}त"), ("id", "Provinsi Uva"), ("it", "Uva"), ("ja", "ウバ州"), ("ka", "უვის პროვინცია"), ("ko", "우바 주"), ("mr", "उवा प\u{94d}रा\u{902}त"), ("nl", "Uva"), ("pl", "Prowincja Uwa"), ("pt", "Uva"), ("ru", "Ува"), ("si", "ඌව පළ\u{dcf}ත"), ("sv", "Uvaprovinsen"), ("ta", "ஊவ\u{bbe} ம\u{bbe}க\u{bbe}ணம\u{bcd}"), ("uk", "Ува"), ("ur", "اووا صوبہ"), ("zh", "烏沃省")]),
                        unofficial_name_list: [].to_vec(),
                    }
                ),
                (
                    "81",
                    Subdivision{
                        name: "Badulla",
                        country_alpha2: Alpha2::LK,
                        code: "81",
                        #[cfg(feature = "geo")]
                        geo: Some(SubdivisionGeo{latitude: Some(6.993400899999999), longitude: Some(81.0549815), max_latitude: Some(7.014605), min_latitude: Some(6.9629781), max_longitude: Some(81.0796166), min_longitude: Some(81.0384179)}),
                        comments: None,
                        subdivision_type: SubdivisionType::District,
                        #[cfg(feature = "translations")]
                        translations: HashMap::from([("ar", "حي بادولا"), ("bn", "ব\u{9be}দ\u{9c1}ল\u{9be} জেল\u{9be}"), ("ca", "Badulla"), ("ccp", "𑄝𑄓\u{1112a}𑄣\u{11133}𑄦"), ("ceb", "Badulla District"), ("da", "Badulla District"), ("de", "Badulla (Distrikt)"), ("el", "Μπαντούλα"), ("en", "Badulla"), ("es", "Distrito de Badulla"), ("fa", "ناحیه بادولا"), ("fi", "Badullan piirikunta"), ("fr", "Badulla (district)"), ("gu", "બડ\u{ac1}લા જિલ\u{acd}લો"), ("hi", "बड\u{941}ला जिला"), ("id", "Distrik Badulla"), ("it", "Distretto di Badulla"), ("ja", "バドゥッラ県"), ("ka", "ბადულის ოლქი"), ("kn", "ಬದುಲ\u{ccd}ಲಾ ಜ\u{cbf}ಲ\u{ccd}ಲ\u{cc6}"), ("ko", "바둘라 구"), ("lt", "Badulos apskritis"), ("lv", "Badullas distrikts"), ("ml", "ബഡ\u{d41}ല\u{d4d}ല ജില\u{d4d}ല"), ("mr", "बद\u{941}ल\u{94d}ला जिल\u{94d}हा"), ("ms", "Badulla District"), ("nb", "Badulla distrikt"), ("nl", "Badulla"), ("no", "Badulla distrikt"), ("pl", "Dystrykt Badulla"), ("pt", "Distrito de Badulla"), ("ru", "Бадулла"), ("si", "බද\u{dd4}ල\u{dca}ල පර\u{dd2}ප\u{dcf}ලන ද\u{dd2}ස\u{dca}ත\u{dca}\u{200d}ර\u{dd2}ක\u{dca}කය"), ("sv", "Badulla (distrikt)"), ("ta", "பதுளை ம\u{bbe}வட\u{bcd}டம\u{bcd}"), ("te", "బదుల\u{c4d}ల\u{c3e} జ\u{c3f}ల\u{c4d}ల\u{c3e}"), ("th", "เขตบาด\u{e38}ลลา"), ("tr", "Badulla District"), ("uk", "Бадулла"), ("ur", "بادولا ضلع"), ("vi", "Quận Badulla"), ("zh", "巴杜勒區")]),
                        unofficial_name_list: ["Badulla"].to_vec(),
                    }
                ),
                (
                    "82",
                    Subdivision{
                        name: "Monaragala",
                        country_alpha2: Alpha2::LK,
                        code: "82",
                        #[cfg(feature = "geo")]
                        geo: Some(SubdivisionGeo{latitude: Some(6.890645399999999), longitude: Some(81.34544170000001), max_latitude: Some(6.9151796), min_latitude: Some(6.858940199999999), max_longitude: Some(81.3671493), min_longitude: Some(81.3208008)}),
                        comments: None,
                        subdivision_type: SubdivisionType::District,
                        #[cfg(feature = "translations")]
                        translations: HashMap::from([("ar", "مديرية موناراغالا"), ("ca", "Districte de Monaragala"), ("ccp", "𑄟\u{11127}𑄚𑄢𑄉𑄣"), ("ceb", "Moneragala District"), ("de", "Moneragala"), ("en", "Moneragala"), ("es", "Distrito de Moneragala"), ("fa", "ناحیه موناراگالا"), ("fi", "Moneragalan piirikunta"), ("fr", "Moneragala"), ("hi", "मोनरागल’ जिला"), ("id", "Distrik Monaragala"), ("it", "Distretto di Moneragala"), ("ja", "モナラーガラ県"), ("ka", "მონერაგალის ოლქი"), ("ko", "모나라갈라 구"), ("ml", "മോണര\u{d3e}ഗല ജില\u{d4d}ല"), ("mr", "मोनरागला जिल\u{94d}हा"), ("nl", "Moneragala"), ("pl", "Monaragala (dystrykt)"), ("ru", "Монерагала"), ("si", "මොණර\u{dcf}ගල ද\u{dd2}ස\u{dca}ත\u{dca}\u{200d}ර\u{dd2}ක\u{dca}කය"), ("sv", "Moneragala"), ("ta", "மொனர\u{bbe}கலை ம\u{bbe}வட\u{bcd}டம\u{bcd}"), ("uk", "Монерагала"), ("ur", "مونیراگالا ضلع"), ("zh", "莫訥勒格勒區")]),
                        unofficial_name_list: ["Monaragalla", "Moneragala"].to_vec(),
                    }
                ),
                (
                    "9",
                    Subdivision{
                        name: "සබරගම\u{dd4}ව පළ\u{dcf}ත",
                        country_alpha2: Alpha2::LK,
                        code: "9",
                        #[cfg(feature = "geo")]
                        geo: None,
                        comments: None,
                        subdivision_type: SubdivisionType::Province,
                        #[cfg(feature = "translations")]
                        translations: HashMap::from([("ar", "مقاطعة ساباراغاموا (سريلانكا)"), ("bg", "Сабарагамува"), ("bn", "স\u{9be}বর\u{9be}গম\u{9c1}ওয\u{9bc}\u{9be} প\u{9cd}রদেশ"), ("ca", "Província de Sabaragamuwa"), ("ccp", "𑄥𑄝𑄢𑄇\u{11134}𑄟\u{1112a}𑄤"), ("ceb", "Province of Sabaragamuwa"), ("cy", "Talaith Sabaragamuwa"), ("de", "Sabaragamuwa"), ("el", "Σαμπαραγκαμούβα"), ("en", "Sabaragamuwa"), ("es", "Sabaragamuwa"), ("fa", "استان ساباراگامووا"), ("fi", "Sabaragamuwa"), ("fr", "Province de Sabaragamuwa"), ("he", "מחוז סבראגמובה"), ("hi", "सबरगम\u{941}वा प\u{94d}रान\u{94d}त"), ("id", "Provinsi Sabaragamuwa"), ("it", "Sabaragamuwa"), ("ja", "サバラガムワ州"), ("ka", "საბარაგამუვის პროვინცია"), ("ko", "사바라가무와 주"), ("mr", "सबरगम\u{941}वा प\u{94d}रा\u{902}त"), ("nl", "Sabaragamuwa"), ("pl", "Prowincja Sabaragamuwa"), ("pt", "Sabaragamuwa"), ("ru", "Сабарагамува"), ("si", "සබරගම\u{dd4}ව පළ\u{dcf}ත"), ("sv", "Sabaragamuwa"), ("ta", "சப\u{bcd}பிரகமுவ\u{bbe} ம\u{bbe}க\u{bbe}ணம\u{bcd}"), ("uk", "Сабарагамува"), ("ur", "سبراگموا علاقہ"), ("zh", "薩伯勒格穆沃省")]),
                        unofficial_name_list: [].to_vec(),
                    }
                ),
                (
                    "91",
                    Subdivision{
                        name: "Ratnapura",
                        country_alpha2: Alpha2::LK,
                        code: "91",
                        #[cfg(feature = "geo")]
                        geo: Some(SubdivisionGeo{latitude: Some(6.7081032), longitude: Some(80.3769999), max_latitude: Some(6.7672387), min_latitude: Some(6.666312599999999), max_longitude: Some(80.4288483), min_longitude: Some(80.3114319)}),
                        comments: None,
                        subdivision_type: SubdivisionType::District,
                        #[cfg(feature = "translations")]
                        translations: HashMap::from([("ar", "مقاطعة راتنابورا"), ("bn", "র\u{9be}তন\u{9be}প\u{9c1}র\u{9be} জেল\u{9be}"), ("ca", "Ratnapura"), ("ccp", "𑄢𑄖\u{11134}𑄚\u{11127}𑄛\u{1112a}𑄢\u{11134}"), ("ceb", "Ratnapura District"), ("da", "Ratnapura district"), ("de", "Ratnapura (Distrikt)"), ("el", "Ρατναπούρα"), ("en", "Ratnapura"), ("es", "Distrito de Ratnapura"), ("fa", "ناحیه راتناپورا"), ("fi", "Ratnapuran piirikunta"), ("fr", "Ratnapura"), ("gu", "રત\u{acd}નાપ\u{ac1}રા જિલ\u{acd}લો"), ("hi", "रत\u{94d}नप\u{941}र जिला"), ("id", "Distrik Ratnapura"), ("it", "Distretto di Ratnapura"), ("ja", "ラトゥナプラ県"), ("ka", "რატნაპურის ოლქი"), ("kn", "ರತ\u{ccd}ನಾಪುರ ಜ\u{cbf}ಲ\u{ccd}ಲ\u{cc6}"), ("ko", "라트나푸라 구"), ("lt", "Ratnapuros apskritis"), ("lv", "Ratnapura distrikts"), ("ml", "രത\u{d4d}നപ\u{d41}ര ജില\u{d4d}ല"), ("mr", "रत\u{94d}नप\u{941}रा जिल\u{94d}हा"), ("ms", "Ratnapura district"), ("nb", "Ratnapura distrikt"), ("nl", "Ratnapura (district)"), ("no", "Ratnapura distrikt"), ("pl", "Dystrykt Ratnapura"), ("pt", "Distrito de Ratnapura"), ("ru", "Ратнапура"), ("si", "රත\u{dca}නප\u{dd4}ර ද\u{dd2}ස\u{dca}ත\u{dca} ර\u{dd2}ක\u{dca}කය"), ("sv", "Ratnapura"), ("ta", "இரத\u{bcd}தினபுரி ம\u{bbe}வட\u{bcd}டம\u{bcd}"), ("te", "రత\u{c4d}నపుర జ\u{c3f}ల\u{c4d}ల\u{c3e}"), ("th", "เขตร\u{e31}ทนาป\u{e38}ระ"), ("tr", "Ratnapura District"), ("uk", "Ратнапура"), ("ur", "رتناپورہ ضلع"), ("vi", "Quận Ratnapura"), ("zh", "拉特納普勒區")]),
                        unofficial_name_list: ["Ratnapūraya"].to_vec(),
                    }
                ),
                (
                    "92",
                    Subdivision{
                        name: "Kegalla",
                        country_alpha2: Alpha2::LK,
                        code: "92",
                        #[cfg(feature = "geo")]
                        geo: Some(SubdivisionGeo{latitude: Some(7.251331700000001), longitude: Some(80.3463754), max_latitude: Some(7.264479499999999), min_latitude: Some(7.242469799999999), max_longitude: Some(80.3595828), min_longitude: Some(80.3318596)}),
                        comments: None,
                        subdivision_type: SubdivisionType::District,
                        #[cfg(feature = "translations")]
                        translations: HashMap::from([("ar", "مقاطعة كيغال"), ("bn", "কেগ\u{9be}লে জেল\u{9be}"), ("ccp", "𑄇\u{11128}𑄉𑄣\u{11128}"), ("ceb", "Kegalle District"), ("da", "Kegalle District"), ("de", "Kegalle (Distrikt)"), ("el", "Κεγκάλε"), ("en", "Kegalle"), ("es", "Distrito de Kegalle"), ("fa", "ناحیه کگاله"), ("fi", "Kegallen piirikunta"), ("fr", "Kegalle"), ("gu", "ક\u{ac7}ગલ\u{ac7} જિલ\u{acd}લો"), ("hi", "क\u{93c}\u{947}गल जिला"), ("id", "Distrik Kegalle"), ("it", "Distretto di Kegalle"), ("ja", "ケーガッラ県"), ("ka", "კეგალეს ოლქი"), ("kn", "ಕ\u{cc7}ಗಲ\u{ccd} ಜ\u{cbf}ಲ\u{ccd}ಲ\u{cc6}"), ("ko", "케갈레 구"), ("lt", "Kegaės apskritis"), ("lv", "Kegalle distrikts"), ("ml", "കെഗല\u{d4d}ലെ ജില\u{d4d}ല"), ("mr", "क\u{947}गल\u{94d}ल\u{947} जिल\u{94d}हा"), ("ms", "Kegalle District"), ("nb", "Kegalle distrikt"), ("nl", "Kegalle (district)"), ("no", "Kegalle distrikt"), ("pl", "Dystrykt Kegalle"), ("pt", "Distrito de Kegalle"), ("ru", "Кегалле"), ("si", "කෑගල\u{dca}ල පර\u{dd2}ප\u{dcf}ලන ද\u{dd2}ස\u{dca}ත\u{dca}\u{200d}ර\u{dd2}ක\u{dca}කය"), ("sv", "Kegalle (distrikt)"), ("ta", "கேக\u{bbe}லை ம\u{bbe}வட\u{bcd}டம\u{bcd}"), ("te", "క\u{c46}గ\u{c3e}ల\u{c46} జ\u{c3f}ల\u{c4d}ల\u{c3e}"), ("th", "เคเกลเล\u{e48}"), ("tr", "Kegalle District"), ("uk", "Кегалле"), ("ur", "کاگال ضلع"), ("vi", "Quận Kegalle"), ("zh", "凱格勒區")]),
                        unofficial_name_list: ["Kegalle"].to_vec(),
                    }
                ),
            ]

        )
    }
}
#[allow(unused_imports)]
use crate::{
    Alpha2, Alpha3, Continent, Country, CurrencyCode, DistanceUnit, Region, SubRegion, VatRates,
    WeekDay, WorldRegion, GEC, IOC,
};
#[allow(unused_imports)]
use std::collections::HashMap;
#[cfg(feature = "lk")]
/// [`Country`](crate::Country) struct for this country.
pub fn new() -> Country {
    Country {
        alpha2: Alpha2::LK,
        alpha3: Alpha3::LKA,
        address_format: None,
        continent: Continent::Asia,
        country_code: 94,
        currency_code: CurrencyCode::LKR,
        maybe_gec: Some(GEC::CE),
        #[cfg(feature = "geo")]
        geo: geo::new(),
        maybe_international_prefix: Some("00"),
        maybe_ioc: Some(IOC::SRI),
        iso_long_name: "The Democratic Socialist Republic of Sri Lanka",
        iso_short_name: "Sri Lanka",
        maybe_official_language_list: Some(["si", "ta"].to_vec()),
        maybe_spoken_language_list: Some(["si", "ta"].to_vec()),
        maybe_national_destination_code_length_list: Some([2].to_vec()),
        maybe_national_number_length_list: Some([10].to_vec()),
        maybe_national_prefix: Some("0"),
        maybe_nationality: Some("Sri Lankan"),
        maybe_nanp_prefix: None,
        number: "144",
        postal_code: true,
        postal_code_format: Some("\\d{5}"),
        maybe_region: Some(Region::Asia),
        start_of_week: WeekDay::Monday,
        maybe_subregion: Some(SubRegion::SouthernAsia),
        un_locode: "LK",
        un_member: true,
        unofficial_name_list: ["Sri Lanka", "スリランカ"].to_vec(),
        maybe_vehicle_registration_code: Some("CL"),
        world_region: WorldRegion::APAC,
        #[cfg(feature = "emojis")]
        emoji: "🇱🇰",
        #[cfg(feature = "translations")]
        translations: HashMap::from([
            ("ab", "Sri Lanka"),
            ("af", "Sri Lanka"),
            ("ak", "Sri Lanka"),
            ("am", "ሽሪ ላንካ"),
            ("an", "Sri Lanka"),
            ("ar", "سريلانكا"),
            ("as", "শ\u{9cd}ৰীলঙ\u{9cd}ক\u{9be}"),
            ("ay", "Sri Lanka"),
            ("az", "Şri Lanka"),
            ("ba", "Sri Lanka"),
            ("be", "Шры-Ланка"),
            ("bg", "Шри Ланка"),
            ("bi", "Sri Lanka"),
            ("bn", "শ\u{9cd}রীলঙ\u{9cd}ক\u{9be}"),
            ("bn_IN", "শ\u{9cd}রীলঙ\u{9cd}ক\u{9be}"),
            ("br", "Sri Lanka"),
            ("bs", "Šri Lanka"),
            ("ca", "Sri Lanka"),
            ("ce", "Шри-Ланка"),
            ("ch", "Sri Lanka"),
            ("cs", "Šrí Lanka"),
            ("cv", "Шри-Ланка"),
            ("cy", "Sri Lanka"),
            ("da", "Sri Lanka"),
            ("de", "Sri Lanka"),
            ("dv", "އ\u{7ae}ޅ\u{7aa}ދ\u{7ab}ކ\u{7a6}ރ\u{7a6}"),
            ("dz", "ས\u{f72}་ར\u{f72}་ལང་ཀ།(ཤ\u{fb2}\u{f72}་ལང\u{f90}་)"),
            ("ee", "Sri Lanka"),
            ("el", "Σρι Λάνκα"),
            ("en", "Sri Lanka"),
            ("eo", "Sri-Lanko"),
            ("es", "Sri Lanka"),
            ("et", "Sri Lanka"),
            ("eu", "Sri Lanka"),
            ("fa", "سری\u{200c}لانکا"),
            ("ff", "Sri Lanka"),
            ("fi", "Sri Lanka"),
            ("fo", "Sri Lanka"),
            ("fr", "Sri Lanka"),
            ("fy", "Sry Lanka"),
            ("ga", "Srí Lanca"),
            ("gl", "Sri Lanka"),
            ("gn", "Sri Lanka"),
            ("gu", "શ\u{acd}રી લ\u{a82}કા"),
            ("gv", "Sri Lanka"),
            ("ha", "Sri Lanka"),
            ("he", "סרי לנקה"),
            ("hi", "श\u{94d}रील\u{902}का"),
            ("hr", "Šri Lanka"),
            ("ht", "Srilanka"),
            ("hu", "Srí Lanka"),
            ("hy", "Շրի Լանկա"),
            ("ia", "Sri Lanka"),
            ("id", "Sri Lanka"),
            ("io", "Sri-Lanka"),
            ("is", "Srí Lanka"),
            ("it", "Sri Lanka"),
            ("iu", "Sri Lanka"),
            ("ja", "スリランカ"),
            ("ka", "შრი-ლანკა"),
            ("ki", "Sri Lanka"),
            ("kk", "Шри-Ланка"),
            ("kl", "Sri Lanka"),
            ("km", "ស\u{17d2}រ\u{17b8}លង\u{17d2}កា"),
            ("kn", "ಶ\u{ccd}ರ\u{cc0}ಲಂಕಾ"),
            ("ko", "스리랑카"),
            ("ku", "Srî Lanka"),
            ("kv", "Шри-Ланка"),
            ("kw", "Shri Lanka"),
            ("ky", "Шри-Ланка"),
            ("lo", "ປະເທດສ\u{eb5}ລ\u{eb1}ງກາ"),
            ("lt", "Šri Lanka"),
            ("lv", "Šrilanka"),
            ("mi", "Hiri Rānaka"),
            ("mk", "Шри Ланка"),
            ("ml", "ശ\u{d4d}രീലങ\u{d4d}ക"),
            ("mn", "Шри Ланка"),
            ("mr", "श\u{94d}री ल\u{902}का"),
            ("ms", "Sri Lanka"),
            ("mt", "Sri Lanka"),
            (
                "my",
                "သ\u{102e}ရ\u{102d}လင\u{103a}\u{1039}ကာန\u{102d}\u{102f}င\u{103a}င\u{1036}",
            ),
            ("na", "Sri Lanka"),
            ("nb", "Sri Lanka"),
            ("ne", "श\u{94d}री लङ\u{94d}का"),
            ("nl", "Sri Lanka"),
            ("nn", "Sri Lanka"),
            ("nv", "Naakaii Dootłʼizhí Bikéyah Dah Naaʼeełígíí"),
            ("oc", "Sri Lanka"),
            ("or", "ଶ\u{b4d}ରୀଲଙ\u{b4d}କ\u{b3e}"),
            ("pa", "ਸ\u{a4d}ਰੀਲ\u{a70}ਕਾ"),
            ("pi", "श\u{94d}रीलङ\u{94d}का"),
            ("pl", "Sri Lanka"),
            ("ps", "سریلانکا"),
            ("pt", "Sri Lanka"),
            ("pt_BR", "Sri Lanka"),
            ("ro", "Sri Lanka"),
            ("ru", "Шри-Ланка"),
            ("rw", "Siri Lanka"),
            ("sc", "Sri Lanka"),
            ("sd", "سريلنڪا"),
            ("si", "ශ\u{dca}\u{200d}ර\u{dd3} ලංක\u{dcf}ව"),
            ("sk", "Srí Lanka"),
            ("sl", "Šrilanka"),
            ("so", "Siirilaanka"),
            ("sq", "Sri Lankë"),
            ("sr", "Шри Ланка"),
            ("sv", "Sri Lanka"),
            ("sw", "Sri Lanka"),
            ("ta", "இலங\u{bcd}கை"),
            ("te", "శ\u{c4d}ర\u{c40}లంక"),
            ("tg", "Князигарии Лихтенштейн"),
            ("th", "ศร\u{e35}ล\u{e31}งกา"),
            ("ti", "ስሪ ላንካ"),
            ("tk", "Şri-Lanka"),
            ("tl", "Sri Lanka"),
            ("tr", "Sri Lanka"),
            ("tt", "Шри Ланка"),
            ("ug", "سىرىلانكا"),
            ("uk", "Шрі-Ланка"),
            ("ur", "سری لنکا"),
            ("uz", "Shri-Lanka"),
            ("ve", "Sri Lanka"),
            ("vi", "Tích Lan"),
            ("wa", "Sri Lanka"),
            ("wo", "Siri Laaŋka"),
            ("xh", "Sri Lanka"),
            ("yo", "Sri Lanka"),
            ("zh_CN", "斯里兰卡"),
            ("zh_HK", "斯里蘭卡"),
            ("zh_TW", "斯里蘭卡"),
            ("zu", "Sri Lanka"),
        ]),
        #[cfg(feature = "subdivisions")]
        subdivisions: subdivisions::new(),
        g7_member: false,
        g20_member: false,
        eu_member: false,
        eea_member: false,
        maybe_vat_rates: None,
        distance_unit: DistanceUnit::Km,
        maybe_population: Some(22181000),
    }
}
