// DO NOT TOUCH THIS FILE. (Auto-generated via `code_gen/countries.rs`)

// The Republic of Madagascar

#[cfg(all(feature = "mg", feature = "constants"))]
pub mod consts {
    #[allow(unused_imports)]
    use crate::{
        Alpha2, Alpha3, Continent, CurrencyCode, Region, SubRegion, WeekDay, WorldRegion, GEC, IOC,
    };

    pub const ADDRESS_FORMAT: Option<&str> = None;
    pub const ALPHA2: Alpha2 = Alpha2::MG;
    pub const ALPHA3: Alpha3 = Alpha3::MDG;
    pub const CONTINENT: Continent = Continent::Africa;
    pub const COUNTRY_CODE: usize = 261;
    pub const CURRENCY_CODE: CurrencyCode = CurrencyCode::MGA;
    pub const GEC: Option<GEC> = Some(GEC::MA);
    pub const INTERNATIONAL_PREFIX: &str = "00";
    pub const IOC: Option<IOC> = Some(IOC::MAD);
    pub const ISO_SHORT_NAME: &str = "Madagascar";
    pub const ISO_LONG_NAME: &str = "The Republic of Madagascar";
    pub const OFFICIAL_LANGUAGE_LIST: &[&str] = &["fr", "mg"];
    pub const SPOKEN_LANGUAGE_LIST: &[&str] = &["fr", "mg"];
    pub const NATIONAL_DESTINATION_CODE_LENGTH_LIST: &[usize] = &[2];
    pub const NATIONAL_NUMBER_LENGTH_LIST: &[usize] = &[9];
    pub const NATIONAL_PREFIX: &str = "None";
    pub const NATIONALITY: Option<&str> = Some("Malagasy");
    pub const NUMBER: &str = "450";
    pub const POSTAL_CODE: bool = true;
    pub const POSTAL_CODE_FORMAT: Option<&str> = Some("\\d{3}");
    pub const REGION: Option<Region> = Some(Region::Africa);
    pub const START_DAY_OF_WEEK: WeekDay = WeekDay::Monday;
    pub const SUBREGION: Option<SubRegion> = Some(SubRegion::EasternAfrica);
    pub const UN_LOCODE: &str = "MG";
    pub const UNOFFICIAL_NAME_LIST: &[&str] = &[
        "Madagascar",
        "Madagaskar",
        "the Republic of Madagascar",
        "マダガスカル",
    ];
    pub const WORLD_REGION: WorldRegion = WorldRegion::EMEA;
    #[cfg(feature = "translations")]
    pub const TRANSLATIONS: &[(&str, &str)] = &[
        ("ab", "Madagascar"),
        ("af", "Madagaskar"),
        ("ak", "Madagascar"),
        ("am", "ማዳጋስካር"),
        ("an", "Madagascar"),
        ("ar", "مدغشقر"),
        ("as", "ম\u{9be}ড\u{9be}গ\u{9be}স\u{9cd}ক\u{9be}ৰ"),
        ("ay", "Madagascar"),
        ("az", "Madaqaskar"),
        ("ba", "Madagascar"),
        ("be", "Мадагаскар"),
        ("bg", "Мадагаскар"),
        ("bi", "Madagascar"),
        ("bn", "ম\u{9be}দ\u{9be}গ\u{9be}স\u{9cd}ক\u{9be}র"),
        ("bn_IN", "ম\u{9be}দ\u{9be}গ\u{9be}স\u{9cd}ক\u{9be}র"),
        ("br", "Madagaskar"),
        ("bs", "Madagaskar"),
        ("ca", "Madagascar"),
        ("ce", "Мадагаскар"),
        ("ch", "Madagascar"),
        ("cs", "Madagaskar"),
        ("cv", "Мадагаскар"),
        ("cy", "Madagascar"),
        ("da", "Madagaskar"),
        ("de", "Madagaskar"),
        ("dv", "މ\u{7a6}ޑ\u{7a6}ގ\u{7a6}ސ\u{7b0}ކ\u{7a6}ރ\u{7a6}"),
        ("dz", "མ་ད་ག\u{f71}ས\u{f72}་ཀར།"),
        ("ee", "Madagascar"),
        ("el", "Μαδαγασκάρη"),
        ("en", "Madagascar"),
        ("eo", "Madagaskaro"),
        ("es", "Madagascar"),
        ("et", "Madagaskar"),
        ("eu", "Madagaskar"),
        ("fa", "ماداگاسکار"),
        ("ff", "Madagascar"),
        ("fi", "Madagaskar"),
        ("fo", "Madagaskar"),
        ("fr", "Madagascar"),
        ("fy", "Madagaskar"),
        ("ga", "Madagascar"),
        ("gl", "Madagascar"),
        ("gn", "Madagascar"),
        ("gu", "માડાગાસ\u{acd}કર"),
        ("gv", "Madagascar"),
        ("ha", "Madagascar"),
        ("he", "מדגסקר"),
        ("hi", "म\u{947}डागास\u{94d}कर"),
        ("hr", "Madagaskar"),
        ("ht", "Madagaskar"),
        ("hu", "Madagaszkár"),
        ("hy", "Մադագասկար"),
        ("ia", "Madagascar"),
        ("id", "Madagaskar"),
        ("io", "Madagaskar"),
        ("is", "Madagaskar"),
        ("it", "Madagascar"),
        ("iu", "Madagascar"),
        ("ja", "マダガスカル"),
        ("ka", "მადაგასკარი"),
        ("ki", "Madagascar"),
        ("kk", "Мадагаскар"),
        ("kl", "Madagascar"),
        ("km", "ម\u{17c9}ាដាហ\u{17d2}គាស\u{17d2}ការ"),
        ("kn", "ಮಡಗಾಸ\u{ccd}ಕರ\u{ccd}"),
        ("ko", "마다가스카르"),
        ("ku", "Madagaskar"),
        ("kv", "Madagascar"),
        ("kw", "Madagaskar"),
        ("ky", "Мадагаскар Республикасы"),
        ("lo", "Madagascar"),
        ("lt", "Madagaskaras"),
        ("lv", "Madagaskara"),
        ("mi", "Marakāhia"),
        ("mk", "Мадагаскар"),
        ("ml", "മഡഗ\u{d3e}സ\u{d4d}കര\u{d4d}\u{200d}"),
        ("mn", "Мадагаскар"),
        ("mr", "मादागास\u{94d}कर"),
        ("ms", "Madagaskar"),
        ("mt", "Madagaskar"),
        ("my", "မဒါဂတ\u{103a}စကားန\u{102d}\u{102f}င\u{103a}င\u{1036}"),
        ("na", "Madagascar"),
        ("nb", "Madagaskar"),
        ("ne", "मदगास\u{94d}कार"),
        ("nl", "Madagaskar"),
        ("nn", "Madagaskar"),
        ("nv", "Mágí Bitseeʼ Noodǫ\u{301}zí Bikéyah"),
        ("oc", "Madagascar"),
        ("or", "ମ\u{b3e}ଡ\u{b3e}ଗ\u{b3e}ସ\u{b4d}କ\u{b3e}ର"),
        ("pa", "ਮ\u{a48}ਡਾਗਾਸਕਰ"),
        ("pi", "मडगास\u{94d}कर"),
        ("pl", "Madagaskar"),
        ("ps", "مادغاسکر"),
        ("pt", "Madagáscar"),
        ("pt_BR", "Madagascar"),
        ("ro", "Madagascar"),
        ("ru", "Мадагаскар"),
        ("rw", "Madagasikari"),
        ("sc", "Madagascàr"),
        ("sd", "Madagascar"),
        ("si", "මැඩගස\u{dca}කරය"),
        ("sk", "Madagaskar"),
        ("sl", "Madagaskar"),
        ("so", "Madagaskar"),
        ("sq", "Madagaskar"),
        ("sr", "Мадагаскар"),
        ("sv", "Madagaskar"),
        ("sw", "Madagascar"),
        ("ta", "மடக\u{bbe}ஸ\u{bcd}கர\u{bcd}"),
        ("te", "మడగ\u{c3e}స\u{c4d}కర\u{c4d}"),
        ("tg", "Мадагаскар"),
        ("th", "มาดาก\u{e31}สการ\u{e4c}"),
        ("ti", "ማዳጋስካር"),
        ("tk", "Madagaskar"),
        ("tl", "Madagascar"),
        ("tr", "Madagaskar"),
        ("tt", "Мадаgаскар"),
        ("ug", "ماداغاسقار"),
        ("uk", "Мадагаскар"),
        ("ur", "مڈغاسکر"),
        ("uz", "Madagaskar"),
        ("ve", "Madagascar"),
        ("vi", "Ma-đa-ga-xợ-ca"),
        ("wa", "Madagascar"),
        ("wo", "Madagaskar"),
        ("xh", "Madagascar"),
        ("yo", "Madagáskàr"),
        ("zh_CN", "马达加斯加"),
        ("zh_HK", "馬達加斯加"),
        ("zh_TW", "馬達加斯加"),
        ("zu", "IMadagasika"),
    ];
    #[cfg(all(feature = "mg", feature = "geo", feature = "constants"))]
    pub mod geo {
        pub const LATITUDE: f64 = -18.766947;
        pub const LONGITUDE: f64 = 46.869107;
        pub const MAX_LATITUDE: f64 = -11.4369999;
        pub const MAX_LONGITUDE: f64 = 50.9985001;
        pub const MIN_LATITUDE: f64 = -26.2146;
        pub const MIN_LONGITUDE: f64 = 42.7368;
        pub const NORTHEAST_LATITUDE: f64 = -11.4369999;
        pub const NORTHEAST_LONGITUDE: f64 = 50.9985001;
        pub const SOUTHWEST_LATITUDE: f64 = -26.2146;
        pub const SOUTHWEST_LONGITUDE: f64 = 42.7368;
    }
}
#[cfg(all(feature = "mg", feature = "geo"))]
pub mod geo {
    use crate::{CountryGeo, CountryGeoBound, CountryGeoBounds};

    pub fn new() -> CountryGeo {
        CountryGeo {
            latitude: -18.766947,
            longitude: 46.869107,
            max_latitude: -11.4369999,
            max_longitude: 50.9985001,
            min_latitude: -26.2146,
            min_longitude: 42.7368,
            bounds: CountryGeoBounds {
                northeast: CountryGeoBound {
                    latitude: -11.4369999,
                    longitude: 50.9985001,
                },
                southwest: CountryGeoBound {
                    latitude: -26.2146,
                    longitude: 42.7368,
                },
            },
        }
    }
}

#[cfg(all(feature = "mg", feature = "subdivisions"))]
pub mod subdivisions {
    #[allow(unused_imports)]
    use crate::{Alpha2, Subdivision, SubdivisionType};
    use std::collections::HashMap;
    // In this state, We do not know if subdivisions have geo or not!
    #[cfg(feature = "geo")]
    #[allow(unused_imports)]
    use crate::SubdivisionGeo;

    pub fn new() -> HashMap<&'static str, Subdivision> {
        HashMap::from([
            (
                "A",
                Subdivision {
                    name: "Toamasina",
                    country_alpha2: Alpha2::MG,
                    code: "A",
                    #[cfg(feature = "geo")]
                    geo: Some(SubdivisionGeo {
                        latitude: Some(-18.15),
                        longitude: Some(49.416667),
                        max_latitude: Some(-18.0708419),
                        min_latitude: Some(-18.1902246),
                        max_longitude: Some(49.4305587),
                        min_longitude: Some(49.3536083),
                    }),
                    comments: None,
                    subdivision_type: SubdivisionType::Province,
                    #[cfg(feature = "translations")]
                    translations: HashMap::from([
                        ("ar", "مقاطعة تواماسينا"),
                        ("bg", "Тоамасина"),
                        ("ca", "Província de Toamasina"),
                        ("ccp", "𑄑\u{1112e}𑄟𑄥\u{11128}𑄚"),
                        ("da", "Toamasina-provinsen"),
                        ("de", "Toamasina"),
                        ("el", "Επαρχία Τοαμασίνα"),
                        ("en", "Toamasina"),
                        ("es", "Provincia de Toamasina"),
                        ("et", "Toamasina provints"),
                        ("fa", "تواماسینا"),
                        ("fr", "province de Tamatave"),
                        ("id", "Provinsi Toamasina"),
                        ("it", "provincia di Toamasina"),
                        ("ja", "トアマシナ州"),
                        ("ka", "ტუამასინის პროვინცია"),
                        ("ko", "토아마시나 주"),
                        ("nb", "Toamasina"),
                        ("nl", "Toamasina"),
                        ("no", "Toamasina"),
                        ("pl", "Prowincja Toamasina"),
                        ("pt", "Toamasina"),
                        ("ru", "Туамасина"),
                        ("sv", "Toamasina"),
                        ("uk", "Туамасіна"),
                        ("ur", "تواماسینا صوبہ"),
                        ("uz", "Tuamasina"),
                        ("yue", "圖阿馬西納省"),
                        ("yue_Hans", "图阿马西纳省"),
                        ("zh", "圖阿馬西納省"),
                    ]),
                    unofficial_name_list: ["Tamatave"].to_vec(),
                },
            ),
            (
                "D",
                Subdivision {
                    name: "Antsiranana",
                    country_alpha2: Alpha2::MG,
                    code: "D",
                    #[cfg(feature = "geo")]
                    geo: Some(SubdivisionGeo {
                        latitude: Some(-12.3231349),
                        longitude: Some(49.2942833),
                        max_latitude: Some(-12.2668974),
                        min_latitude: Some(-12.3658257),
                        max_longitude: Some(49.3142177),
                        min_longitude: Some(49.2734241),
                    }),
                    comments: None,
                    subdivision_type: SubdivisionType::Province,
                    #[cfg(feature = "translations")]
                    translations: HashMap::from([
                        ("ar", "مقاطعة أنتسيرانانا"),
                        ("bg", "Антсиранана"),
                        ("ca", "Província d’Antsiranana"),
                        ("ccp", "𑄃𑄚\u{11134}𑄑\u{11134}𑄥\u{11128}𑄢𑄚𑄚\u{11134}"),
                        ("da", "Antsiranana-provinsen"),
                        ("de", "Antsiranana"),
                        ("el", "Επαρχία Αντσιρανάνα"),
                        ("en", "Antsiranana"),
                        ("es", "Provincia de Antsiranana"),
                        ("et", "Antsiranana provints"),
                        ("fa", "آنسیرانانا"),
                        ("fr", "province de Diego-Suarez"),
                        ("id", "Provinsi Antsiranana"),
                        ("it", "provincia di Antsiranana"),
                        ("ja", "アンツィラナナ州"),
                        ("ka", "ანცირანანის პროვინცია"),
                        ("ko", "안치라나나 주"),
                        ("lt", "Ancerananos provincija"),
                        ("nb", "Antsiranana"),
                        ("nl", "Antsiranana"),
                        ("no", "Antsiranana"),
                        ("pl", "Prowincja Antsiranana"),
                        ("pt", "Antsiranana"),
                        ("ru", "Анциранана"),
                        ("sv", "Antsiranana"),
                        (
                            "ta",
                            "அண\u{bcd}ட\u{bcd}சிரனன\u{bbe} ம\u{bbe}க\u{bbe}ணம\u{bcd}",
                        ),
                        ("uk", "Анціранана (провінція)"),
                        ("ur", "انتسیرانانا صوبہ"),
                        ("uz", "Antsiranana"),
                        ("vi", "Antsiranana"),
                        ("zh", "安齊拉納納省"),
                    ]),
                    unofficial_name_list: ["Antseranana", "Diégo Suarez"].to_vec(),
                },
            ),
            (
                "F",
                Subdivision {
                    name: "Fianarantsoa",
                    country_alpha2: Alpha2::MG,
                    code: "F",
                    #[cfg(feature = "geo")]
                    geo: Some(SubdivisionGeo {
                        latitude: Some(-21.453611),
                        longitude: Some(47.085833),
                        max_latitude: Some(-21.4065204),
                        min_latitude: Some(-21.4888523),
                        max_longitude: Some(47.1303177),
                        min_longitude: Some(47.04122539999999),
                    }),
                    comments: None,
                    subdivision_type: SubdivisionType::Province,
                    #[cfg(feature = "translations")]
                    translations: HashMap::from([
                        ("ar", "مقاطعة فيانارانتسوا"),
                        ("bg", "Фианарантсоа"),
                        ("ca", "Província de Fianarantsoa"),
                        ("ccp", "𑄜\u{11128}𑄠𑄚𑄢𑄚𑄚\u{11134}𑄑\u{11134}𑄥\u{1112e}𑄠"),
                        ("da", "Fianarantsoa-provinsen"),
                        ("de", "Fianarantsoa"),
                        ("el", "Επαρχία Φιαναραντσόα"),
                        ("en", "Fianarantsoa"),
                        ("es", "Provincia de Fianarantsoa"),
                        ("et", "Fianarantsoa provints"),
                        ("fa", "فیانارانسوا"),
                        ("fr", "province de Fianarantsoa"),
                        ("he", "מחוז פיאנארנצוה"),
                        ("id", "Provinsi Fianarantsoa"),
                        ("it", "provincia di Fianarantsoa"),
                        ("ja", "フィアナランツァ州"),
                        ("ka", "ფიანარანცუის პროვინცია"),
                        ("ko", "피아나란초아 주"),
                        ("nb", "Fianarantsoa"),
                        ("nl", "Fianarantsoa"),
                        ("no", "Fianarantsoa"),
                        ("pl", "Prowincja Fianarantsoa"),
                        ("pt", "Fianarantsoa"),
                        ("ru", "Фианаранцуа"),
                        ("sv", "Fianarantsoa"),
                        ("uk", "Фіанаранцуа"),
                        ("ur", "فیانارانتسوا صوبہ"),
                        ("uz", "Fianarantsua"),
                        ("zh", "菲亞納蘭楚阿省"),
                    ]),
                    unofficial_name_list: ["Fianar"].to_vec(),
                },
            ),
            (
                "M",
                Subdivision {
                    name: "Mahajanga",
                    country_alpha2: Alpha2::MG,
                    code: "M",
                    #[cfg(feature = "geo")]
                    geo: Some(SubdivisionGeo {
                        latitude: Some(-15.716667),
                        longitude: Some(46.316667),
                        max_latitude: Some(-15.6463868),
                        min_latitude: Some(-15.7284058),
                        max_longitude: Some(46.3819599),
                        min_longitude: Some(46.294654),
                    }),
                    comments: None,
                    subdivision_type: SubdivisionType::Province,
                    #[cfg(feature = "translations")]
                    translations: HashMap::from([
                        ("ar", "مقاطعة ماهاجانجا"),
                        ("bg", "Махаджанга"),
                        ("ca", "Província de Mahajanga"),
                        ("ccp", "𑄟𑄦\u{11134}𑄎𑄚\u{11134}𑄉"),
                        ("da", "Mahajanga-provinsen"),
                        ("de", "Mahajanga"),
                        ("el", "Επαρχία Μαχατζάνγκα"),
                        ("en", "Mahajanga"),
                        ("es", "Provincia de Mahajanga"),
                        ("fa", "ماهاجانگا"),
                        ("fr", "province de Majunga"),
                        ("he", "מחוז מאהאז׳אנגה"),
                        ("id", "Provinsi Mahajanga"),
                        ("it", "provincia di Mahajanga"),
                        ("ja", "マジュンガ州"),
                        ("ka", "მაჰაძანგის პროვინცია"),
                        ("ko", "마하장가 주"),
                        ("nb", "Mahajanga"),
                        ("nl", "Mahajanga"),
                        ("no", "Mahajanga"),
                        ("pl", "Prowincja Mahajanga"),
                        ("pt", "Mahajanga"),
                        ("ru", "Махадзанга"),
                        ("sv", "Mahajanga"),
                        ("uk", "Махадзанга (провінція)"),
                        ("ur", "ماہاجانگا صوبہ"),
                        ("uz", "Maxadzanga"),
                        ("vi", "Mahajanga"),
                        ("yue", "馬哈贊加省"),
                        ("yue_Hans", "马哈赞加省"),
                        ("zh", "馬哈贊加省"),
                    ]),
                    unofficial_name_list: ["Majunga"].to_vec(),
                },
            ),
            (
                "T",
                Subdivision {
                    name: "Antananarivo",
                    country_alpha2: Alpha2::MG,
                    code: "T",
                    #[cfg(feature = "geo")]
                    geo: Some(SubdivisionGeo {
                        latitude: Some(-18.933333),
                        longitude: Some(47.516667),
                        max_latitude: Some(-18.747587),
                        min_latitude: Some(-19.0278715),
                        max_longitude: Some(47.60607719999999),
                        min_longitude: Some(47.4191379),
                    }),
                    comments: None,
                    subdivision_type: SubdivisionType::Province,
                    #[cfg(feature = "translations")]
                    translations: HashMap::from([
                        ("ar", "مقاطعة فيانارانتسوا²"),
                        ("be", "правінцыя Антананарыву"),
                        ("bg", "Антананариво"),
                        ("ca", "Província d’Antananarivo"),
                        ("ccp", "𑄃𑄚\u{11134}𑄑𑄚𑄚𑄢\u{11128}𑄞\u{1112e}"),
                        ("ceb", "Antananarivo Province"),
                        ("da", "Antananarivo-provinsen"),
                        ("de", "Antananarivo"),
                        ("el", "Επαρχία Ανταναναρίβο"),
                        ("en", "Antananarivo"),
                        ("es", "Provincia de Antananarivo"),
                        ("et", "Antananarivo provints"),
                        ("fa", "آنتاناناریوو"),
                        ("fi", "Antananarivon provinssi"),
                        ("fr", "province d’Antananarivo"),
                        ("gl", "Provincia de Antananarivo"),
                        ("hu", "Antananarivo megye"),
                        ("id", "Provinsi Antananarivo"),
                        ("it", "provincia di Antananarivo"),
                        ("ja", "アンタナナリボ州"),
                        ("ka", "ანტანანარივუს პროვინცია"),
                        ("ko", "안타나나리보 주"),
                        ("lt", "Antananaryvo provincija"),
                        ("ms", "Wilayah Antananarivo"),
                        ("nb", "Antananarivo"),
                        ("nl", "Antananarivo"),
                        ("no", "Antananarivo"),
                        ("pl", "Prowincja Antananarywa"),
                        ("pt", "Antananarivo"),
                        ("ru", "Антананариву"),
                        ("sv", "Antananarivo"),
                        ("uk", "Антананаріву"),
                        ("ur", "انتاناناریوو صوبہ"),
                        ("uz", "Antananarivu"),
                        ("zh", "塔那那利佛省"),
                    ]),
                    unofficial_name_list: ["Tananarive"].to_vec(),
                },
            ),
            (
                "U",
                Subdivision {
                    name: "Toliara",
                    country_alpha2: Alpha2::MG,
                    code: "U",
                    #[cfg(feature = "geo")]
                    geo: Some(SubdivisionGeo {
                        latitude: Some(-23.35),
                        longitude: Some(43.666667),
                        max_latitude: Some(-23.314592),
                        min_latitude: Some(-23.3970146),
                        max_longitude: Some(43.73601439999999),
                        min_longitude: Some(43.6393261),
                    }),
                    comments: None,
                    subdivision_type: SubdivisionType::Province,
                    #[cfg(feature = "translations")]
                    translations: HashMap::from([
                        ("ar", "مقاطعة توليارا"),
                        ("bg", "Толиара"),
                        ("ca", "Província de Toliara"),
                        ("ccp", "𑄑\u{1112e}𑄣\u{11128}𑄠𑄢"),
                        ("ceb", "Toliara Province"),
                        ("de", "Toliara"),
                        ("el", "Επαρχία Τολιάρα"),
                        ("en", "Toliara"),
                        ("es", "Provincia de Toliara"),
                        ("fa", "تولیارا"),
                        ("fr", "province de Toliara"),
                        ("he", "טוליארה"),
                        ("hr", "Provincija Toliara"),
                        ("id", "Provinsi Toliara"),
                        ("it", "provincia di Toliara"),
                        ("ja", "トゥリアラ州"),
                        ("ka", "ტულიარის პროვინცია"),
                        ("ko", "톨리아라 주"),
                        ("nb", "Toliara"),
                        ("nl", "Toliara"),
                        ("no", "Toliara"),
                        ("pl", "Prowincja Toliara"),
                        ("pt", "Toliara"),
                        ("ru", "Тулиара"),
                        ("sr", "Толиара"),
                        ("sr_Latn", "Toliara"),
                        ("sv", "Toliara"),
                        ("uk", "Туліара (провінція)"),
                        ("ur", "تولیارا صوبہ"),
                        ("uz", "Tuliara"),
                        ("zh", "圖利亞拉省"),
                    ]),
                    unofficial_name_list: ["Toliara", "Tuléar"].to_vec(),
                },
            ),
        ])
    }
}
#[allow(unused_imports)]
use crate::{
    Alpha2, Alpha3, Continent, Country, CurrencyCode, Region, SubRegion, WeekDay, WorldRegion, GEC,
    IOC,
};
#[allow(unused_imports)]
use std::collections::HashMap;
#[cfg(feature = "mg")]
pub fn new() -> Country {
    Country {
        alpha2: Alpha2::MG,
        alpha3: Alpha3::MDG,
        address_format: None,
        continent: Continent::Africa,
        country_code: 261,
        currency_code: CurrencyCode::MGA,
        gec: Some(GEC::MA),
        #[cfg(feature = "geo")]
        geo: geo::new(),
        international_prefix: "00",
        ioc: Some(IOC::MAD),
        iso_long_name: "The Republic of Madagascar",
        iso_short_name: "Madagascar",
        official_language_list: ["fr", "mg"].to_vec(),
        spoken_language_list: ["fr", "mg"].to_vec(),
        national_destination_code_length_list: [2].to_vec(),
        national_number_length_list: [9].to_vec(),
        national_prefix: "None",
        nationality: Some("Malagasy"),
        number: "450",
        postal_code: true,
        postal_code_format: Some("\\d{3}"),
        region: Some(Region::Africa),
        start_of_week: WeekDay::Monday,
        subregion: Some(SubRegion::EasternAfrica),
        un_locode: "MG",
        unofficial_name_list: [
            "Madagascar",
            "Madagaskar",
            "the Republic of Madagascar",
            "マダガスカル",
        ]
        .to_vec(),
        world_region: WorldRegion::EMEA,
        #[cfg(feature = "translations")]
        translations: HashMap::from([
            ("ab", "Madagascar"),
            ("af", "Madagaskar"),
            ("ak", "Madagascar"),
            ("am", "ማዳጋስካር"),
            ("an", "Madagascar"),
            ("ar", "مدغشقر"),
            ("as", "ম\u{9be}ড\u{9be}গ\u{9be}স\u{9cd}ক\u{9be}ৰ"),
            ("ay", "Madagascar"),
            ("az", "Madaqaskar"),
            ("ba", "Madagascar"),
            ("be", "Мадагаскар"),
            ("bg", "Мадагаскар"),
            ("bi", "Madagascar"),
            ("bn", "ম\u{9be}দ\u{9be}গ\u{9be}স\u{9cd}ক\u{9be}র"),
            ("bn_IN", "ম\u{9be}দ\u{9be}গ\u{9be}স\u{9cd}ক\u{9be}র"),
            ("br", "Madagaskar"),
            ("bs", "Madagaskar"),
            ("ca", "Madagascar"),
            ("ce", "Мадагаскар"),
            ("ch", "Madagascar"),
            ("cs", "Madagaskar"),
            ("cv", "Мадагаскар"),
            ("cy", "Madagascar"),
            ("da", "Madagaskar"),
            ("de", "Madagaskar"),
            ("dv", "މ\u{7a6}ޑ\u{7a6}ގ\u{7a6}ސ\u{7b0}ކ\u{7a6}ރ\u{7a6}"),
            ("dz", "མ་ད་ག\u{f71}ས\u{f72}་ཀར།"),
            ("ee", "Madagascar"),
            ("el", "Μαδαγασκάρη"),
            ("en", "Madagascar"),
            ("eo", "Madagaskaro"),
            ("es", "Madagascar"),
            ("et", "Madagaskar"),
            ("eu", "Madagaskar"),
            ("fa", "ماداگاسکار"),
            ("ff", "Madagascar"),
            ("fi", "Madagaskar"),
            ("fo", "Madagaskar"),
            ("fr", "Madagascar"),
            ("fy", "Madagaskar"),
            ("ga", "Madagascar"),
            ("gl", "Madagascar"),
            ("gn", "Madagascar"),
            ("gu", "માડાગાસ\u{acd}કર"),
            ("gv", "Madagascar"),
            ("ha", "Madagascar"),
            ("he", "מדגסקר"),
            ("hi", "म\u{947}डागास\u{94d}कर"),
            ("hr", "Madagaskar"),
            ("ht", "Madagaskar"),
            ("hu", "Madagaszkár"),
            ("hy", "Մադագասկար"),
            ("ia", "Madagascar"),
            ("id", "Madagaskar"),
            ("io", "Madagaskar"),
            ("is", "Madagaskar"),
            ("it", "Madagascar"),
            ("iu", "Madagascar"),
            ("ja", "マダガスカル"),
            ("ka", "მადაგასკარი"),
            ("ki", "Madagascar"),
            ("kk", "Мадагаскар"),
            ("kl", "Madagascar"),
            ("km", "ម\u{17c9}ាដាហ\u{17d2}គាស\u{17d2}ការ"),
            ("kn", "ಮಡಗಾಸ\u{ccd}ಕರ\u{ccd}"),
            ("ko", "마다가스카르"),
            ("ku", "Madagaskar"),
            ("kv", "Madagascar"),
            ("kw", "Madagaskar"),
            ("ky", "Мадагаскар Республикасы"),
            ("lo", "Madagascar"),
            ("lt", "Madagaskaras"),
            ("lv", "Madagaskara"),
            ("mi", "Marakāhia"),
            ("mk", "Мадагаскар"),
            ("ml", "മഡഗ\u{d3e}സ\u{d4d}കര\u{d4d}\u{200d}"),
            ("mn", "Мадагаскар"),
            ("mr", "मादागास\u{94d}कर"),
            ("ms", "Madagaskar"),
            ("mt", "Madagaskar"),
            ("my", "မဒါဂတ\u{103a}စကားန\u{102d}\u{102f}င\u{103a}င\u{1036}"),
            ("na", "Madagascar"),
            ("nb", "Madagaskar"),
            ("ne", "मदगास\u{94d}कार"),
            ("nl", "Madagaskar"),
            ("nn", "Madagaskar"),
            ("nv", "Mágí Bitseeʼ Noodǫ\u{301}zí Bikéyah"),
            ("oc", "Madagascar"),
            ("or", "ମ\u{b3e}ଡ\u{b3e}ଗ\u{b3e}ସ\u{b4d}କ\u{b3e}ର"),
            ("pa", "ਮ\u{a48}ਡਾਗਾਸਕਰ"),
            ("pi", "मडगास\u{94d}कर"),
            ("pl", "Madagaskar"),
            ("ps", "مادغاسکر"),
            ("pt", "Madagáscar"),
            ("pt_BR", "Madagascar"),
            ("ro", "Madagascar"),
            ("ru", "Мадагаскар"),
            ("rw", "Madagasikari"),
            ("sc", "Madagascàr"),
            ("sd", "Madagascar"),
            ("si", "මැඩගස\u{dca}කරය"),
            ("sk", "Madagaskar"),
            ("sl", "Madagaskar"),
            ("so", "Madagaskar"),
            ("sq", "Madagaskar"),
            ("sr", "Мадагаскар"),
            ("sv", "Madagaskar"),
            ("sw", "Madagascar"),
            ("ta", "மடக\u{bbe}ஸ\u{bcd}கர\u{bcd}"),
            ("te", "మడగ\u{c3e}స\u{c4d}కర\u{c4d}"),
            ("tg", "Мадагаскар"),
            ("th", "มาดาก\u{e31}สการ\u{e4c}"),
            ("ti", "ማዳጋስካር"),
            ("tk", "Madagaskar"),
            ("tl", "Madagascar"),
            ("tr", "Madagaskar"),
            ("tt", "Мадаgаскар"),
            ("ug", "ماداغاسقار"),
            ("uk", "Мадагаскар"),
            ("ur", "مڈغاسکر"),
            ("uz", "Madagaskar"),
            ("ve", "Madagascar"),
            ("vi", "Ma-đa-ga-xợ-ca"),
            ("wa", "Madagascar"),
            ("wo", "Madagaskar"),
            ("xh", "Madagascar"),
            ("yo", "Madagáskàr"),
            ("zh_CN", "马达加斯加"),
            ("zh_HK", "馬達加斯加"),
            ("zh_TW", "馬達加斯加"),
            ("zu", "IMadagasika"),
        ]),
        #[cfg(feature = "subdivisions")]
        subdivisions: subdivisions::new(),
    }
}
