// DO NOT TOUCH THIS FILE. (Auto-generated via `code_gen/countries.rs`)

// The Republic of Mali

#[cfg(all(feature = "ml", feature = "constants"))]
pub mod consts {
    #[allow(unused_imports)]
    use crate::{Alpha2, Alpha3, Continent, Region, SubRegion, WeekDay, WorldRegion, GEC, IOC};

    pub const ADDRESS_FORMAT: Option<&str> = None;
    pub const ALPHA2: Alpha2 = Alpha2::ML;
    pub const ALPHA3: Alpha3 = Alpha3::MLI;
    pub const CONTINENT: Continent = Continent::Africa;
    pub const COUNTRY_CODE: usize = 223;
    pub const CURRENCY_CODE: &str = "XOF";
    pub const GEC: Option<GEC> = Some(GEC::ML);
    pub const INTERNATIONAL_PREFIX: &str = "00";
    pub const IOC: Option<IOC> = Some(IOC::MLI);
    pub const ISO_SHORT_NAME: &str = "Mali";
    pub const ISO_LONG_NAME: &str = "The Republic of Mali";
    pub const OFFICIAL_LANGUAGE_LIST: &[&str] = &["fr"];
    pub const SPOKEN_LANGUAGE_LIST: &[&str] = &["fr"];
    pub const NATIONAL_DESTINATION_CODE_LENGTH_LIST: &[usize] = &[2];
    pub const NATIONAL_NUMBER_LENGTH_LIST: &[usize] = &[8];
    pub const NATIONAL_PREFIX: &str = "0";
    pub const NATIONALITY: Option<&str> = Some("Malian");
    pub const NUMBER: &str = "466";
    pub const POSTAL_CODE: bool = false;
    pub const POSTAL_CODE_FORMAT: Option<&str> = None;
    pub const REGION: Option<Region> = Some(Region::Africa);
    pub const START_DAY_OF_WEEK: WeekDay = WeekDay::Monday;
    pub const SUBREGION: Option<SubRegion> = Some(SubRegion::WesternAfrica);
    pub const UN_LOCODE: &str = "ML";
    pub const UNOFFICIAL_NAME_LIST: &[&str] = &["Mali", "マリ"];
    pub const WORLD_REGION: WorldRegion = WorldRegion::EMEA;
    #[cfg(feature = "translations")]
    pub const TRANSLATIONS: &[(&str, &str)] = &[
        ("ab", "Mali"),
        ("af", "Mali"),
        ("ak", "Mali"),
        ("am", "ማሊ"),
        ("an", "Mali"),
        ("ar", "مالي"),
        ("as", "ম\u{9be}লি"),
        ("ay", "Mali"),
        ("az", "Mali"),
        ("ba", "Mali"),
        ("be", "Малі"),
        ("bg", "Мали"),
        ("bi", "Mali"),
        ("bn", "ম\u{9be}লি"),
        ("bn_IN", "ম\u{9be}লি"),
        ("br", "Mali"),
        ("bs", "Mali"),
        ("ca", "Mali"),
        ("ce", "Мали"),
        ("ch", "Mali"),
        ("cs", "Mali"),
        ("cv", "Мали"),
        ("cy", "Mali"),
        ("da", "Mali"),
        ("de", "Mali"),
        ("dv", "މ\u{7a7}ލ\u{7a9}"),
        ("dz", "མ་ལ\u{f72}།"),
        ("ee", "Mali"),
        ("el", "Μάλι"),
        ("en", "Mali"),
        ("eo", "Malio"),
        ("es", "Malí"),
        ("et", "Mali"),
        ("eu", "Mali"),
        ("fa", "مالی"),
        ("ff", "Maali"),
        ("fi", "Mali"),
        ("fo", "Mali"),
        ("fr", "Mali"),
        ("fy", "Maly"),
        ("ga", "Mailí"),
        ("gl", "Mali"),
        ("gn", "Mali"),
        ("gu", "માલી"),
        ("gv", "Malee"),
        ("ha", "Mali"),
        ("he", "מאלי"),
        ("hi", "माली"),
        ("hr", "Mali"),
        ("ht", "Mali"),
        ("hu", "Mali"),
        ("hy", "Մալի"),
        ("ia", "Mali"),
        ("id", "Mali"),
        ("io", "Mali"),
        ("is", "Malí"),
        ("it", "Mali"),
        ("iu", "Mali"),
        ("ja", "マリ"),
        ("ka", "მალი"),
        ("ki", "Mali"),
        ("kk", "Мали"),
        ("kl", "Mali"),
        ("km", "ម\u{17c9}ាល\u{17b8}"),
        ("kn", "ಮಾಲ\u{cbf}"),
        ("ko", "말리"),
        ("ku", "Malî"),
        ("kv", "Mali"),
        ("kw", "Mali"),
        ("ky", "Мали"),
        ("lo", "Mali"),
        ("lt", "Malis"),
        ("lv", "Mali"),
        ("mi", "Māri"),
        ("mk", "Мали"),
        ("ml", "മ\u{d3e}ലി"),
        ("mn", "Мали"),
        ("mr", "माली"),
        ("ms", "Mali"),
        ("mt", "Mali"),
        ("my", "မာလ\u{102e}န\u{102d}\u{102f}င\u{103a}င\u{1036}"),
        ("na", "Mali"),
        ("nb", "Mali"),
        ("ne", "माली"),
        ("nl", "Mali"),
        ("nn", "Mali"),
        ("nv", "Mali"),
        ("oc", "Mali"),
        ("or", "ମ\u{b3e}ଲୀ"),
        ("pa", "ਮਾਲੀ"),
        ("pi", "माली"),
        ("pl", "Mali"),
        ("ps", "مالي"),
        ("pt", "Mali"),
        ("pt_BR", "Mali"),
        ("ro", "Mali"),
        ("ru", "Мали"),
        ("rw", "Mali"),
        ("sc", "Mali"),
        ("sd", "Mali"),
        ("si", "ම\u{dcf}ල\u{dd2}"),
        ("sk", "Mali"),
        ("sl", "Mali"),
        ("so", "Maali"),
        ("sq", "Mali"),
        ("sr", "Мали"),
        ("sv", "Mali"),
        ("sw", "Mali"),
        ("ta", "ம\u{bbe}லி"),
        ("te", "माली"),
        ("tg", "Мали"),
        ("th", "มาล\u{e35}"),
        ("ti", "ማሊ"),
        ("tk", "Mali"),
        ("tl", "Mali"),
        ("tr", "Mali"),
        ("tt", "Мали"),
        ("ug", "مالى"),
        ("uk", "Малі"),
        ("ur", "مالی"),
        ("uz", "Mali"),
        ("ve", "Mali"),
        ("vi", "Ma-li"),
        ("wa", "Mali"),
        ("wo", "Mali"),
        ("xh", "Mali"),
        ("yo", "Málì"),
        ("zh_CN", "马里"),
        ("zh_HK", "馬里"),
        ("zh_TW", "馬利"),
        ("zu", "IMali"),
    ];
    #[cfg(all(feature = "ml", feature = "geo", feature = "constants"))]
    pub mod geo {
        pub const LATITUDE: f64 = 17.570692;
        pub const LONGITUDE: f64 = -3.996166;
        pub const MAX_LATITUDE: f64 = 25.001084;
        pub const MAX_LONGITUDE: f64 = 4.267382599999999;
        pub const MIN_LATITUDE: f64 = 10.147811;
        pub const MIN_LONGITUDE: f64 = -12.2403447;
        pub const NORTHEAST_LATITUDE: f64 = 25.001084;
        pub const NORTHEAST_LONGITUDE: f64 = 4.267382599999999;
        pub const SOUTHWEST_LATITUDE: f64 = 10.147811;
        pub const SOUTHWEST_LONGITUDE: f64 = -12.2403447;
    }
}
#[cfg(all(feature = "ml", feature = "geo"))]
pub mod geo {
    use crate::{CountryGeo, CountryGeoBound, CountryGeoBounds};

    pub fn new() -> CountryGeo {
        CountryGeo {
            latitude: 17.570692,
            longitude: -3.996166,
            max_latitude: 25.001084,
            max_longitude: 4.267382599999999,
            min_latitude: 10.147811,
            min_longitude: -12.2403447,
            bounds: CountryGeoBounds {
                northeast: CountryGeoBound {
                    latitude: 25.001084,
                    longitude: 4.267382599999999,
                },
                southwest: CountryGeoBound {
                    latitude: 10.147811,
                    longitude: -12.2403447,
                },
            },
        }
    }
}

#[cfg(all(feature = "ml", feature = "subdivisions"))]
pub mod subdivisions {
    use crate::Subdivision;
    use std::collections::HashMap;
    // In this state, We do not know if subdivisions have geo or not!
    #[cfg(feature = "geo")]
    #[allow(unused_imports)]
    use crate::{Alpha2, SubdivisionGeo, SubdivisionType};

    pub fn new() -> HashMap<&'static str, Subdivision> {
        HashMap::from([
            (
                "1",
                Subdivision {
                    name: "1",
                    country_alpha2: Alpha2::ML,
                    code: "1",
                    #[cfg(feature = "geo")]
                    geo: Some(SubdivisionGeo {
                        latitude: Some(14.4367876),
                        longitude: Some(-11.4452717),
                        max_latitude: Some(14.4902814),
                        min_latitude: Some(14.4186581),
                        max_longitude: Some(-11.3716221),
                        min_longitude: Some(-11.4719188),
                    }),
                    comments: None,
                    subdivision_type: SubdivisionType::Region,
                    #[cfg(feature = "translations")]
                    translations: HashMap::from([
                        ("ar", "منطقة كايس"),
                        ("bg", "Кайес"),
                        ("bn", "ক\u{9be}য\u{9bc}েস অঞ\u{9cd}চল"),
                        ("ccp", "𑄇𑄬𑄠𑄬𑄌\u{11134}"),
                        ("ceb", "Kayes Region"),
                        ("da", "Kayes"),
                        ("de", "Region Kayes"),
                        ("el", "Περιφέρεια Καγιές"),
                        ("en", "Kayes"),
                        ("es", "Kayes"),
                        ("et", "Kayesi piirkond"),
                        ("eu", "Kayes eskualdea"),
                        ("fa", "استان کایس"),
                        ("fi", "Kayesin alue"),
                        ("fr", "Région de Kayes"),
                        ("gu", "કાય\u{ac7}સ પ\u{acd}રદ\u{ac7}શ"),
                        ("hi", "काय\u{947}स क\u{94d}ष\u{947}त\u{94d}र"),
                        ("hu", "Kayes régió"),
                        ("id", "Region Kayes"),
                        ("it", "regione di Kayes"),
                        ("ja", "カイ州"),
                        ("ka", "კაესის რეგიონი"),
                        ("kn", "ಕೇಯ\u{ccd}ಸ\u{ccd} ಪ\u{ccd}ರದೇಶ"),
                        ("ko", "케이스 주"),
                        ("lt", "Kajeso regionas"),
                        ("lv", "Kajesas reģions"),
                        ("mr", "काय\u{947}स प\u{94d}रद\u{947}श"),
                        ("ms", "Kayes Region"),
                        ("nb", "Kayes"),
                        ("nl", "Kayes"),
                        ("no", "Kayes"),
                        ("pl", "Region Kayes"),
                        ("pt", "Kayes"),
                        ("ro", "Regiunea Kayes"),
                        ("ru", "Каес"),
                        ("si", "කේයස\u{dca} ප\u{dca}\u{200d}ර\u{dcf}න\u{dca}තය"),
                        ("sv", "Kayes"),
                        ("ta", "கேஎஸ\u{bcd} பகுதி"),
                        ("te", "క\u{c47}య\u{c46}స\u{c4d} ప\u{c4d}ర\u{c3e}ంతం"),
                        ("th", "อาณาเขตคาเยส"),
                        ("tr", "Kayes Bölgesi"),
                        ("uk", "Каєс"),
                        ("ur", "علاقہ کیز"),
                        ("vi", "Khu vực Kayes"),
                        ("zh", "卡伊區"),
                    ]),
                    unofficial_name_list: ["Kayes"].to_vec(),
                },
            ),
            (
                "10",
                Subdivision {
                    name: "10",
                    country_alpha2: Alpha2::ML,
                    code: "10",
                    #[cfg(feature = "geo")]
                    geo: Some(SubdivisionGeo {
                        latitude: Some(-15.7753392),
                        longitude: Some(-47.8138065),
                        max_latitude: Some(-15.7724352),
                        min_latitude: Some(-15.7804757),
                        max_longitude: Some(-47.8095817),
                        min_longitude: Some(-47.817425),
                    }),
                    comments: None,
                    subdivision_type: SubdivisionType::Region,
                    #[cfg(feature = "translations")]
                    translations: HashMap::from([
                        ("en", "Taoudénit"),
                        ("fi", "Taoudénitin alue"),
                        ("fr", "Région de Taoudénit"),
                        ("ja", "タウデニ州"),
                    ]),
                    unofficial_name_list: [].to_vec(),
                },
            ),
            (
                "2",
                Subdivision {
                    name: "2",
                    country_alpha2: Alpha2::ML,
                    code: "2",
                    #[cfg(feature = "geo")]
                    geo: Some(SubdivisionGeo {
                        latitude: Some(12.861111),
                        longitude: Some(-7.558332999999999),
                        max_latitude: Some(12.8789565),
                        min_latitude: Some(12.8513625),
                        max_longitude: Some(-7.5457191),
                        min_longitude: Some(-7.571923199999999),
                    }),
                    comments: None,
                    subdivision_type: SubdivisionType::Region,
                    #[cfg(feature = "translations")]
                    translations: HashMap::from([
                        ("ar", "منطقة كوليكورو"),
                        ("bg", "Куликоро"),
                        ("bn", "কউলিক\u{9c1}রো অঞ\u{9cd}চল"),
                        ("ca", "Regió de Koulikoro"),
                        ("ccp", "𑄇\u{1112f}𑄣\u{11128}𑄇\u{1112e}𑄢\u{1112e}"),
                        ("ceb", "Koulikoro Region"),
                        ("da", "Koulikoro"),
                        ("de", "Region Koulikoro"),
                        ("el", "Περιφέρεια Κουλικορό"),
                        ("en", "Koulikoro"),
                        ("es", "Kulikoró"),
                        ("et", "Koulikoro piirkond"),
                        ("eu", "Koulikoro eskualdea"),
                        ("fa", "استان کولیکورو"),
                        ("fi", "Koulikoron alue"),
                        ("fr", "Région de Koulikoro"),
                        ("gu", "કૌલીકોરો પ\u{acd}રદ\u{ac7}શ"),
                        ("hi", "कोइलिकोरो क\u{94d}ष\u{947}त\u{94d}र"),
                        ("hu", "Koulikoro régió"),
                        ("id", "Region Koulikoro"),
                        ("it", "regione di Koulikoro"),
                        ("ja", "クリコロ州"),
                        ("ka", "კულიკოროს რეგიონი"),
                        ("kn", "ಕ\u{ccc}ಲ\u{cbf}ಕೊರೋ ಪ\u{ccd}ರದೇಶ"),
                        ("ko", "쿨리코로 주"),
                        ("lt", "Kulikoro regionas"),
                        ("lv", "Kulikoro reģions"),
                        ("mr", "कोलिको प\u{94d}रा\u{902}त"),
                        ("ms", "Koulikoro Region"),
                        ("nb", "Koulikoro"),
                        ("nl", "Koulikoro"),
                        ("no", "Koulikoro"),
                        ("pl", "Region Koulikoro"),
                        ("pt", "Koulikoro"),
                        ("ro", "Regiunea Koulikoro"),
                        ("ru", "Куликоро"),
                        ("si", "කොව\u{dd4}ල\u{dd2}කොරෝ කල\u{dcf}පය"),
                        ("sv", "Koulikoro"),
                        ("ta", "கோழிகோரோ பகுதி"),
                        ("te", "క\u{c4b}ల\u{c3f}క\u{c4b}ర\u{c4b} ప\u{c4d}ర\u{c3e}ంతం"),
                        ("th", "เขตก\u{e39}ล\u{e35}กอโร"),
                        ("tr", "Koulikoro Bölgesi"),
                        ("uk", "Кулікоро"),
                        ("ur", "علاقہ کولیکورو"),
                        ("vi", "Khu vực Koulikoro"),
                        ("zh", "库利科罗区"),
                    ]),
                    unofficial_name_list: ["Koulikoro"].to_vec(),
                },
            ),
            (
                "3",
                Subdivision {
                    name: "3",
                    country_alpha2: Alpha2::ML,
                    code: "3",
                    #[cfg(feature = "geo")]
                    geo: Some(SubdivisionGeo {
                        latitude: Some(11.316667),
                        longitude: Some(-5.666666999999999),
                        max_latitude: Some(11.3538204),
                        min_latitude: Some(11.2896322),
                        max_longitude: Some(-5.634414),
                        min_longitude: Some(-5.7206155),
                    }),
                    comments: None,
                    subdivision_type: SubdivisionType::Region,
                    #[cfg(feature = "translations")]
                    translations: HashMap::from([
                        ("ar", "منطقة سيكاسو"),
                        ("be", "Сікасо"),
                        ("bn", "সিক\u{9be}সো অঞ\u{9cd}চল"),
                        ("ccp", "𑄥\u{11128}𑄇𑄥\u{1112e}"),
                        ("ceb", "Sikasso Region"),
                        ("da", "Sikasso"),
                        ("de", "Region Sikasso"),
                        ("el", "Περιφέρεια Σικασσό"),
                        ("en", "Sikasso"),
                        ("es", "Sikasso"),
                        ("et", "Sikasso piirkond"),
                        ("eu", "Sikasso eskualdea"),
                        ("fa", "استان سیکاسو"),
                        ("fi", "Sikasson alue"),
                        ("fr", "Région de Sikasso"),
                        ("gu", "સિકાસો પ\u{acd}રદ\u{ac7}શ"),
                        ("hi", "सिकासो क\u{94d}ष\u{947}त\u{94d}र"),
                        ("hu", "Sikasso régió"),
                        ("id", "Region Sikasso"),
                        ("it", "regione di Sikasso"),
                        ("ja", "シカソ州"),
                        ("ka", "სიკასოს რეგიონი"),
                        ("kn", "ಸ\u{cbf}ಕಸ\u{ccd}ಸೊ ಪ\u{ccd}ರದೇಶ"),
                        ("ko", "시카소 주"),
                        ("lt", "Sikaso regionas"),
                        ("lv", "Sikaso reģions"),
                        ("mr", "सिकासो प\u{94d}रद\u{947}श"),
                        ("ms", "Sikasso Region"),
                        ("nb", "Sikasso"),
                        ("nl", "Sikasso"),
                        ("no", "Sikasso"),
                        ("pl", "Region Sikasso"),
                        ("pt", "Sikasso"),
                        ("ro", "Regiunea Sikasso"),
                        ("ru", "Сикасо"),
                        ("si", "ස\u{dd2}කස\u{dca}සෝ කල\u{dcf}පය"),
                        ("sv", "Sikasso"),
                        ("ta", "சிக\u{bbe}ஸோ பகுதி"),
                        ("te", "స\u{c3f}క\u{c3e}స\u{c4b} ప\u{c4d}ర\u{c3e}ంతం"),
                        ("th", "ซ\u{e34}คาสโซ"),
                        ("tr", "Sikasso Bölgesi"),
                        ("uk", "Сікасо"),
                        ("ur", "علاقہ سیکاسو"),
                        ("vi", "Khu vực Sikasso"),
                        ("zh", "锡卡索区"),
                    ]),
                    unofficial_name_list: ["Sikasso"].to_vec(),
                },
            ),
            (
                "4",
                Subdivision {
                    name: "4",
                    country_alpha2: Alpha2::ML,
                    code: "4",
                    #[cfg(feature = "geo")]
                    geo: Some(SubdivisionGeo {
                        latitude: Some(13.45),
                        longitude: Some(-6.266667),
                        max_latitude: Some(13.4589132),
                        min_latitude: Some(13.4017673),
                        max_longitude: Some(-6.2011928),
                        min_longitude: Some(-6.3270675),
                    }),
                    comments: None,
                    subdivision_type: SubdivisionType::Region,
                    #[cfg(feature = "translations")]
                    translations: HashMap::from([
                        ("ar", "منطقة سيغو"),
                        ("bn", "সেগ\u{9c1}উ অঞ\u{9cd}চল"),
                        ("ca", "Regió de Ségou"),
                        ("ccp", "𑄥𑄬𑄉\u{1112f}"),
                        ("ceb", "Ségou Region"),
                        ("da", "Ségou"),
                        ("de", "Region Ségou"),
                        ("el", "Περιφέρεια Σεγκού"),
                        ("en", "Ségou"),
                        ("es", "Segú"),
                        ("et", "Ségou piirkond"),
                        ("eu", "Ségou eskualdea"),
                        ("fa", "استان سگو"),
                        ("fi", "Ségoun alue"),
                        ("fr", "Région de Ségou"),
                        ("gu", "સ\u{ac7}ગોઉ પ\u{acd}રદ\u{ac7}શ"),
                        ("hi", "स\u{947}गोऊ क\u{94d}ष\u{947}त\u{94d}र"),
                        ("id", "Region Ségou"),
                        ("it", "regione di Ségou"),
                        ("ja", "セグー州"),
                        ("ka", "სეგუს რეგიონი"),
                        ("kn", "ಸ\u{cc6}ಗಾವ\u{ccd} ಪ\u{ccd}ರದೇಶ"),
                        ("ko", "세구 주"),
                        ("lt", "Segu regionas"),
                        ("lv", "Segu reģions"),
                        ("mr", "स\u{947}गो प\u{94d}रद\u{947}श"),
                        ("ms", "Segou Region"),
                        ("nb", "Ségou"),
                        ("nl", "Ségou"),
                        ("no", "Ségou"),
                        ("pl", "Region Ségou"),
                        ("pt", "Ségou"),
                        ("ro", "Regiunea Ségou"),
                        ("ru", "Сегу"),
                        ("si", "සෙගෞ කල\u{dcf}පය"),
                        ("sv", "Ségou"),
                        ("ta", "செகௌ பகுதி"),
                        ("te", "స\u{c46}గ\u{c4c} ప\u{c4d}ర\u{c3e}ంతం"),
                        ("th", "เซเกา"),
                        ("tr", "Ségou Bölgesi"),
                        ("uk", "Сегу"),
                        ("ur", "علاقہ سیگو"),
                        ("vi", "Khu vực Ségou"),
                        ("zh", "塞古区"),
                    ]),
                    unofficial_name_list: ["Ségou"].to_vec(),
                },
            ),
            (
                "5",
                Subdivision {
                    name: "5",
                    country_alpha2: Alpha2::ML,
                    code: "5",
                    #[cfg(feature = "geo")]
                    geo: Some(SubdivisionGeo {
                        latitude: Some(14.495833),
                        longitude: Some(-4.198611),
                        max_latitude: Some(14.5178846),
                        min_latitude: Some(14.4526312),
                        max_longitude: Some(-4.1471441),
                        min_longitude: Some(-4.2045531),
                    }),
                    comments: None,
                    subdivision_type: SubdivisionType::Region,
                    #[cfg(feature = "translations")]
                    translations: HashMap::from([
                        ("ar", "منطقة موبتي"),
                        ("be", "Мопці"),
                        ("bg", "Мопти"),
                        ("bn", "ম\u{9c1}প\u{9cd}তি অঞ\u{9cd}চল"),
                        ("ca", "Regió de Mopti"),
                        ("ccp", "𑄟\u{1112e}𑄛\u{11134}𑄑\u{11128}"),
                        ("ceb", "Mopti Region"),
                        ("da", "Mopti"),
                        ("de", "Region Mopti"),
                        ("el", "Περιφέρεια Μοπτί"),
                        ("en", "Mopti"),
                        ("es", "Región de Mopti"),
                        ("et", "Mopti piirkond"),
                        ("eu", "Mopti eskualdea"),
                        ("fa", "استان موپتی"),
                        ("fi", "Moptin alue"),
                        ("fr", "Région de Mopti"),
                        ("gu", "મોપ\u{acd}ટી પ\u{acd}રદ\u{ac7}શ"),
                        ("hi", "मोपटी क\u{94d}ष\u{947}त\u{94d}र"),
                        ("id", "Region Mopti"),
                        ("it", "regione di Mopti"),
                        ("ja", "モプティ州"),
                        ("ka", "მოპტის რეგიონი"),
                        ("kn", "ಮೊಪ\u{ccd}ಟ\u{cbf} ಪ\u{ccd}ರದೇಶ"),
                        ("ko", "몹티 주"),
                        ("lt", "Mopčio regionas"),
                        ("lv", "Mopti reģions"),
                        ("mr", "मोपटी प\u{94d}रद\u{947}श"),
                        ("ms", "Mopti Region"),
                        ("nb", "Mopti"),
                        ("nl", "Mopti"),
                        ("no", "Mopti"),
                        ("pl", "Region Mopti"),
                        ("pt", "Mopti"),
                        ("ro", "Regiunea Mopti"),
                        ("ru", "Мопти"),
                        ("si", "මොප\u{dca}ට\u{dd2} කල\u{dcf}පය"),
                        ("sv", "Mopti"),
                        ("ta", "மோப\u{bcd}டி பகுதி"),
                        ("te", "మ\u{c4b}ప\u{c4d}ట\u{c3f} ప\u{c4d}ర\u{c3e}ంతం"),
                        ("th", "เม\u{e37}องม\u{e4a}อปต\u{e34}"),
                        ("tr", "Mopti Region"),
                        ("uk", "Мопті"),
                        ("ur", "علاقہ موپٹی"),
                        ("vi", "Khu vực Mopti"),
                        ("zh", "莫普提区"),
                    ]),
                    unofficial_name_list: ["Mopti"].to_vec(),
                },
            ),
            (
                "6",
                Subdivision {
                    name: "6",
                    country_alpha2: Alpha2::ML,
                    code: "6",
                    #[cfg(feature = "geo")]
                    geo: Some(SubdivisionGeo {
                        latitude: Some(16.7665887),
                        longitude: Some(-3.0025615),
                        max_latitude: Some(16.7901617),
                        min_latitude: Some(16.7526054),
                        max_longitude: Some(-2.9932594),
                        min_longitude: Some(-3.0226994),
                    }),
                    comments: None,
                    subdivision_type: SubdivisionType::Region,
                    #[cfg(feature = "translations")]
                    translations: HashMap::from([
                        ("ar", "منطقة تمبكتو"),
                        ("bn", "তম\u{9cd}ব\u{9c1}কত\u{9c1} অঞ\u{9cd}চল"),
                        ("ca", "Regió de Tombouctou"),
                        ("ccp", "𑄑\u{1112e}𑄟\u{11134}𑄝\u{1112f}𑄇\u{11134}𑄑\u{1112f}"),
                        ("ceb", "Tombouctou Region"),
                        ("da", "Timbuktu"),
                        ("de", "Region Timbuktu"),
                        ("el", "Περιφέρεια Τομπουκτού"),
                        ("en", "Tombouctou"),
                        ("es", "Tombuctú"),
                        ("et", "Tombouctou piirkond"),
                        ("eu", "Tonbuktu eskualdea"),
                        ("fa", "استان تومبوکتو"),
                        ("fi", "Timbuktun alue"),
                        ("fr", "Région de Tombouctou"),
                        ("gu", "ટોમ\u{acd}બૌક\u{acd}ટોઉ પ\u{acd}રદ\u{ac7}શ"),
                        ("he", "מחוז טימבוקטו"),
                        ("hi", "टॉम\u{94d}बौक\u{94d}टाउ क\u{94d}ष\u{947}त\u{94d}र"),
                        ("id", "Region Timbuktu"),
                        ("it", "regione di Timbuctù"),
                        ("ja", "トンブクトゥ州"),
                        ("ka", "ტომბუქტუს რეგიონი"),
                        ("kn", "ಟೊಂಬ\u{ccc}ಕ\u{ccd}ಟ\u{ccc} ಪ\u{ccd}ರದೇಶ"),
                        ("ko", "통북투 주"),
                        ("lt", "Tombuktu regionas"),
                        ("lv", "Tombuktu reģions"),
                        ("mr", "टॉम\u{94d}बॉक\u{94d}टौ प\u{94d}रद\u{947}श"),
                        ("ms", "Tombouctou Region"),
                        ("nb", "Timbuktu"),
                        ("nl", "Timboektoe"),
                        ("no", "Timbuktu"),
                        ("pl", "Region Timbuktu"),
                        ("pt", "Tombouctou"),
                        ("ro", "Regiunea Tombouctou"),
                        ("ru", "Томбукту"),
                        ("si", "ටෝම\u{dca}බෝක\u{dca}ට\u{dd4} කල\u{dcf}පය"),
                        ("sv", "Timbuktu"),
                        ("ta", "ட\u{bbe}ம\u{bcd}போவுக\u{bcd}டோக\u{bcd}கு பகுதி"),
                        (
                            "te",
                            "ట\u{c3e}ంబ\u{c4b}క\u{c4d}ట\u{c4b}వ\u{c4d} ప\u{c4d}ర\u{c3e}ంతం",
                        ),
                        ("th", "ทอมบ\u{e31}วซเทา"),
                        ("tr", "Tombouctou Bölgesi"),
                        ("uk", "Тімбукту"),
                        ("ur", "علاقہ ٹمبکٹو"),
                        ("vi", "Khu vực Tombouctou"),
                        ("zh", "通布圖區"),
                    ]),
                    unofficial_name_list: ["Tombouctou"].to_vec(),
                },
            ),
            (
                "7",
                Subdivision {
                    name: "7",
                    country_alpha2: Alpha2::ML,
                    code: "7",
                    #[cfg(feature = "geo")]
                    geo: Some(SubdivisionGeo {
                        latitude: Some(16.2639807),
                        longitude: Some(-0.0279867),
                        max_latitude: Some(16.3047953),
                        min_latitude: Some(16.2237359),
                        max_longitude: Some(0.0254726),
                        min_longitude: Some(-0.0576808),
                    }),
                    comments: None,
                    subdivision_type: SubdivisionType::Region,
                    #[cfg(feature = "translations")]
                    translations: HashMap::from([
                        ("ar", "منطقة غاو"),
                        ("bg", "Гао"),
                        ("bn", "গ\u{9be}ও অঞ\u{9cd}চল"),
                        ("ccp", "𑄉𑄃\u{1112e}"),
                        ("ceb", "Gao Region"),
                        ("da", "Gao"),
                        ("de", "Region Gao"),
                        ("el", "Περιφέρεια Γκαό"),
                        ("en", "Gao"),
                        ("es", "Gao"),
                        ("et", "Gao piirkond"),
                        ("eu", "Gao eskualdea"),
                        ("fa", "استان گائو"),
                        ("fi", "Gaon alue"),
                        ("fr", "Région de Gao"),
                        ("gu", "ગાઓ પ\u{acd}રદ\u{ac7}શ"),
                        ("hi", "गाओ क\u{94d}ष\u{947}त\u{94d}र"),
                        ("hu", "Gao régió"),
                        ("id", "Region Gao"),
                        ("it", "regione di Gao"),
                        ("ja", "ガオ州"),
                        ("ka", "გაოს რეგიონი"),
                        ("kn", "ಗಾವೊ ಪ\u{ccd}ರದೇಶ"),
                        ("ko", "가오 주"),
                        ("lt", "Gao regionas"),
                        ("lv", "Gao reģions"),
                        ("mr", "गाओ प\u{94d}रद\u{947}श"),
                        ("ms", "Gao Region"),
                        ("nb", "Gao"),
                        ("nl", "Gao"),
                        ("no", "Gao"),
                        ("pl", "Region Gao"),
                        ("pt", "Gao"),
                        ("ro", "Regiunea Gao"),
                        ("ru", "Гао"),
                        ("si", "ග\u{dcf}ඕ කල\u{dcf}පය"),
                        ("sv", "Gao"),
                        ("ta", "க\u{bbe}வோ பகுதி"),
                        ("te", "గ\u{c3e}వ\u{c4d} ప\u{c4d}ర\u{c3e}ంతం"),
                        ("th", "เกา"),
                        ("tr", "Gao Belediyesi"),
                        ("uk", "Гао"),
                        ("ur", "علاقہ گاو"),
                        ("vi", "Khu vực Gao"),
                        ("zh", "加奥区"),
                    ]),
                    unofficial_name_list: ["Gao"].to_vec(),
                },
            ),
            (
                "8",
                Subdivision {
                    name: "8",
                    country_alpha2: Alpha2::ML,
                    code: "8",
                    #[cfg(feature = "geo")]
                    geo: Some(SubdivisionGeo {
                        latitude: Some(18.438889),
                        longitude: Some(1.408333),
                        max_latitude: Some(18.4647725),
                        min_latitude: Some(18.4226161),
                        max_longitude: Some(1.4252616),
                        min_longitude: Some(1.39359),
                    }),
                    comments: None,
                    subdivision_type: SubdivisionType::Region,
                    #[cfg(feature = "translations")]
                    translations: HashMap::from([
                        ("ar", "منطقة كيدال"),
                        ("bg", "Кидал"),
                        ("bn", "কিড\u{9be}ল অঞ\u{9cd}চল"),
                        ("ccp", "𑄇\u{11128}𑄓𑄣\u{11134}"),
                        ("ceb", "Kidal Region"),
                        ("da", "Kidal"),
                        ("de", "Region Kidal"),
                        ("el", "Περιφέρεια Κιντάλ"),
                        ("en", "Kidal"),
                        ("es", "Kidal"),
                        ("et", "Kidali piirkond"),
                        ("eu", "Kidal eskualdea"),
                        ("fa", "استان کیدال"),
                        ("fi", "Kidalin alue"),
                        ("fr", "Région de Kidal"),
                        ("gu", "કિડલ પ\u{acd}રદ\u{ac7}શ"),
                        ("hi", "किडाल प\u{94d}रद\u{947}श"),
                        ("hu", "Kidal régió"),
                        ("id", "Region Kidal"),
                        ("it", "regione di Kidal"),
                        ("ja", "キダル州"),
                        ("ka", "კიდალის რეგიონი"),
                        ("kn", "ಕ\u{cbf}ಡಾಲ\u{ccd} ಪ\u{ccd}ರದೇಶ"),
                        ("ko", "키달 주"),
                        ("lt", "Kidalio regionas"),
                        ("lv", "Kidalas reģions"),
                        ("mr", "किदील प\u{94d}रद\u{947}श"),
                        ("ms", "Daerah Kidal"),
                        ("nb", "Kidal"),
                        ("nl", "Kidal"),
                        ("no", "Kidal"),
                        ("pl", "Region Kidal"),
                        ("pt", "Kidal"),
                        ("ro", "Regiunea Kidal"),
                        ("ru", "Кидаль"),
                        ("si", "ක\u{dd2}ඩල\u{dca} කල\u{dcf}පය"),
                        ("sv", "Kidal"),
                        ("ta", "கிடல\u{bcd} பகுதி"),
                        ("te", "క\u{c3f}డ\u{c3e}ల\u{c4d} ప\u{c4d}ర\u{c3e}ంతం"),
                        ("th", "ภ\u{e39}ม\u{e34}ภาคค\u{e34}ด\u{e31}ล"),
                        ("tr", "Kidal Region"),
                        ("uk", "Кідаль"),
                        ("ur", "علاقہ کڈال"),
                        ("vi", "Khu vực Kidal"),
                        ("zh", "基達爾區"),
                    ]),
                    unofficial_name_list: ["Kidal"].to_vec(),
                },
            ),
            (
                "9",
                Subdivision {
                    name: "9",
                    country_alpha2: Alpha2::ML,
                    code: "9",
                    #[cfg(feature = "geo")]
                    geo: None,
                    comments: None,
                    subdivision_type: SubdivisionType::Region,
                    #[cfg(feature = "translations")]
                    translations: HashMap::from([
                        ("en", "Ménaka"),
                        ("fi", "Ménakan alue"),
                        ("fr", "Région de Ménaka"),
                        ("ja", "メナカ州"),
                    ]),
                    unofficial_name_list: [].to_vec(),
                },
            ),
            (
                "BKO",
                Subdivision {
                    name: "BKO",
                    country_alpha2: Alpha2::ML,
                    code: "BKO",
                    #[cfg(feature = "geo")]
                    geo: Some(SubdivisionGeo {
                        latitude: Some(12.65),
                        longitude: Some(-8.0),
                        max_latitude: Some(12.7329742),
                        min_latitude: Some(12.4909088),
                        max_longitude: Some(-7.8759453),
                        min_longitude: Some(-8.1150808),
                    }),
                    comments: None,
                    subdivision_type: SubdivisionType::District,
                    #[cfg(feature = "translations")]
                    translations: HashMap::from([
                        ("af", "Bamako"),
                        ("am", "ባማኮ"),
                        ("ar", "باماكو"),
                        ("az", "Bamako"),
                        ("be", "Горад Бамако"),
                        ("bg", "Бамако"),
                        ("bn", "ব\u{9be}ম\u{9be}কো"),
                        ("bs", "Bamako"),
                        ("ca", "Bamako"),
                        ("ccp", "𑄝𑄟𑄇\u{1112e}"),
                        ("ceb", "Bamako Region"),
                        ("cs", "Bamako"),
                        ("cy", "Bamako"),
                        ("da", "Bamako"),
                        ("de", "Bamako"),
                        ("el", "Μπαμακό"),
                        ("en", "Bamako"),
                        ("es", "Bamako"),
                        ("et", "Bamako"),
                        ("eu", "Bamako"),
                        ("fa", "باماکو"),
                        ("fi", "Bamako"),
                        ("fr", "Bamako"),
                        ("ga", "Bamako"),
                        ("gl", "Bamaco"),
                        ("gu", "બામાકો"),
                        ("ha", "Bamako"),
                        ("ha_NE", "Bamako"),
                        ("he", "במקו"),
                        ("hi", "बमाको"),
                        ("hr", "Bamako"),
                        ("hu", "Bamako"),
                        ("hy", "Բամակո"),
                        ("id", "Bamako"),
                        ("is", "Bamakó"),
                        ("it", "Bamako"),
                        ("ja", "バマコ"),
                        ("jv", "Bamako"),
                        ("ka", "ბამაკო"),
                        ("kk", "Бамако"),
                        ("kn", "ಬಮಾಕೋ"),
                        ("ko", "바마코"),
                        ("ky", "Бамако"),
                        ("lt", "Bamakas"),
                        ("lv", "Bamako"),
                        ("mk", "Бамако"),
                        ("ml", "ബ\u{d3e}മ\u{d3e}കോ"),
                        ("mn", "Бамако"),
                        ("mr", "बमाको"),
                        ("ms", "Bamako"),
                        ("nb", "Bamako"),
                        ("nl", "Bamako"),
                        ("no", "Bamako"),
                        ("pa", "ਬਮਾਕ\u{a4b}"),
                        ("pl", "Bamako"),
                        ("pt", "Bamako"),
                        ("ro", "Bamako"),
                        ("ru", "Бамако"),
                        ("si", "බම\u{dcf}කෝ"),
                        ("sk", "Bamako"),
                        ("sl", "Bamako"),
                        ("so", "Bamako"),
                        ("sq", "Bamako"),
                        ("sr", "Бамако"),
                        ("sr_Latn", "Bamako"),
                        ("sv", "Bamako"),
                        ("sw", "Bamako"),
                        ("ta", "பம\u{bbe}க\u{bcd}கோ"),
                        ("te", "బమ\u{c3e}క\u{c4b}"),
                        ("th", "บามาโก"),
                        ("tk", "Bamako"),
                        ("tr", "Bamako"),
                        ("uk", "Бамако"),
                        ("ur", "بماکو"),
                        ("uz", "Bamako"),
                        ("vi", "Bamako"),
                        ("yo", "Bamako"),
                        ("yo_BJ", "Bamako"),
                        ("yue", "巴馬科"),
                        ("yue_Hans", "巴马科"),
                        ("zh", "巴馬科"),
                    ]),
                    unofficial_name_list: ["Bamako"].to_vec(),
                },
            ),
        ])
    }
}
#[allow(unused_imports)]
use crate::{
    Alpha2, Alpha3, Continent, Country, Region, SubRegion, WeekDay, WorldRegion, GEC, IOC,
};
#[allow(unused_imports)]
use std::collections::HashMap;
#[cfg(feature = "ml")]
pub fn new() -> Country {
    Country {
        alpha2: Alpha2::ML,
        alpha3: Alpha3::MLI,
        address_format: None,
        continent: Continent::Africa,
        country_code: 223,
        currency_code: "XOF",
        gec: Some(GEC::ML),
        #[cfg(feature = "geo")]
        geo: geo::new(),
        international_prefix: "00",
        ioc: Some(IOC::MLI),
        iso_long_name: "The Republic of Mali",
        iso_short_name: "Mali",
        official_language_list: ["fr"].to_vec(),
        spoken_language_list: ["fr"].to_vec(),
        national_destination_code_length_list: [2].to_vec(),
        national_number_length_list: [8].to_vec(),
        national_prefix: "0",
        nationality: Some("Malian"),
        number: "466",
        postal_code: false,
        postal_code_format: None,
        region: Some(Region::Africa),
        start_of_week: WeekDay::Monday,
        subregion: Some(SubRegion::WesternAfrica),
        un_locode: "ML",
        unofficial_name_list: ["Mali", "マリ"].to_vec(),
        world_region: WorldRegion::EMEA,
        #[cfg(feature = "translations")]
        translations: HashMap::from([
            ("ab", "Mali"),
            ("af", "Mali"),
            ("ak", "Mali"),
            ("am", "ማሊ"),
            ("an", "Mali"),
            ("ar", "مالي"),
            ("as", "ম\u{9be}লি"),
            ("ay", "Mali"),
            ("az", "Mali"),
            ("ba", "Mali"),
            ("be", "Малі"),
            ("bg", "Мали"),
            ("bi", "Mali"),
            ("bn", "ম\u{9be}লি"),
            ("bn_IN", "ম\u{9be}লি"),
            ("br", "Mali"),
            ("bs", "Mali"),
            ("ca", "Mali"),
            ("ce", "Мали"),
            ("ch", "Mali"),
            ("cs", "Mali"),
            ("cv", "Мали"),
            ("cy", "Mali"),
            ("da", "Mali"),
            ("de", "Mali"),
            ("dv", "މ\u{7a7}ލ\u{7a9}"),
            ("dz", "མ་ལ\u{f72}།"),
            ("ee", "Mali"),
            ("el", "Μάλι"),
            ("en", "Mali"),
            ("eo", "Malio"),
            ("es", "Malí"),
            ("et", "Mali"),
            ("eu", "Mali"),
            ("fa", "مالی"),
            ("ff", "Maali"),
            ("fi", "Mali"),
            ("fo", "Mali"),
            ("fr", "Mali"),
            ("fy", "Maly"),
            ("ga", "Mailí"),
            ("gl", "Mali"),
            ("gn", "Mali"),
            ("gu", "માલી"),
            ("gv", "Malee"),
            ("ha", "Mali"),
            ("he", "מאלי"),
            ("hi", "माली"),
            ("hr", "Mali"),
            ("ht", "Mali"),
            ("hu", "Mali"),
            ("hy", "Մալի"),
            ("ia", "Mali"),
            ("id", "Mali"),
            ("io", "Mali"),
            ("is", "Malí"),
            ("it", "Mali"),
            ("iu", "Mali"),
            ("ja", "マリ"),
            ("ka", "მალი"),
            ("ki", "Mali"),
            ("kk", "Мали"),
            ("kl", "Mali"),
            ("km", "ម\u{17c9}ាល\u{17b8}"),
            ("kn", "ಮಾಲ\u{cbf}"),
            ("ko", "말리"),
            ("ku", "Malî"),
            ("kv", "Mali"),
            ("kw", "Mali"),
            ("ky", "Мали"),
            ("lo", "Mali"),
            ("lt", "Malis"),
            ("lv", "Mali"),
            ("mi", "Māri"),
            ("mk", "Мали"),
            ("ml", "മ\u{d3e}ലി"),
            ("mn", "Мали"),
            ("mr", "माली"),
            ("ms", "Mali"),
            ("mt", "Mali"),
            ("my", "မာလ\u{102e}န\u{102d}\u{102f}င\u{103a}င\u{1036}"),
            ("na", "Mali"),
            ("nb", "Mali"),
            ("ne", "माली"),
            ("nl", "Mali"),
            ("nn", "Mali"),
            ("nv", "Mali"),
            ("oc", "Mali"),
            ("or", "ମ\u{b3e}ଲୀ"),
            ("pa", "ਮਾਲੀ"),
            ("pi", "माली"),
            ("pl", "Mali"),
            ("ps", "مالي"),
            ("pt", "Mali"),
            ("pt_BR", "Mali"),
            ("ro", "Mali"),
            ("ru", "Мали"),
            ("rw", "Mali"),
            ("sc", "Mali"),
            ("sd", "Mali"),
            ("si", "ම\u{dcf}ල\u{dd2}"),
            ("sk", "Mali"),
            ("sl", "Mali"),
            ("so", "Maali"),
            ("sq", "Mali"),
            ("sr", "Мали"),
            ("sv", "Mali"),
            ("sw", "Mali"),
            ("ta", "ம\u{bbe}லி"),
            ("te", "माली"),
            ("tg", "Мали"),
            ("th", "มาล\u{e35}"),
            ("ti", "ማሊ"),
            ("tk", "Mali"),
            ("tl", "Mali"),
            ("tr", "Mali"),
            ("tt", "Мали"),
            ("ug", "مالى"),
            ("uk", "Малі"),
            ("ur", "مالی"),
            ("uz", "Mali"),
            ("ve", "Mali"),
            ("vi", "Ma-li"),
            ("wa", "Mali"),
            ("wo", "Mali"),
            ("xh", "Mali"),
            ("yo", "Málì"),
            ("zh_CN", "马里"),
            ("zh_HK", "馬里"),
            ("zh_TW", "馬利"),
            ("zu", "IMali"),
        ]),
        #[cfg(feature = "subdivisions")]
        subdivisions: subdivisions::new(),
    }
}
