// DO NOT TOUCH THIS FILE. (Auto-generated via `code_gen/countries.rs`)

// The Republic of Sierra Leone

#[cfg(all(feature = "sl", feature = "constants"))]
pub mod consts {
    #[allow(unused_imports)]
    use crate::{Alpha2, Alpha3, Continent, Region, SubRegion, WeekDay, WorldRegion, GEC};

    pub const ADDRESS_FORMAT: Option<&str> = None;
    pub const ALPHA2: Alpha2 = Alpha2::SL;
    pub const ALPHA3: Alpha3 = Alpha3::SLE;
    pub const CONTINENT: Continent = Continent::Africa;
    pub const COUNTRY_CODE: usize = 232;
    pub const CURRENCY_CODE: &str = "SLL";
    pub const GEC: Option<GEC> = Some(GEC::SL);
    pub const INTERNATIONAL_PREFIX: &str = "00";
    pub const IOC: Option<&str> = Some("SLE");
    pub const ISO_SHORT_NAME: &str = "Sierra Leone";
    pub const ISO_LONG_NAME: &str = "The Republic of Sierra Leone";
    pub const OFFICIAL_LANGUAGE_LIST: &[&str] = &["en"];
    pub const SPOKEN_LANGUAGE_LIST: &[&str] = &["en"];
    pub const NATIONAL_DESTINATION_CODE_LENGTH_LIST: &[usize] = &[2];
    pub const NATIONAL_NUMBER_LENGTH_LIST: &[usize] = &[8];
    pub const NATIONAL_PREFIX: &str = "0";
    pub const NATIONALITY: Option<&str> = Some("Sierra Leonean");
    pub const NUMBER: &str = "694";
    pub const POSTAL_CODE: bool = false;
    pub const POSTAL_CODE_FORMAT: Option<&str> = None;
    pub const REGION: Option<Region> = Some(Region::Africa);
    pub const START_DAY_OF_WEEK: WeekDay = WeekDay::Monday;
    pub const SUBREGION: Option<SubRegion> = Some(SubRegion::WesternAfrica);
    pub const UN_LOCODE: &str = "SL";
    pub const UNOFFICIAL_NAME_LIST: &[&str] = &["Sierra Leone", "シエラレオネ"];
    pub const WORLD_REGION: WorldRegion = WorldRegion::EMEA;
    #[cfg(feature = "translations")]
    pub const TRANSLATIONS: &[(&str, &str)] = &[
        ("ab", "Sierra Leone"),
        ("af", "Siërra Leone"),
        ("ak", "Sierra Leone"),
        ("am", "ሴየራ ሌዎን"),
        ("an", "Sierra Leone"),
        ("ar", "سيراليون"),
        ("as", "চিয়েৰ\u{9be} লিওন"),
        ("ay", "Sierra Leone"),
        ("az", "Siera Lione"),
        ("ba", "Sierra Leone"),
        ("be", "Сьера-Леонэ"),
        ("bg", "Сиера Леоне"),
        ("bi", "Sierra Leone"),
        ("bn", "সিয়ের\u{9be} লিওন"),
        ("bn_IN", "সিয়ের\u{9be} লিওন"),
        ("br", "Sierra Leone"),
        ("bs", "Sierra Leone"),
        ("ca", "Sierra Leone"),
        ("ce", "Сьерра-Леоне"),
        ("ch", "Sierra Leone"),
        ("cs", "Sierra Leone"),
        ("cv", "Сьерра-Леоне"),
        ("cy", "Sierra Leone"),
        ("da", "Sierra Leone"),
        ("de", "Sierra Leone"),
        ("dv", "ސ\u{7ac}ރ\u{7ac}ލ\u{7a8}އ\u{7af}ނ\u{7b0}"),
        ("dz", "ས\u{f72}་ར་ ལ\u{f72}འ\u{f7c}་ན\u{f72}།"),
        ("ee", "Sierra Leone"),
        ("el", "Σιέρα Λεόνε"),
        ("en", "Sierra Leone"),
        ("eo", "Siera-Leono"),
        ("es", "Sierra Leona"),
        ("et", "Sierra Leone"),
        ("eu", "Sierra Leona"),
        ("fa", "سیرالئون"),
        ("ff", "Sarliyon"),
        ("fi", "Sierra Leone"),
        ("fo", "Sierra Leone"),
        ("fr", "Sierra Leone"),
        ("fy", "Sierra Leöane"),
        ("ga", "Siarra Leon"),
        ("gl", "Serra Leoa"),
        ("gn", "Sierra Leone"),
        ("gu", "સિએરા લીઓન"),
        ("gv", "Sierra Leone"),
        ("ha", "Sierra Leone"),
        ("he", "סיירה לאון"),
        ("hi", "सिएरा लियोन"),
        ("hr", "Sijera Leone"),
        ("ht", "Syera Leòn"),
        ("hu", "Sierra Leone"),
        ("hy", "Սյերա-Լեոնե"),
        ("ia", "Sierra Leone"),
        ("id", "Sierra Leone"),
        ("io", "Sierra Leone"),
        ("is", "Síerra Leóne"),
        ("it", "Sierra Leone"),
        ("iu", "Sierra Leone"),
        ("ja", "シエラレオネ"),
        ("ka", "სიერა-ლეონე"),
        ("ki", "Sierra Leone"),
        ("kk", "Сьерра-Леоне"),
        ("kl", "Sierra Leone"),
        ("km", "សេរ\u{17c9}ាឡេអ\u{17bc}ន"),
        ("kn", "Sierra Leone"),
        ("ko", "시에라리온"),
        ("ku", "Sîera Leone"),
        ("kv", "Sierra Leone"),
        ("kw", "Sierra Leon"),
        ("ky", "Сьерра-Леоне"),
        ("lo", "Sierra Leone"),
        ("lt", "Siera Leonė"),
        ("lv", "Sjerraleone"),
        ("mi", "Te Araone"),
        ("mk", "Сиера Леоне"),
        ("ml", "സിയേറ ലിയോണ\u{d4d}\u{200d}"),
        ("mn", "Сьерра-Леоне"),
        ("mr", "सिय\u{947}रा ल\u{947}ओन"),
        ("ms", "Siera Leon"),
        ("mt", "Sierra Leone"),
        (
            "my",
            "ဆ\u{102e}ရာလ\u{102e}ယ\u{103d}န\u{103a}န\u{102d}\u{102f}င\u{103a}င\u{1036}",
        ),
        ("na", "Sierra Leone"),
        ("nb", "Sierra Leone"),
        ("ne", "साइरा लिओनरा"),
        ("nl", "Sierra Leone"),
        ("nn", "Sierra Leone"),
        ("nv", "Náshdóítsoh Bitsiijįʼ Daditłʼooʼígíí Bidził"),
        ("oc", "Sierra Leone"),
        ("or", "ସ\u{b3f}ୟେର\u{b3e} ଲ\u{b3f}ୟୋନ"),
        ("pa", "ਸੀਈਰਆ ਲਿਏਨ"),
        ("pi", "सियारा-लियोन"),
        ("pl", "Sierra Leone"),
        ("ps", "سېرالیون"),
        ("pt", "Serra Leoa"),
        ("pt_BR", "Serra Leoa"),
        ("ro", "Sierra Leone"),
        ("ru", "Сьерра-Леоне"),
        ("rw", "Siyera Lewone"),
        ("sc", "Sierra Leone"),
        ("sd", "Sierra Leone"),
        ("si", "ස\u{dd2}යෙර\u{dcf} ල\u{dd2}යොන\u{dca}"),
        ("sk", "Sierra Leone"),
        ("sl", "Sierra Leone"),
        ("so", "Siraaliyoon"),
        ("sq", "Sierra Leone"),
        ("sr", "Сијера Леоне"),
        ("sv", "Sierra Leone"),
        ("sw", "Sierra Leone"),
        ("ta", "சியர\u{bbe}லியோன\u{bcd}"),
        ("te", "స\u{c3f}య\u{c47}ర\u{c3e} ల\u{c47}ఓన"),
        ("tg", "Сиерра-Леоне"),
        ("th", "เซ\u{e35}ยร\u{e4c}ราล\u{e35}โอน"),
        ("ti", "Sierra Leone"),
        ("tk", "Serra-Leone"),
        ("tl", "Sierra Leone"),
        ("tr", "Sierra Leone"),
        ("tt", "Сиерра Леоне"),
        ("ug", "سېررالېئون"),
        ("uk", "Сьєрра-Леоне"),
        ("ur", "سیرالیون"),
        ("uz", "Syerra Leone"),
        ("ve", "Sierra Leone"),
        ("vi", "Xi-ê-ra Lê-ô-nê"),
        ("wa", "Siera Leyone"),
        ("wo", "Siraa Leyoon"),
        ("xh", "Sierra Leone"),
        ("yo", "Siẹrra Léònè"),
        ("zh_CN", "塞拉利昂"),
        ("zh_HK", "塞拉利昂"),
        ("zh_TW", "獅子山"),
        ("zu", "ISiera Liyoni"),
    ];
    #[cfg(all(feature = "sl", feature = "geo", feature = "constants"))]
    pub mod geo {
        pub const LATITUDE: f64 = 8.460555;
        pub const LONGITUDE: f64 = -11.779889;
        pub const MAX_LATITUDE: f64 = 9.9999737;
        pub const MAX_LONGITUDE: f64 = -10.2716829;
        pub const MIN_LATITUDE: f64 = 6.8446;
        pub const MIN_LONGITUDE: f64 = -13.4032999;
        pub const NORTHEAST_LATITUDE: f64 = 9.9999737;
        pub const NORTHEAST_LONGITUDE: f64 = -10.2716829;
        pub const SOUTHWEST_LATITUDE: f64 = 6.8446;
        pub const SOUTHWEST_LONGITUDE: f64 = -13.4032999;
    }
}
#[cfg(all(feature = "sl", feature = "geo"))]
pub mod geo {
    use crate::{CountryGeo, CountryGeoBound, CountryGeoBounds};

    pub fn new() -> CountryGeo {
        CountryGeo {
            latitude: 8.460555,
            longitude: -11.779889,
            max_latitude: 9.9999737,
            max_longitude: -10.2716829,
            min_latitude: 6.8446,
            min_longitude: -13.4032999,
            bounds: CountryGeoBounds {
                northeast: CountryGeoBound {
                    latitude: 9.9999737,
                    longitude: -10.2716829,
                },
                southwest: CountryGeoBound {
                    latitude: 6.8446,
                    longitude: -13.4032999,
                },
            },
        }
    }
}

#[cfg(all(feature = "sl", feature = "subdivisions"))]
pub mod subdivisions {
    use crate::Subdivision;
    use std::collections::HashMap;
    // In this state, We do not know if subdivisions have geo or not!
    #[cfg(feature = "geo")]
    #[allow(unused_imports)]
    use crate::{Alpha2, SubdivisionGeo, SubdivisionType};

    pub fn new() -> HashMap<&'static str, Subdivision> {
        HashMap::from([
            (
                "E",
                Subdivision {
                    name: "E",
                    country_alpha2: Alpha2::SL,
                    code: "E",
                    #[cfg(feature = "geo")]
                    geo: Some(SubdivisionGeo {
                        latitude: Some(8.247377499999999),
                        longitude: Some(-10.8903099),
                        max_latitude: Some(9.069968),
                        min_latitude: Some(7.341372000000001),
                        max_longitude: Some(-10.2842381),
                        min_longitude: Some(-11.5805801),
                    }),
                    comments: None,
                    subdivision_type: SubdivisionType::Province,
                    #[cfg(feature = "translations")]
                    translations: HashMap::from([
                        ("ar", "المحافظة الشرقية"),
                        ("be", "Усходняя правінцыя, Сьера-Леонэ"),
                        ("bg", "Източна провинция"),
                        ("bn", "ইস\u{9cd}ট\u{9be}র\u{9cd}ন প\u{9cd}রদেশ"),
                        ("ccp", "𑄛\u{1112a}𑄇\u{11134}𑄟𑄬𑄇\u{11134}𑄈𑄬"),
                        ("ceb", "Eastern Province (lalawigan sa Sierra Leone)"),
                        ("da", "Eastern Province"),
                        ("de", "Eastern"),
                        ("el", "Ανατολική Περιφέρεια"),
                        ("en", "Eastern"),
                        ("es", "Provincia del Este"),
                        ("fa", "استان شرقی، سیرالئون"),
                        ("fi", "Itäinen maakunta"),
                        ("fr", "Province de l’Est"),
                        ("gu", "પ\u{ac2}ર\u{acd}વીય પ\u{acd}રા\u{a82}ત"),
                        ("hi", "प\u{942}र\u{94d}वी प\u{94d}रा\u{902}त"),
                        ("hr", "Istočna provincija"),
                        ("id", "Provinsi Timur, Sierra Leone"),
                        ("it", "provincia dell’Est"),
                        ("ja", "東部州"),
                        ("kn", "ಪ\u{cc2}ರ\u{ccd}ವ ಪ\u{ccd}ರಾಂತ\u{ccd}ಯ"),
                        ("ko", "동부 주"),
                        ("lt", "Rytų provincija"),
                        ("lv", "Austrumu province"),
                        ("mr", "प\u{942}र\u{94d}व प\u{94d}रा\u{902}त"),
                        ("ms", "Eastern Province"),
                        ("nb", "Eastern"),
                        ("nl", "Eastern"),
                        ("no", "Eastern"),
                        ("pl", "Prowincja Wschodnia"),
                        ("pt", "Eastern"),
                        ("ro", "Provincia Eastern, Sierra Leone"),
                        ("ru", "Восточная провинция"),
                        ("si", "නැගෙනහ\u{dd2}ර පළ\u{dcf}ත"),
                        ("sv", "Östra provinsen"),
                        ("ta", "கிழக\u{bcd}கு ம\u{bbe}க\u{bbe}ணம\u{bcd}"),
                        (
                            "te",
                            "తూర\u{c4d}పు ప\u{c4d}ర\u{c3e}వ\u{c3f}న\u{c4d}స\u{c4d}",
                        ),
                        ("th", "อ\u{e34}สเท\u{e34}น โพว\u{e34}\u{e49}น"),
                        ("tr", "Eastern Province"),
                        ("uk", "Східна провінція"),
                        ("ur", "مشرقی صوبہ، سیرالیون"),
                        ("vi", "Tỉnh Phía Đông"),
                        ("zh", "東方省"),
                    ]),
                    unofficial_name_list: ["Eastern"].to_vec(),
                },
            ),
            (
                "N",
                Subdivision {
                    name: "N",
                    country_alpha2: Alpha2::SL,
                    code: "N",
                    #[cfg(feature = "geo")]
                    geo: Some(SubdivisionGeo {
                        latitude: Some(9.3500888),
                        longitude: Some(-11.7068294),
                        max_latitude: Some(10.0004329),
                        min_latitude: Some(8.241974899999999),
                        max_longitude: Some(-10.5848049),
                        min_longitude: Some(-13.3032624),
                    }),
                    comments: None,
                    subdivision_type: SubdivisionType::Province,
                    #[cfg(feature = "translations")]
                    translations: HashMap::from([
                        ("ar", "المحافظة الشمالية"),
                        ("bg", "Северна провинция"),
                        ("bn", "নর\u{9cd}দ\u{9be}ন প\u{9cd}রদেশ"),
                        (
                            "ccp",
                            "𑄅\u{1112a}𑄖\u{11133}𑄦\u{11127}𑄢\u{11134}𑄟𑄬𑄇\u{11134}𑄈𑄬",
                        ),
                        ("ceb", "Northern Province (lalawigan sa Sierra Leone)"),
                        ("da", "Northern Province"),
                        ("de", "Northern"),
                        ("el", "Βόρεια Περιφέρεια"),
                        ("en", "Northern"),
                        ("es", "Provincia del Norte"),
                        ("fa", "استان شمالی، سیرالئون"),
                        ("fi", "Pohjoinen maakunta"),
                        ("fr", "Province du Nord"),
                        ("gu", "ઉત\u{acd}તરીય પ\u{acd}રા\u{a82}ત"),
                        ("hi", "उत\u{94d}तरी प\u{94d}रा\u{902}त"),
                        ("hr", "Sjeverna provincija"),
                        ("hy", "Հյուսիսային նահանգ"),
                        ("id", "Provinsi Utara, Sierra Leone"),
                        ("it", "provincia del Nord"),
                        ("ja", "北部州"),
                        ("kn", "ಉತ\u{ccd}ತರ ಪ\u{ccd}ರಾಂತ\u{ccd}ಯ"),
                        ("ko", "북부 주"),
                        ("lt", "Šiaurės provincija"),
                        ("lv", "Ziemeļu province"),
                        ("mr", "उत\u{94d}तर प\u{94d}रा\u{902}त"),
                        ("ms", "Northern Province"),
                        ("nb", "Northern"),
                        ("nl", "Northern"),
                        ("no", "Northern"),
                        ("pl", "Prowincja Północna"),
                        ("pt", "Northern"),
                        ("ro", "Provincia de Nord, Sierra Leone"),
                        ("ru", "Северная провинция"),
                        ("si", "උත\u{dd4}ර\u{dd4} පළ\u{dcf}ත"),
                        ("sv", "Nord (provins)"),
                        ("ta", "வடக\u{bcd}கு ம\u{bbe}க\u{bbe}ணம\u{bcd}"),
                        ("te", "ఉత\u{c4d}తర ప\u{c4d}ర\u{c3e}వ\u{c3f}న\u{c4d}స\u{c4d}"),
                        ("th", "นอร\u{e4c}ทเท\u{e34}ร\u{e4c}นโพว\u{e34}\u{e49}น"),
                        ("tr", "Northern Province"),
                        ("uk", "Північна провінція (Сьєрра-Леоне)"),
                        ("ur", "شمالی صوبہ، سیرالیون"),
                        ("vi", "Tỉnh Phía Bắc"),
                        ("zh", "北方省"),
                    ]),
                    unofficial_name_list: ["Northern"].to_vec(),
                },
            ),
            (
                "NW",
                Subdivision {
                    name: "NW",
                    country_alpha2: Alpha2::SL,
                    code: "NW",
                    #[cfg(feature = "geo")]
                    geo: Some(SubdivisionGeo {
                        latitude: Some(8.460555),
                        longitude: Some(-11.779889),
                        max_latitude: Some(9.9999737),
                        min_latitude: Some(6.8446),
                        max_longitude: Some(-10.2716829),
                        min_longitude: Some(-13.4032999),
                    }),
                    comments: None,
                    subdivision_type: SubdivisionType::Province,
                    #[cfg(feature = "translations")]
                    translations: HashMap::from([("en", "North Western")]),
                    unofficial_name_list: [].to_vec(),
                },
            ),
            (
                "S",
                Subdivision {
                    name: "S",
                    country_alpha2: Alpha2::SL,
                    code: "S",
                    #[cfg(feature = "geo")]
                    geo: Some(SubdivisionGeo {
                        latitude: Some(7.790662499999999),
                        longitude: Some(-11.8891721),
                        max_latitude: Some(8.507107),
                        min_latitude: Some(6.9296111),
                        max_longitude: Some(-11.1348019),
                        min_longitude: Some(-13.0692559),
                    }),
                    comments: None,
                    subdivision_type: SubdivisionType::Province,
                    #[cfg(feature = "translations")]
                    translations: HashMap::from([
                        ("ar", "المحافظة الجنوبية"),
                        ("bg", "Южна провинция"),
                        ("bn", "দক\u{9cd}ষিণ প\u{9cd}রদেশ"),
                        ("ccp", "𑄘\u{11127}𑄊\u{11128}𑄚\u{11134}𑄟𑄬𑄇\u{11134}𑄈𑄬"),
                        ("ceb", "Southern Province"),
                        ("da", "Southern Province"),
                        ("de", "Southern"),
                        ("el", "Νότια Περιφέρεια"),
                        ("en", "Southern"),
                        ("es", "Provincia del Sur"),
                        ("fa", "استان جنوبی، سیرالئون"),
                        ("fi", "Eteläinen maakunta"),
                        ("fr", "Province du Sud"),
                        ("gl", "Provincia do Sur, Serra Leoa"),
                        ("gu", "દક\u{acd}ષિણ પ\u{acd}રા\u{a82}ત"),
                        ("hi", "दक\u{94d}षिणी प\u{94d}रा\u{902}त"),
                        ("hr", "Južna provincija"),
                        ("id", "Provinsi Selatan, Sierra Leone"),
                        ("it", "provincia del Sud"),
                        ("ja", "南部州"),
                        ("kn", "ದಕ\u{ccd}ಷ\u{cbf}ಣ ಪ\u{ccd}ರಾಂತ\u{ccd}ಯ"),
                        ("ko", "남부 주"),
                        ("lt", "Pietų provincija"),
                        ("lv", "Dienvidu province"),
                        ("mr", "दक\u{94d}षिण प\u{94d}रा\u{902}त"),
                        ("ms", "Southern Province"),
                        ("nb", "Southern"),
                        ("nl", "Southern"),
                        ("no", "Southern"),
                        ("pl", "Prowincja Południowa"),
                        ("pt", "Província do Sul"),
                        ("ro", "Provincia Southern, Sierra Leone"),
                        ("ru", "Южная провинция"),
                        ("si", "දක\u{dd4}ණ\u{dd4} පළ\u{dcf}ත"),
                        ("sv", "Södra provinsen"),
                        ("ta", "தெற\u{bcd}கு ம\u{bbe}க\u{bbe}ணம\u{bcd}"),
                        (
                            "te",
                            "దక\u{c4d}ష\u{c3f}ణ ప\u{c4d}ర\u{c3e}వ\u{c3f}న\u{c4d}స\u{c4d}",
                        ),
                        ("th", "เซาเท\u{e34}ร\u{e4c}น โพรว\u{e34}\u{e49}น"),
                        ("tr", "Southern Province"),
                        ("uk", "Південна провінція"),
                        ("ur", "جنوبی صوبہ، سیرالیون"),
                        ("vi", "Tỉnh Phía Nam"),
                        ("zh", "南方省"),
                    ]),
                    unofficial_name_list: ["Southern"].to_vec(),
                },
            ),
            (
                "W",
                Subdivision {
                    name: "W",
                    country_alpha2: Alpha2::SL,
                    code: "W",
                    #[cfg(feature = "geo")]
                    geo: Some(SubdivisionGeo {
                        latitude: Some(8.484444),
                        longitude: Some(-13.234444),
                        max_latitude: Some(8.4996723),
                        min_latitude: Some(8.4091211),
                        max_longitude: Some(-13.1487465),
                        min_longitude: Some(-13.2985468),
                    }),
                    comments: None,
                    subdivision_type: SubdivisionType::Area,
                    #[cfg(feature = "translations")]
                    translations: HashMap::from([
                        ("ar", "المقاطعة الغربية"),
                        ("be", "Заходняя вобласць, Сьера-Леонэ"),
                        ("bg", "Западна област"),
                        (
                            "bn",
                            "পশ\u{9cd}চিম\u{9be}ঞ\u{9cd}চল, সিয\u{9bc}ের\u{9be} লিওন",
                        ),
                        ("ccp", "𑄛\u{11127}𑄏\u{11128}𑄟\u{11134}𑄟𑄬𑄇\u{11134}𑄈𑄬 𑄎𑄉"),
                        ("ceb", "Western Area"),
                        ("da", "Western Area"),
                        ("de", "Western"),
                        ("el", "Δυτική Περιφέρεια"),
                        ("en", "Western Area"),
                        ("es", "Área Occidental"),
                        ("et", "Läänepiirkond"),
                        ("fi", "Läntinen alue"),
                        ("fr", "Zone de l’Ouest"),
                        ("gu", "વ\u{ac7}સ\u{acd}ટર\u{acd}ન એરિયા"),
                        ("hi", "पश\u{94d}चिमी क\u{94d}ष\u{947}त\u{94d}र"),
                        ("hr", "Zapadna zona"),
                        ("id", "Wilayah Barat"),
                        ("it", "Area occidentale della Sierra Leone"),
                        ("ja", "西部地域"),
                        ("kn", "ಪಾಶ\u{ccd}ಚಾತ\u{ccd}ಯ ಪ\u{ccd}ರದೇಶ"),
                        ("ko", "서부 구"),
                        ("lt", "Vakarų sritis"),
                        ("lv", "Rietumu apgabals"),
                        ("mr", "व\u{947}स\u{94d}टर\u{94d}न रिजन"),
                        ("ms", "Western Area"),
                        ("nb", "Western"),
                        ("nl", "Western"),
                        ("no", "Western"),
                        ("pl", "Obszar Zachodni"),
                        ("pt", "Western Area"),
                        ("ro", "Zona de Vest, Sierra Leone"),
                        ("ru", "Западная область"),
                        ("si", "බටහ\u{dd2}ර ප\u{dca}\u{200d}රදේශය"),
                        ("sv", "Freetown Peninsula"),
                        ("ta", "மேற\u{bcd}கு ஏரிய\u{bbe}"),
                        ("te", "పశ\u{c4d}చ\u{c3f}మ ప\u{c4d}ర\u{c3e}ంతం"),
                        ("th", "เวสเท\u{e34}ร\u{e4c}น เอเร\u{e35}ย"),
                        ("tr", "Western Area"),
                        ("uk", "Західний регіон"),
                        ("ur", "مغربی علاقہ"),
                        ("vi", "Khu vực Phía Tây"),
                        ("zh", "西部區"),
                    ]),
                    unofficial_name_list: ["Western Area (Freetown)"].to_vec(),
                },
            ),
        ])
    }
}
#[allow(unused_imports)]
use crate::{Alpha2, Alpha3, Continent, Country, Region, SubRegion, WeekDay, WorldRegion, GEC};
#[allow(unused_imports)]
use std::collections::HashMap;
#[cfg(feature = "sl")]
pub fn new() -> Country {
    Country {
        alpha2: Alpha2::SL,
        alpha3: Alpha3::SLE,
        address_format: None,
        continent: Continent::Africa,
        country_code: 232,
        currency_code: "SLL",
        gec: Some(GEC::SL),
        #[cfg(feature = "geo")]
        geo: geo::new(),
        international_prefix: "00",
        ioc: Some("SLE"),
        iso_long_name: "The Republic of Sierra Leone",
        iso_short_name: "Sierra Leone",
        official_language_list: ["en"].to_vec(),
        spoken_language_list: ["en"].to_vec(),
        national_destination_code_length_list: [2].to_vec(),
        national_number_length_list: [8].to_vec(),
        national_prefix: "0",
        nationality: Some("Sierra Leonean"),
        number: "694",
        postal_code: false,
        postal_code_format: None,
        region: Some(Region::Africa),
        start_of_week: WeekDay::Monday,
        subregion: Some(SubRegion::WesternAfrica),
        un_locode: "SL",
        unofficial_name_list: ["Sierra Leone", "シエラレオネ"].to_vec(),
        world_region: WorldRegion::EMEA,
        #[cfg(feature = "translations")]
        translations: HashMap::from([
            ("ab", "Sierra Leone"),
            ("af", "Siërra Leone"),
            ("ak", "Sierra Leone"),
            ("am", "ሴየራ ሌዎን"),
            ("an", "Sierra Leone"),
            ("ar", "سيراليون"),
            ("as", "চিয়েৰ\u{9be} লিওন"),
            ("ay", "Sierra Leone"),
            ("az", "Siera Lione"),
            ("ba", "Sierra Leone"),
            ("be", "Сьера-Леонэ"),
            ("bg", "Сиера Леоне"),
            ("bi", "Sierra Leone"),
            ("bn", "সিয়ের\u{9be} লিওন"),
            ("bn_IN", "সিয়ের\u{9be} লিওন"),
            ("br", "Sierra Leone"),
            ("bs", "Sierra Leone"),
            ("ca", "Sierra Leone"),
            ("ce", "Сьерра-Леоне"),
            ("ch", "Sierra Leone"),
            ("cs", "Sierra Leone"),
            ("cv", "Сьерра-Леоне"),
            ("cy", "Sierra Leone"),
            ("da", "Sierra Leone"),
            ("de", "Sierra Leone"),
            ("dv", "ސ\u{7ac}ރ\u{7ac}ލ\u{7a8}އ\u{7af}ނ\u{7b0}"),
            ("dz", "ས\u{f72}་ར་ ལ\u{f72}འ\u{f7c}་ན\u{f72}།"),
            ("ee", "Sierra Leone"),
            ("el", "Σιέρα Λεόνε"),
            ("en", "Sierra Leone"),
            ("eo", "Siera-Leono"),
            ("es", "Sierra Leona"),
            ("et", "Sierra Leone"),
            ("eu", "Sierra Leona"),
            ("fa", "سیرالئون"),
            ("ff", "Sarliyon"),
            ("fi", "Sierra Leone"),
            ("fo", "Sierra Leone"),
            ("fr", "Sierra Leone"),
            ("fy", "Sierra Leöane"),
            ("ga", "Siarra Leon"),
            ("gl", "Serra Leoa"),
            ("gn", "Sierra Leone"),
            ("gu", "સિએરા લીઓન"),
            ("gv", "Sierra Leone"),
            ("ha", "Sierra Leone"),
            ("he", "סיירה לאון"),
            ("hi", "सिएरा लियोन"),
            ("hr", "Sijera Leone"),
            ("ht", "Syera Leòn"),
            ("hu", "Sierra Leone"),
            ("hy", "Սյերա-Լեոնե"),
            ("ia", "Sierra Leone"),
            ("id", "Sierra Leone"),
            ("io", "Sierra Leone"),
            ("is", "Síerra Leóne"),
            ("it", "Sierra Leone"),
            ("iu", "Sierra Leone"),
            ("ja", "シエラレオネ"),
            ("ka", "სიერა-ლეონე"),
            ("ki", "Sierra Leone"),
            ("kk", "Сьерра-Леоне"),
            ("kl", "Sierra Leone"),
            ("km", "សេរ\u{17c9}ាឡេអ\u{17bc}ន"),
            ("kn", "Sierra Leone"),
            ("ko", "시에라리온"),
            ("ku", "Sîera Leone"),
            ("kv", "Sierra Leone"),
            ("kw", "Sierra Leon"),
            ("ky", "Сьерра-Леоне"),
            ("lo", "Sierra Leone"),
            ("lt", "Siera Leonė"),
            ("lv", "Sjerraleone"),
            ("mi", "Te Araone"),
            ("mk", "Сиера Леоне"),
            ("ml", "സിയേറ ലിയോണ\u{d4d}\u{200d}"),
            ("mn", "Сьерра-Леоне"),
            ("mr", "सिय\u{947}रा ल\u{947}ओन"),
            ("ms", "Siera Leon"),
            ("mt", "Sierra Leone"),
            (
                "my",
                "ဆ\u{102e}ရာလ\u{102e}ယ\u{103d}န\u{103a}န\u{102d}\u{102f}င\u{103a}င\u{1036}",
            ),
            ("na", "Sierra Leone"),
            ("nb", "Sierra Leone"),
            ("ne", "साइरा लिओनरा"),
            ("nl", "Sierra Leone"),
            ("nn", "Sierra Leone"),
            ("nv", "Náshdóítsoh Bitsiijįʼ Daditłʼooʼígíí Bidził"),
            ("oc", "Sierra Leone"),
            ("or", "ସ\u{b3f}ୟେର\u{b3e} ଲ\u{b3f}ୟୋନ"),
            ("pa", "ਸੀਈਰਆ ਲਿਏਨ"),
            ("pi", "सियारा-लियोन"),
            ("pl", "Sierra Leone"),
            ("ps", "سېرالیون"),
            ("pt", "Serra Leoa"),
            ("pt_BR", "Serra Leoa"),
            ("ro", "Sierra Leone"),
            ("ru", "Сьерра-Леоне"),
            ("rw", "Siyera Lewone"),
            ("sc", "Sierra Leone"),
            ("sd", "Sierra Leone"),
            ("si", "ස\u{dd2}යෙර\u{dcf} ල\u{dd2}යොන\u{dca}"),
            ("sk", "Sierra Leone"),
            ("sl", "Sierra Leone"),
            ("so", "Siraaliyoon"),
            ("sq", "Sierra Leone"),
            ("sr", "Сијера Леоне"),
            ("sv", "Sierra Leone"),
            ("sw", "Sierra Leone"),
            ("ta", "சியர\u{bbe}லியோன\u{bcd}"),
            ("te", "స\u{c3f}య\u{c47}ర\u{c3e} ల\u{c47}ఓన"),
            ("tg", "Сиерра-Леоне"),
            ("th", "เซ\u{e35}ยร\u{e4c}ราล\u{e35}โอน"),
            ("ti", "Sierra Leone"),
            ("tk", "Serra-Leone"),
            ("tl", "Sierra Leone"),
            ("tr", "Sierra Leone"),
            ("tt", "Сиерра Леоне"),
            ("ug", "سېررالېئون"),
            ("uk", "Сьєрра-Леоне"),
            ("ur", "سیرالیون"),
            ("uz", "Syerra Leone"),
            ("ve", "Sierra Leone"),
            ("vi", "Xi-ê-ra Lê-ô-nê"),
            ("wa", "Siera Leyone"),
            ("wo", "Siraa Leyoon"),
            ("xh", "Sierra Leone"),
            ("yo", "Siẹrra Léònè"),
            ("zh_CN", "塞拉利昂"),
            ("zh_HK", "塞拉利昂"),
            ("zh_TW", "獅子山"),
            ("zu", "ISiera Liyoni"),
        ]),
        #[cfg(feature = "subdivisions")]
        subdivisions: subdivisions::new(),
    }
}
