// DO NOT TOUCH THIS FILE. (Auto-generated via `code_gen/countries.rs`)

// The Republic of Senegal

#[cfg(all(feature = "sn", feature = "constants"))]
pub mod consts {
    #[allow(unused_imports)]
    use crate::{Alpha2, Alpha3, Continent, Region, SubRegion, WeekDay, WorldRegion, GEC, IOC};

    pub const ADDRESS_FORMAT: Option<&str> = None;
    pub const ALPHA2: Alpha2 = Alpha2::SN;
    pub const ALPHA3: Alpha3 = Alpha3::SEN;
    pub const CONTINENT: Continent = Continent::Africa;
    pub const COUNTRY_CODE: usize = 221;
    pub const CURRENCY_CODE: &str = "XOF";
    pub const GEC: Option<GEC> = Some(GEC::SG);
    pub const INTERNATIONAL_PREFIX: &str = "00";
    pub const IOC: Option<IOC> = Some(IOC::SEN);
    pub const ISO_SHORT_NAME: &str = "Senegal";
    pub const ISO_LONG_NAME: &str = "The Republic of Senegal";
    pub const OFFICIAL_LANGUAGE_LIST: &[&str] = &["fr"];
    pub const SPOKEN_LANGUAGE_LIST: &[&str] = &["fr"];
    pub const NATIONAL_DESTINATION_CODE_LENGTH_LIST: &[usize] = &[2];
    pub const NATIONAL_NUMBER_LENGTH_LIST: &[usize] = &[7];
    pub const NATIONAL_PREFIX: &str = "None";
    pub const NATIONALITY: Option<&str> = Some("Senegalese");
    pub const NUMBER: &str = "686";
    pub const POSTAL_CODE: bool = true;
    pub const POSTAL_CODE_FORMAT: Option<&str> = Some("\\d{5}");
    pub const REGION: Option<Region> = Some(Region::Africa);
    pub const START_DAY_OF_WEEK: WeekDay = WeekDay::Monday;
    pub const SUBREGION: Option<SubRegion> = Some(SubRegion::WesternAfrica);
    pub const UN_LOCODE: &str = "SN";
    pub const UNOFFICIAL_NAME_LIST: &[&str] = &["Senegal", "Sénégal", "セネガル"];
    pub const WORLD_REGION: WorldRegion = WorldRegion::EMEA;
    #[cfg(feature = "translations")]
    pub const TRANSLATIONS: &[(&str, &str)] = &[
        ("ab", "Senegal"),
        ("af", "Senegal"),
        ("ak", "Senegal"),
        ("am", "ሴኔጒሔ"),
        ("an", "Senegal"),
        ("ar", "الس\u{651}نغال"),
        ("as", "ছেনেগ\u{9be}ল"),
        ("ay", "Senegal"),
        ("az", "Seneqal"),
        ("ba", "Senegal"),
        ("be", "Сенегал"),
        ("bg", "Сенегал"),
        ("bi", "Senegal"),
        ("bn", "সেনেগ\u{9be}ল"),
        ("bn_IN", "সেনেগ\u{9be}ল"),
        ("br", "Senegal"),
        ("bs", "Senegal"),
        ("ca", "Senegal"),
        ("ce", "Сенегал"),
        ("ch", "Senegal"),
        ("cs", "Senegal"),
        ("cv", "Сенегал"),
        ("cy", "Senegal"),
        ("da", "Senegal"),
        ("de", "Senegal"),
        ("dv", "ސ\u{7ac}ނ\u{7ac}ގ\u{7a7}ލ\u{7b0}"),
        ("dz", "ས\u{f72}་ན\u{f72}་ག\u{f71}ལ།"),
        ("ee", "Senegal"),
        ("el", "Σενεγάλη"),
        ("en", "Senegal"),
        ("eo", "Senegalo"),
        ("es", "Senegal"),
        ("et", "Senegal"),
        ("eu", "Senegal"),
        ("fa", "سنگال"),
        ("ff", "Senegaal"),
        ("fi", "Senegal"),
        ("fo", "Senegal"),
        ("fr", "Sénégal"),
        ("fy", "Senegal"),
        ("ga", "An tSeineagáil"),
        ("gl", "Senegal"),
        ("gn", "Senegal"),
        ("gu", "સ\u{ac7}ન\u{ac7}ગલ"),
        ("gv", "Yn Tenegaal"),
        ("ha", "Senegal"),
        ("he", "סנגל"),
        ("hi", "स\u{947}न\u{947}गल"),
        ("hr", "Senegal"),
        ("ht", "Senegal"),
        ("hu", "Szenegál"),
        ("hy", "Սենեգալ"),
        ("ia", "Senegal"),
        ("id", "Senegal"),
        ("io", "Senegal"),
        ("is", "Senegal"),
        ("it", "Senegal"),
        ("iu", "Senegal"),
        ("ja", "セネガル"),
        ("ka", "სენეგალი"),
        ("ki", "Senegal"),
        ("kk", "Сенегал"),
        ("kl", "Senegal"),
        ("km", "សេណេហ\u{17d2}គាល\u{17cb}"),
        ("kn", "ಸ\u{cc6}ನ\u{cc6}ಗಾಲ\u{ccd}"),
        ("ko", "세네갈"),
        ("ku", "Senegal"),
        ("kv", "Senegal"),
        ("kw", "Senegal"),
        ("ky", "Сенегал"),
        ("lo", "Senegal"),
        ("lt", "Senegalas"),
        ("lv", "Senegāla"),
        ("mi", "Senegal"),
        ("mk", "Сенегал"),
        ("ml", "സെനഗല\u{d4d}\u{200d}"),
        ("mn", "Сингали"),
        ("mr", "स\u{947}न\u{947}गल"),
        ("ms", "Senegal"),
        ("mt", "Senegal"),
        (
            "my",
            "ဆ\u{102e}န\u{102e}ဂေါန\u{102d}\u{102f}င\u{103a}င\u{1036}",
        ),
        ("na", "Senegal"),
        ("nb", "Senegal"),
        ("ne", "स\u{947}न\u{947}गल"),
        ("nl", "Senegal"),
        ("nn", "Senegal"),
        ("nv", "Senegal"),
        ("oc", "Senegal"),
        ("or", "ସେନେଗ\u{b3e}ଲ"),
        ("pa", "ਸ\u{a48}ਨ\u{a47}ਗਾਲ"),
        ("pi", "स\u{947}न\u{947}गल"),
        ("pl", "Senegal"),
        ("ps", "سېنېګال"),
        ("pt", "Senegal"),
        ("pt_BR", "Senegal"),
        ("ro", "Senegal"),
        ("ru", "Сенегал"),
        ("rw", "Senegali"),
        ("sc", "Senegàl"),
        ("sd", "سينيگال"),
        ("si", "සෙනග\u{dcf}ලය"),
        ("sk", "Senegal"),
        ("sl", "Senegal"),
        ("so", "Senegal"),
        ("sq", "Senegal"),
        ("sr", "Сенегал"),
        ("sv", "Senegal"),
        ("sw", "Senegal"),
        ("ta", "செனகல\u{bcd}"),
        ("te", "స\u{c46}న\u{c46}గల\u{c4d}"),
        ("tg", "Сенегал"),
        ("th", "เซเนก\u{e31}ล"),
        ("ti", "ሴኔጋል"),
        ("tk", "Senegal"),
        ("tl", "Senegal"),
        ("tr", "Senegal"),
        ("tt", "Сенеgал"),
        ("ug", "سېنېگال"),
        ("uk", "Сенегал"),
        ("ur", "سینیگال"),
        ("uz", "Senegal"),
        ("ve", "Senegal"),
        ("vi", "Xê-nê-gan"),
        ("wa", "Senegål"),
        ("wo", "Senegaal"),
        ("xh", "Senegal"),
        ("yo", "Sẹ\u{300}nẹ\u{300}gàl"),
        ("zh_CN", "塞内加尔"),
        ("zh_HK", "塞內加爾"),
        ("zh_TW", "塞內加爾"),
        ("zu", "ISenegal"),
    ];
    #[cfg(all(feature = "sn", feature = "geo", feature = "constants"))]
    pub mod geo {
        pub const LATITUDE: f64 = 14.497401;
        pub const LONGITUDE: f64 = -14.452362;
        pub const MAX_LATITUDE: f64 = 16.6929572;
        pub const MAX_LONGITUDE: f64 = -11.3457683;
        pub const MIN_LATITUDE: f64 = 12.2649001;
        pub const MIN_LONGITUDE: f64 = -17.6879999;
        pub const NORTHEAST_LATITUDE: f64 = 16.6929572;
        pub const NORTHEAST_LONGITUDE: f64 = -11.3457683;
        pub const SOUTHWEST_LATITUDE: f64 = 12.2649001;
        pub const SOUTHWEST_LONGITUDE: f64 = -17.6879999;
    }
}
#[cfg(all(feature = "sn", feature = "geo"))]
pub mod geo {
    use crate::{CountryGeo, CountryGeoBound, CountryGeoBounds};

    pub fn new() -> CountryGeo {
        CountryGeo {
            latitude: 14.497401,
            longitude: -14.452362,
            max_latitude: 16.6929572,
            max_longitude: -11.3457683,
            min_latitude: 12.2649001,
            min_longitude: -17.6879999,
            bounds: CountryGeoBounds {
                northeast: CountryGeoBound {
                    latitude: 16.6929572,
                    longitude: -11.3457683,
                },
                southwest: CountryGeoBound {
                    latitude: 12.2649001,
                    longitude: -17.6879999,
                },
            },
        }
    }
}

#[cfg(all(feature = "sn", feature = "subdivisions"))]
pub mod subdivisions {
    use crate::Subdivision;
    use std::collections::HashMap;
    // In this state, We do not know if subdivisions have geo or not!
    #[cfg(feature = "geo")]
    #[allow(unused_imports)]
    use crate::{Alpha2, SubdivisionGeo, SubdivisionType};

    pub fn new() -> HashMap<&'static str, Subdivision> {
        HashMap::from([
            (
                "DB",
                Subdivision {
                    name: "DB",
                    country_alpha2: Alpha2::SN,
                    code: "DB",
                    #[cfg(feature = "geo")]
                    geo: Some(SubdivisionGeo {
                        latitude: Some(14.6561238),
                        longitude: Some(-16.2345633),
                        max_latitude: Some(14.6780086),
                        min_latitude: Some(14.6305864),
                        max_longitude: Some(-16.1984396),
                        min_longitude: Some(-16.2716103),
                    }),
                    comments: None,
                    subdivision_type: SubdivisionType::Region,
                    #[cfg(feature = "translations")]
                    translations: HashMap::from([
                        ("ar", "إقليم ديوربيل"),
                        ("bg", "Диурбел"),
                        ("bn", "ডিউরেবেল অঞ\u{9cd}চল"),
                        ("ca", "Regió de Diourbel"),
                        ("ccp", "𑄓\u{11128}𑄠\u{1112e}𑄢\u{11134}𑄝𑄬𑄣\u{11134}"),
                        ("ceb", "Diourbel"),
                        ("da", "Diourbel Region"),
                        ("de", "Region Diourbel"),
                        ("el", "Ντιουρμπέλ"),
                        ("en", "Diourbel"),
                        ("es", "Diourbel"),
                        ("eu", "Diourbel eskualdea"),
                        ("fi", "Diourbelin maakunta"),
                        ("fr", "Région de Diourbel"),
                        ("gl", "Rexión de Diourbel"),
                        ("gu", "દીઉર\u{acd}બ\u{ac7}લ પ\u{acd}રદ\u{ac7}શ"),
                        ("hi", "डिउरब\u{947}ल प\u{94d}रद\u{947}श"),
                        ("hu", "Diourbel régió"),
                        ("id", "Region Diourbel"),
                        ("it", "Diourbel"),
                        ("ja", "ジュルベル州"),
                        ("kn", "ಡ\u{cbf}ಯರ\u{ccd}ಬ\u{cc6}ಲ\u{ccd} ಪ\u{ccd}ರದೇಶ"),
                        ("ko", "디우르벨 주"),
                        ("lt", "Diurbelio regionas"),
                        ("lv", "Diūrbelas reģions"),
                        ("mr", "दिओर\u{94d}ब\u{947}ल प\u{94d}रद\u{947}श"),
                        ("ms", "Diourbel Region"),
                        ("nb", "Diourbel"),
                        ("nl", "Diourbel"),
                        ("no", "Diourbel"),
                        ("pl", "Regon Diourbel"),
                        ("pt", "Diourbel"),
                        ("ro", "Regiunea Diourbel"),
                        ("ru", "Диурбель"),
                        ("si", "ඩයෝර\u{dca}බෙල\u{dca} කල\u{dcf}පය"),
                        ("sv", "Diourbel"),
                        ("ta", "தியர\u{bcd}பேல\u{bcd} பகுதி"),
                        (
                            "te",
                            "డయ\u{c3e}ర\u{c4d}బ\u{c46}ల\u{c4d} ప\u{c4d}ర\u{c3e}ంతం",
                        ),
                        ("th", "เซาท\u{e37} ซ\u{e34}ไน โกเวอโนเรท"),
                        ("tr", "Diorbel Bölgesi"),
                        ("uk", "Регіон Діурбель"),
                        ("ur", "دیوربیل علاقہ"),
                        ("vi", "Khu vực Diourbel"),
                        ("zh", "久尔贝勒区"),
                    ]),
                    unofficial_name_list: ["Diourbel"].to_vec(),
                },
            ),
            (
                "DK",
                Subdivision {
                    name: "DK",
                    country_alpha2: Alpha2::SN,
                    code: "DK",
                    #[cfg(feature = "geo")]
                    geo: Some(SubdivisionGeo {
                        latitude: Some(14.7645042),
                        longitude: Some(-17.3660286),
                        max_latitude: Some(14.8178645),
                        min_latitude: Some(14.6469399),
                        max_longitude: Some(-17.2463906),
                        min_longitude: Some(-17.5298482),
                    }),
                    comments: None,
                    subdivision_type: SubdivisionType::Region,
                    #[cfg(feature = "translations")]
                    translations: HashMap::from([
                        ("ar", "داكار"),
                        ("be", "вобласць Дакар"),
                        ("bg", "Дакар"),
                        ("bn", "ড\u{9be}ক\u{9be}র"),
                        ("bs", "Regija Dakar"),
                        ("ccp", "𑄓𑄇𑄢\u{11134}"),
                        ("ceb", "Dakar"),
                        ("da", "Dakar"),
                        ("de", "Dakar"),
                        ("el", "Ντακάρ"),
                        ("en", "Dakar"),
                        ("es", "Dakar"),
                        ("eu", "Dakar eskualdea"),
                        ("fi", "Dagar"),
                        ("fr", "Dakar"),
                        ("gl", "Rexión de Dakar"),
                        ("gu", "ડકાર"),
                        ("hi", "डकार"),
                        ("id", "Region Dakar"),
                        ("it", "Dakar"),
                        ("ja", "ダカール州"),
                        ("kn", "ಡಾಕರ\u{ccd}"),
                        ("ko", "다카르 주"),
                        ("lt", "Dakaro regionas"),
                        ("lv", "Dakara"),
                        ("mr", "डाकार"),
                        ("ms", "Dakar"),
                        ("nb", "Dakar"),
                        ("nl", "Dakar"),
                        ("no", "Dakar"),
                        ("pl", "Dakar"),
                        ("pt", "Dakar"),
                        ("ro", "Regiunea Dakar"),
                        ("ru", "Дакар"),
                        ("si", "ඩක\u{dcf}ර\u{dca}"),
                        ("sv", "Dakar"),
                        ("ta", "தக\u{bcd}க\u{bbe}ர\u{bcd}"),
                        ("te", "డ\u{c3e}కర\u{c4d}"),
                        ("th", "เม\u{e37}องดาการ\u{e4c}"),
                        ("tr", "Dakar"),
                        ("uk", "Дакар"),
                        ("ur", "ڈاکار علاقہ"),
                        ("vi", "Dakar"),
                        ("zh", "达喀尔区"),
                    ]),
                    unofficial_name_list: ["Dakar"].to_vec(),
                },
            ),
            (
                "FK",
                Subdivision {
                    name: "FK",
                    country_alpha2: Alpha2::SN,
                    code: "FK",
                    #[cfg(feature = "geo")]
                    geo: Some(SubdivisionGeo {
                        latitude: Some(14.333333),
                        longitude: Some(-16.406944),
                        max_latitude: Some(14.3521257),
                        min_latitude: Some(14.3167832),
                        max_longitude: Some(-16.3943481),
                        min_longitude: Some(-16.4239168),
                    }),
                    comments: None,
                    subdivision_type: SubdivisionType::Region,
                    #[cfg(feature = "translations")]
                    translations: HashMap::from([
                        ("ar", "اقليم فاتيك"),
                        ("bg", "Фатик"),
                        ("bn", "ফ\u{9cd}য\u{9be}টিক"),
                        ("ccp", "𑄜𑄑\u{11128}𑄇\u{11134}"),
                        ("da", "Fatick"),
                        ("de", "Region Fatick"),
                        ("el", "Φατίκ"),
                        ("en", "Fatick"),
                        ("es", "Fatick"),
                        ("eu", "Fatick eskualdea"),
                        ("fi", "Fatick"),
                        ("fr", "Fatick"),
                        ("gl", "Rexión de Fatick"),
                        ("gu", "ફ\u{ac7}ટિક"),
                        ("hi", "फटिक"),
                        ("id", "Region Fatick"),
                        ("it", "Fatick"),
                        ("ja", "ファティック州"),
                        ("kn", "ಫ\u{ccd}ಯಾಟ\u{cbf}ಕ\u{ccd}"),
                        ("ko", "파티크 주"),
                        ("lt", "Fatiko regionas"),
                        ("lv", "Fatika"),
                        ("mr", "फातिक"),
                        ("ms", "Fatick"),
                        ("nb", "Fatick"),
                        ("nl", "Fatick"),
                        ("no", "Fatick"),
                        ("pl", "Fatick"),
                        ("pt", "Fatick"),
                        ("ro", "Regiunea Fatick"),
                        ("ru", "Фатик"),
                        ("si", "ෆැට\u{dd2}ක\u{dca}"),
                        ("sv", "Fatick"),
                        ("ta", "ப\u{bbe}டிக\u{bcd}"),
                        ("te", "ఫ\u{c3e}ట\u{c3f}క\u{c4d}"),
                        ("th", "เขตฟาทร\u{e34}ก"),
                        ("tr", "Fatick"),
                        ("uk", "Регіон Фатік"),
                        ("ur", "فاتیک علاقہ"),
                        ("vi", "Fatick"),
                        ("zh", "法蒂克区"),
                    ]),
                    unofficial_name_list: ["Fatick"].to_vec(),
                },
            ),
            (
                "KA",
                Subdivision {
                    name: "KA",
                    country_alpha2: Alpha2::SN,
                    code: "KA",
                    #[cfg(feature = "geo")]
                    geo: None,
                    comments: None,
                    subdivision_type: SubdivisionType::Region,
                    #[cfg(feature = "translations")]
                    translations: HashMap::from([
                        ("ar", "اقليم كفرين"),
                        ("bn", "ক\u{9cd}য\u{9be}ফ\u{9cd}রিন"),
                        ("ccp", "𑄇𑄜\u{11133}𑄢\u{11128}𑄚\u{11134}"),
                        ("da", "Kaffrine"),
                        ("de", "Region Kaffrine"),
                        ("el", "Καφρίν"),
                        ("en", "Kaffrine"),
                        ("es", "Kaffrine"),
                        ("eu", "Kaffrine eskualdea"),
                        ("fi", "Kaffrine"),
                        ("fr", "Kaffrine"),
                        ("gl", "Rexión de Kaffrine"),
                        ("gu", "ક\u{ac7}ફ\u{acd}રીન"),
                        ("hi", "क\u{948}फरीन"),
                        ("id", "Kaffrine"),
                        ("it", "Kaffrine"),
                        ("ja", "カフリン州"),
                        ("kn", "ಕ\u{cc6}ಫ\u{ccd}ರೈನ\u{ccd}"),
                        ("ko", "카프린 주"),
                        ("lt", "Kafrinė"),
                        ("lv", "Kafrines reģions"),
                        ("mr", "क\u{945}फ\u{94d}रीन"),
                        ("ms", "Kaffrine"),
                        ("nb", "Kaffrine"),
                        ("nl", "Kaffrine"),
                        ("no", "Kaffrine"),
                        ("pl", "Kaffrine"),
                        ("pt", "Kaffrine"),
                        ("ro", "Regiunea Kaffrine"),
                        ("ru", "Кафрин"),
                        ("si", "කෆ\u{dca}ර\u{dd2}න\u{dca}"),
                        ("sv", "Kaffrine"),
                        ("ta", "கஃரின\u{bcd}"),
                        ("te", "క\u{c3e}ఫ\u{c4d}ర\u{c3f}న\u{c4d}"),
                        ("th", "เขตคราฟฟร\u{e34}เน"),
                        ("tr", "Kaffrine"),
                        ("uk", "Регіон Кафрін"),
                        ("ur", "کفرین علاقہ"),
                        ("vi", "Kaffrine"),
                        ("zh", "卡夫林區"),
                    ]),
                    unofficial_name_list: [].to_vec(),
                },
            ),
            (
                "KD",
                Subdivision {
                    name: "KD",
                    country_alpha2: Alpha2::SN,
                    code: "KD",
                    #[cfg(feature = "geo")]
                    geo: Some(SubdivisionGeo {
                        latitude: Some(12.883333),
                        longitude: Some(-14.95),
                        max_latitude: Some(12.9560481),
                        min_latitude: Some(12.8554019),
                        max_longitude: Some(-14.9008942),
                        min_longitude: Some(-14.9931822),
                    }),
                    comments: None,
                    subdivision_type: SubdivisionType::Region,
                    #[cfg(feature = "translations")]
                    translations: HashMap::from([
                        ("ar", "كولدا"),
                        ("bg", "Колда"),
                        ("bn", "কোডল\u{9be}"),
                        ("ccp", "𑄇\u{1112e}𑄣\u{11134}𑄓"),
                        ("ceb", "Kolda"),
                        ("cs", "Kolda"),
                        ("da", "Kolda"),
                        ("de", "Region Kolda"),
                        ("el", "Κολντά"),
                        ("en", "Kolda"),
                        ("es", "Kolda"),
                        ("eu", "Kolda eskualdea"),
                        ("fi", "Kolda"),
                        ("fr", "Kolda"),
                        ("gl", "Rexión de Kolda"),
                        ("gu", "કોલ\u{acd}ડા"),
                        ("hi", "कोल\u{94d}डा"),
                        ("id", "Region Kolda"),
                        ("it", "Kolda"),
                        ("ja", "コルダ州"),
                        ("kn", "ಕೊಲ\u{ccd}ಡಾ"),
                        ("ko", "콜다 주"),
                        ("lt", "Koldos regionas"),
                        ("lv", "Kolda"),
                        ("mr", "कोल\u{94d}डा"),
                        ("ms", "Kolda"),
                        ("nb", "Kolda"),
                        ("nl", "Kolda"),
                        ("no", "Kolda"),
                        ("pl", "Kolda"),
                        ("pt", "Kolda"),
                        ("ro", "Regiunea Kolda"),
                        ("ru", "Колда"),
                        ("si", "කොල\u{dca}ඩ\u{dcf}"),
                        ("sk", "Kolda"),
                        ("sv", "Kolda"),
                        ("ta", "கொலட\u{bbe}"),
                        ("te", "క\u{c4b}ల\u{c4d}డ\u{c3e}"),
                        ("th", "เขตโคลดา"),
                        ("tr", "Kolda"),
                        ("uk", "Регіон Колда"),
                        ("ur", "کولدا علاقہ"),
                        ("vi", "Kolda"),
                        ("zh", "科爾達區"),
                    ]),
                    unofficial_name_list: ["Kolda"].to_vec(),
                },
            ),
            (
                "KE",
                Subdivision {
                    name: "KE",
                    country_alpha2: Alpha2::SN,
                    code: "KE",
                    #[cfg(feature = "geo")]
                    geo: None,
                    comments: None,
                    subdivision_type: SubdivisionType::Region,
                    #[cfg(feature = "translations")]
                    translations: HashMap::from([
                        ("ar", "كيدوغو"),
                        ("bn", "কেদ\u{9c1}গো"),
                        ("ccp", "𑄇𑄬𑄓\u{1112f}𑄉\u{1112f}"),
                        ("ceb", "Région de Kédougou"),
                        ("da", "Kédougou"),
                        ("de", "Region Kédougou"),
                        ("el", "Κεντούγκου"),
                        ("en", "Kédougou"),
                        ("es", "Kédougou"),
                        ("eu", "Kédougou eskualdea"),
                        ("fi", "Kédougoun alue"),
                        ("fr", "Kédougou"),
                        ("gl", "Rexión de Kédougou"),
                        ("gu", "ક\u{ac7}ડૌગ\u{ac2}"),
                        ("hi", "क\u{947}ड\u{942}ग\u{942}"),
                        ("id", "Kédougou"),
                        ("it", "Kédougou"),
                        ("ja", "ケドゥグ州"),
                        ("kn", "ಕ\u{cc6}ಡೊಗ\u{ccc}"),
                        ("ko", "케두구 주"),
                        ("lt", "Kedugu"),
                        ("lv", "Kēdugu"),
                        ("mr", "क\u{947}डौग\u{941}"),
                        ("ms", "Kedougou"),
                        ("nb", "Kédougou"),
                        ("nl", "Kédougou"),
                        ("no", "Kédougou"),
                        ("pl", "Kédougou"),
                        ("pt", "Kédougou"),
                        ("ro", "Regiunea Kédougou"),
                        ("ru", "Кедугу"),
                        ("si", "කෙදොග\u{dd4}"),
                        ("sv", "Kédougou"),
                        ("ta", "கெடௌகௌ"),
                        ("te", "క\u{c46}డ\u{c4b}గూ"),
                        ("th", "เคด\u{e39}ด\u{e39}"),
                        ("tr", "Kédougou"),
                        ("uk", "Регіон Кедугу"),
                        ("ur", "کیدؤگؤ علاقہ"),
                        ("vi", "Kédougou"),
                        ("zh", "凱杜古區"),
                    ]),
                    unofficial_name_list: [].to_vec(),
                },
            ),
            (
                "KL",
                Subdivision {
                    name: "KL",
                    country_alpha2: Alpha2::SN,
                    code: "KL",
                    #[cfg(feature = "geo")]
                    geo: Some(SubdivisionGeo {
                        latitude: Some(14.1652083),
                        longitude: Some(-16.0757749),
                        max_latitude: Some(14.1926668),
                        min_latitude: Some(14.1218433),
                        max_longitude: Some(-16.0231304),
                        min_longitude: Some(-16.1165143),
                    }),
                    comments: None,
                    subdivision_type: SubdivisionType::Region,
                    #[cfg(feature = "translations")]
                    translations: HashMap::from([
                        ("ar", "كاولاك"),
                        ("bg", "Каолак"),
                        ("bn", "ক\u{9be}ওল\u{9be}ক"),
                        ("ccp", "𑄇𑄠\u{1112e}𑄣𑄇\u{11134}"),
                        ("ceb", "Kaolack"),
                        ("da", "Kaolack"),
                        ("de", "Region Kaolack"),
                        ("el", "Καολάκ"),
                        ("en", "Kaolack"),
                        ("es", "Kaolack"),
                        ("eu", "Kaolack eskualdea"),
                        ("fi", "Kaolackin alue"),
                        ("fr", "Kaolack"),
                        ("gl", "Rexión de Kaolack"),
                        ("gu", "ક\u{ac7}ઓલ\u{ac7}ક"),
                        ("hi", "काओल\u{948}क"),
                        ("id", "Region Kaolack"),
                        ("it", "Kaolack"),
                        ("ja", "カオラック州"),
                        ("kn", "ಕಾಲೋಕ\u{ccd}"),
                        ("ko", "카올라크 주"),
                        ("lt", "Kaolako regionas"),
                        ("lv", "Kaulaka"),
                        ("mr", "क\u{945}ओक\u{945}क"),
                        ("ms", "Kaolack"),
                        ("nb", "Kaolack"),
                        ("nl", "Kaolack"),
                        ("no", "Kaolack"),
                        ("pl", "Kaolack"),
                        ("pt", "Kaolack"),
                        ("ro", "Regiunea Kaolack"),
                        ("ru", "Каолак"),
                        ("si", "ක\u{dcf}ඕලැක\u{dca}"),
                        ("sv", "Kaolack"),
                        ("ta", "கலோக\u{bcd}"),
                        ("te", "క\u{c3e}వ\u{c4b}ల\u{c3e}క\u{c4d}"),
                        ("th", "เคาก\u{e4c}แลค"),
                        ("tr", "kaolack"),
                        ("uk", "Каолак"),
                        ("ur", "کاولاک علاقہ"),
                        ("vi", "Kaolack"),
                        ("zh", "考拉克区"),
                    ]),
                    unofficial_name_list: ["Kaolack"].to_vec(),
                },
            ),
            (
                "LG",
                Subdivision {
                    name: "LG",
                    country_alpha2: Alpha2::SN,
                    code: "LG",
                    #[cfg(feature = "geo")]
                    geo: Some(SubdivisionGeo {
                        latitude: Some(15.616667),
                        longitude: Some(-16.216667),
                        max_latitude: Some(15.6584121),
                        min_latitude: Some(15.5760808),
                        max_longitude: Some(-16.1677551),
                        min_longitude: Some(-16.273842),
                    }),
                    comments: None,
                    subdivision_type: SubdivisionType::Region,
                    #[cfg(feature = "translations")]
                    translations: HashMap::from([
                        ("ar", "إقليم لوغا"),
                        ("be", "Луга"),
                        ("bg", "Луга"),
                        ("bn", "ল\u{9c1}গ\u{9be}"),
                        ("ccp", "𑄣\u{1112f}𑄉"),
                        ("ceb", "Louga"),
                        ("cs", "Louga"),
                        ("da", "Louga"),
                        ("de", "Region Louga"),
                        ("el", "Λουγκά"),
                        ("en", "Louga"),
                        ("es", "Louga"),
                        ("eu", "Louga eskualdea"),
                        ("fi", "Louga"),
                        ("fr", "Louga"),
                        ("gl", "Rexión de Louga"),
                        ("gu", "લૌગા"),
                        ("hi", "ल\u{942}गा प\u{94d}रद\u{947}श"),
                        ("id", "Region Louga"),
                        ("it", "Louga"),
                        ("ja", "ルーガ州"),
                        ("kn", "ಲ\u{ccc}ಗಾ"),
                        ("ko", "루가 주"),
                        ("lt", "Lugos regionas"),
                        ("lv", "Lugas reģions"),
                        ("mr", "ल\u{942}गा"),
                        ("ms", "Louga"),
                        ("nb", "Louga"),
                        ("nl", "Louga"),
                        ("no", "Louga"),
                        ("pl", "Louga"),
                        ("pt", "Louga"),
                        ("ro", "Regiunea Louga"),
                        ("ru", "Луга"),
                        ("si", "ලොඋග\u{dcf}"),
                        ("sk", "Louga"),
                        ("sv", "Louga"),
                        ("ta", "லூக\u{bcd}க\u{bbe}"),
                        ("te", "ల\u{c4c}గ\u{c3e}"),
                        ("th", "ล\u{e31}วกา"),
                        ("tr", "Louga"),
                        ("uk", "Регіон Луга"),
                        ("ur", "لؤگا علاقہ"),
                        ("vi", "Louga"),
                        ("zh", "盧加區"),
                    ]),
                    unofficial_name_list: ["Louga"].to_vec(),
                },
            ),
            (
                "MT",
                Subdivision {
                    name: "MT",
                    country_alpha2: Alpha2::SN,
                    code: "MT",
                    #[cfg(feature = "geo")]
                    geo: Some(SubdivisionGeo {
                        latitude: Some(15.6600225),
                        longitude: Some(-13.2576906),
                        max_latitude: Some(15.6690317),
                        min_latitude: Some(15.6390722),
                        max_longitude: Some(-13.2462503),
                        min_longitude: Some(-13.2636738),
                    }),
                    comments: None,
                    subdivision_type: SubdivisionType::Region,
                    #[cfg(feature = "translations")]
                    translations: HashMap::from([
                        ("ar", "ماتام"),
                        ("bg", "Матам"),
                        ("bn", "ম\u{9be}ত\u{9be}ম"),
                        ("ccp", "𑄟𑄑𑄟\u{11134}"),
                        ("ceb", "Matam"),
                        ("da", "Matam"),
                        ("de", "Region Matam"),
                        ("el", "Ματάμ"),
                        ("en", "Matam"),
                        ("es", "Matam"),
                        ("eu", "Matam eskualdea"),
                        ("fi", "Matam"),
                        ("fr", "Matam"),
                        ("gl", "Rexión de Matam"),
                        ("gu", "માતમ"),
                        ("hi", "मतम"),
                        ("id", "Region Matam"),
                        ("it", "Matam"),
                        ("ja", "マタム州"),
                        ("kn", "ಮಾತಮ\u{ccd}"),
                        ("ko", "마탐 주"),
                        ("lt", "Matamo regionas"),
                        ("lv", "Matama"),
                        ("mr", "मातम"),
                        ("ms", "Matam"),
                        ("nb", "Matam"),
                        ("nl", "Matam"),
                        ("no", "Matam"),
                        ("pl", "Matam"),
                        ("pt", "Matam"),
                        ("ro", "Regiunea Matam"),
                        ("ru", "Матам"),
                        ("si", "මටම\u{dca}"),
                        ("sv", "Matam"),
                        ("ta", "மதம\u{bcd}"),
                        ("te", "మ\u{c3e}టమ\u{c4d}"),
                        ("th", "มป\u{e39}มาลานกา"),
                        ("tr", "Matam"),
                        ("uk", "Регіон Матам"),
                        ("ur", "ماتام علاقہ"),
                        ("vi", "Matam"),
                        ("zh", "馬塔姆區"),
                    ]),
                    unofficial_name_list: ["Matam"].to_vec(),
                },
            ),
            (
                "SE",
                Subdivision {
                    name: "SE",
                    country_alpha2: Alpha2::SN,
                    code: "SE",
                    #[cfg(feature = "geo")]
                    geo: None,
                    comments: None,
                    subdivision_type: SubdivisionType::Region,
                    #[cfg(feature = "translations")]
                    translations: HashMap::from([
                        ("ar", "سيدهيو"),
                        ("be", "рэгіён Седзіу"),
                        ("bn", "সেধিউ"),
                        ("ccp", "𑄥𑄬𑄙\u{11128}𑄠\u{1112e}"),
                        ("ceb", "Région de Sédhiou"),
                        ("da", "Sédhiou"),
                        ("de", "Region Sédhiou"),
                        ("el", "Σεντιού"),
                        ("en", "Sédhiou"),
                        ("es", "Sédhiou"),
                        ("eu", "Sédhiou eskualdea"),
                        ("fi", "Sédhiou"),
                        ("fr", "Sédhiou"),
                        ("gl", "Rexión de Sédhiou"),
                        ("gu", "સ\u{ac7}ધિઓ"),
                        ("hi", "स\u{947}दियोऊ"),
                        ("id", "Sédhiou"),
                        ("it", "Sédhiou"),
                        ("ja", "セディウ州"),
                        ("kn", "ಸ\u{cc6}ಡ\u{cbf}ಯ\u{cc2}"),
                        ("ko", "세디우 주"),
                        ("lt", "Sediju regionas"),
                        ("lv", "Sēgu"),
                        ("mr", "स\u{947}धियो"),
                        ("ms", "Sedhiou"),
                        ("nb", "Sédhiou"),
                        ("nl", "Sédhiou"),
                        ("no", "Sédhiou"),
                        ("pl", "Sédhiou"),
                        ("pt", "Região de Sédhiou"),
                        ("ro", "Regiunea Sédhiou"),
                        ("ru", "Седиу"),
                        ("si", "සෙදෞ"),
                        ("sq", "Rajoni Sédhiou"),
                        ("sv", "Sédhiou"),
                        ("ta", "சேதிய"),
                        ("te", "స\u{c46}ద\u{c3f}య\u{c4b}"),
                        ("th", "เซดเฮ\u{e35}ยว"),
                        ("tr", "Sédhiou"),
                        ("uk", "Регіон Седіу"),
                        ("ur", "سیدھیو علاقہ"),
                        ("vi", "Sédhiou"),
                        ("zh", "塞久區"),
                    ]),
                    unofficial_name_list: [].to_vec(),
                },
            ),
            (
                "SL",
                Subdivision {
                    name: "SL",
                    country_alpha2: Alpha2::SN,
                    code: "SL",
                    #[cfg(feature = "geo")]
                    geo: Some(SubdivisionGeo {
                        latitude: Some(16.0326307),
                        longitude: Some(-16.4818167),
                        max_latitude: Some(16.0760986),
                        min_latitude: Some(15.9638125),
                        max_longitude: Some(-16.403041),
                        min_longitude: Some(-16.5135574),
                    }),
                    comments: None,
                    subdivision_type: SubdivisionType::Region,
                    #[cfg(feature = "translations")]
                    translations: HashMap::from([
                        ("ar", "إقليم سانت لويس"),
                        ("bg", "Сен-Луи"),
                        ("bn", "সেন\u{9cd}ট ল\u{9c1}ইস"),
                        ("ca", "regió de Saint-Louis"),
                        (
                            "ccp",
                            "𑄥𑄬𑄚\u{11134}𑄑\u{11134}-𑄣\u{1112a}𑄃\u{11128}𑄌\u{11134}",
                        ),
                        ("ceb", "Saint-Louis"),
                        ("da", "Saint-Louis"),
                        ("de", "Region Saint-Louis"),
                        ("el", "Σεν Λουί"),
                        ("en", "Saint-Louis"),
                        ("es", "Saint-Louis"),
                        ("eu", "Saint-Louis eskualdea"),
                        ("fi", "Saint-Louis"),
                        ("fr", "Saint-Louis"),
                        ("gl", "Rexión de Saint-Louis"),
                        ("gu", "સ\u{ac7}ન\u{acd}ટ લ\u{ac2}ઇસ"),
                        ("hi", "स\u{947}\u{902}ट-ल\u{941}इ प\u{94d}रद\u{947}श"),
                        ("id", "Region Saint-Louis"),
                        ("it", "Saint-Louis"),
                        ("ja", "サンルイ州"),
                        ("kn", "ಸೇಂಟ\u{ccd} ಲ\u{cc2}ಯ\u{cbf}ಸ\u{ccd}"),
                        ("ko", "생루이 주"),
                        ("lt", "Sen Luji regionas"),
                        ("lv", "Senluisa"),
                        ("mr", "स\u{947}\u{902}ट ल\u{941}ईस"),
                        ("ms", "Saint-Louis"),
                        ("nb", "Saint-Louis"),
                        ("nl", "Saint-Louis"),
                        ("no", "Saint-Louis"),
                        ("pl", "Saint-Louis"),
                        ("pt", "Saint-Louis"),
                        ("ro", "Regiunea Saint-Louis"),
                        ("ru", "Сен-Луи"),
                        ("si", "ශ\u{dcf}න\u{dca}ත-ල\u{dd4}ව\u{dd2}ස\u{dca}"),
                        ("sv", "Saint-Louis"),
                        ("ta", "செயின\u{bcd}ட\u{bcd} -லூயிஸ\u{bcd}"),
                        ("te", "స\u{c46}య\u{c3f}ంట\u{c4d}-లూయ\u{c40}"),
                        ("th", "เซนต\u{e4c} ล\u{e39}อ\u{e34}ส"),
                        ("tr", "Saint-Louis"),
                        ("uk", "Регіон Сент-Луїс"),
                        ("ur", "سینٹ-لوئیس ریجن"),
                        ("vi", "Saint-Louis"),
                        ("zh", "聖路易區"),
                    ]),
                    unofficial_name_list: ["Saint-Louis"].to_vec(),
                },
            ),
            (
                "TC",
                Subdivision {
                    name: "TC",
                    country_alpha2: Alpha2::SN,
                    code: "TC",
                    #[cfg(feature = "geo")]
                    geo: Some(SubdivisionGeo {
                        latitude: Some(13.768889),
                        longitude: Some(-13.667222),
                        max_latitude: Some(13.7971567),
                        min_latitude: Some(13.7446376),
                        max_longitude: Some(-13.6352349),
                        min_longitude: Some(-13.7030293),
                    }),
                    comments: None,
                    subdivision_type: SubdivisionType::Region,
                    #[cfg(feature = "translations")]
                    translations: HashMap::from([
                        ("ar", "إقليم تامباكوندا"),
                        ("bg", "Тамбакунда"),
                        (
                            "bn",
                            "ত\u{9be}ম\u{9cd}ব\u{9be}ক\u{9c1}ন\u{9cd}ড\u{9be} অঞ\u{9cd}চল",
                        ),
                        ("ca", "Tambacounda"),
                        ("ccp", "𑄑𑄟\u{11134}𑄝𑄇\u{1112f}𑄅\u{1112a}𑄚\u{11134}𑄓"),
                        ("ceb", "Tambacounda"),
                        ("cs", "Tambacounda"),
                        ("da", "Tambacounda Region"),
                        ("de", "Region Tambacounda"),
                        ("el", "Ταμπακούντα"),
                        ("en", "Tambacounda"),
                        ("es", "Región de Tambacounda"),
                        ("eu", "Tambacounda eskualdea"),
                        ("fi", "Tambacoundan maakunta"),
                        ("fr", "Tambacounda"),
                        ("gl", "Rexión de Tambacounda"),
                        ("gu", "ટ\u{ac7}મ\u{acd}બકોન\u{acd}ડા પ\u{acd}રદ\u{ac7}શ"),
                        ("hi", "ताम\u{94d}बाक\u{941}\u{902}डा प\u{94d}रद\u{947}श"),
                        ("id", "Region Tambacounda"),
                        ("it", "regione di Tambacounda"),
                        ("ja", "タンバクンダ州"),
                        ("kn", "ತಂಬಾಕ\u{ccc}ಂಡಾ ಪ\u{ccd}ರದೇಶ"),
                        ("ko", "탐바쿤다 주"),
                        ("lt", "Tambakundos regionas"),
                        ("lv", "Tambakundas reģions"),
                        ("mr", "ट\u{947}म\u{94d}बाबा\u{902}डा प\u{94d}रद\u{947}श"),
                        ("ms", "Tambacounda Region"),
                        ("nb", "Rambacounda region"),
                        ("nl", "Tambacounda"),
                        ("no", "Rambacounda region"),
                        ("pl", "Region Tambacounda"),
                        ("pt", "Tambacounda"),
                        ("ro", "Regiunea Tambacounda"),
                        ("ru", "Тамбакунда"),
                        ("si", "ටම\u{dca}බක\u{dd4}න\u{dca}ඩ\u{dcf} කල\u{dcf}පය"),
                        ("sv", "Tambacounda"),
                        ("ta", "டம\u{bcd}பகொண\u{bcd}ட\u{bbe} பகுதி"),
                        (
                            "te",
                            "ట\u{c3e}ంబ\u{c3e}క\u{c4c}ండ\u{c3e} ప\u{c4d}ర\u{c3e}ంతం",
                        ),
                        ("th", "จ\u{e31}งหว\u{e31}ดส\u{e38}โขท\u{e31}ย"),
                        ("tr", "Tambacounda Bölgesi"),
                        ("uk", "Регіон Тамбакунда"),
                        ("ur", "تامباکؤندا علاقہ"),
                        ("vi", "Khu vực Tambacounda"),
                        ("zh", "坦巴昆達區"),
                    ]),
                    unofficial_name_list: ["Tambacounda"].to_vec(),
                },
            ),
            (
                "TH",
                Subdivision {
                    name: "TH",
                    country_alpha2: Alpha2::SN,
                    code: "TH",
                    #[cfg(feature = "geo")]
                    geo: Some(SubdivisionGeo {
                        latitude: Some(14.766667),
                        longitude: Some(-16.9),
                        max_latitude: Some(14.8497212),
                        min_latitude: Some(14.7351422),
                        max_longitude: Some(-16.8717166),
                        min_longitude: Some(-16.9828215),
                    }),
                    comments: None,
                    subdivision_type: SubdivisionType::Region,
                    #[cfg(feature = "translations")]
                    translations: HashMap::from([
                        ("ar", "ثيس"),
                        ("be", "вобласць Ціес"),
                        ("bg", "Тиес"),
                        ("bn", "থিস"),
                        ("ccp", "𑄗\u{1112d}𑄌\u{11134}"),
                        ("ceb", "Région de Thiès"),
                        ("da", "Thiès"),
                        ("de", "Region Thiès"),
                        ("el", "Τιες"),
                        ("en", "Thiès"),
                        ("es", "Thiès"),
                        ("eu", "Thiès eskualdea"),
                        ("fa", "منطقه تی\u{200c}یس"),
                        ("fi", "Thiès"),
                        ("fr", "Thiès"),
                        ("gl", "Rexión de Thiès"),
                        ("gu", "થિઝ"),
                        ("hi", "थीस"),
                        ("id", "Region Thiès"),
                        ("it", "Thiès"),
                        ("ja", "ティエス州"),
                        ("kn", "ಥೀಸ\u{ccd}"),
                        ("ko", "티에스 주"),
                        ("lt", "Tieso regionas"),
                        ("lv", "Tjesas reģions"),
                        ("mr", "थीस"),
                        ("ms", "Thies"),
                        ("nb", "Thiès"),
                        ("nl", "Thiès"),
                        ("no", "Thiès"),
                        ("pl", "Thiès"),
                        ("pt", "Thiès"),
                        ("ro", "Regiunea Thiès"),
                        ("ru", "Тиес"),
                        ("si", "ත\u{dcf}ය\u{dd2}ස\u{dca}"),
                        ("sv", "Thiès"),
                        ("ta", "திஸ\u{bcd}"),
                        ("te", "థ\u{c40}స\u{c4d}"),
                        ("th", "ท\u{e35}ส"),
                        ("tr", "Thiès"),
                        ("uk", "Регіон Тієс"),
                        ("ur", "تھیس علاقہ"),
                        ("vi", "Thiès"),
                        ("zh", "捷斯區"),
                    ]),
                    unofficial_name_list: ["Thiès"].to_vec(),
                },
            ),
            (
                "ZG",
                Subdivision {
                    name: "ZG",
                    country_alpha2: Alpha2::SN,
                    code: "ZG",
                    #[cfg(feature = "geo")]
                    geo: Some(SubdivisionGeo {
                        latitude: Some(12.583333),
                        longitude: Some(-16.266667),
                        max_latitude: Some(12.5895155),
                        min_latitude: Some(12.5297862),
                        max_longitude: Some(-16.2420399),
                        min_longitude: Some(-16.3063271),
                    }),
                    comments: None,
                    subdivision_type: SubdivisionType::Region,
                    #[cfg(feature = "translations")]
                    translations: HashMap::from([
                        ("ar", "زينغشور"),
                        ("bg", "Зигиншор"),
                        ("bn", "জিগ\u{9c1}ইনক\u{9be}"),
                        ("ca", "Regió de Ziguinchor"),
                        (
                            "ccp",
                            "𑄎\u{11128}𑄉\u{1112d}\u{1112a}𑄚\u{11134}𑄇\u{1112e}𑄢\u{11134}",
                        ),
                        ("ceb", "Ziguinchor"),
                        ("cs", "Ziguinchor"),
                        ("da", "Ziguinchor"),
                        ("de", "Region Ziguinchor"),
                        ("el", "Ζιγκινσόρ"),
                        ("en", "Ziguinchor"),
                        ("es", "Ziguinchor"),
                        ("eu", "Ziguinchor eskualdea"),
                        ("fa", "ناحیه زیگینچور"),
                        ("fi", "Ziguinchor"),
                        ("fr", "Ziguinchor"),
                        ("gl", "Rexión de Ziguinchor"),
                        ("gu", "ઝિગ\u{acd}વિન\u{acd}ચોર"),
                        ("hi", "ज\u{93c}िग\u{941}इनिचर क\u{94d}ष\u{947}त\u{94d}र"),
                        ("id", "Region Ziguinchor"),
                        ("it", "Ziguinchor"),
                        ("ja", "ジガンショール州"),
                        ("kn", "ಝ\u{cbf}ಗುನ\u{ccd}ಚೋರ\u{ccd}"),
                        ("ko", "지긴쇼르 주"),
                        ("lt", "Ziginšoro regionas"),
                        ("lv", "Ziginšora"),
                        ("mr", "झिग\u{941}इन\u{94d}चॉर"),
                        ("ms", "Ziguinchor"),
                        ("nb", "Ziguinchor"),
                        ("nl", "Ziguinchor"),
                        ("no", "Ziguinchor"),
                        ("pl", "Ziguinchor"),
                        ("pt", "Ziguinchor"),
                        ("ru", "Зигиншор"),
                        ("si", "ස\u{dd2}ග\u{dd4}ය\u{dd2}න\u{dca}කොර\u{dca}"),
                        ("sv", "Ziguinchor"),
                        ("ta", "ஜிகின\u{bcd}சோர\u{bcd}"),
                        ("te", "జ\u{c40}గ\u{c3f}ంక\u{c4b}ర\u{c4d}"),
                        ("th", "ซ\u{e34}ก\u{e34}นชอร\u{e4c}"),
                        ("tr", "Ziguinchor"),
                        ("uk", "Регіон Зігіншор"),
                        ("ur", "زیگینچور علاقہ"),
                        ("vi", "Ziguinchor"),
                        ("zh", "济金绍尔区"),
                    ]),
                    unofficial_name_list: ["Ziguinchor"].to_vec(),
                },
            ),
        ])
    }
}
#[allow(unused_imports)]
use crate::{
    Alpha2, Alpha3, Continent, Country, Region, SubRegion, WeekDay, WorldRegion, GEC, IOC,
};
#[allow(unused_imports)]
use std::collections::HashMap;
#[cfg(feature = "sn")]
pub fn new() -> Country {
    Country {
        alpha2: Alpha2::SN,
        alpha3: Alpha3::SEN,
        address_format: None,
        continent: Continent::Africa,
        country_code: 221,
        currency_code: "XOF",
        gec: Some(GEC::SG),
        #[cfg(feature = "geo")]
        geo: geo::new(),
        international_prefix: "00",
        ioc: Some(IOC::SEN),
        iso_long_name: "The Republic of Senegal",
        iso_short_name: "Senegal",
        official_language_list: ["fr"].to_vec(),
        spoken_language_list: ["fr"].to_vec(),
        national_destination_code_length_list: [2].to_vec(),
        national_number_length_list: [7].to_vec(),
        national_prefix: "None",
        nationality: Some("Senegalese"),
        number: "686",
        postal_code: true,
        postal_code_format: Some("\\d{5}"),
        region: Some(Region::Africa),
        start_of_week: WeekDay::Monday,
        subregion: Some(SubRegion::WesternAfrica),
        un_locode: "SN",
        unofficial_name_list: ["Senegal", "Sénégal", "セネガル"].to_vec(),
        world_region: WorldRegion::EMEA,
        #[cfg(feature = "translations")]
        translations: HashMap::from([
            ("ab", "Senegal"),
            ("af", "Senegal"),
            ("ak", "Senegal"),
            ("am", "ሴኔጒሔ"),
            ("an", "Senegal"),
            ("ar", "الس\u{651}نغال"),
            ("as", "ছেনেগ\u{9be}ল"),
            ("ay", "Senegal"),
            ("az", "Seneqal"),
            ("ba", "Senegal"),
            ("be", "Сенегал"),
            ("bg", "Сенегал"),
            ("bi", "Senegal"),
            ("bn", "সেনেগ\u{9be}ল"),
            ("bn_IN", "সেনেগ\u{9be}ল"),
            ("br", "Senegal"),
            ("bs", "Senegal"),
            ("ca", "Senegal"),
            ("ce", "Сенегал"),
            ("ch", "Senegal"),
            ("cs", "Senegal"),
            ("cv", "Сенегал"),
            ("cy", "Senegal"),
            ("da", "Senegal"),
            ("de", "Senegal"),
            ("dv", "ސ\u{7ac}ނ\u{7ac}ގ\u{7a7}ލ\u{7b0}"),
            ("dz", "ས\u{f72}་ན\u{f72}་ག\u{f71}ལ།"),
            ("ee", "Senegal"),
            ("el", "Σενεγάλη"),
            ("en", "Senegal"),
            ("eo", "Senegalo"),
            ("es", "Senegal"),
            ("et", "Senegal"),
            ("eu", "Senegal"),
            ("fa", "سنگال"),
            ("ff", "Senegaal"),
            ("fi", "Senegal"),
            ("fo", "Senegal"),
            ("fr", "Sénégal"),
            ("fy", "Senegal"),
            ("ga", "An tSeineagáil"),
            ("gl", "Senegal"),
            ("gn", "Senegal"),
            ("gu", "સ\u{ac7}ન\u{ac7}ગલ"),
            ("gv", "Yn Tenegaal"),
            ("ha", "Senegal"),
            ("he", "סנגל"),
            ("hi", "स\u{947}न\u{947}गल"),
            ("hr", "Senegal"),
            ("ht", "Senegal"),
            ("hu", "Szenegál"),
            ("hy", "Սենեգալ"),
            ("ia", "Senegal"),
            ("id", "Senegal"),
            ("io", "Senegal"),
            ("is", "Senegal"),
            ("it", "Senegal"),
            ("iu", "Senegal"),
            ("ja", "セネガル"),
            ("ka", "სენეგალი"),
            ("ki", "Senegal"),
            ("kk", "Сенегал"),
            ("kl", "Senegal"),
            ("km", "សេណេហ\u{17d2}គាល\u{17cb}"),
            ("kn", "ಸ\u{cc6}ನ\u{cc6}ಗಾಲ\u{ccd}"),
            ("ko", "세네갈"),
            ("ku", "Senegal"),
            ("kv", "Senegal"),
            ("kw", "Senegal"),
            ("ky", "Сенегал"),
            ("lo", "Senegal"),
            ("lt", "Senegalas"),
            ("lv", "Senegāla"),
            ("mi", "Senegal"),
            ("mk", "Сенегал"),
            ("ml", "സെനഗല\u{d4d}\u{200d}"),
            ("mn", "Сингали"),
            ("mr", "स\u{947}न\u{947}गल"),
            ("ms", "Senegal"),
            ("mt", "Senegal"),
            (
                "my",
                "ဆ\u{102e}န\u{102e}ဂေါန\u{102d}\u{102f}င\u{103a}င\u{1036}",
            ),
            ("na", "Senegal"),
            ("nb", "Senegal"),
            ("ne", "स\u{947}न\u{947}गल"),
            ("nl", "Senegal"),
            ("nn", "Senegal"),
            ("nv", "Senegal"),
            ("oc", "Senegal"),
            ("or", "ସେନେଗ\u{b3e}ଲ"),
            ("pa", "ਸ\u{a48}ਨ\u{a47}ਗਾਲ"),
            ("pi", "स\u{947}न\u{947}गल"),
            ("pl", "Senegal"),
            ("ps", "سېنېګال"),
            ("pt", "Senegal"),
            ("pt_BR", "Senegal"),
            ("ro", "Senegal"),
            ("ru", "Сенегал"),
            ("rw", "Senegali"),
            ("sc", "Senegàl"),
            ("sd", "سينيگال"),
            ("si", "සෙනග\u{dcf}ලය"),
            ("sk", "Senegal"),
            ("sl", "Senegal"),
            ("so", "Senegal"),
            ("sq", "Senegal"),
            ("sr", "Сенегал"),
            ("sv", "Senegal"),
            ("sw", "Senegal"),
            ("ta", "செனகல\u{bcd}"),
            ("te", "స\u{c46}న\u{c46}గల\u{c4d}"),
            ("tg", "Сенегал"),
            ("th", "เซเนก\u{e31}ล"),
            ("ti", "ሴኔጋል"),
            ("tk", "Senegal"),
            ("tl", "Senegal"),
            ("tr", "Senegal"),
            ("tt", "Сенеgал"),
            ("ug", "سېنېگال"),
            ("uk", "Сенегал"),
            ("ur", "سینیگال"),
            ("uz", "Senegal"),
            ("ve", "Senegal"),
            ("vi", "Xê-nê-gan"),
            ("wa", "Senegål"),
            ("wo", "Senegaal"),
            ("xh", "Senegal"),
            ("yo", "Sẹ\u{300}nẹ\u{300}gàl"),
            ("zh_CN", "塞内加尔"),
            ("zh_HK", "塞內加爾"),
            ("zh_TW", "塞內加爾"),
            ("zu", "ISenegal"),
        ]),
        #[cfg(feature = "subdivisions")]
        subdivisions: subdivisions::new(),
    }
}
