// DO NOT TOUCH THIS FILE. (Auto-generated via `code_gen/countries.rs`)

// The Federal Republic of Somalia

#[cfg(all(feature = "so", feature = "constants"))]
pub mod consts {
    #[allow(unused_imports)]
    use crate::{
        Alpha2, Alpha3, Continent, CurrencyCode, Region, SubRegion, WeekDay, WorldRegion, GEC, IOC,
    };

    pub const ADDRESS_FORMAT: Option<&str> = None;
    pub const ALPHA2: Alpha2 = Alpha2::SO;
    pub const ALPHA3: Alpha3 = Alpha3::SOM;
    pub const CONTINENT: Continent = Continent::Africa;
    pub const COUNTRY_CODE: usize = 252;
    pub const CURRENCY_CODE: CurrencyCode = CurrencyCode::SOS;
    pub const GEC: Option<GEC> = Some(GEC::SO);
    pub const INTERNATIONAL_PREFIX: &str = "00";
    pub const IOC: Option<IOC> = Some(IOC::SOM);
    pub const ISO_SHORT_NAME: &str = "Somalia";
    pub const ISO_LONG_NAME: &str = "The Federal Republic of Somalia";
    pub const OFFICIAL_LANGUAGE_LIST: &[&str] = &["ar", "so"];
    pub const SPOKEN_LANGUAGE_LIST: &[&str] = &["ar", "so"];
    pub const NATIONAL_DESTINATION_CODE_LENGTH_LIST: &[usize] = &[2];
    pub const NATIONAL_NUMBER_LENGTH_LIST: &[usize] = &[7, 8];
    pub const NATIONAL_PREFIX: &str = "None";
    pub const NATIONALITY: Option<&str> = Some("Somali");
    pub const NUMBER: &str = "706";
    pub const POSTAL_CODE: bool = true;
    pub const POSTAL_CODE_FORMAT: Option<&str> = Some("[A-Z]{2} ?\\d{5}");
    pub const REGION: Option<Region> = Some(Region::Africa);
    pub const START_DAY_OF_WEEK: WeekDay = WeekDay::Monday;
    pub const SUBREGION: Option<SubRegion> = Some(SubRegion::EasternAfrica);
    pub const UN_LOCODE: &str = "SO";
    pub const UNOFFICIAL_NAME_LIST: &[&str] = &["Somalia", "الصومال", "ソマリア", "Somalië"];
    pub const WORLD_REGION: WorldRegion = WorldRegion::EMEA;
    #[cfg(feature = "translations")]
    pub const TRANSLATIONS: &[(&str, &str)] = &[
        ("ab", "Somalia"),
        ("af", "Somalië"),
        ("ak", "Somalia"),
        ("am", "ሱሢሓ"),
        ("an", "Somalia"),
        ("ar", "الصومال"),
        ("as", "ছোম\u{9be}লিয়\u{9be}"),
        ("ay", "Somalia"),
        ("az", "Somali"),
        ("ba", "Somalia"),
        ("be", "Самалі"),
        ("bg", "Сомалия"),
        ("bi", "Somalia"),
        ("bn", "সোম\u{9be}লিয়\u{9be}"),
        ("bn_IN", "সোম\u{9be}লিয়\u{9be}"),
        ("br", "Somalia"),
        ("bs", "Somalija"),
        ("ca", "Somàlia"),
        ("ce", "Сомали"),
        ("ch", "Somalia"),
        ("cs", "Somálsko"),
        ("cv", "Сомали"),
        ("cy", "Somalia"),
        ("da", "Somalia"),
        ("de", "Somalia"),
        ("dv", "ސ\u{7af}މ\u{7a7}ލ\u{7a8}އ\u{7a7}"),
        ("dz", "ས\u{f7c}་མ་ལ\u{f72}་ཡ།"),
        ("ee", "Somalia"),
        ("el", "Σομαλία"),
        ("en", "Somalia"),
        ("eo", "Somalio"),
        ("es", "Somalia"),
        ("et", "Somaalia"),
        ("eu", "Somalia"),
        ("fa", "سومالی"),
        ("ff", "Somaaliya"),
        ("fi", "Somalia"),
        ("fo", "Somalia"),
        ("fr", "Somalie"),
        ("fy", "Somaalje"),
        ("ga", "An tSomáil"),
        ("gl", "Somalia"),
        ("gn", "Somalia"),
        ("gu", "સોમાલિયા"),
        ("gv", "Yn Tomaal"),
        ("ha", "Somaliya"),
        ("he", "סומליה"),
        ("hi", "सोमालिया"),
        ("hr", "Somalija"),
        ("ht", "Somali"),
        ("hu", "Szomália"),
        ("hy", "Սոմալի"),
        ("ia", "Somalia"),
        ("id", "Somalia"),
        ("io", "Somalia"),
        ("is", "Sómalía"),
        ("it", "Somalia"),
        ("iu", "Somalia"),
        ("ja", "ソマリア"),
        ("ka", "სომალი"),
        ("ki", "Somalia"),
        ("kk", "Сомали"),
        ("kl", "Somalia"),
        ("km", "ស\u{17bc}ម\u{17c9}ាល\u{17b8}"),
        ("kn", "ಸೋಮಾಲ\u{cbf}ಯಾ"),
        ("ko", "소말리아"),
        ("ku", "Somalî"),
        ("kv", "Somalia"),
        ("kw", "Somali"),
        ("ky", "Сомали"),
        ("lo", "Somalia"),
        ("lt", "Somalis"),
        ("lv", "Somālija"),
        ("mi", "Somalia"),
        ("mk", "Сомалија"),
        ("ml", "സോമ\u{d3e}ലിയ"),
        ("mn", "Сомали"),
        ("mr", "सोमालिया"),
        ("ms", "Somalia"),
        ("mt", "Somalja"),
        (
            "my",
            "ဆ\u{102d}\u{102f}မာလ\u{102e}ယာန\u{102d}\u{102f}င\u{103a}င\u{1036}",
        ),
        ("na", "Tomariya"),
        ("nb", "Somalia"),
        ("ne", "सोमालिया"),
        ("nl", "Somalië"),
        ("nn", "Somalia"),
        ("nv", "Soomáálii Bikéyah"),
        ("oc", "Somalia"),
        ("or", "ସୋମ\u{b3e}ଲ\u{b3f}ୟ\u{b3e}"),
        ("pa", "ਸ\u{a4b}ਮਾਲੀਆ"),
        ("pi", "सोमालिया"),
        ("pl", "Somalia"),
        ("ps", "سومالیا"),
        ("pt", "Somália"),
        ("pt_BR", "Somália"),
        ("ro", "Somalia"),
        ("ru", "Сомали"),
        ("rw", "Somaliya"),
        ("sc", "Somàlia"),
        ("sd", "صوماليه"),
        ("si", "සෝම\u{dcf}ල\u{dd2}ය\u{dcf}ව"),
        ("sk", "Somálsko"),
        ("sl", "Somalija"),
        ("so", "Soomaaliya"),
        ("sq", "Somali"),
        ("sr", "Сомалија"),
        ("sv", "Somalia"),
        ("sw", "Somalia"),
        ("ta", "சோம\u{bbe}லிய\u{bbe}"),
        ("te", "స\u{c4b}మ\u{c3e}ల\u{c3f}య\u{c3e}"),
        ("tg", "Сомалӣ"),
        ("th", "โซมาเล\u{e35}ย"),
        ("ti", "ሶማልያ"),
        ("tk", "Somalia"),
        ("tl", "Somalia"),
        ("tr", "Somali"),
        ("tt", "Сомалиа"),
        ("ug", "سومالى"),
        ("uk", "Сомалі"),
        ("ur", "صومالیہ"),
        ("uz", "Somali"),
        ("ve", "Somalia"),
        ("vi", "Xo-ma-li"),
        ("wa", "Somaleye"),
        ("wo", "Somaali"),
        ("xh", "Somalia"),
        ("yo", "Sòmálíà"),
        ("zh_CN", "索马里"),
        ("zh_HK", "索馬里"),
        ("zh_TW", "索馬利亞"),
        ("zu", "ISomalia"),
    ];
    #[cfg(all(feature = "so", feature = "geo", feature = "constants"))]
    pub mod geo {
        pub const LATITUDE: f64 = 5.152149;
        pub const LONGITUDE: f64 = 46.199616;
        pub const MAX_LATITUDE: f64 = 12.3615;
        pub const MAX_LONGITUDE: f64 = 51.6138;
        pub const MIN_LATITUDE: f64 = -1.8673;
        pub const MIN_LONGITUDE: f64 = 40.994373;
        pub const NORTHEAST_LATITUDE: f64 = 12.3615;
        pub const NORTHEAST_LONGITUDE: f64 = 51.6138;
        pub const SOUTHWEST_LATITUDE: f64 = -1.8673;
        pub const SOUTHWEST_LONGITUDE: f64 = 40.994373;
    }
}
#[cfg(all(feature = "so", feature = "geo"))]
pub mod geo {
    use crate::{CountryGeo, CountryGeoBound, CountryGeoBounds};

    pub fn new() -> CountryGeo {
        CountryGeo {
            latitude: 5.152149,
            longitude: 46.199616,
            max_latitude: 12.3615,
            max_longitude: 51.6138,
            min_latitude: -1.8673,
            min_longitude: 40.994373,
            bounds: CountryGeoBounds {
                northeast: CountryGeoBound {
                    latitude: 12.3615,
                    longitude: 51.6138,
                },
                southwest: CountryGeoBound {
                    latitude: -1.8673,
                    longitude: 40.994373,
                },
            },
        }
    }
}

#[cfg(all(feature = "so", feature = "subdivisions"))]
pub mod subdivisions {
    use crate::Subdivision;
    use std::collections::HashMap;
    // In this state, We do not know if subdivisions have geo or not!
    #[cfg(feature = "geo")]
    #[allow(unused_imports)]
    use crate::{Alpha2, SubdivisionGeo, SubdivisionType};

    pub fn new() -> HashMap<&'static str, Subdivision> {
        HashMap::from([
            (
                "AW",
                Subdivision {
                    name: "AW",
                    country_alpha2: Alpha2::SO,
                    code: "AW",
                    #[cfg(feature = "geo")]
                    geo: Some(SubdivisionGeo {
                        latitude: Some(10.6334285),
                        longitude: Some(43.329466),
                        max_latitude: Some(11.5114751),
                        min_latitude: Some(9.721214999999999),
                        max_longitude: Some(44.2172924),
                        min_longitude: Some(42.68300989999999),
                    }),
                    comments: None,
                    subdivision_type: SubdivisionType::Region,
                    #[cfg(feature = "translations")]
                    translations: HashMap::from([
                        ("ar", "عدل"),
                        ("bg", "Аудал"),
                        ("ca", "Awdal"),
                        ("ccp", "𑄃\u{11127}𑄓𑄣\u{11134}"),
                        ("ceb", "Gobolka Awdal"),
                        ("cs", "Awdal"),
                        ("da", "Awdal"),
                        ("de", "Awdal"),
                        ("en", "Awdal"),
                        ("es", "Awdal"),
                        ("eu", "Awdal"),
                        ("fi", "Awdal"),
                        ("fr", "Awdal"),
                        ("id", "Awdal"),
                        ("it", "Adal"),
                        ("ja", "アウダル州"),
                        ("jv", "Awdal"),
                        ("ka", "ავდალის რეგიონი"),
                        ("ko", "아우달 주"),
                        ("nl", "Awdal"),
                        ("pl", "Awdal"),
                        ("pt", "Awdal"),
                        ("ru", "Авдал"),
                        ("so", "Awdal"),
                        ("sv", "Awdal"),
                        ("tr", "Adal"),
                        ("uk", "Авдал"),
                        ("ur", "عدل علاقہ"),
                        ("zh", "奥达勒州"),
                    ]),
                    unofficial_name_list: ["Awdal"].to_vec(),
                },
            ),
            (
                "BK",
                Subdivision {
                    name: "BK",
                    country_alpha2: Alpha2::SO,
                    code: "BK",
                    #[cfg(feature = "geo")]
                    geo: Some(SubdivisionGeo {
                        latitude: Some(4.3657221),
                        longitude: Some(44.0960311),
                        max_latitude: Some(4.960437),
                        min_latitude: Some(3.529067),
                        max_longitude: Some(44.617615),
                        min_longitude: Some(42.750198),
                    }),
                    comments: None,
                    subdivision_type: SubdivisionType::Region,
                    #[cfg(feature = "translations")]
                    translations: HashMap::from([
                        ("ar", "باكول"),
                        ("bg", "Бакол"),
                        ("bn", "ব\u{9be}ক\u{9c1}ল"),
                        ("ca", "Bakool"),
                        ("ccp", "𑄝𑄇\u{1112b}𑄣\u{11134}"),
                        ("ceb", "Gobolka Bakool"),
                        ("da", "Bakool"),
                        ("de", "Bakool"),
                        ("el", "Μπακούλ"),
                        ("en", "Bakool"),
                        ("es", "Bakool"),
                        ("eu", "Bakool"),
                        ("fi", "Bakool"),
                        ("fr", "Bakool"),
                        ("gu", "બાક\u{ac2}લ"),
                        ("hi", "बाक\u{941}ल"),
                        ("id", "Bakool"),
                        ("it", "Bakool"),
                        ("ja", "バコール州"),
                        ("jv", "Bakool"),
                        ("ka", "ბაკულის რეგიონი"),
                        ("kn", "ಬಾಕ\u{cc2}ಲ\u{ccd}"),
                        ("ko", "바콜 주"),
                        ("lt", "Bakulas"),
                        ("lv", "Bakūla"),
                        ("mr", "बाक\u{942}ल"),
                        ("ms", "Bakool"),
                        ("nb", "Bakool"),
                        ("nl", "Bakool"),
                        ("no", "Bakool"),
                        ("pl", "Bakool"),
                        ("pt", "Bakool"),
                        ("ru", "Баколь"),
                        ("si", "බක\u{dd6}ල\u{dca}"),
                        ("so", "Bakool"),
                        ("sv", "Bakool"),
                        ("ta", "பகோள\u{bcd}"),
                        ("te", "బకూల\u{c4d}"),
                        ("th", "บาก\u{e39}ล"),
                        ("tr", "Bakul"),
                        ("uk", "Баколь"),
                        ("ur", "باکول"),
                        ("vi", "Bakool"),
                        ("zh", "巴科勒州"),
                    ]),
                    unofficial_name_list: ["Bakool"].to_vec(),
                },
            ),
            (
                "BN",
                Subdivision {
                    name: "BN",
                    country_alpha2: Alpha2::SO,
                    code: "BN",
                    #[cfg(feature = "geo")]
                    geo: Some(SubdivisionGeo {
                        latitude: Some(2.1187375),
                        longitude: Some(45.3369459),
                        max_latitude: Some(2.195059),
                        min_latitude: Some(1.9337841),
                        max_longitude: Some(45.5860699),
                        min_longitude: Some(45.14145629999999),
                    }),
                    comments: None,
                    subdivision_type: SubdivisionType::Region,
                    #[cfg(feature = "translations")]
                    translations: HashMap::from([
                        ("ar", "بنادر"),
                        ("bn", "ব\u{9be}ন\u{9be}দির"),
                        ("ca", "Banaadir"),
                        ("ccp", "𑄝𑄚\u{11133}𑄃𑄓\u{11128}𑄢\u{11134}"),
                        ("ceb", "Gobolka Banaadir"),
                        ("da", "Banaadir"),
                        ("de", "Banaadir"),
                        ("el", "Μπανααντίρ"),
                        ("en", "Banaadir"),
                        ("es", "Benadir"),
                        ("eu", "Banaadir"),
                        ("fa", "بنادر"),
                        ("fi", "Banaadir"),
                        ("fr", "Banaadir"),
                        ("gu", "બનાદિર"),
                        ("hi", "बानादीर"),
                        ("id", "Banaadir"),
                        ("it", "Benadir"),
                        ("ja", "バナディール州"),
                        ("jv", "Banaadir"),
                        ("ka", "ბენადირის რეგიონი"),
                        ("kn", "ಬನಾಡ\u{cbf}ರ\u{ccd}"),
                        ("ko", "바나디르 주"),
                        ("lt", "Benadiras"),
                        ("lv", "Banādira"),
                        ("mr", "बानादीर"),
                        ("ms", "Banaadir"),
                        ("nb", "Banaadir"),
                        ("nl", "Banaadir"),
                        ("no", "Banaadir"),
                        ("pl", "Banaadir"),
                        ("pt", "Banaadir"),
                        ("ru", "Банадир"),
                        ("si", "බන\u{dcf}ද\u{dd3}ර\u{dca}"),
                        ("so", "Banaadir"),
                        ("sv", "Banaadir"),
                        ("ta", "பந\u{bbe}டிர\u{bcd}"),
                        ("te", "బన\u{c3e}డ\u{c3f}ర\u{c4d}"),
                        ("th", "บานาเด\u{e35}ยร\u{e4c}"),
                        ("tr", "Banaadir"),
                        ("uk", "Бенадір"),
                        ("ur", "بنادر"),
                        ("vi", "Banaadir"),
                        ("zh", "巴納迪爾州"),
                    ]),
                    unofficial_name_list: ["Banaadir"].to_vec(),
                },
            ),
            (
                "BR",
                Subdivision {
                    name: "BR",
                    country_alpha2: Alpha2::SO,
                    code: "BR",
                    #[cfg(feature = "geo")]
                    geo: Some(SubdivisionGeo {
                        latitude: Some(10.1203847),
                        longitude: Some(49.6911374),
                        max_latitude: Some(11.9852029),
                        min_latitude: Some(8.326447),
                        max_longitude: Some(51.4130282),
                        min_longitude: Some(48.906651),
                    }),
                    comments: None,
                    subdivision_type: SubdivisionType::Region,
                    #[cfg(feature = "translations")]
                    translations: HashMap::from([
                        ("ar", "باري"),
                        ("bg", "Бари"),
                        ("bn", "ব\u{9be}রি"),
                        ("ca", "Bari"),
                        ("ccp", "𑄝𑄢\u{11128}"),
                        ("ceb", "Gobolka Bari"),
                        ("da", "Bari"),
                        ("de", "Bari"),
                        ("el", "Μπάρι"),
                        ("en", "Bari"),
                        ("es", "Bari"),
                        ("et", "Bari ringkond"),
                        ("eu", "Bari"),
                        ("fi", "Bari"),
                        ("fr", "Bari"),
                        ("gu", "બારી"),
                        ("hi", "बारी"),
                        ("id", "Bari"),
                        ("it", "Bari"),
                        ("ja", "バリ州"),
                        ("jv", "Bari, Somalia"),
                        ("ka", "ბარის რეგიონი"),
                        ("kn", "ಬಾರ\u{cbf}"),
                        ("ko", "바리 주"),
                        ("lt", "Baris"),
                        ("lv", "Bari"),
                        ("mr", "बारी"),
                        ("ms", "Bari"),
                        ("nb", "Bari"),
                        ("nl", "Bari"),
                        ("no", "Bari"),
                        ("pl", "Bari"),
                        ("pt", "Bari"),
                        ("ru", "Бари"),
                        ("si", "බ\u{dcf}ර\u{dd2}"),
                        ("so", "Bari"),
                        ("sv", "Bari"),
                        ("ta", "பரி"),
                        ("te", "బ\u{c3e}ర\u{c3f}"),
                        ("th", "บาร\u{e34}"),
                        ("tr", "Bari"),
                        ("uk", "Барі"),
                        ("ur", "باری، صومالیہ"),
                        ("vi", "Bari"),
                        ("zh", "巴里州"),
                    ]),
                    unofficial_name_list: ["Bari"].to_vec(),
                },
            ),
            (
                "BY",
                Subdivision {
                    name: "BY",
                    country_alpha2: Alpha2::SO,
                    code: "BY",
                    #[cfg(feature = "geo")]
                    geo: Some(SubdivisionGeo {
                        latitude: Some(2.4825193),
                        longitude: Some(43.483738),
                        max_latitude: Some(3.543456),
                        min_latitude: Some(1.625444),
                        max_longitude: Some(44.63283209999999),
                        min_longitude: Some(42.3411179),
                    }),
                    comments: None,
                    subdivision_type: SubdivisionType::Region,
                    #[cfg(feature = "translations")]
                    translations: HashMap::from([
                        ("ar", "باي"),
                        ("bg", "Бай"),
                        ("bn", "বে"),
                        ("ca", "Bay (Somàlia)"),
                        ("ccp", "𑄝𑄬, 𑄥\u{1112e}𑄟𑄣\u{11128}𑄠"),
                        ("ceb", "Gobolka Bay"),
                        ("da", "Baay"),
                        ("de", "Bay"),
                        ("el", "Μπέι"),
                        ("en", "Bay, Somalia"),
                        ("es", "Bay (Somalia)"),
                        ("eu", "Bay (Somalia)"),
                        ("fi", "Bay"),
                        ("fr", "Bay (Somalie)"),
                        ("gu", "બ\u{ac7}"),
                        ("hi", "ब\u{947}, सोमालिया"),
                        ("id", "Bay"),
                        ("it", "Bai"),
                        ("ja", "ベイ州"),
                        ("jv", "Bay, Somalia"),
                        ("ka", "ბეის რეგიონი"),
                        ("kn", "ಬೇ"),
                        ("ko", "바이 주"),
                        ("lt", "Baja"),
                        ("lv", "Bāja"),
                        ("mr", "ब\u{947}"),
                        ("ms", "Bay"),
                        ("nb", "Bay"),
                        ("nl", "Bay"),
                        ("no", "Bay"),
                        ("pl", "Bay"),
                        ("pt", "Bay (Somália)"),
                        ("ro", "Bay, Somalia"),
                        ("ru", "Бай"),
                        ("si", "බේ"),
                        ("so", "Baay"),
                        ("sv", "Bay (Somalien)"),
                        ("ta", "பே"),
                        ("te", "బ\u{c47}"),
                        ("th", "เบย\u{e4c}"),
                        ("tr", "Bay"),
                        ("uk", "Бай"),
                        ("ur", "بای، صومالیہ"),
                        ("vi", "Bay"),
                        ("zh", "拜州"),
                    ]),
                    unofficial_name_list: ["Bay"].to_vec(),
                },
            ),
            (
                "GA",
                Subdivision {
                    name: "GA",
                    country_alpha2: Alpha2::SO,
                    code: "GA",
                    #[cfg(feature = "geo")]
                    geo: Some(SubdivisionGeo {
                        latitude: Some(5.1850128),
                        longitude: Some(46.8252838),
                        max_latitude: Some(6.221599899999999),
                        min_latitude: Some(3.5412981),
                        max_longitude: Some(47.939419),
                        min_longitude: Some(45.5051261),
                    }),
                    comments: None,
                    subdivision_type: SubdivisionType::Region,
                    #[cfg(feature = "translations")]
                    translations: HashMap::from([
                        ("ar", "جلجدود"),
                        ("bg", "Галгудууд"),
                        ("bn", "গেল\u{9cd}গ\u{9c1}দ\u{9c1}দ"),
                        ("ca", "Galguduud"),
                        ("ccp", "𑄉\u{11133}𑄠𑄣\u{11134}𑄉\u{1112a}𑄓\u{1112b}𑄖\u{11134}"),
                        ("ceb", "Gobolka Galguduud"),
                        ("da", "Galguduud"),
                        ("de", "Galguduud"),
                        ("el", "Γκαλγκουντουούντ"),
                        ("en", "Galguduud"),
                        ("es", "Galguduud"),
                        ("eu", "Galguduud"),
                        ("fi", "Galguduud"),
                        ("fr", "Galguduud"),
                        ("gu", "ગાલગ\u{ac1}ડ\u{ac1}ડ"),
                        ("hi", "ग\u{948}लग\u{941}ड\u{942}ड"),
                        ("id", "Galguduud"),
                        ("it", "Galgudud"),
                        ("ja", "ガルグドゥード州"),
                        ("jv", "Galguduud"),
                        ("ka", "გალგუდუდის რეგიონი"),
                        ("kn", "ಗಾಲ\u{ccd}ಗುಡುಡ\u{ccd}"),
                        ("ko", "갈구두드 주"),
                        ("lt", "Galgududas"),
                        ("lv", "Galgududa"),
                        ("mr", "गालग\u{941}ड\u{942}ड"),
                        ("ms", "Galguduud"),
                        ("nb", "Galguduud"),
                        ("nl", "Galguduud"),
                        ("no", "Galguduud"),
                        ("pl", "Galguduud"),
                        ("pt", "Galguduud"),
                        ("ru", "Галгудуд"),
                        ("si", "ගලග\u{dd4}ඩ\u{dd4}ඩ\u{dca}"),
                        ("so", "Galguduud"),
                        ("sv", "Galguduud"),
                        ("ta", "கல\u{bcd}குடுட\u{bcd}"),
                        ("te", "గ\u{c3e}ల\u{c4d}గుడూడ\u{c4d}"),
                        ("th", "ก\u{e31}ลก\u{e39}ด\u{e39}ด"),
                        ("tr", "Galgudud"),
                        ("uk", "Галгудуд"),
                        ("ur", "جلجدود"),
                        ("vi", "Galguduud"),
                        ("zh", "加勒古杜德州"),
                    ]),
                    unofficial_name_list: ["Galguduud"].to_vec(),
                },
            ),
            (
                "GE",
                Subdivision {
                    name: "GE",
                    country_alpha2: Alpha2::SO,
                    code: "GE",
                    #[cfg(feature = "geo")]
                    geo: Some(SubdivisionGeo {
                        latitude: Some(3.5039227),
                        longitude: Some(42.2362435),
                        max_latitude: Some(4.264552999999999),
                        min_latitude: Some(2.28444),
                        max_longitude: Some(43.004589),
                        min_longitude: Some(40.992082),
                    }),
                    comments: None,
                    subdivision_type: SubdivisionType::Region,
                    #[cfg(feature = "translations")]
                    translations: HashMap::from([
                        ("ar", "جدو"),
                        ("bg", "Гедо"),
                        ("bn", "গেডো"),
                        ("ca", "Gedo"),
                        ("ccp", "𑄉𑄬𑄓\u{1112e}"),
                        ("ceb", "Gobolka Gedo"),
                        ("da", "Geedo"),
                        ("de", "Gedo"),
                        ("el", "Γκέντο"),
                        ("en", "Gedo"),
                        ("es", "Gedo"),
                        ("eu", "Gedo"),
                        ("fi", "Gedo"),
                        ("fr", "Gedo"),
                        ("gu", "ગ\u{ac7}ડો"),
                        ("hi", "ग\u{947}डो"),
                        ("id", "Gedo"),
                        ("it", "Ghedo"),
                        ("ja", "ゲド州"),
                        ("jv", "Gedo"),
                        ("ka", "გედოს რეგიონი"),
                        ("kn", "ಗ\u{cc6}ಡೋ"),
                        ("ko", "게도 주"),
                        ("lt", "Gedas"),
                        ("lv", "Gedo"),
                        ("mr", "ग\u{947}डो"),
                        ("ms", "Gedo"),
                        ("nb", "Gedo"),
                        ("nl", "Gedo"),
                        ("no", "Gedo"),
                        ("pl", "Gedo"),
                        ("pt", "Gedo"),
                        ("ru", "Гедо"),
                        ("si", "ගෙඩෝ"),
                        ("so", "Gedo"),
                        ("sv", "Gedo"),
                        ("ta", "ஜெடோ"),
                        ("te", "గ\u{c46}డ\u{c4b}"),
                        ("th", "เกโด"),
                        ("tr", "Gedo"),
                        ("uk", "Гедо"),
                        ("ur", "جدو"),
                        ("vi", "Gedo"),
                        ("zh", "蓋多州"),
                    ]),
                    unofficial_name_list: ["Gedo"].to_vec(),
                },
            ),
            (
                "HI",
                Subdivision {
                    name: "HI",
                    country_alpha2: Alpha2::SO,
                    code: "HI",
                    #[cfg(feature = "geo")]
                    geo: Some(SubdivisionGeo {
                        latitude: Some(4.321015),
                        longitude: Some(45.29938620000001),
                        max_latitude: Some(5.454314),
                        min_latitude: Some(3.3195169),
                        max_longitude: Some(46.361508),
                        min_longitude: Some(44.4159971),
                    }),
                    comments: None,
                    subdivision_type: SubdivisionType::Region,
                    #[cfg(feature = "translations")]
                    translations: HashMap::from([
                        ("ar", "هيران"),
                        ("bg", "Хираан"),
                        ("bn", "হিরন"),
                        ("ca", "Hiiraan"),
                        ("ccp", "𑄦\u{11128}𑄢\u{11127}𑄚\u{11134}"),
                        ("ceb", "Gobolka Hiiraan"),
                        ("da", "Hiiraan"),
                        ("de", "Hiiraan"),
                        ("el", "Χιράν"),
                        ("en", "Hiran"),
                        ("es", "Hiiraan"),
                        ("eu", "Hiiraan"),
                        ("fi", "Hiiraan"),
                        ("fr", "Hiiraan"),
                        ("gu", "હિરન"),
                        ("hi", "हिरान"),
                        ("id", "Hiiraan"),
                        ("it", "Hiran"),
                        ("ja", "ヒーラーン州"),
                        ("jv", "Hiiraan"),
                        ("ka", "ჰირანის რეგიონი"),
                        ("kn", "ಹ\u{cbf}ರಾನ\u{ccd}"),
                        ("ko", "히란 주"),
                        ("lt", "Hiranas"),
                        ("lv", "Hīrāna"),
                        ("mr", "हिरण"),
                        ("ms", "Hiran"),
                        ("nb", "Hiiraan"),
                        ("nl", "Hiiraan"),
                        ("no", "Hiiraan"),
                        ("pl", "Hiran"),
                        ("pt", "Hiiraan"),
                        ("ru", "Хиран"),
                        ("si", "හ\u{dd2}ර\u{dcf}න\u{dca}"),
                        ("so", "Hiiraan"),
                        ("sv", "Hiiraan"),
                        ("ta", "ஹிர\u{bbe}ன\u{bcd}"),
                        ("te", "హ\u{c3f}ర\u{c3e}న\u{c4d}"),
                        ("th", "ซาโปรอซย\u{e48}า โอแบลส"),
                        ("tr", "Hiran"),
                        ("uk", "Хіран"),
                        ("ur", "ہیران، صومالیہ"),
                        ("vi", "Hiran"),
                        ("zh", "希蘭州"),
                    ]),
                    unofficial_name_list: ["Hiiraan"].to_vec(),
                },
            ),
            (
                "JD",
                Subdivision {
                    name: "JD",
                    country_alpha2: Alpha2::SO,
                    code: "JD",
                    #[cfg(feature = "geo")]
                    geo: Some(SubdivisionGeo {
                        latitude: Some(2.0780488),
                        longitude: Some(41.6011814),
                        max_latitude: Some(2.38058),
                        min_latitude: Some(0.352452),
                        max_longitude: Some(43.4949649),
                        min_longitude: Some(40.990269),
                    }),
                    comments: None,
                    subdivision_type: SubdivisionType::Region,
                    #[cfg(feature = "translations")]
                    translations: HashMap::from([
                        ("ar", "جوبا الوسطى"),
                        ("bg", "Юбада Дексе"),
                        ("bn", "মধ\u{9cd}য য\u{9c1}ব\u{9be}"),
                        ("ca", "Jubbada Dhexe"),
                        ("ccp", "𑄟\u{11128}𑄓\u{11127}𑄣\u{11134} 𑄎\u{1112a}𑄝"),
                        ("ceb", "Gobolka Jubbada Dhexe"),
                        ("da", "Jubbada Dhexe"),
                        ("de", "Jubbada Dhexe"),
                        ("el", "Μίντλ Τζούμπα"),
                        ("en", "Middle Juba"),
                        ("es", "Jubbada Dhexe"),
                        ("eu", "Jubbada Dhexe"),
                        ("fi", "Keski-Juba"),
                        ("fr", "Jubbada Dhexe"),
                        ("gu", "મિડલ જ\u{ac1}બા"),
                        ("he", "ג׳ובה המרכזית"),
                        ("hi", "मध\u{94d}य ज\u{942}बा"),
                        ("id", "Middle Juba"),
                        ("it", "Medio Giuba"),
                        ("ja", "中部ジュバ州"),
                        ("jv", "Jubbada Dhexe"),
                        ("ka", "შუა ჯუბის რეგიონი"),
                        ("kn", "ಮಧ\u{ccd}ಯ ಜುಬಾ"),
                        ("ko", "주바다데헤 주"),
                        ("lt", "Vidurinioji Džuba"),
                        ("lv", "Vidusdžūba"),
                        ("mr", "मिडल य\u{941}बा"),
                        ("ms", "Middle Juba"),
                        ("nb", "Jubbada Dhexe"),
                        ("nl", "Jubbada Dhexe"),
                        ("no", "Jubbada Dhexe"),
                        ("pl", "Dżuba Środkowa"),
                        ("pt", "Jubbada Dhexe"),
                        ("ru", "Средняя Джубба"),
                        ("si", "මද\u{dca}\u{200d}යම ජ\u{dd4}බ\u{dcf}"),
                        ("so", "Jubbada Dhexe"),
                        ("sv", "Jubbada Dhexe"),
                        ("ta", "மிடில\u{bcd} ஜூப\u{bbe}"),
                        ("te", "మ\u{c3f}డ\u{c3f}ల\u{c4d} జూబ\u{c3e}"),
                        ("th", "จ\u{e39}เด\u{e35}ยกลาง"),
                        ("tr", "Orta Cuba"),
                        ("uk", "Середня Джуба"),
                        ("ur", "وسطی جوبا"),
                        ("vi", "Middle Juba"),
                        ("zh", "中朱巴州"),
                    ]),
                    unofficial_name_list: ["Jubbada Dhexe"].to_vec(),
                },
            ),
            (
                "JH",
                Subdivision {
                    name: "JH",
                    country_alpha2: Alpha2::SO,
                    code: "JH",
                    #[cfg(feature = "geo")]
                    geo: Some(SubdivisionGeo {
                        latitude: Some(0.224021),
                        longitude: Some(41.6011814),
                        max_latitude: Some(1.382667),
                        min_latitude: Some(-1.6541275),
                        max_longitude: Some(43.2361241),
                        min_longitude: Some(40.9886321),
                    }),
                    comments: None,
                    subdivision_type: SubdivisionType::Region,
                    #[cfg(feature = "translations")]
                    translations: HashMap::from([
                        ("ar", "جوبا السفلى"),
                        ("bg", "Юбада Хуусе"),
                        ("bn", "লোয\u{9bc}\u{9be}র জ\u{9c1}ব\u{9be}"),
                        ("ca", "Jubbada Hoose"),
                        ("ccp", "𑄣\u{1112e}𑄠𑄢\u{11134} 𑄎\u{1112a}𑄝"),
                        ("ceb", "Gobolka Jubbada Hoose"),
                        ("cs", "Jižní Džuba"),
                        ("da", "Jubbada Hoose"),
                        ("de", "Jubbada Hoose"),
                        ("el", "Λόουερ Τζούμπα"),
                        ("en", "Lower Juba"),
                        ("es", "Jubbada Hoose"),
                        ("eu", "Jubbada Hoose"),
                        ("fi", "Ala-Juba"),
                        ("fr", "Jubbada Hoose"),
                        ("gu", "લોવર જ\u{ac1}બા"),
                        ("he", "ג׳ובה תחתית"),
                        ("hi", "निचला ज\u{941}बा"),
                        ("id", "Lower Juba"),
                        ("it", "Basso Giuba"),
                        ("ja", "下部ジュバ州"),
                        ("ka", "ქვემო ჯუბის რეგიონი"),
                        ("kn", "ಲೋ ಜುಬಾ"),
                        ("ko", "주바다호세 주"),
                        ("lt", "Žemutinė Džuba"),
                        ("lv", "Lejasdžūba"),
                        ("mr", "लोअर ज\u{941}बा"),
                        ("ms", "Lower Juba"),
                        ("nb", "Nedre Juba"),
                        ("nl", "Jubbada Hoose"),
                        ("no", "Nedre Juba"),
                        ("pl", "Dżuba Dolna"),
                        ("pt", "Jubbada Hoose"),
                        ("ru", "Нижняя Джубба"),
                        ("si", "පහල ජ\u{dd4}බ\u{dcf}"),
                        ("so", "Jubbada Hoose"),
                        ("sv", "Nedre Juba"),
                        ("ta", "லோயர\u{bcd} ஜூப\u{bbe}"),
                        ("te", "ల\u{c4b}యర\u{c4d} జూబ\u{c3e}"),
                        ("th", "จ\u{e31}บบาดาฮ\u{e39}ส"),
                        ("tr", "Aşağı Cubba"),
                        ("uk", "Нижня Джуба"),
                        ("ur", "زیریں جوبا"),
                        ("vi", "Hạ Juba"),
                        ("zh", "下朱巴州"),
                    ]),
                    unofficial_name_list: ["Jubbada Hoose"].to_vec(),
                },
            ),
            (
                "MU",
                Subdivision {
                    name: "MU",
                    country_alpha2: Alpha2::SO,
                    code: "MU",
                    #[cfg(feature = "geo")]
                    geo: Some(SubdivisionGeo {
                        latitude: Some(6.5656726),
                        longitude: Some(47.7637565),
                        max_latitude: Some(7.797689),
                        min_latitude: Some(4.427916),
                        max_longitude: Some(49.635255),
                        min_longitude: Some(46.2261429),
                    }),
                    comments: None,
                    subdivision_type: SubdivisionType::Region,
                    #[cfg(feature = "translations")]
                    translations: HashMap::from([
                        ("ar", "مدج"),
                        ("bg", "Мудуг"),
                        ("bn", "ম\u{9c1}দ\u{9c1}গ"),
                        ("ca", "Mudug"),
                        ("ccp", "𑄟\u{1112a}𑄓\u{1112a}𑄇\u{11134}"),
                        ("ceb", "Gobolka Mudug"),
                        ("da", "Mudug"),
                        ("de", "Mudug"),
                        ("el", "Μούντουγκ"),
                        ("en", "Mudug"),
                        ("es", "Mudug"),
                        ("eu", "Mudug"),
                        ("fi", "Mudug"),
                        ("fr", "Mudug"),
                        ("gu", "મ\u{ac1}દગ"),
                        ("hi", "म\u{941}द\u{941}ग"),
                        ("hy", "Մուդուգ"),
                        ("id", "Mudug"),
                        ("it", "Mudugh"),
                        ("ja", "ムドゥグ州"),
                        ("jv", "Mudug"),
                        ("ka", "მუდუგის რეგიონი"),
                        ("kn", "ಮುದುಗ\u{ccd}"),
                        ("ko", "무두그 주"),
                        ("lt", "Mudugas"),
                        ("lv", "Muduga"),
                        ("mr", "म\u{941}दग"),
                        ("ms", "Mudug"),
                        ("nb", "Mudug"),
                        ("nl", "Mudug"),
                        ("no", "Mudug"),
                        ("pl", "Mudug"),
                        ("pt", "Mudug"),
                        ("ru", "Мудуг"),
                        ("si", "ම\u{dd4}ඩග\u{dca}"),
                        ("so", "Mudug"),
                        ("sv", "Mudug"),
                        ("ta", "முதுகு"),
                        ("te", "ముడుగ\u{c4d}"),
                        ("th", "มาด\u{e31}ก"),
                        ("tr", "Mudug"),
                        ("uk", "Мудуг"),
                        ("ur", "مدق"),
                        ("vi", "Mudug"),
                        ("zh", "穆杜格州"),
                    ]),
                    unofficial_name_list: ["Mudug"].to_vec(),
                },
            ),
            (
                "NU",
                Subdivision {
                    name: "NU",
                    country_alpha2: Alpha2::SO,
                    code: "NU",
                    #[cfg(feature = "geo")]
                    geo: Some(SubdivisionGeo {
                        latitude: Some(8.2173496),
                        longitude: Some(49.2030851),
                        max_latitude: Some(8.9382501),
                        min_latitude: Some(7.386317599999999),
                        max_longitude: Some(50.16936099999999),
                        min_longitude: Some(47.789005),
                    }),
                    comments: None,
                    subdivision_type: SubdivisionType::Region,
                    #[cfg(feature = "translations")]
                    translations: HashMap::from([
                        ("ar", "نوجال"),
                        ("bg", "Нугаал"),
                        ("bn", "ন\u{9c1}গ\u{9be}ল"),
                        ("ca", "Nugaal"),
                        ("ccp", "𑄚\u{1112a}𑄉𑄣\u{11134}"),
                        ("ceb", "Gobolka Nugaal"),
                        ("da", "Nugaal"),
                        ("de", "Nugaal"),
                        ("el", "Νούγκαλ"),
                        ("en", "Nugal"),
                        ("es", "Nugaal"),
                        ("eu", "Nugaal"),
                        ("fi", "Nugaal"),
                        ("fr", "Nugaal"),
                        ("gu", "નગલ"),
                        ("hi", "न\u{941}गल"),
                        ("id", "Nugal"),
                        ("it", "Nogal"),
                        ("ja", "ヌガール州"),
                        ("ka", "ნუგალის რეგიონი"),
                        ("kn", "ನುಗಲ\u{ccd}"),
                        ("ko", "누갈 주"),
                        ("lt", "Nugalis"),
                        ("lv", "Nūgālas reģions"),
                        ("mr", "नगल"),
                        ("ms", "Nugal"),
                        ("nb", "Nugal"),
                        ("nl", "Nugaal"),
                        ("no", "Nugal"),
                        ("pl", "Nugal"),
                        ("pt", "Nugaal"),
                        ("ru", "Нугаль"),
                        ("si", "න\u{dd4}ගල\u{dca}"),
                        ("so", "Nugaal"),
                        ("sv", "Nugal"),
                        ("ta", "நுகள\u{bcd}"),
                        ("te", "నూగల\u{c4d}"),
                        ("th", "น\u{e39}ก\u{e31}ล"),
                        ("tr", "Nugal"),
                        ("uk", "Нугаль"),
                        ("ur", "نوغال، صومالیہ"),
                        ("vi", "Nugal"),
                        ("zh", "努加爾州"),
                    ]),
                    unofficial_name_list: ["Nugaal"].to_vec(),
                },
            ),
            (
                "SA",
                Subdivision {
                    name: "SA",
                    country_alpha2: Alpha2::SO,
                    code: "SA",
                    #[cfg(feature = "geo")]
                    geo: Some(SubdivisionGeo {
                        latitude: Some(10.3938218),
                        longitude: Some(47.7637565),
                        max_latitude: Some(11.322548),
                        min_latitude: Some(9.2556839),
                        max_longitude: Some(48.95186),
                        min_longitude: Some(45.88597009999999),
                    }),
                    comments: None,
                    subdivision_type: SubdivisionType::Region,
                    #[cfg(feature = "translations")]
                    translations: HashMap::from([
                        ("ar", "سناج"),
                        ("bg", "Санааг"),
                        ("ca", "Sanaag"),
                        ("ccp", "𑄥𑄚\u{11133}𑄃𑄇\u{11134}"),
                        ("ceb", "Gobolka Sanaag"),
                        ("cs", "Sanaag"),
                        ("da", "Sanaag"),
                        ("de", "Sanaag"),
                        ("en", "Sanaag"),
                        ("es", "Sanaag"),
                        ("eu", "Sanaag"),
                        ("fi", "Sanaag"),
                        ("fr", "Sanaag"),
                        ("hy", "Սանագ"),
                        ("it", "Sanag"),
                        ("ja", "サナーグ州"),
                        ("ka", "სანაგის რეგიონი"),
                        ("ko", "사나그 주"),
                        ("nl", "Sanaag"),
                        ("pt", "Sanaag"),
                        ("ru", "Санааг"),
                        ("so", "Sanaag"),
                        ("sv", "Sanaag"),
                        ("tr", "Sanag"),
                        ("uk", "Санааг"),
                        ("ur", "سناج"),
                        ("zh", "薩那格州"),
                    ]),
                    unofficial_name_list: ["Sanaag"].to_vec(),
                },
            ),
            (
                "SD",
                Subdivision {
                    name: "SD",
                    country_alpha2: Alpha2::SO,
                    code: "SD",
                    #[cfg(feature = "geo")]
                    geo: Some(SubdivisionGeo {
                        latitude: Some(2.9250247),
                        longitude: Some(45.9039689),
                        max_latitude: Some(4.030119),
                        min_latitude: Some(2.170552),
                        max_longitude: Some(47.10182959999999),
                        min_longitude: Some(45.03761),
                    }),
                    comments: None,
                    subdivision_type: SubdivisionType::Region,
                    #[cfg(feature = "translations")]
                    translations: HashMap::from([
                        ("ar", "شبيلا الوسطى"),
                        ("be", "Сярэдняя Шабеле"),
                        ("bg", "Шабелаха Дексе"),
                        ("bn", "মিডল শেবিলে"),
                        ("ca", "Shabeellaha Dhexe"),
                        ("ccp", "𑄟\u{11128}𑄓\u{11127}𑄣\u{11134} 𑄥𑄬𑄞𑄬𑄣𑄬"),
                        ("ceb", "Gobolka Shabeellaha Dhexe"),
                        ("da", "Shabeellaha Dhexe"),
                        ("de", "Shabeellaha Dhexe"),
                        ("el", "Μιντλ Σεμπέλε"),
                        ("en", "Middle Shebelle"),
                        ("es", "Shabeellaha Dhexe"),
                        ("eu", "Shabeellaha Dhexe"),
                        ("fi", "Shabeellaha Dhexe"),
                        ("fr", "Shabeellaha Dhexe"),
                        ("gu", "મિડલ શબ\u{ac7}લ"),
                        ("hi", "मध\u{94d}य शीब\u{948}ल"),
                        ("id", "Middle Shebelle"),
                        ("it", "Medio Scebeli"),
                        ("ja", "中部シェベリ州"),
                        ("jv", "Shabeellaha Dhexe"),
                        ("ka", "შუა შაბელეს რეგიონი"),
                        ("kn", "ಮಧ\u{ccd}ಯ ಶ\u{cc6}ಬ\u{cc6}ಲ\u{cc6}"),
                        ("ko", "샤벨라하데헤 주"),
                        ("lt", "Vidurio Šebelė"),
                        ("lv", "Vidusšabēlaha"),
                        ("mr", "मध\u{94d}य श\u{947}ब\u{947}ल\u{94d}ल\u{947}"),
                        ("ms", "Middle Shebelle"),
                        ("nb", "Shabeellaha Dhexe"),
                        ("nl", "Shabeellaha Dhexe"),
                        ("no", "Shabeellaha Dhexe"),
                        ("pl", "Shabeellaha Dhexe"),
                        ("pt", "Shabeellaha Dhexe"),
                        ("ru", "Средняя Шабелле"),
                        ("si", "මද\u{dca}\u{200d}යම ශෙබෙල\u{dca}"),
                        ("so", "Shabeellaha Dhexe"),
                        ("sv", "Shabeellaha Dhexe"),
                        ("ta", "மிடில\u{bcd} ஷெபெல\u{bcd}லே"),
                        (
                            "te",
                            "మ\u{c3f}డ\u{c3f}ల\u{c4d} ష\u{c46}బ\u{c3f}ల\u{c4d}ల\u{c47}",
                        ),
                        ("th", "เม\u{e37}องร\u{e34}เบรา กรานเด"),
                        ("tr", "Orta Şabel"),
                        ("uk", "Середня Шабелле"),
                        ("ur", "وسطی شبیلی"),
                        ("vi", "Middle Shebelle"),
                        ("zh", "中謝貝利州"),
                    ]),
                    unofficial_name_list: ["Shabeellaha Dhexe"].to_vec(),
                },
            ),
            (
                "SH",
                Subdivision {
                    name: "SH",
                    country_alpha2: Alpha2::SO,
                    code: "SH",
                    #[cfg(feature = "geo")]
                    geo: Some(SubdivisionGeo {
                        latitude: Some(1.8766458),
                        longitude: Some(44.2479015),
                        max_latitude: Some(3.320112),
                        min_latitude: Some(0.6533486),
                        max_longitude: Some(45.317607),
                        min_longitude: Some(42.904155),
                    }),
                    comments: None,
                    subdivision_type: SubdivisionType::Region,
                    #[cfg(feature = "translations")]
                    translations: HashMap::from([
                        ("ar", "شبيلا السفلى"),
                        ("bg", "Шабелаха Хуусе"),
                        ("bn", "লোয\u{9bc}\u{9be}র শেব\u{9be}রেল"),
                        ("ca", "Shabeellaha Hoose"),
                        ("ccp", "𑄣\u{1112e}𑄠𑄢\u{11134} 𑄥𑄬𑄞𑄬𑄣𑄬"),
                        ("ceb", "Gobolka Shabeellaha Hoose"),
                        ("da", "Shabeellaha Hoose"),
                        ("de", "Shabeellaha Hoose"),
                        ("el", "Λόουερ Σέμπελε"),
                        ("en", "Lower Shebelle"),
                        ("es", "Shabeellaha Hoose"),
                        ("eu", "Shabeellaha Hoose"),
                        ("fi", "Shabeellaha Hoose"),
                        ("fr", "Shabeellaha Hoose"),
                        ("gu", "લોવર શ\u{ac7}બ\u{ac7}લ"),
                        ("hi", "निचला शीब\u{947}ल"),
                        ("id", "Lower Shebelle"),
                        ("it", "Basso Scebeli"),
                        ("ja", "下部シャベレ州"),
                        ("jv", "Shabeellaha Hoose"),
                        ("ka", "ქვემო შაბელეს რეგიონი"),
                        ("kn", "ಲೋಯರ\u{ccd} ಶ\u{cc6}ಬ\u{cc6}ಲ\u{ccd}"),
                        ("ko", "샤벨라하호세 주"),
                        ("lt", "Žamutinė Šebelė"),
                        ("lv", "Lejasšabele"),
                        ("mr", "लोअर श\u{947}ब\u{947}ल"),
                        ("ms", "Lower Shebelle"),
                        ("nb", "Nedre Shebelle"),
                        ("nl", "Shabeellaha Hoose"),
                        ("no", "Nedre Shebelle"),
                        ("pl", "Shabeellaha Hoose"),
                        ("pt", "Shabeellaha Hoose"),
                        ("ro", "Shabeellaha Hoose"),
                        ("ru", "Нижняя Шабелле"),
                        ("si", "පහල ශේබෙලේ"),
                        ("so", "Shabeellaha Hoose"),
                        ("sv", "Nedre Shebelle"),
                        ("ta", "லோயர\u{bcd} ஷெபெல\u{bcd}லே"),
                        ("te", "ల\u{c4b}యర\u{c4d} ష\u{c3f}బ\u{c46}ల\u{c4d}ల\u{c46}"),
                        ("th", "โลเวอ ช\u{e35}เบลล\u{e4c}"),
                        ("tr", "Aşağı Şabel"),
                        ("uk", "Нижня Шабелле"),
                        ("ur", "زیریں شبیلی"),
                        ("vi", "Hạ Shebelle"),
                        ("zh", "下謝貝利州"),
                    ]),
                    unofficial_name_list: ["Shabeellaha Hoose"].to_vec(),
                },
            ),
            (
                "SO",
                Subdivision {
                    name: "SO",
                    country_alpha2: Alpha2::SO,
                    code: "SO",
                    #[cfg(feature = "geo")]
                    geo: Some(SubdivisionGeo {
                        latitude: Some(8.722155599999999),
                        longitude: Some(47.7637565),
                        max_latitude: Some(9.778229999999999),
                        min_latitude: Some(7.999999899999999),
                        max_longitude: Some(48.973164),
                        min_longitude: Some(45.982599),
                    }),
                    comments: None,
                    subdivision_type: SubdivisionType::Region,
                    #[cfg(feature = "translations")]
                    translations: HashMap::from([
                        ("ar", "سول"),
                        ("bg", "Сол"),
                        ("ca", "Sool"),
                        ("ccp", "𑄥\u{1112b}𑄣\u{11134}"),
                        ("ceb", "Gobolka Sool"),
                        ("cs", "Sool"),
                        ("da", "Sool"),
                        ("de", "Sool"),
                        ("en", "Sool"),
                        ("es", "Sool"),
                        ("eu", "Sool"),
                        ("fi", "Sool"),
                        ("fr", "Sool"),
                        ("it", "Sol"),
                        ("ja", "スール州"),
                        ("jv", "Sool"),
                        ("ka", "სოლის რეგიონი"),
                        ("ko", "솔 주"),
                        ("nb", "Sool"),
                        ("nl", "Sool"),
                        ("no", "Sool"),
                        ("pt", "Sool"),
                        ("ru", "Сул"),
                        ("so", "Sool"),
                        ("sv", "Sool"),
                        ("tr", "Sul"),
                        ("uk", "Сул"),
                        ("ur", "سول"),
                        ("zh", "蘇爾州"),
                    ]),
                    unofficial_name_list: ["Sool"].to_vec(),
                },
            ),
            (
                "TO",
                Subdivision {
                    name: "TO",
                    country_alpha2: Alpha2::SO,
                    code: "TO",
                    #[cfg(feature = "geo")]
                    geo: Some(SubdivisionGeo {
                        latitude: Some(9.4460587),
                        longitude: Some(45.29938620000001),
                        max_latitude: Some(10.1261651),
                        min_latitude: Some(8.0030579),
                        max_longitude: Some(46.98998),
                        min_longitude: Some(44.6282671),
                    }),
                    comments: None,
                    subdivision_type: SubdivisionType::Region,
                    #[cfg(feature = "translations")]
                    translations: HashMap::from([
                        ("ar", "توجدير"),
                        ("bg", "Тогдер"),
                        ("ca", "Togdheer"),
                        ("ccp", "𑄑\u{1112e}𑄇\u{11134}𑄙\u{11129}𑄢\u{11134}"),
                        ("ceb", "Gobolka Togdheer"),
                        ("cs", "Togdheer"),
                        ("da", "Togdheer"),
                        ("de", "Togdheer"),
                        ("en", "Togdheer"),
                        ("es", "Togdheer"),
                        ("eu", "Togdheer"),
                        ("fi", "Togdheer"),
                        ("fr", "Togdheer"),
                        ("it", "Tug Dair"),
                        ("ja", "トゲアー州"),
                        ("ka", "ტოგდერის რეგიონი"),
                        ("ko", "토그데르 주"),
                        ("nl", "Togdheer"),
                        ("pt", "Togdheer"),
                        ("ru", "Тогдер"),
                        ("so", "Togdheer"),
                        ("sv", "Togdheer"),
                        ("tr", "Togdeyr"),
                        ("uk", "Тогдер"),
                        ("ur", "توجدیر"),
                        ("zh", "托格代爾州"),
                    ]),
                    unofficial_name_list: ["Togdheer"].to_vec(),
                },
            ),
            (
                "WO",
                Subdivision {
                    name: "WO",
                    country_alpha2: Alpha2::SO,
                    code: "WO",
                    #[cfg(feature = "geo")]
                    geo: Some(SubdivisionGeo {
                        latitude: Some(9.542373999999999),
                        longitude: Some(44.0960311),
                        max_latitude: Some(10.8666542),
                        min_latitude: Some(8.785137899999999),
                        max_longitude: Some(45.927817),
                        min_longitude: Some(43.2783189),
                    }),
                    comments: None,
                    subdivision_type: SubdivisionType::Region,
                    #[cfg(feature = "translations")]
                    translations: HashMap::from([
                        ("ar", "وقويي جالبيد"),
                        ("bg", "Вокои Галбеед"),
                        ("ca", "Woqooyi Galbeed"),
                        ("ccp", "𑄤𑄇\u{1112a}𑄠\u{11128} 𑄉𑄣\u{11134}𑄝𑄬𑄖\u{11134}"),
                        ("ceb", "Gobolka Woqooyi Galbeed"),
                        ("da", "Woqooyi Galbeed"),
                        ("de", "Woqooyi Galbeed"),
                        ("en", "Woqooyi Galbeed"),
                        ("es", "Woqooyi Galbeed"),
                        ("eu", "Woqooyi Galbeed"),
                        ("fi", "Woqooyi Galbeed"),
                        ("fr", "Woqooyi Galbeed"),
                        ("it", "Nordovest"),
                        ("ja", "北部ガルベード州"),
                        ("ka", "ვოკუი-გალბიდის რეგიონი"),
                        ("ko", "워코이갈베드 주"),
                        ("nb", "Woqooyi Galbeed"),
                        ("nl", "Woqooyi-Galbeed"),
                        ("no", "Woqooyi Galbeed"),
                        ("pt", "Woqooyi Galbeed"),
                        ("ru", "Мароди Чех"),
                        ("so", "Woqooyi Galbeed"),
                        ("sv", "Woqooyi Galbeed"),
                        ("tr", "Woqoyi Galbed"),
                        ("uk", "Вокуй-Гальбід"),
                        ("ur", "وقویی جالبید"),
                        ("zh", "沃戈伊加勒贝德州"),
                    ]),
                    unofficial_name_list: ["Woqooyi Galbeed"].to_vec(),
                },
            ),
        ])
    }
}
#[allow(unused_imports)]
use crate::{
    Alpha2, Alpha3, Continent, Country, CurrencyCode, Region, SubRegion, WeekDay, WorldRegion, GEC,
    IOC,
};
#[allow(unused_imports)]
use std::collections::HashMap;
#[cfg(feature = "so")]
pub fn new() -> Country {
    Country {
        alpha2: Alpha2::SO,
        alpha3: Alpha3::SOM,
        address_format: None,
        continent: Continent::Africa,
        country_code: 252,
        currency_code: CurrencyCode::SOS,
        gec: Some(GEC::SO),
        #[cfg(feature = "geo")]
        geo: geo::new(),
        international_prefix: "00",
        ioc: Some(IOC::SOM),
        iso_long_name: "The Federal Republic of Somalia",
        iso_short_name: "Somalia",
        official_language_list: ["ar", "so"].to_vec(),
        spoken_language_list: ["ar", "so"].to_vec(),
        national_destination_code_length_list: [2].to_vec(),
        national_number_length_list: [7, 8].to_vec(),
        national_prefix: "None",
        nationality: Some("Somali"),
        number: "706",
        postal_code: true,
        postal_code_format: Some("[A-Z]{2} ?\\d{5}"),
        region: Some(Region::Africa),
        start_of_week: WeekDay::Monday,
        subregion: Some(SubRegion::EasternAfrica),
        un_locode: "SO",
        unofficial_name_list: ["Somalia", "الصومال", "ソマリア", "Somalië"].to_vec(),
        world_region: WorldRegion::EMEA,
        #[cfg(feature = "translations")]
        translations: HashMap::from([
            ("ab", "Somalia"),
            ("af", "Somalië"),
            ("ak", "Somalia"),
            ("am", "ሱሢሓ"),
            ("an", "Somalia"),
            ("ar", "الصومال"),
            ("as", "ছোম\u{9be}লিয়\u{9be}"),
            ("ay", "Somalia"),
            ("az", "Somali"),
            ("ba", "Somalia"),
            ("be", "Самалі"),
            ("bg", "Сомалия"),
            ("bi", "Somalia"),
            ("bn", "সোম\u{9be}লিয়\u{9be}"),
            ("bn_IN", "সোম\u{9be}লিয়\u{9be}"),
            ("br", "Somalia"),
            ("bs", "Somalija"),
            ("ca", "Somàlia"),
            ("ce", "Сомали"),
            ("ch", "Somalia"),
            ("cs", "Somálsko"),
            ("cv", "Сомали"),
            ("cy", "Somalia"),
            ("da", "Somalia"),
            ("de", "Somalia"),
            ("dv", "ސ\u{7af}މ\u{7a7}ލ\u{7a8}އ\u{7a7}"),
            ("dz", "ས\u{f7c}་མ་ལ\u{f72}་ཡ།"),
            ("ee", "Somalia"),
            ("el", "Σομαλία"),
            ("en", "Somalia"),
            ("eo", "Somalio"),
            ("es", "Somalia"),
            ("et", "Somaalia"),
            ("eu", "Somalia"),
            ("fa", "سومالی"),
            ("ff", "Somaaliya"),
            ("fi", "Somalia"),
            ("fo", "Somalia"),
            ("fr", "Somalie"),
            ("fy", "Somaalje"),
            ("ga", "An tSomáil"),
            ("gl", "Somalia"),
            ("gn", "Somalia"),
            ("gu", "સોમાલિયા"),
            ("gv", "Yn Tomaal"),
            ("ha", "Somaliya"),
            ("he", "סומליה"),
            ("hi", "सोमालिया"),
            ("hr", "Somalija"),
            ("ht", "Somali"),
            ("hu", "Szomália"),
            ("hy", "Սոմալի"),
            ("ia", "Somalia"),
            ("id", "Somalia"),
            ("io", "Somalia"),
            ("is", "Sómalía"),
            ("it", "Somalia"),
            ("iu", "Somalia"),
            ("ja", "ソマリア"),
            ("ka", "სომალი"),
            ("ki", "Somalia"),
            ("kk", "Сомали"),
            ("kl", "Somalia"),
            ("km", "ស\u{17bc}ម\u{17c9}ាល\u{17b8}"),
            ("kn", "ಸೋಮಾಲ\u{cbf}ಯಾ"),
            ("ko", "소말리아"),
            ("ku", "Somalî"),
            ("kv", "Somalia"),
            ("kw", "Somali"),
            ("ky", "Сомали"),
            ("lo", "Somalia"),
            ("lt", "Somalis"),
            ("lv", "Somālija"),
            ("mi", "Somalia"),
            ("mk", "Сомалија"),
            ("ml", "സോമ\u{d3e}ലിയ"),
            ("mn", "Сомали"),
            ("mr", "सोमालिया"),
            ("ms", "Somalia"),
            ("mt", "Somalja"),
            (
                "my",
                "ဆ\u{102d}\u{102f}မာလ\u{102e}ယာန\u{102d}\u{102f}င\u{103a}င\u{1036}",
            ),
            ("na", "Tomariya"),
            ("nb", "Somalia"),
            ("ne", "सोमालिया"),
            ("nl", "Somalië"),
            ("nn", "Somalia"),
            ("nv", "Soomáálii Bikéyah"),
            ("oc", "Somalia"),
            ("or", "ସୋମ\u{b3e}ଲ\u{b3f}ୟ\u{b3e}"),
            ("pa", "ਸ\u{a4b}ਮਾਲੀਆ"),
            ("pi", "सोमालिया"),
            ("pl", "Somalia"),
            ("ps", "سومالیا"),
            ("pt", "Somália"),
            ("pt_BR", "Somália"),
            ("ro", "Somalia"),
            ("ru", "Сомали"),
            ("rw", "Somaliya"),
            ("sc", "Somàlia"),
            ("sd", "صوماليه"),
            ("si", "සෝම\u{dcf}ල\u{dd2}ය\u{dcf}ව"),
            ("sk", "Somálsko"),
            ("sl", "Somalija"),
            ("so", "Soomaaliya"),
            ("sq", "Somali"),
            ("sr", "Сомалија"),
            ("sv", "Somalia"),
            ("sw", "Somalia"),
            ("ta", "சோம\u{bbe}லிய\u{bbe}"),
            ("te", "స\u{c4b}మ\u{c3e}ల\u{c3f}య\u{c3e}"),
            ("tg", "Сомалӣ"),
            ("th", "โซมาเล\u{e35}ย"),
            ("ti", "ሶማልያ"),
            ("tk", "Somalia"),
            ("tl", "Somalia"),
            ("tr", "Somali"),
            ("tt", "Сомалиа"),
            ("ug", "سومالى"),
            ("uk", "Сомалі"),
            ("ur", "صومالیہ"),
            ("uz", "Somali"),
            ("ve", "Somalia"),
            ("vi", "Xo-ma-li"),
            ("wa", "Somaleye"),
            ("wo", "Somaali"),
            ("xh", "Somalia"),
            ("yo", "Sòmálíà"),
            ("zh_CN", "索马里"),
            ("zh_HK", "索馬里"),
            ("zh_TW", "索馬利亞"),
            ("zu", "ISomalia"),
        ]),
        #[cfg(feature = "subdivisions")]
        subdivisions: subdivisions::new(),
    }
}
