// DO NOT TOUCH THIS FILE. (Auto-generated via `code_gen/countries.rs`)

// The Togolese Republic

#[cfg(all(feature = "tg", feature = "constants"))]
pub mod consts {
    #[allow(unused_imports)]
    use crate::{
        Alpha2, Alpha3, Continent, CurrencyCode, Region, SubRegion, WeekDay, WorldRegion, GEC, IOC,
    };

    pub const ADDRESS_FORMAT: Option<&str> = None;
    pub const ALPHA2: Alpha2 = Alpha2::TG;
    pub const ALPHA3: Alpha3 = Alpha3::TGO;
    pub const CONTINENT: Continent = Continent::Africa;
    pub const COUNTRY_CODE: usize = 228;
    pub const CURRENCY_CODE: CurrencyCode = CurrencyCode::XOF;
    pub const GEC: Option<GEC> = Some(GEC::TO);
    pub const INTERNATIONAL_PREFIX: &str = "00";
    pub const IOC: Option<IOC> = Some(IOC::TOG);
    pub const ISO_SHORT_NAME: &str = "Togo";
    pub const ISO_LONG_NAME: &str = "The Togolese Republic";
    pub const OFFICIAL_LANGUAGE_LIST: &[&str] = &["fr"];
    pub const SPOKEN_LANGUAGE_LIST: &[&str] = &["fr"];
    pub const NATIONAL_DESTINATION_CODE_LENGTH_LIST: &[usize] = &[2];
    pub const NATIONAL_NUMBER_LENGTH_LIST: &[usize] = &[7];
    pub const NATIONAL_PREFIX: &str = "None";
    pub const NATIONALITY: Option<&str> = Some("Togolese");
    pub const NUMBER: &str = "768";
    pub const POSTAL_CODE: bool = false;
    pub const POSTAL_CODE_FORMAT: Option<&str> = None;
    pub const REGION: Option<Region> = Some(Region::Africa);
    pub const START_DAY_OF_WEEK: WeekDay = WeekDay::Monday;
    pub const SUBREGION: Option<SubRegion> = Some(SubRegion::WesternAfrica);
    pub const UN_LOCODE: &str = "TG";
    pub const UNOFFICIAL_NAME_LIST: &[&str] = &["Togo", "トーゴ"];
    pub const WORLD_REGION: WorldRegion = WorldRegion::EMEA;
    #[cfg(feature = "translations")]
    pub const TRANSLATIONS: &[(&str, &str)] = &[
        ("ab", "Togo"),
        ("af", "Togo"),
        ("ak", "Togo"),
        ("am", "ቶጎ"),
        ("an", "Togo"),
        ("ar", "توغو"),
        ("as", "টোগো"),
        ("ay", "Togo"),
        ("az", "Toqo"),
        ("ba", "Togo"),
        ("be", "Тога"),
        ("bg", "Того"),
        ("bi", "Togo"),
        ("bn", "টোগো"),
        ("bn_IN", "টোগো"),
        ("br", "Togo"),
        ("bs", "Togo"),
        ("ca", "Togo"),
        ("ce", "Того"),
        ("ch", "Togo"),
        ("cs", "Togo"),
        ("cv", "Того"),
        ("cy", "Togo"),
        ("da", "Togo"),
        ("de", "Togo"),
        ("dv", "ޓ\u{7af}ގ\u{7af}"),
        ("dz", "ཊ\u{f7c}་ག\u{f7c}།"),
        ("ee", "Togo"),
        ("el", "Τόγκο"),
        ("en", "Togo"),
        ("eo", "Togo"),
        ("es", "Togo"),
        ("et", "Togo"),
        ("eu", "Togo"),
        ("fa", "توگو"),
        ("ff", "Togo"),
        ("fi", "Togo"),
        ("fo", "Togo"),
        ("fr", "Togo"),
        ("fy", "Togo"),
        ("ga", "Tóga"),
        ("gl", "Togo"),
        ("gn", "Togo"),
        ("gu", "ટોગો"),
        ("gv", "Yn Togo"),
        ("ha", "Togo"),
        ("he", "טוגו"),
        ("hi", "टोगो"),
        ("hr", "Togo"),
        ("ht", "Togo"),
        ("hu", "Togo"),
        ("hy", "Տոգո"),
        ("ia", "Togo"),
        ("id", "Togo"),
        ("io", "Togo"),
        ("is", "Tógó"),
        ("it", "Togo"),
        ("iu", "Togo"),
        ("ja", "トーゴ"),
        ("ka", "ტოგო"),
        ("ki", "Togo"),
        ("kk", "Того"),
        ("kl", "Togo"),
        ("km", "ត\u{17bc}ហ\u{17d2}គោ"),
        ("kn", "ಟೋಗೋ"),
        ("ko", "토고"),
        ("ku", "Togo"),
        ("kv", "Togo"),
        ("kw", "Togo"),
        ("ky", "Того"),
        ("lo", "Togo"),
        ("lt", "Togas"),
        ("lv", "Togo"),
        ("mi", "Toko"),
        ("mk", "Того"),
        ("ml", "ടോഗോ"),
        ("mn", "Того"),
        ("mr", "तोगो"),
        ("ms", "Togo"),
        ("mt", "Togo"),
        (
            "my",
            "တ\u{102d}\u{102f}ဂ\u{102d}\u{102f}န\u{102d}\u{102f}င\u{103a}င\u{1036}",
        ),
        ("na", "Togo"),
        ("nb", "Togo"),
        ("ne", "टोगो"),
        ("nl", "Togo"),
        ("nn", "Togo"),
        ("nv", "Togo"),
        ("oc", "Tògo"),
        ("or", "ଟୋଗୋ"),
        ("pa", "ਟ\u{a4b}ਗ\u{a4b}"),
        ("pi", "टोगो"),
        ("pl", "Togo"),
        ("ps", "Togo"),
        ("pt", "Togo"),
        ("pt_BR", "Togo"),
        ("ro", "Togo"),
        ("ru", "Того"),
        ("rw", "Togo"),
        ("sc", "Togo"),
        ("sd", "ٽوگو"),
        ("si", "ටෝගෝ"),
        ("sk", "Togo"),
        ("sl", "Togo"),
        ("so", "Toogo"),
        ("sq", "Togo"),
        ("sr", "Того"),
        ("sv", "Togo"),
        ("sw", "Togo"),
        ("ta", "டோகோ"),
        ("te", "త\u{c4b}గ\u{c4b}"),
        ("tg", "Того"),
        ("th", "โตโก"),
        ("ti", "ቶጎ"),
        ("tk", "Togolez"),
        ("tl", "Togo"),
        ("tr", "Togo"),
        ("tt", "Тоgо"),
        ("ug", "توگو"),
        ("uk", "Того"),
        ("ur", "ٹوگو"),
        ("uz", "Togo"),
        ("ve", "Togo"),
        ("vi", "Tô-gô"),
        ("wa", "Togo"),
        ("wo", "Togóo"),
        ("xh", "Togo"),
        ("yo", "Tógò"),
        ("zh_CN", "多哥"),
        ("zh_HK", "多哥"),
        ("zh_TW", "多哥"),
        ("zu", "ITogo"),
    ];
    #[cfg(all(feature = "tg", feature = "geo", feature = "constants"))]
    pub mod geo {
        pub const LATITUDE: f64 = 8.619543;
        pub const LONGITUDE: f64 = 0.824782;
        pub const MAX_LATITUDE: f64 = 11.139617;
        pub const MAX_LONGITUDE: f64 = 1.8089071;
        pub const MIN_LATITUDE: f64 = 6.0812;
        pub const MIN_LONGITUDE: f64 = -0.1440418;
        pub const NORTHEAST_LATITUDE: f64 = 11.139617;
        pub const NORTHEAST_LONGITUDE: f64 = 1.8089071;
        pub const SOUTHWEST_LATITUDE: f64 = 6.0812;
        pub const SOUTHWEST_LONGITUDE: f64 = -0.1440418;
    }
}
#[cfg(all(feature = "tg", feature = "geo"))]
pub mod geo {
    use crate::{CountryGeo, CountryGeoBound, CountryGeoBounds};

    pub fn new() -> CountryGeo {
        CountryGeo {
            latitude: 8.619543,
            longitude: 0.824782,
            max_latitude: 11.139617,
            max_longitude: 1.8089071,
            min_latitude: 6.0812,
            min_longitude: -0.1440418,
            bounds: CountryGeoBounds {
                northeast: CountryGeoBound {
                    latitude: 11.139617,
                    longitude: 1.8089071,
                },
                southwest: CountryGeoBound {
                    latitude: 6.0812,
                    longitude: -0.1440418,
                },
            },
        }
    }
}

#[cfg(all(feature = "tg", feature = "subdivisions"))]
pub mod subdivisions {
    #[allow(unused_imports)]
    use crate::{Alpha2, Subdivision, SubdivisionType};
    use std::collections::HashMap;
    // In this state, We do not know if subdivisions have geo or not!
    #[cfg(feature = "geo")]
    #[allow(unused_imports)]
    use crate::SubdivisionGeo;

    pub fn new() -> HashMap<&'static str, Subdivision> {
        HashMap::from([
            (
                "C",
                Subdivision {
                    name: "Centre",
                    country_alpha2: Alpha2::TG,
                    code: "C",
                    #[cfg(feature = "geo")]
                    geo: Some(SubdivisionGeo {
                        latitude: Some(8.6586029),
                        longitude: Some(1.0586135),
                        max_latitude: Some(9.296292),
                        min_latitude: Some(7.9023141),
                        max_longitude: Some(1.650187),
                        min_longitude: Some(0.3816739),
                    }),
                    comments: None,
                    subdivision_type: SubdivisionType::Region,
                    #[cfg(feature = "translations")]
                    translations: HashMap::from([
                        ("ar", "الإقليم الأوسط"),
                        ("bg", "Централен регион"),
                        ("bn", "সেন\u{9cd}ট\u{9cd}র\u{9be}ল অঞ\u{9cd}চল"),
                        ("ca", "Regió Central"),
                        ("ccp", "𑄥𑄬𑄚\u{11134}𑄑\u{11133}𑄢𑄣\u{11134}"),
                        ("ceb", "Centrale"),
                        ("da", "Centrale"),
                        ("de", "Region Centrale"),
                        ("el", "Κεντρική Περιφέρεια"),
                        ("en", "Centrale"),
                        ("es", "Central"),
                        ("fi", "Centrale"),
                        ("fr", "Région centrale"),
                        ("gu", "સ\u{ac7}ન\u{acd}ટ\u{acd}રલ પ\u{acd}રદ\u{ac7}શ"),
                        ("hi", "स\u{947}\u{902}ट\u{94d}रल क\u{94d}ष\u{947}त\u{94d}र"),
                        ("id", "Region Centrale"),
                        ("it", "regione Centrale"),
                        ("ja", "中央州"),
                        ("kn", "ಸ\u{cc6}ಂಟ\u{ccd}ರೇಲ\u{ccd} ಪ\u{ccd}ರದೇಶ"),
                        ("ko", "중앙 주"),
                        ("lt", "Centrinis regionas"),
                        ("lv", "Centrālais reģions"),
                        ("mr", "मध\u{94d}यवर\u{94d}ती प\u{94d}रद\u{947}श"),
                        ("ms", "Centrale Region"),
                        ("nb", "Centrale"),
                        ("nl", "Centrale"),
                        ("no", "Centrale"),
                        ("pl", "Region Centre"),
                        ("pt", "Centrale"),
                        ("ro", "Regiunea Centrale"),
                        ("ru", "Центральная область"),
                        ("si", "සෙන\u{dca}ට\u{dca}\u{200d}රලේ කල\u{dcf}පය"),
                        ("sv", "Centrale (region)"),
                        ("ta", "சென\u{bcd}ற\u{bbe}லே பகுதி"),
                        (
                            "te",
                            "స\u{c46}ంట\u{c4d}ర\u{c47}ల\u{c4d} ప\u{c4d}ర\u{c3e}ంతం",
                        ),
                        ("th", "เขตเซนทราเล"),
                        ("tr", "Centrale"),
                        ("uk", "Центральний регіон"),
                        ("ur", "سونترال علاقہ، ٹوگو"),
                        ("vi", "Centrale"),
                        ("zh", "中部区"),
                    ]),
                    unofficial_name_list: ["Centre"].to_vec(),
                },
            ),
            (
                "K",
                Subdivision {
                    name: "Kara",
                    country_alpha2: Alpha2::TG,
                    code: "K",
                    #[cfg(feature = "geo")]
                    geo: Some(SubdivisionGeo {
                        latitude: Some(9.548888999999999),
                        longitude: Some(1.190556),
                        max_latitude: Some(9.5661352),
                        min_latitude: Some(9.534310099999999),
                        max_longitude: Some(1.2201691),
                        min_longitude: Some(1.1657524),
                    }),
                    comments: None,
                    subdivision_type: SubdivisionType::Region,
                    #[cfg(feature = "translations")]
                    translations: HashMap::from([
                        ("ar", "إقليم كارا"),
                        ("bg", "Кара"),
                        ("bn", "ক\u{9be}র\u{9be} অঞ\u{9cd}চল"),
                        ("ca", "Regió de la Kara"),
                        ("ccp", "𑄇𑄢"),
                        ("ceb", "Kara"),
                        ("da", "Kara"),
                        ("de", "Region Kara"),
                        ("el", "Περιφέρεια Καρά"),
                        ("en", "Kara"),
                        ("es", "Kara"),
                        ("fa", "منطقه کارا"),
                        ("fi", "Kara"),
                        ("fr", "Région de la Kara"),
                        ("gu", "કારા પ\u{acd}રદ\u{ac7}શ"),
                        ("hi", "कारा प\u{94d}रद\u{947}श"),
                        ("id", "Region Kara"),
                        ("it", "regione di Kara"),
                        ("ja", "カラ州"),
                        ("kn", "ಕಾರಾ ಪ\u{ccd}ರದೇಶ"),
                        ("ko", "카라 주"),
                        ("lt", "Karos regionas"),
                        ("lv", "Karas reģions"),
                        ("mr", "कारा प\u{94d}रद\u{947}श"),
                        ("ms", "Kara Region"),
                        ("nb", "Kara"),
                        ("nl", "Kara"),
                        ("no", "Kara"),
                        ("pl", "Region Kara"),
                        ("pt", "Kara"),
                        ("ro", "Regiunea Kara"),
                        ("ru", "Кара"),
                        ("si", "කර\u{dcf} කල\u{dcf}පය"),
                        ("sq", "Kara"),
                        ("sv", "Kara (region)"),
                        ("ta", "க\u{bbe}ர\u{bbe} பகுதி"),
                        ("te", "క\u{c3e}ర\u{c3e} ప\u{c4d}ర\u{c3e}ంతం"),
                        (
                            "th",
                            "นอร\u{e4c}ทร\u{e35}เจ\u{e35}\u{e49}ยน, ส\u{e34}งคโปร\u{e4c}",
                        ),
                        ("tr", "Kara"),
                        ("uk", "Регіон Кари"),
                        ("ur", "کارا علاقہ"),
                        ("vi", "Kara"),
                        ("zh", "卡拉区"),
                    ]),
                    unofficial_name_list: ["Kara"].to_vec(),
                },
            ),
            (
                "M",
                Subdivision {
                    name: "Maritime (Région)",
                    country_alpha2: Alpha2::TG,
                    code: "M",
                    #[cfg(feature = "geo")]
                    geo: Some(SubdivisionGeo {
                        latitude: Some(6.4913504),
                        longitude: Some(1.2891036),
                        max_latitude: Some(6.918175),
                        min_latitude: Some(6.109153399999999),
                        max_longitude: Some(1.806693),
                        min_longitude: Some(0.717368),
                    }),
                    comments: None,
                    subdivision_type: SubdivisionType::Region,
                    #[cfg(feature = "translations")]
                    translations: HashMap::from([
                        ("ar", "إقليم البحرية"),
                        ("be", "Прыморская вобласць"),
                        ("bg", "Маритим"),
                        ("bn", "মেরিট\u{9be}ইম অঞ\u{9cd}চল"),
                        ("ca", "Regió Marítima"),
                        ("ccp", "𑄟𑄬𑄢\u{11128}𑄑\u{1112d}𑄟\u{11134}"),
                        ("ceb", "Maritime"),
                        ("da", "Maritime"),
                        ("de", "Region Maritime"),
                        ("el", "Μαριτίμ"),
                        ("en", "Maritime"),
                        ("es", "Marítima"),
                        ("et", "Rannikupiirkond"),
                        ("fa", "منطقه ماریتیم"),
                        ("fi", "Maritime"),
                        ("fr", "Région maritime"),
                        ("gu", "મ\u{ac7}રીટાઈમ પ\u{acd}રદ\u{ac7}શ"),
                        ("hi", "म\u{947}रीटाइम प\u{94d}रा\u{902}त"),
                        ("id", "Region Maritime"),
                        ("it", "regione Marittima"),
                        ("ja", "沿岸州"),
                        ("kn", "ಕಡಲ ಪ\u{ccd}ರದೇಶ"),
                        ("ko", "마리팀 주"),
                        ("lt", "Pajūrio regionas"),
                        ("lv", "Piejūras reģions"),
                        ("mr", "म\u{947}रीटाइम प\u{94d}रद\u{947}श"),
                        ("ms", "Maritime Region"),
                        ("nb", "Maritime"),
                        ("nl", "Maritime"),
                        ("no", "Maritime"),
                        ("pl", "Region Maritime"),
                        ("pt", "Maritime"),
                        ("ro", "Regiunea Maritime"),
                        ("ru", "Приморская область"),
                        ("si", "මර\u{dd2}ටය\u{dd2}ම\u{dca} කල\u{dcf}පය"),
                        ("sv", "Maritime"),
                        ("ta", "ம\u{bbe}ரிடைம\u{bcd} பகுதி"),
                        ("te", "మ\u{c3e}ర\u{c3f}ట\u{c48}మ\u{c4d} ప\u{c4d}ర\u{c3e}ంతం"),
                        ("th", "มาร\u{e34}ไทม\u{e4c}"),
                        ("tr", "Maritime"),
                        ("uk", "Марітіме"),
                        ("ur", "میری ٹائم علاقہ"),
                        ("vi", "Maritime"),
                        ("zh", "濱海區"),
                    ]),
                    unofficial_name_list: ["Maritime (Région)"].to_vec(),
                },
            ),
            (
                "P",
                Subdivision {
                    name: "Plateaux",
                    country_alpha2: Alpha2::TG,
                    code: "P",
                    #[cfg(feature = "geo")]
                    geo: Some(SubdivisionGeo {
                        latitude: Some(7.6101378),
                        longitude: Some(1.0586135),
                        max_latitude: Some(8.368130899999999),
                        min_latitude: Some(6.542187),
                        max_longitude: Some(1.677525),
                        min_longitude: Some(0.501813),
                    }),
                    comments: None,
                    subdivision_type: SubdivisionType::Region,
                    #[cfg(feature = "translations")]
                    translations: HashMap::from([
                        ("ar", "إقليم بلاتيوكس"),
                        ("bg", "Плато"),
                        ("bn", "প\u{9cd}ল\u{9be}তেঊ অঞ\u{9cd}চল"),
                        ("ca", "Regió dels Altiplans"),
                        ("ccp", "𑄛\u{11133}𑄣𑄑\u{11128}𑄠𑄇\u{11134}"),
                        ("ceb", "Plateaux"),
                        ("da", "Plateaux"),
                        ("de", "Region Plateaux"),
                        ("el", "Πλατώ"),
                        ("en", "Plateaux"),
                        ("es", "Altiplano"),
                        ("fi", "Plateaux"),
                        ("fr", "Région des plateaux"),
                        ("gu", "પ\u{acd}લ\u{ac7}ટોક\u{acd}સ પ\u{acd}રદ\u{ac7}શ"),
                        ("hi", "प\u{94d}ल\u{947}टो क\u{94d}ष\u{947}त\u{94d}र"),
                        ("id", "Region Plateaux"),
                        ("it", "regione degli Altopiani"),
                        ("ja", "高原州"),
                        ("kn", "ಪ\u{ccd}ಲಾಟ\u{cc6}ಯಾಕ\u{ccd}ಸ\u{ccd} ಪ\u{ccd}ರದೇಶ"),
                        ("ko", "플라토 주"),
                        ("lt", "Plynaukštės regionas"),
                        ("lv", "Plato reģions"),
                        ("mr", "प\u{94d}ल\u{947}टो प\u{94d}रद\u{947}श"),
                        ("ms", "Plateaux Region"),
                        ("nb", "Plateaux"),
                        ("nl", "Plateaux"),
                        ("no", "Plateaux"),
                        ("pl", "Region Plateaux"),
                        ("pt", "Plateaux"),
                        ("ru", "Плато"),
                        ("si", "ප\u{dca}ලටෙක\u{dca}ස\u{dca} කල\u{dcf}පය"),
                        ("sv", "Plateaux"),
                        ("ta", "பிலேட\u{bc0}ஸ\u{bcd} பகுதி"),
                        (
                            "te",
                            "ప\u{c4d}ల\u{c3e}టూక\u{c4d}స\u{c4d} ప\u{c4d}ర\u{c3e}ంతం",
                        ),
                        ("th", "ปลาโต"),
                        ("tr", "Plateaux"),
                        ("uk", "Регіон Плато"),
                        ("ur", "پلاٹوس علاقہ، ٹوگو"),
                        ("vi", "Plateaux"),
                        ("zh", "高原區"),
                    ]),
                    unofficial_name_list: ["Plateaux"].to_vec(),
                },
            ),
            (
                "S",
                Subdivision {
                    name: "Savannes",
                    country_alpha2: Alpha2::TG,
                    code: "S",
                    #[cfg(feature = "geo")]
                    geo: Some(SubdivisionGeo {
                        latitude: Some(10.5291781),
                        longitude: Some(0.5257822999999999),
                        max_latitude: Some(11.138977),
                        min_latitude: Some(9.879532),
                        max_longitude: Some(0.9969091000000001),
                        min_longitude: Some(-0.1473239),
                    }),
                    comments: None,
                    subdivision_type: SubdivisionType::Region,
                    #[cfg(feature = "translations")]
                    translations: HashMap::from([
                        ("ar", "إقليم سافانس"),
                        ("bg", "Саван"),
                        ("bn", "স\u{9be}ভ\u{9be}নেস অঞ\u{9cd}চল"),
                        ("ca", "Regió de les Sabanes"),
                        ("ccp", "𑄥𑄝𑄚𑄬𑄌\u{11134}"),
                        ("ceb", "Savanes"),
                        ("da", "Savanes"),
                        ("de", "Region Savanes"),
                        ("el", "Σαβάν"),
                        ("en", "Savanes"),
                        ("es", "Sabana"),
                        ("fi", "Savanes"),
                        ("fr", "Région des Savanes"),
                        ("gu", "સાવાન\u{ac7}સ પ\u{acd}રદ\u{ac7}શ"),
                        ("hi", "साव\u{947}न\u{947}स क\u{94d}ष\u{947}त\u{94d}र, टोगो"),
                        ("id", "Region Savanes"),
                        ("it", "regione delle Savane"),
                        ("ja", "サバナ州"),
                        ("kn", "ಸವನ\u{cc6}ಸ\u{ccd} ಪ\u{ccd}ರದೇಶ"),
                        ("ko", "사반 주"),
                        ("lt", "Savanų regionas"),
                        ("lv", "Savanes reģions"),
                        ("mr", "साव\u{947}न\u{947}श प\u{94d}रद\u{947}श"),
                        ("ms", "Savanes Region"),
                        ("nb", "Savanes"),
                        ("nl", "Savanes"),
                        ("no", "Savanes"),
                        ("pl", "Region Savanes"),
                        ("pt", "Savanes"),
                        ("ro", "Regiunea Savanes"),
                        ("ru", "Область Саванн"),
                        ("si", "සවනෙස\u{dca} කල\u{dcf}පය"),
                        ("sv", "Savanes (region)"),
                        ("ta", "சவனேஸ\u{bcd} பகுதி"),
                        ("te", "సవ\u{c3e}న\u{c46}స\u{c4d} ప\u{c4d}ర\u{c3e}ంతం"),
                        ("th", "ซาว\u{e35}เน"),
                        ("tr", "Savanes"),
                        ("uk", "Регіон Саванн"),
                        ("ur", "ساوانیس علاقہ، ٹوگو"),
                        ("vi", "Savanes"),
                        ("zh", "草原區"),
                    ]),
                    unofficial_name_list: ["Savannes"].to_vec(),
                },
            ),
        ])
    }
}
#[allow(unused_imports)]
use crate::{
    Alpha2, Alpha3, Continent, Country, CurrencyCode, Region, SubRegion, WeekDay, WorldRegion, GEC,
    IOC,
};
#[allow(unused_imports)]
use std::collections::HashMap;
#[cfg(feature = "tg")]
pub fn new() -> Country {
    Country {
        alpha2: Alpha2::TG,
        alpha3: Alpha3::TGO,
        address_format: None,
        continent: Continent::Africa,
        country_code: 228,
        currency_code: CurrencyCode::XOF,
        gec: Some(GEC::TO),
        #[cfg(feature = "geo")]
        geo: geo::new(),
        international_prefix: "00",
        ioc: Some(IOC::TOG),
        iso_long_name: "The Togolese Republic",
        iso_short_name: "Togo",
        official_language_list: ["fr"].to_vec(),
        spoken_language_list: ["fr"].to_vec(),
        national_destination_code_length_list: [2].to_vec(),
        national_number_length_list: [7].to_vec(),
        national_prefix: "None",
        nationality: Some("Togolese"),
        number: "768",
        postal_code: false,
        postal_code_format: None,
        region: Some(Region::Africa),
        start_of_week: WeekDay::Monday,
        subregion: Some(SubRegion::WesternAfrica),
        un_locode: "TG",
        unofficial_name_list: ["Togo", "トーゴ"].to_vec(),
        world_region: WorldRegion::EMEA,
        #[cfg(feature = "translations")]
        translations: HashMap::from([
            ("ab", "Togo"),
            ("af", "Togo"),
            ("ak", "Togo"),
            ("am", "ቶጎ"),
            ("an", "Togo"),
            ("ar", "توغو"),
            ("as", "টোগো"),
            ("ay", "Togo"),
            ("az", "Toqo"),
            ("ba", "Togo"),
            ("be", "Тога"),
            ("bg", "Того"),
            ("bi", "Togo"),
            ("bn", "টোগো"),
            ("bn_IN", "টোগো"),
            ("br", "Togo"),
            ("bs", "Togo"),
            ("ca", "Togo"),
            ("ce", "Того"),
            ("ch", "Togo"),
            ("cs", "Togo"),
            ("cv", "Того"),
            ("cy", "Togo"),
            ("da", "Togo"),
            ("de", "Togo"),
            ("dv", "ޓ\u{7af}ގ\u{7af}"),
            ("dz", "ཊ\u{f7c}་ག\u{f7c}།"),
            ("ee", "Togo"),
            ("el", "Τόγκο"),
            ("en", "Togo"),
            ("eo", "Togo"),
            ("es", "Togo"),
            ("et", "Togo"),
            ("eu", "Togo"),
            ("fa", "توگو"),
            ("ff", "Togo"),
            ("fi", "Togo"),
            ("fo", "Togo"),
            ("fr", "Togo"),
            ("fy", "Togo"),
            ("ga", "Tóga"),
            ("gl", "Togo"),
            ("gn", "Togo"),
            ("gu", "ટોગો"),
            ("gv", "Yn Togo"),
            ("ha", "Togo"),
            ("he", "טוגו"),
            ("hi", "टोगो"),
            ("hr", "Togo"),
            ("ht", "Togo"),
            ("hu", "Togo"),
            ("hy", "Տոգո"),
            ("ia", "Togo"),
            ("id", "Togo"),
            ("io", "Togo"),
            ("is", "Tógó"),
            ("it", "Togo"),
            ("iu", "Togo"),
            ("ja", "トーゴ"),
            ("ka", "ტოგო"),
            ("ki", "Togo"),
            ("kk", "Того"),
            ("kl", "Togo"),
            ("km", "ត\u{17bc}ហ\u{17d2}គោ"),
            ("kn", "ಟೋಗೋ"),
            ("ko", "토고"),
            ("ku", "Togo"),
            ("kv", "Togo"),
            ("kw", "Togo"),
            ("ky", "Того"),
            ("lo", "Togo"),
            ("lt", "Togas"),
            ("lv", "Togo"),
            ("mi", "Toko"),
            ("mk", "Того"),
            ("ml", "ടോഗോ"),
            ("mn", "Того"),
            ("mr", "तोगो"),
            ("ms", "Togo"),
            ("mt", "Togo"),
            (
                "my",
                "တ\u{102d}\u{102f}ဂ\u{102d}\u{102f}န\u{102d}\u{102f}င\u{103a}င\u{1036}",
            ),
            ("na", "Togo"),
            ("nb", "Togo"),
            ("ne", "टोगो"),
            ("nl", "Togo"),
            ("nn", "Togo"),
            ("nv", "Togo"),
            ("oc", "Tògo"),
            ("or", "ଟୋଗୋ"),
            ("pa", "ਟ\u{a4b}ਗ\u{a4b}"),
            ("pi", "टोगो"),
            ("pl", "Togo"),
            ("ps", "Togo"),
            ("pt", "Togo"),
            ("pt_BR", "Togo"),
            ("ro", "Togo"),
            ("ru", "Того"),
            ("rw", "Togo"),
            ("sc", "Togo"),
            ("sd", "ٽوگو"),
            ("si", "ටෝගෝ"),
            ("sk", "Togo"),
            ("sl", "Togo"),
            ("so", "Toogo"),
            ("sq", "Togo"),
            ("sr", "Того"),
            ("sv", "Togo"),
            ("sw", "Togo"),
            ("ta", "டோகோ"),
            ("te", "త\u{c4b}గ\u{c4b}"),
            ("tg", "Того"),
            ("th", "โตโก"),
            ("ti", "ቶጎ"),
            ("tk", "Togolez"),
            ("tl", "Togo"),
            ("tr", "Togo"),
            ("tt", "Тоgо"),
            ("ug", "توگو"),
            ("uk", "Того"),
            ("ur", "ٹوگو"),
            ("uz", "Togo"),
            ("ve", "Togo"),
            ("vi", "Tô-gô"),
            ("wa", "Togo"),
            ("wo", "Togóo"),
            ("xh", "Togo"),
            ("yo", "Tógò"),
            ("zh_CN", "多哥"),
            ("zh_HK", "多哥"),
            ("zh_TW", "多哥"),
            ("zu", "ITogo"),
        ]),
        #[cfg(feature = "subdivisions")]
        subdivisions: subdivisions::new(),
    }
}
