name: Check

on:
  push:
    tags-ignore:
      - "*.*.*"
    paths-ignore:
      - "**.md"
    branches-ignore:
      - "documentation"
  pull_request:
    branches:
      - "master"
    paths-ignore:
      - "**.md"

jobs:
  build:
    name: Test
    runs-on: ubuntu-22.04
    steps:
      - name: Installing Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustfmt, clippy
      - name: Checking out sources
        uses: actions/checkout@v1
      - name: Pull submodule(s)
        run: git submodule update --init
      - name: Build
        run: make code_gen
      - name: Test
        run: make test
      - name: Lint
        run: make lint
