name: Check

on:
  push:
    tags-ignore:
      - "*.*.*"
    paths-ignore:
      - "**.md"
    branches-ignore:
      - "documentation"
  pull_request:
    branches:
      - "master"
    paths-ignore:
      - "**.md"

jobs:
  build:
    name: Test
    runs-on: ubuntu-22.04
    steps:
      - name: Installing Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustfmt, clippy

      - name: Checking out sources
        uses: actions/checkout@v1
      - name: Pull submodule(s)
        run: git submodule update --init

      - name: Build current source
        run: make build
      - name: Check current source style
        run: make check-style
      - name: Test current source
        run: make test

      - name: Generate new source
        run: make generate
      - name: Build newly generated source
        run: make build
      - name: Test newly generated source
        run: make test
      - name: Clippy
        run: make clippy
